force-app/main/default/objects/ApplicationDocument__c/ApplicationDocument__c.object-meta.xml
<CustomObject>
    <label>Application Document</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Application Documents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ApplicationDocument__c/fields/RecordType__c.field-meta.xml
<CustomField>
    <fullName>RecordType__c</fullName>
    <label>Record Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Enrolment</fullName>
            </value>
            <value>
                <fullName>Juilliard Summer Arts</fullName>
            </value>
            <value>
                <fullName>Reenrolment</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ApplicationDocument__c/fields/School__c.field-meta.xml
<CustomField>
    <fullName>School__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>School</label>
    <referenceTo>School__c</referenceTo>
    <relationshipLabel>Application Documents</relationshipLabel>
    <relationshipName>ApplicationDocuments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ApplicationDocument__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Enquiry</fullName>
            </value>
            <value>
                <fullName>Application</fullName>
            </value>
            <value>
                <fullName>Acceptance</fullName>
            </value>
            <value>
                <fullName>Enrolled</fullName>
            </value>
            <value>
                <fullName>Visit</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case.object
<CustomObject>
    <fields>
        <fullName>School__c</fullName>
        <formula>Contact.SchoolText__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>School</label>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/DocumentChecklist__c/DocumentChecklist__c.object-meta.xml
<CustomObject>
    <label>Document Checklist</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Document Checklists</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/DocumentChecklist__c/fields/ApplicationDocument__c.field-meta.xml
<CustomField>
    <fullName>ApplicationDocument__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Application Document</label>
    <referenceTo>ApplicationDocument__c</referenceTo>
    <relationshipLabel>Document Checklists</relationshipLabel>
    <relationshipName>DocumentChecklists</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DocumentChecklist__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Document Checklists</relationshipLabel>
    <relationshipName>DocumentChecklists</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/DocumentChecklist__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Enquiry</fullName>
            </value>
            <value>
                <fullName>Application</fullName>
            </value>
            <value>
                <fullName>Acceptance</fullName>
            </value>
            <value>
                <fullName>Enrolled</fullName>
            </value>
            <value>
                <fullName>Visit</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DocumentChecklist__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Requested</fullName>
                <default>true</default>
                <label>Requested</label>
            </value>
            <value>
                <fullName>Received</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DocumentChecklist__c/fields/YearGrade__c.field-meta.xml
<CustomField>
    <fullName>YearGrade__c</fullName>
    <label>YearGrade</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>-4</fullName>
            </value>
            <value>
                <fullName>-3</fullName>
            </value>
            <value>
                <fullName>-2</fullName>
            </value>
            <value>
                <fullName>-1</fullName>
            </value>
            <value>
                <fullName>0</fullName>
            </value>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>6</fullName>
            </value>
            <value>
                <fullName>7</fullName>
            </value>
            <value>
                <fullName>8</fullName>
            </value>
            <value>
                <fullName>9</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
            <value>
                <fullName>11</fullName>
            </value>
            <value>
                <fullName>12</fullName>
            </value>
            <value>
                <fullName>13</fullName>
            </value>
            <value>
                <fullName>14</fullName>
            </value>
            <value>
                <fullName>15</fullName>
            </value>
            <value>
                <fullName>16</fullName>
            </value>
            <value>
                <fullName>17</fullName>
            </value>
            <value>
                <fullName>18</fullName>
            </value>
            <value>
                <fullName>19</fullName>
            </value>
            <value>
                <fullName>20</fullName>
            </value>
            <value>
                <fullName>21</fullName>
            </value>
            <value>
                <fullName>22</fullName>
            </value>
            <value>
                <fullName>23</fullName>
            </value>
            <value>
                <fullName>24</fullName>
            </value>
            <value>
                <fullName>25</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>School__c</fullName>
        <formula>Account.SchoolText__pc</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>School</label>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/School__c.object
<CustomObject>
    <label>School</label>
    <nameField>
        <label>School Code/UID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Schools</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/YearGrade__c/YearGrade__c.object-meta.xml
<CustomObject>
    <label>Year/Grade</label>
    <nameField>
        <label>Year/Grade Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Years/Grades</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/AP04_CreateDocumentChecklist.cls
public with sharing class AP04_CreateDocumentChecklist {
/**************************************************************************************
-- - Author        : Spoon Consulting
-- - Description   : Apex class for creation on document checklist on insertion of application document
--
-- Maintenance History: 
--
-- Date         Name  Version  Remarks 
-- -----------  ----  -------  -------------------------------------------------------
-- 03-JAN-2018  RRAJ    1.0     Initial version
-- 03-MAR-2020  CRA     1.1     Implement Case 00002205
--------------------------------------------------------------------------------------
***************************************************************************************/
    
    /**
     * Method to create document checklists for opportunities depending on the school of interest of each opportunity
     * @param lstOpp    List of opportunities for which to create document checklists
     * @param lstAppDoc list of application documents used by school
     */
    public static void createDocChklst(List<Opportunity> lstOpp, List<ApplicationDocument__c> lstAppDoc){
        List<DocumentChecklist__c> lstDocChklstToInsert = new List<DocumentChecklist__c>();
        //build map of school => list of app doc
        Map<Id, List<ApplicationDocument__c>> mapSchoolIdToAppDoc = new Map<Id, List<ApplicationDocument__c>>();
        for(ApplicationDocument__c appDoc : lstAppDoc){
            if(mapSchoolIdToAppDoc.containsKey(appDoc.School__c)){
                mapSchoolIdToAppDoc.get(appDoc.School__c).add(appDoc);
            }else{
                mapSchoolIdToAppDoc.put(appDoc.School__c, new List<ApplicationDocument__c>{appDoc});
            }
        }
        //create document checklist for each opportunity related to shcool
        for(Opportunity opp : lstOpp){
            //if opp = juliart then use 2nd map
            if(mapSchoolIdToAppDoc.containsKey(opp.SchoolOfInterest__c)){
                for(ApplicationDocument__c appDoc : mapSchoolIdToAppDoc.get(opp.SchoolOfInterest__c)){
                    //afo if beau soleil and summer camps
                    if(Schema.SObjectType.Opportunity.getRecordTypeInfosById().get(opp.RecordTypeId).getName() == AP_Constant.oppRecordTypeJulliardSummerArtsLabel
                       && opp.TECH_SchoolCode__c == 'CBS'){
                           if(appDoc.RecordType__c == AP_Constant.oppRecordTypeJulliardSummerArtsLabel){
                               DocumentChecklist__c docChklst = new DocumentChecklist__c(
                                   Opportunity__c = opp.Id,
                                   ApplicationDocument__c = appDoc.Id,
                                   Name = appDoc.Name,
                                   Status__c = AP_Constant.docChklstStatusRequested,
                                   //edit CRA - 1407 
                                   Required__c = Schema.SObjectType.Opportunity.getRecordTypeInfosById().get(opp.RecordTypeId).getName() == AP_Constant.oppRecordTypeJulliardSummerArtsLabel 
                                   && appDoc.Name != Label.AppDocNameApplicationForm ? false : appDoc.Required__c, 
                                   Stage__c = appDoc.Stage__c,
                                   recordtype__c = appDoc.RecordType__c,
                                   yeargrade__c = appDoc.YearGrade__c
                               );
                               lstDocChklstToInsert.add(docChklst);
                           }
                       }
                    else if(appDoc.RecordType__c != AP_Constant.oppRecordTypeJulliardSummerArtsLabel || 
                            (Schema.SObjectType.Opportunity.getRecordTypeInfosById().get(opp.RecordTypeId).getName() == AP_Constant.oppRecordTypeJulliardSummerArtsLabel
                             && opp.TECH_SchoolCode__c != 'CBS')){
                                 
                                 DocumentChecklist__c docChklst = new DocumentChecklist__c(
                                     Opportunity__c = opp.Id,
                                     ApplicationDocument__c = appDoc.Id,
                                     Name = appDoc.Name,
                                     Status__c = AP_Constant.docChklstStatusRequested,
                                     //edit CRA - 1407 
                                     Required__c = Schema.SObjectType.Opportunity.getRecordTypeInfosById().get(opp.RecordTypeId).getName() == AP_Constant.oppRecordTypeJulliardSummerArtsLabel 
                                     && appDoc.Name != Label.AppDocNameApplicationForm ? false : appDoc.Required__c, 
                                     Stage__c = appDoc.Stage__c,
                                     recordtype__c = appDoc.RecordType__c,
                                     yeargrade__c = appDoc.YearGrade__c
                                 );
                                 lstDocChklstToInsert.add(docChklst); 
                                 
                             }
                }
            }
        }
        //insert newly created document checklist
        if(lstDocChklstToInsert.size() > 0){
            insert lstDocChklstToInsert;
        }
    }

    /**
     * Method to create document checklist on opportunities when a new application document is created
     * @param lstNewAppDoc list of created application documents
     */
    public static void createAppDocDocumentChecklists(List<ApplicationDocument__c> lstNewAppDoc){
        List<Id> lstSchoolId = new List<Id>();
        for(ApplicationDocument__c appDoc : lstNewAppDoc){
            lstSchoolId.add(appDoc.School__c);
        }
        //Query list of opportunities having same school as application document
        List<Opportunity> lstOpp = [SELECT Id, Name, SchoolOfInterest__c, TECH_SchoolCode__c, RecordTypeId FROM Opportunity WHERE SchoolOfInterest__c IN :lstSchoolId];
        createDocChklst(lstOpp, lstNewAppDoc);
    }

    /**
     * Method to create document checklist on opportunities after insert
     * @param lstNewOpp List of newly created opportunities
     */
    public static void createOppDocumentChecklists(List<Opportunity> lstNewOpp){
        List<Id> lstSchoolId = new List<Id>();
        for(Opportunity opp: lstNewOpp){
            lstSchoolId.add(opp.SchoolOfInterest__c);
        }
        //Query list of application documents related to school associated with opportunity
        List<ApplicationDocument__c> lstAppDoc = [SELECT Id, Name, School__c, Stage__c, Required__c, RecordType__c, yeargrade__c
                                                  FROM ApplicationDocument__c WHERE School__c IN :lstSchoolId];
        createDocChklst(lstNewOpp, lstAppDoc);
    } 

    /**
    * @description Create document checklist on opportunities after update - Case 00002205
    * @author CRA | 03/03/2020 
    * @param mapOpp Map of updated opportunties
    * @param setSchId  Set of School Interest Ids of the updated opportunities
    * @return void 
    **/
    public static void createOppDocumentChecklistsAfterUpdate(Map<Id, Opportunity> mapOpp, Set<Id> setSchId) {
        Set<Id> setSchoolId = new Set<Id>();

        //check if the updated opportunities do not have any DocumentChecklist and we create
        for (DocumentChecklist__c docCheck : [SELECT Id, Opportunity__r.SchoolOfInterest__c, Opportunity__c FROM DocumentChecklist__c WHERE Opportunity__c IN :mapOpp.keySet()]) {
            setSchoolId.remove(docCheck.Opportunity__r.SchoolOfInterest__c);
            mapOpp.remove(docCheck.Opportunity__c);
        }
        
        //Query list of application documents related to school associated with opportunity
        List<ApplicationDocument__c> lstAppDoc = [SELECT Id, Name, School__c, Stage__c, Required__c, RecordType__c, yeargrade__c
                                                  FROM ApplicationDocument__c WHERE School__c IN :setSchId];
        
        if (lstAppDoc.size() > 0 && mapOpp.values().size() > 0) {
            createDocChklst(mapOpp.values(), lstAppDoc);
        }                                      
    }
}