force-app/main/default/objects/ApplicationDocument__c/ApplicationDocument__c.object-meta.xml
<CustomObject>
    <label>Application Document</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Application Documents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CS_Bypass__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Setup tool to configure whether a user can execute trigger, workflow rule, validation rule or process builder</description>
    <fields>
        <fullName>BypassTrigger__c</fullName>
        <label>Bypass Trigger</label>
        <type>TextArea</type>
    </fields>
    <label>CS_Bypass</label>
</CustomObject>

force-app/main/default/classes/ApplicationDocumentTriggerHandler.cls
public class ApplicationDocumentTriggerHandler {
/**************************************************************************************
-- - Author        : Spoon Consulting
-- - Description   : Application Document Trigger Handler Class
--
-- Maintenance History: 
--
-- Date         Name  Version  Remarks 
-- -----------  ----  -------  ------------------------------------------------------- 
-- 03-JAN-2018  RRAJ   1.0     Initial Version
--------------------------------------------------------------------------------------
**************************************************************************************/
    
    private CS_Bypass__c userBypass;
    public ApplicationDocumentTriggerHandler() {
        userBypass = CS_Bypass__c.getInstance(UserInfo.getUserId());
    }

    public void handleAfterInsert(List<ApplicationDocument__c> lstNewAppDoc){
        if(userBypass.BypassTrigger__c == NULL || !userBypass.BypassTrigger__c.contains('AP04')){
            AP04_CreateDocumentChecklist.createAppDocDocumentChecklists(lstNewAppDoc);
        }
    }

}