force-app/main/default/objects/Class__c/Class__c.object-meta.xml
<CustomObject>
    <label>Class</label>
    <nameField>
        <label>Class Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Classes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Class__c/fields/FemaleCount__c.field-meta.xml
<CustomField>
    <fullName>FemaleCount__c</fullName>
    <label>Female Count</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Class__c/fields/MaleCount__c.field-meta.xml
<CustomField>
    <fullName>MaleCount__c</fullName>
    <label>Male Count</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Class__c</fullName>
        <description>Defaults:
From Lead Convert: Will be &apos;Pending&apos; for schools without campus options and any of the 3 &apos;Pending&apos; options for schools with campus options (&apos;Not Sure&apos; = &apos;Pending&apos;)
From Student Clone: Will be copied from the record that is cloned as it cannot be blank and can therefore not revert to the default of &apos;Pending&apos;.</description>
        <inlineHelpText>A to H = Campus 1 (Krylatskoe/CF)
I to P = Campus 2 (Rosinka/ CJ)</inlineHelpText>
        <label>Class</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>School_Controlling_Picklist1__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                    <default>true</default>
                    <label>Pending</label>
                </value>
                <value>
                    <fullName>Pending (Campus 1: A-H)</fullName>
                </value>
                <value>
                    <fullName>Pending (Campus 2: I-P)</fullName>
                </value>
                <value>
                    <fullName>A</fullName>
                </value>
                <value>
                    <fullName>B</fullName>
                </value>
                <value>
                    <fullName>C</fullName>
                </value>
                <value>
                    <fullName>D</fullName>
                </value>
                <value>
                    <fullName>E</fullName>
                </value>
                <value>
                    <fullName>F</fullName>
                </value>
                <value>
                    <fullName>G</fullName>
                </value>
                <value>
                    <fullName>H</fullName>
                </value>
                <value>
                    <fullName>I</fullName>
                </value>
                <value>
                    <fullName>J</fullName>
                </value>
                <value>
                    <fullName>K</fullName>
                </value>
                <value>
                    <fullName>L</fullName>
                </value>
                <value>
                    <fullName>M</fullName>
                </value>
                <value>
                    <fullName>N</fullName>
                </value>
                <value>
                    <fullName>O</fullName>
                </value>
                <value>
                    <fullName>P</fullName>
                </value>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
                <value>
                    <fullName>4</fullName>
                </value>
                <value>
                    <fullName>5</fullName>
                </value>
                <value>
                    <fullName>[House] 1</fullName>
                </value>
                <value>
                    <fullName>[House] 2</fullName>
                </value>
                <value>
                    <fullName>[House] 3</fullName>
                </value>
                <value>
                    <fullName>[House] 4</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Gender__c</fullName>
        <label>Gender</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Gender_Options</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/globalValueSets/Gender_Options.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Male</fullName>
    </customValue>
    <customValue>
        <fullName>Female</fullName>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
    </customValue>
    <customValue>
        <fullName>Prefer not to say</fullName>
    </customValue>
    <masterLabel>Gender Options</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/AP10_UpdateClass.cls
/**************************************************************************************
-- - Author        : Spoon Consulting
-- - Description   : School Capacity - Maintain Database for School Term/Programs on a per school level
--
-- Maintenance History: 
--
-- Date         Name  Version  Remarks 
-- -----------  ----  -------  ------------------------------------------------------- 
-- 31-JUL-2018  AMU   1.0     Initial Version
--------------------------------------------------------------------------------------
**************************************************************************************/
public with sharing class AP10_UpdateClass {

    /**
     * Update class when opportunity changes class.
     * @param      mapOldToNewOpp  Map old opp to new opp
     */
     
    public static void updateClass(Map<Opportunity, Opportunity> mapOldToNewOpp) {
        Map<Id, Class__c> mapIdToClass = getMapClass(mapOldToNewOpp);
        Map<String, String> mapOppIdToGender = getMapOppIdToGender(mapOldToNewOpp.keySet());
        Map<Id, Class__c> mapIdToClassUpd = new Map<Id, Class__c>(); 

        try {
             for(Opportunity oldOpp: mapOldToNewOpp.keySet()) {
                String gender = mapOppIdToGender.get(oldOpp.Id);
                String oldClassId = oldOpp.Class__c;
                String newClassId = mapOldToNewOpp.get(oldOpp).Class__c;

                if(mapIdToClass.containsKey(oldClassId)) {
                    if(gender == AP_Constant.conGenderFemale) {
                        if(mapIdToClass.get(oldClassId).FemaleCount__c > 0) {
                            mapIdToClass.get(oldClassId).FemaleCount__c -= 1;
                        }
                    }

                    else if(gender == AP_Constant.conGenderMale) {
                        if(mapIdToClass.get(oldClassId).MaleCount__c > 0) {
                            mapIdToClass.get(oldClassId).MaleCount__c -= 1;
                        }
                    }
                    mapIdToClassUpd.put(oldClassId, mapIdToClass.get(oldClassId));
                }

                if(mapIdToClass.containsKey(newClassId)) {
                    mapIdToClass.get(newClassId).FemaleCount__c = mapIdToClass.get(newClassId).FemaleCount__c != null? mapIdToClass.get(newClassId).FemaleCount__c : 0;
                    mapIdToClass.get(newClassId).MaleCount__c = mapIdToClass.get(newClassId).MaleCount__c != null? mapIdToClass.get(newClassId).MaleCount__c : 0;

                   // if((mapIdToClass.get(newClassId).MaleCount__c + mapIdToClass.get(newClassId).FemaleCount__c) < mapIdToClass.get(newClassId).Capacity__c) {
                         if(gender == AP_Constant.conGenderFemale) {
                            mapIdToClass.get(newClassId).FemaleCount__c += 1;
                        }

                        else if(gender == AP_Constant.conGenderMale) {
                            mapIdToClass.get(newClassId).MaleCount__c += 1;
                        }
                        mapIdToClassUpd.put(newClassId, mapIdToClass.get(newClassId));
                    //}
                }
            }

            if(mapIdToClassUpd.size() > 0) {
                update new List<Class__c>(mapIdToClassUpd.values());
            }
        } catch(Exception e) {
            System.debug(e.getMessage());
        }
    }

    /**
     * Get Map of classes.
     * @param      mapOldToNewOpp  Map of old to new opp
     * @return     Map of classes
     *
     **/ 
    public static Map<Id, Class__c> getMapClass(Map<Opportunity, Opportunity> mapOldToNewOpp){
         Set<Id> setAllClassesId = new Set<Id>();

        for(Opportunity oldOpp: mapOldToNewOpp.keySet()) {
            if(String.isNotBlank(oldOpp.Class__c)) {
                setAllClassesId.add(oldOpp.Class__c);
            }
            
            if(String.isNotBlank(mapOldToNewOpp.get(oldOpp).Class__c)) {
               setAllClassesId.add(mapOldToNewOpp.get(oldOpp).Class__c); 
            }
        }

        return new Map<Id, Class__c>([SELECT Id, FemaleCount__c, MaleCount__c, Capacity__c
                                                FROM Class__c WHERE Id IN :setAllClassesId]);
    }

    /**
     * Get the map opp to gender.
     * @param      setOpp  The set opp
     * @return     The map opp to gender.
     *
     **/
    public static Map<String, String> getMapOppIdToGender(Set<Opportunity> setOpp){
        Map<String, String> mapOppIdToGender = new Map<String, String>();

        for(Opportunity opp: [SELECT Child__r.Gender__c FROM Opportunity WHERE Id IN: setOpp]) {
            mapOppIdToGender.put(opp.Id, opp.Child__r.Gender__c);
        }
        return mapOppIdToGender;
    }
    
}