force-app/main/default/objects/Class__c/Class__c.object-meta.xml
<CustomObject>
    <label>Class</label>
    <nameField>
        <label>Class Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Classes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Class__c/fields/CapacityAvailable__c.field-meta.xml
<CustomField>
    <fullName>CapacityAvailable__c</fullName>
    <formula>CapacityTotal__c -  CapacityUsed__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Capacity Available</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Class__c/fields/CapacityTotal__c.field-meta.xml
<CustomField>
    <fullName>CapacityTotal__c</fullName>
    <label>Capacity Total</label>
    <summarizedField>ClassCapacity__c.CapacityTotal__c</summarizedField>
    <summaryFilterItems>
        <field>ClassCapacity__c.CurrentYear__c</field>
        <operation>equals</operation>
        <value>True</value>
    </summaryFilterItems>
    <summaryForeignKey>ClassCapacity__c.Class__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Class__c/fields/CapacityUsed__c.field-meta.xml
<CustomField>
    <fullName>CapacityUsed__c</fullName>
    <label>Capacity Used</label>
    <summarizedField>ClassCapacity__c.CapacityUsed__c</summarizedField>
    <summaryFilterItems>
        <field>ClassCapacity__c.CurrentYear__c</field>
        <operation>equals</operation>
        <value>True</value>
    </summaryFilterItems>
    <summaryForeignKey>ClassCapacity__c.Class__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Class__c/fields/SchoolName__c.field-meta.xml
<CustomField>
    <fullName>SchoolName__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>School Name</label>
    <referenceTo>School__c</referenceTo>
    <relationshipLabel>Classes</relationshipLabel>
    <relationshipName>Classes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Class__c/fields/YearGrade__c.field-meta.xml
<CustomField>
    <fullName>YearGrade__c</fullName>
    <label>Year/Grade</label>
    <referenceTo>YearGrade__c</referenceTo>
    <relationshipLabel>Classes</relationshipLabel>
    <relationshipName>Classes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ClassCapacity__c/ClassCapacity__c.object-meta.xml
<CustomObject>
    <description>NDM: Class capacity/ enrolment year</description>
    <label>Class Capacity</label>
    <nameField>
        <label>Class Capacity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Class Capacities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ClassCapacity__c/fields/CapacityAvailable__c.field-meta.xml
<CustomField>
    <fullName>CapacityAvailable__c</fullName>
    <formula>CapacityTotal__c - CapacityUsed__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Capacity Available</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ClassCapacity__c/fields/CapacityTotal__c.field-meta.xml
<CustomField>
    <fullName>CapacityTotal__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Capacity Total</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ClassCapacity__c/fields/CapacityUsed__c.field-meta.xml
<CustomField>
    <fullName>CapacityUsed__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Capacity Used</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ClassCapacity__c/fields/Class__c.field-meta.xml
<CustomField>
    <fullName>Class__c</fullName>
    <label>Class</label>
    <referenceTo>Class__c</referenceTo>
    <relationshipLabel>Class Capacities</relationshipLabel>
    <relationshipName>Class_Capacities</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ClassCapacity__c/fields/CurrentYear__c.field-meta.xml
<CustomField>
    <fullName>CurrentYear__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Current Year</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/EnrolmentPeriod__c/EnrolmentPeriod__c.object-meta.xml
<CustomObject>
    <label>Enrolment Period</label>
    <nameField>
        <label>Enrolment Period Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Enrolment Periods</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/EnrolmentPeriod__c/fields/SchoolName__c.field-meta.xml
<CustomField>
    <fullName>SchoolName__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>School Name</label>
    <referenceTo>School__c</referenceTo>
    <relationshipLabel>Enrolment Periods</relationshipLabel>
    <relationshipName>Enrolment_Periods</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/School__c.object
<CustomObject>
    <label>School</label>
    <nameField>
        <label>School Code/UID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Schools</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/School__c/fields/CapacityTotal__c.field-meta.xml
<CustomField>
    <fullName>CapacityTotal__c</fullName>
    <label>Capacity Total</label>
    <summarizedField>YearGrade__c.CapacityTotal__c</summarizedField>
    <summaryForeignKey>YearGrade__c.SchoolName__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/School__c/fields/CapacityUsed__c.field-meta.xml
<CustomField>
    <fullName>CapacityUsed__c</fullName>
    <label>Capacity Used</label>
    <summarizedField>YearGrade__c.CapacityUsed__c</summarizedField>
    <summaryForeignKey>YearGrade__c.SchoolName__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/School__c/fields/Reference_Date__c.field-meta.xml
<CustomField>
    <fullName>Reference_Date__c</fullName>
    <inlineHelpText>Update this to be the first day of your school year, this is used in the calculation of the Enrolment year on the opportunity</inlineHelpText>
    <label>Reference Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/User.object
<CustomObject>
    <fields>
        <fullName>School__c</fullName>
        <label>School</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>The British Schools Foundation</fullName>
                </value>
                <value>
                    <fullName>The British School of Guangzhou</fullName>
                </value>
                <value>
                    <fullName>The British School of Nanjing</fullName>
                </value>
                <value>
                    <fullName>The British International School of Marbella</fullName>
                </value>
                <value>
                    <fullName>The British School of Navarra</fullName>
                </value>
                <value>
                    <fullName>The British School of Tashkent</fullName>
                </value>
                <value>
                    <fullName>The British College of Brazil</fullName>
                </value>
                <value>
                    <fullName>The British International School of Kuala Lumpur</fullName>
                </value>
                <value>
                    <fullName>The International School of Moscow</fullName>
                </value>
                <value>
                    <fullName>Nord Anglia International School Manila</fullName>
                </value>
                <value>
                    <fullName>King&apos;s College Beijing</fullName>
                </value>
                <value>
                    <fullName>The British School Yangon</fullName>
                </value>
                <value>
                    <fullName>Ukraine International School</fullName>
                </value>
                <value>
                    <fullName>The New York International School</fullName>
                </value>
                <value>
                    <fullName>The British School of Brasilia</fullName>
                </value>
                <value>
                    <fullName>NAE</fullName>
                </value>
                <value>
                    <fullName>The British International School Yangon</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/YearGrade__c/YearGrade__c.object-meta.xml
<CustomObject>
    <label>Year/Grade</label>
    <nameField>
        <label>Year/Grade Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Years/Grades</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/YearGrade__c/fields/CapacityTotal__c.field-meta.xml
<CustomField>
    <fullName>CapacityTotal__c</fullName>
    <label>Capacity Total</label>
    <summarizedField>Class__c.CapacityTotal__c</summarizedField>
    <summaryForeignKey>Class__c.YearGrade__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/YearGrade__c/fields/CapacityUsed__c.field-meta.xml
<CustomField>
    <fullName>CapacityUsed__c</fullName>
    <label>Capacity Used</label>
    <summarizedField>Class__c.CapacityUsed__c</summarizedField>
    <summaryForeignKey>Class__c.YearGrade__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/YearGrade__c/fields/EnrolmentPeriod__c.field-meta.xml
<CustomField>
    <fullName>EnrolmentPeriod__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Enrolment Period</label>
    <referenceTo>EnrolmentPeriod__c</referenceTo>
    <relationshipLabel>Years/Grades</relationshipLabel>
    <relationshipName>YearsGrades</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/YearGrade__c/fields/SchoolName__c.field-meta.xml
<CustomField>
    <fullName>SchoolName__c</fullName>
    <label>School Name</label>
    <referenceTo>School__c</referenceTo>
    <relationshipLabel>Years/Grades</relationshipLabel>
    <relationshipName>Year_Groups2</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/BAT25_ClassCapacityInsert_TEST.cls
/**
 * @description       : BAT25 Test Class
 * @author            : Spoon Consulting
 * @group             : 
 * @last modified on  : 01-12-2021
 * @last modified by  : Spoon Consulting
 * Modifications Log 
 * Ver   Date         Author             Modification
 * 1.0   30-03-2021   FKH                Initial Version
**/
@isTest
public with sharing class BAT25_ClassCapacityInsert_TEST {
    static List<User> lstUser;
    static List<School__c> lstSchool;
    static List<YearGrade__c> lstYearGrade;
    static List<Class__c> lstClass;
    static List<ClassCapacity__c> lstClassCapacity;
    static List<EnrolmentPeriod__c> lstEnrolmentPeriod;


    static {
        lstUser = new List<User>{TestFactory.createUser('Test', TestFactory.getProfileAdminId())};
        insert lstUser;
        
        System.runAs(lstUser[0]){
            
            lstSchool = new List<School__c>{
                TestFactory.createSchool('School1', 'Address1', true, 'SC1'),
                TestFactory.createSchool('School2', 'Address2', true, 'SC2'),
                TestFactory.createSchool('School3', 'Address3', true, 'SC3'),
                TestFactory.createSchool('School4', 'Address4', false,'SC4')
            }; 
            
            lstSchool[2].Reference_Date__c = Date.newInstance(2012, 2, 2);
            lstSchool[3].Reference_Date__c = Date.newInstance(2012, 2, 2);
            insert lstSchool;

            lstEnrolmentPeriod = new List<EnrolmentPeriod__c>{
                TestFactory.createEnrolmentPeriod('EP1', lstSchool[0].id,'SC1EP1', Date.newInstance(2010, 2, 2), Date.newInstance(2011, 2, 2)),
                TestFactory.createEnrolmentPeriod('EP2', lstSchool[1].id,'SC2EP1', Date.newInstance(2010, 2, 2), Date.newInstance(2011, 2, 2)),
                TestFactory.createEnrolmentPeriod('EP3', lstSchool[2].id,'SC2EP3', Date.newInstance(2010, 2, 2), Date.newInstance(2011, 2, 2)),
                TestFactory.createEnrolmentPeriod('EP4', lstSchool[3].id,'SC2EP4', Date.newInstance(2010, 2, 2), Date.newInstance(2011, 2, 2))

            };

            insert lstEnrolmentPeriod;

            lstYearGrade = new List<YearGrade__c>{
                TestFactory.createYearGrade('YG1',lstSchool[0].id,12,14,lstEnrolmentPeriod[0].id),
                TestFactory.createYearGrade('YG2',lstSchool[1].id,13,15,lstEnrolmentPeriod[1].id),
                TestFactory.createYearGrade('YG3',lstSchool[2].id,13,15,lstEnrolmentPeriod[2].id),
                TestFactory.createYearGrade('YG3',lstSchool[3].id,13,15,lstEnrolmentPeriod[3].id)

            }; 

            insert lstYearGrade;

            lstClass = new List<Class__c>{
                 TestFactory.createClass('Class1S1',30 , lstYearGrade[0].id,lstSchool[0].id)
                ,TestFactory.createClass('Class2S2',60 , lstYearGrade[1].id,lstSchool[1].id)
                ,TestFactory.createClass('Class3S3',10 , lstYearGrade[2].id,lstSchool[2].id)
                ,TestFactory.createClass('Class344',10 , lstYearGrade[3].id,lstSchool[3].id)
            }; 

            insert lstClass;

            lstClassCapacity = new List<ClassCapacity__c>{
                TestFactory.createClassCapacity('Class1S1Cap1',30 , lstClass[0].id,Date.newInstance(2016, 2, 2),Date.newInstance(2017, 2, 2)),
                TestFactory.createClassCapacity('Class3S3Cap1',30 , lstClass[2].id,Date.newInstance(2016, 2, 2),Date.newInstance(2017, 2, 2))
            }; 

            insert lstClassCapacity; 
        }
    }   

    @isTest public static void test2() {
        System.runAs(lstUser[0]) {

            Test.StartTest();  
                Class__c newClass = TestFactory.createClass('Class2S2',60 , lstYearGrade[0].id,lstSchool[0].id);
                insert newClass;
            Test.StopTest();

            List<Class__c> lstInsertedClass= [SELECT Id, Name, SchoolName__c, SchoolName__r.Reference_Date__c, (SELECT Id, Name, StartDate__c, EndDate__c, CapacityUsed__c, CapacityTotal__c, CapacityAvailable__c, CurrentYear__c FROM Class_Capacities__r) FROM Class__c];
            System.assertEquals(1, lstInsertedClass[4].Class_Capacities__r.size());
        
        }
    }

    @isTest public static void test1() {
        System.runAs(lstUser[0]) {

            Test.StartTest();  
                SchedulableContext sc = null;
                BAT25_ClassCapacityInsert tsc = new BAT25_ClassCapacityInsert();
                tsc.execute(sc);
            Test.StopTest();

            List<Class__c> lstInsertedClass= [SELECT Id, Name, SchoolName__c, SchoolName__r.Reference_Date__c, (SELECT Id, Name, StartDate__c, EndDate__c, CapacityUsed__c, CapacityTotal__c, CapacityAvailable__c, CurrentYear__c FROM Class_Capacities__r) FROM Class__c];
            
            System.assertEquals(3, lstInsertedClass[0].Class_Capacities__r.size());
            System.assertEquals(2, lstInsertedClass[1].Class_Capacities__r.size());
            System.assertEquals(3, lstInsertedClass[2].Class_Capacities__r.size());          
            System.assertEquals(0, lstInsertedClass[3].Class_Capacities__r.size());          
        }
    }
    

}