force-app/main/default/objects/Class__c/Class__c.object-meta.xml
<CustomObject>
    <label>Class</label>
    <nameField>
        <label>Class Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Classes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Class__c/fields/CapacityAvailable__c.field-meta.xml
<CustomField>
    <fullName>CapacityAvailable__c</fullName>
    <formula>CapacityTotal__c -  CapacityUsed__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Capacity Available</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Class__c/fields/CapacityTotal__c.field-meta.xml
<CustomField>
    <fullName>CapacityTotal__c</fullName>
    <label>Capacity Total</label>
    <summarizedField>ClassCapacity__c.CapacityTotal__c</summarizedField>
    <summaryFilterItems>
        <field>ClassCapacity__c.CurrentYear__c</field>
        <operation>equals</operation>
        <value>True</value>
    </summaryFilterItems>
    <summaryForeignKey>ClassCapacity__c.Class__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Class__c/fields/CapacityUsed__c.field-meta.xml
<CustomField>
    <fullName>CapacityUsed__c</fullName>
    <label>Capacity Used</label>
    <summarizedField>ClassCapacity__c.CapacityUsed__c</summarizedField>
    <summaryFilterItems>
        <field>ClassCapacity__c.CurrentYear__c</field>
        <operation>equals</operation>
        <value>True</value>
    </summaryFilterItems>
    <summaryForeignKey>ClassCapacity__c.Class__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Class__c/fields/SchoolName__c.field-meta.xml
<CustomField>
    <fullName>SchoolName__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>School Name</label>
    <referenceTo>School__c</referenceTo>
    <relationshipLabel>Classes</relationshipLabel>
    <relationshipName>Classes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ClassCapacity__c/ClassCapacity__c.object-meta.xml
<CustomObject>
    <description>NDM: Class capacity/ enrolment year</description>
    <label>Class Capacity</label>
    <nameField>
        <label>Class Capacity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Class Capacities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ClassCapacity__c/fields/CapacityAvailable__c.field-meta.xml
<CustomField>
    <fullName>CapacityAvailable__c</fullName>
    <formula>CapacityTotal__c - CapacityUsed__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Capacity Available</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ClassCapacity__c/fields/CapacityTotal__c.field-meta.xml
<CustomField>
    <fullName>CapacityTotal__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Capacity Total</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ClassCapacity__c/fields/CapacityUsed__c.field-meta.xml
<CustomField>
    <fullName>CapacityUsed__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Capacity Used</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ClassCapacity__c/fields/Class__c.field-meta.xml
<CustomField>
    <fullName>Class__c</fullName>
    <label>Class</label>
    <referenceTo>Class__c</referenceTo>
    <relationshipLabel>Class Capacities</relationshipLabel>
    <relationshipName>Class_Capacities</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ClassCapacity__c/fields/CurrentYear__c.field-meta.xml
<CustomField>
    <fullName>CurrentYear__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Current Year</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ClassCapacity__c/fields/EnrolmentYear__c.field-meta.xml
<CustomField>
    <fullName>EnrolmentYear__c</fullName>
    <formula>IF((NOT(ISBLANK(StartDate__c)) &amp;&amp; NOT(ISBLANK(EndDate__c))), (TEXT(YEAR(StartDate__c)) +&quot;/&quot;+TEXT(YEAR(EndDate__c))), &quot;&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Enrolment Year</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Class__c</fullName>
        <description>Defaults:
From Lead Convert: Will be &apos;Pending&apos; for schools without campus options and any of the 3 &apos;Pending&apos; options for schools with campus options (&apos;Not Sure&apos; = &apos;Pending&apos;)
From Student Clone: Will be copied from the record that is cloned as it cannot be blank and can therefore not revert to the default of &apos;Pending&apos;.</description>
        <inlineHelpText>A to H = Campus 1 (Krylatskoe/CF)
I to P = Campus 2 (Rosinka/ CJ)</inlineHelpText>
        <label>Class</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>School_Controlling_Picklist1__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                    <default>true</default>
                    <label>Pending</label>
                </value>
                <value>
                    <fullName>Pending (Campus 1: A-H)</fullName>
                </value>
                <value>
                    <fullName>Pending (Campus 2: I-P)</fullName>
                </value>
                <value>
                    <fullName>A</fullName>
                </value>
                <value>
                    <fullName>B</fullName>
                </value>
                <value>
                    <fullName>C</fullName>
                </value>
                <value>
                    <fullName>D</fullName>
                </value>
                <value>
                    <fullName>E</fullName>
                </value>
                <value>
                    <fullName>F</fullName>
                </value>
                <value>
                    <fullName>G</fullName>
                </value>
                <value>
                    <fullName>H</fullName>
                </value>
                <value>
                    <fullName>I</fullName>
                </value>
                <value>
                    <fullName>J</fullName>
                </value>
                <value>
                    <fullName>K</fullName>
                </value>
                <value>
                    <fullName>L</fullName>
                </value>
                <value>
                    <fullName>M</fullName>
                </value>
                <value>
                    <fullName>N</fullName>
                </value>
                <value>
                    <fullName>O</fullName>
                </value>
                <value>
                    <fullName>P</fullName>
                </value>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
                <value>
                    <fullName>4</fullName>
                </value>
                <value>
                    <fullName>5</fullName>
                </value>
                <value>
                    <fullName>[House] 1</fullName>
                </value>
                <value>
                    <fullName>[House] 2</fullName>
                </value>
                <value>
                    <fullName>[House] 3</fullName>
                </value>
                <value>
                    <fullName>[House] 4</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Sibling_3__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sibling 3</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>The siblings shown in this field can only be in families other than this one within the same school e.g. half brother or sister.</errorMessage>
            <filterItems>
                <field>Opportunity.AccountId</field>
                <operation>notEqual</operation>
                <valueField>$Source.AccountId</valueField>
            </filterItems>
            <filterItems>
                <field>Opportunity.School_Controlling_Picklist__c</field>
                <operation>equals</operation>
                <valueField>$Source.School_Controlling_Picklist__c</valueField>
            </filterItems>
            <infoMessage>You must select a sibling in another family within the same school. These fields are not meant for siblings under the same family/parent account record.</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Sibling 3</relationshipLabel>
        <relationshipName>Opportunities1</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/School__c.object
<CustomObject>
    <label>School</label>
    <nameField>
        <label>School Code/UID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Schools</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/School__c/fields/CapacityTotal__c.field-meta.xml
<CustomField>
    <fullName>CapacityTotal__c</fullName>
    <label>Capacity Total</label>
    <summarizedField>YearGrade__c.CapacityTotal__c</summarizedField>
    <summaryForeignKey>YearGrade__c.SchoolName__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/School__c/fields/CapacityUsed__c.field-meta.xml
<CustomField>
    <fullName>CapacityUsed__c</fullName>
    <label>Capacity Used</label>
    <summarizedField>YearGrade__c.CapacityUsed__c</summarizedField>
    <summaryForeignKey>YearGrade__c.SchoolName__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/School__c/fields/IsNAESchool__c.field-meta.xml
<CustomField>
    <fullName>IsNAESchool__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is NAE School?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/School__c/fields/Reference_Date__c.field-meta.xml
<CustomField>
    <fullName>Reference_Date__c</fullName>
    <inlineHelpText>Update this to be the first day of your school year, this is used in the calculation of the Enrolment year on the opportunity</inlineHelpText>
    <label>Reference Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/BAT26_ClassCapacityUpdate.cls
/**
 * @File Name          : BAT26_ClassCapacityUpdate.cls
 * @Description        : Invocable methods for automatic capacityrecord update
 * @Author             : Spoon Consulting
 * @Group              : 
 * @Last Modified By   : VJA
 * @Last Modified On   : 08-FEB-2021, 10:00 am
 * @Modification Log   : 
 *==============================================================================
 * Ver         Date                     Author      Modification
 *==============================================================================
 * 1.0    08-FEB-2021, 10:00 am         VJA         Initial Version
**/
global class BAT26_ClassCapacityUpdate implements Database.Batchable<sObject>{

    global String query;
    global List<String> lstSchoolId;
    global Set<Id> setClassId;

    // Constructor for Specific classes
    global BAT26_ClassCapacityUpdate(Set<Id> setClassId){
        System.debug('##BAT26_ClassCapacityUpdate setClassId.size(): ' + setClassId.size());
        if(setClassId == null){
            setClassId = new Set<Id>();
        }
        this.setClassId = setClassId;
        query = buildQuery(setClassId, true);
    }

    global BAT26_ClassCapacityUpdate(){
        query = buildQuery(new Set<Id>{}, false);
    }

    global Database.QueryLocator start(Database.BatchableContext bc) {
        return Database.getQueryLocator(query);
    }
    
    global void execute(Database.BatchableContext bc, List<Class__c> lstClass){

        Map<String, List<Opportunity>> mapClassEnrolmentYearToOpportunityList;
        List<ClassCapacity__c> lstClassCapacityUpdate = new List<ClassCapacity__c>();
        System.debug('###lstClass: ' +  JSON.serialize(lstClass));

        for(Class__c cls : lstClass){
            mapClassEnrolmentYearToOpportunityList = new Map<String, List<Opportunity>>();
            System.debug('###cls.Opportunities1__r.size(): ' +  JSON.serialize(cls.Opportunities1__r.size()));

            if(cls.Opportunities1__r.size() > 0){ //create map of EY to list Of Opp for current class
                for(Opportunity opp : cls.Opportunities1__r){
                    if(opp.StageName == AP_Constant.oppStageNameEnrolled ||
                        opp.StageName == AP_Constant.oppStageNameStarted ||
                        opp.StageName == AP_Constant.oppStageNameAcceptance
                        // opp.StageName == AP_Constant.oppStageNameApplication
                    ){
                        if (mapClassEnrolmentYearToOpportunityList.containsKey(opp.Enrolment_Year__c)) {
                            mapClassEnrolmentYearToOpportunityList.get(opp.Enrolment_Year__c).add(opp);
                        }else{
                            mapClassEnrolmentYearToOpportunityList.put(opp.Enrolment_Year__c, new List<Opportunity> {opp});
                        }
                    }
                }
            }
            System.debug('###mapClassEnrolmentYearToOpportunityList: ' +  JSON.serialize(mapClassEnrolmentYearToOpportunityList));

            if(cls.Class_Capacities__r.size() > 0){ 

                for(ClassCapacity__c classCapacity : cls.Class_Capacities__r){
                    Integer oppListSize = 0;
                    if(mapClassEnrolmentYearToOpportunityList.get(classCapacity.EnrolmentYear__c) != null){
                        oppListSize = mapClassEnrolmentYearToOpportunityList.get(classCapacity.EnrolmentYear__c).size();
                    }
                    lstClassCapacityUpdate.add(new ClassCapacity__c( Id = classCapacity.Id, CapacityUsed__c = oppListSize));
                }

            }
        }

        if(lstClassCapacityUpdate.size() > 0){
            System.debug('###lstClassCapacityUpdate Size: ' +  lstClassCapacityUpdate.size());
            System.debug('###lstClassCapacityUpdate: ' +  JSON.serialize(lstClassCapacityUpdate));
            update lstClassCapacityUpdate;
        }
        
    }    

    global void finish(Database.BatchableContext bc){
        String jobName = 'BAT26_ClassCapacityUpdate' + System.now(); 
    }

    global String buildQuery(Set<Id> setClassId, Boolean hasCond){

        String query = 'SELECT Id, Name, SchoolName__c, SchoolName__r.Reference_Date__c, (SELECT Id, Name, StartDate__c, EndDate__c, CapacityUsed__c, CapacityTotal__c, CapacityAvailable__c, CurrentYear__c,EnrolmentYear__c  FROM Class_Capacities__r ORDER BY EndDate__c Desc), (SELECT Id, StageName, Enrolment_Year__c,EnrolledStartDate__c FROM Opportunities1__r) FROM Class__c WHERE SchoolName__c != null AND SchoolName__r.IsNAESchool__c = true ';
        
        if(hasCond){
            query += ' AND Id in : setClassId';
        }

        return query;
    }
}