force-app/main/default/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <formula>IF( 
   Count_Active_Contracts__c &gt; 0, 
   &quot;Employed&quot;,
   IF(
      Count_Signed_Not_started_Contracts__c &gt; 0,
      &quot;Signed-On&quot;,
      IF(
         Count_Expired_Contracts__c &gt; 0,
         &quot;Left&quot;, 
         IF( 
            Unsuccessful_Applicant__c = TRUE, 
            &quot;Unsuccessful Applicant&quot;, 
            &quot;Applicant&quot;
            )
         )
      )
   )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Status</label>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/CS_Bypass__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Setup tool to configure whether a user can execute trigger, workflow rule, validation rule or process builder</description>
    <fields>
        <fullName>BypassTrigger__c</fullName>
        <label>Bypass Trigger</label>
        <type>TextArea</type>
    </fields>
    <label>CS_Bypass</label>
</CustomObject>

force-app/main/default/classes/EventTriggerHandler.cls
/**************************************************************************************
-- - Author        : Spoon Consulting
-- - Description   : 
--
-- Maintenance History: 
--
-- Date         Name  Version  Remarks 
-- -----------  ----  -------  -------------------------------------------------------
-- 19-OCT-2018  AFO    1.0     Initial version
--------------------------------------------------------------------------------------
***************************************************************************************/
public class EventTriggerHandler {
    private CS_Bypass__c userBypass;
    
    public EventTriggerHandler(){
        userBypass = CS_Bypass__c.getInstance(UserInfo.getUserId());
    }
    
    public void handleAfterUpdate(List<Event> lstOldEvent, List<Event> lstNewEvent){
        List<Event> lstEvent = new List<Event>();
        Set<id> setAccId = new Set<id>();
        Set<id> setAccId2 = new Set<id>();
        
        for(Integer i = 0; i < lstNewEvent.size(); i++){
            if(userBypass.BypassTrigger__c == NULL || !userBypass.BypassTrigger__c.contains('AP17')){
                if(lstNewEvent[i].Status__c == AP_Constant.tskStatusCompleted && lstOldEvent[i].Status__c != AP_Constant.tskStatusCompleted){
                    String whatid = lstNewEvent[i].whatId;
                    if(whatid != null && whatid.startsWith('001')) {
                        lstEvent.add(lstNewEvent[i]);
                        setAccId.add(lstNewEvent[i].whatid);
                    }
                }
            }
            
            if(userBypass.BypassTrigger__c == NULL || !userBypass.BypassTrigger__c.contains('AP21')){
                if(lstNewEvent[i].WhatId != null){
                    String objectType = String.valueOf(lstNewEvent[i].WhatId.getSObjectType());
                    if(objectType == 'Account'){
                        setAccId2.add(lstNewEvent[i].WhatId);
                    }
                }
            }
            
        }
        
        if(setAccId2.size()>0){
            AP21_UpdateAccLastActivityDate.updateLastActivityDate(setAccId2);
        }
        
        if(setAccId.size()>0){
            AP17_EventRules.updateLastVisitDate(lstEvent, setAccId);
        }
        
        
    }
    
    public void handleAfterInsert(List<Event> lstNewEvent){
        List<Event> lstEvent = new List<Event>();
        Set<id> setAccId = new Set<id>();
        Set<id> setAccId2 = new Set<id>();
        
        for(Integer i = 0; i < lstNewEvent.size(); i++){
            if(userBypass.BypassTrigger__c == NULL || !userBypass.BypassTrigger__c.contains('AP17')){
                if(lstNewEvent[i].Status__c == AP_Constant.tskStatusCompleted){
                    String whatid = lstNewEvent[i].whatId;
                    if(whatid != null && whatid.startsWith('001')) {
                        lstEvent.add(lstNewEvent[i]);
                        setAccId.add(lstNewEvent[i].whatid);
                        System.debug('##2');
                    }
                }
            }
            
            if(userBypass.BypassTrigger__c == NULL || !userBypass.BypassTrigger__c.contains('AP21')){
                if(lstNewEvent[i].WhatId != null){
                    String objectType = String.valueOf(lstNewEvent[i].WhatId.getSObjectType());
                    if(objectType == 'Account'){
                        setAccId2.add(lstNewEvent[i].WhatId);
                    }
                }
            }
        }
        
        if(setAccId2.size()>0){
            AP21_UpdateAccLastActivityDate.updateLastActivityDate(setAccId2);
        }
        
        if(setAccId.size()>0){
            AP17_EventRules.updateLastVisitDate(lstEvent, setAccId);
        }
    }
    
}