force-app/main/default/objects/Account.object
<CustomObject>
    <fields>
        <fullName>School__c</fullName>
        <description>Copies the value of SchoolText (which is a workflow copying from School Formula). A little long winded solution to avoid bigger changes in the Teacher/Parent portal.</description>
        <formula>SchoolText__pc</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>School</label>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/ApplicationDocument__c/ApplicationDocument__c.object-meta.xml
<CustomObject>
    <label>Application Document</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Application Documents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ApplicationDocument__c/fields/School__c.field-meta.xml
<CustomField>
    <fullName>School__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>School</label>
    <referenceTo>School__c</referenceTo>
    <relationshipLabel>Application Documents</relationshipLabel>
    <relationshipName>ApplicationDocuments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/School__c.object
<CustomObject>
    <label>School</label>
    <nameField>
        <label>School Code/UID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Schools</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/School__c/fields/SchoolCode__c.field-meta.xml
<CustomField>
    <fullName>SchoolCode__c</fullName>
    <label>School Code</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User.object
<CustomObject>
    <fields>
        <fullName>School__c</fullName>
        <label>School</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>The British Schools Foundation</fullName>
                </value>
                <value>
                    <fullName>The British School of Guangzhou</fullName>
                </value>
                <value>
                    <fullName>The British School of Nanjing</fullName>
                </value>
                <value>
                    <fullName>The British International School of Marbella</fullName>
                </value>
                <value>
                    <fullName>The British School of Navarra</fullName>
                </value>
                <value>
                    <fullName>The British School of Tashkent</fullName>
                </value>
                <value>
                    <fullName>The British College of Brazil</fullName>
                </value>
                <value>
                    <fullName>The British International School of Kuala Lumpur</fullName>
                </value>
                <value>
                    <fullName>The International School of Moscow</fullName>
                </value>
                <value>
                    <fullName>Nord Anglia International School Manila</fullName>
                </value>
                <value>
                    <fullName>King&apos;s College Beijing</fullName>
                </value>
                <value>
                    <fullName>The British School Yangon</fullName>
                </value>
                <value>
                    <fullName>Ukraine International School</fullName>
                </value>
                <value>
                    <fullName>The New York International School</fullName>
                </value>
                <value>
                    <fullName>The British School of Brasilia</fullName>
                </value>
                <value>
                    <fullName>NAE</fullName>
                </value>
                <value>
                    <fullName>The British International School Yangon</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/classes/VFC03_ApplicationDocuments_TEST.cls
/**************************************************************************************
-- - Author        : Spoon Consulting
-- - Description   : Test class for C03_ApplicationDocuments
--
-- Maintenance History: 
--
-- Date         Name  Version  Remarks 
-- -----------  ----  -------  -------------------------------------------------------
-- 27-JUL-2018  AMU     1.0     Get list of Application documents for a particular school
--------------------------------------------------------------------------------------
***************************************************************************************/
@isTest
public with sharing class VFC03_ApplicationDocuments_TEST {
	static Map<string,Id> mapRecordType = new Map<String, Id>();
    static User testUserAdmin;
    static Account account;
    static List<School__c> lstSchool;
    static List<ApplicationDocument__c> lstAppDoc;

    static {
        //creating user
        testUserAdmin = TestFactory.createUser('testUserAdmin',TestFactory.getProfileAdminId());
        testUserAdmin.SchoolCode__c = 'PPE';
        insert testUserAdmin;

        System.runAs(testUserAdmin){

            mapRecordType = AP_Constant.getDeveloperIdMap(new Set<String>{AP_Constant.oppObject});
            //creating account
            account = TestFactory.createAccount('Henry Family');
            insert account;

            //creating school
            lstSchool = new List<School__c> {
                TestFactory.createSchool('Petit Verger School', 'Petit Verger', false, 'PVS'),
                TestFactory.createSchool('Le Petit Pouce Elementary School', 'Vivéa Business Park', false, 'PPE')
            };
            insert lstSchool;

            // creating application document
            lstAppDoc = new List<ApplicationDocument__c> {
                TestFactory.createApplicationDoc('Birth Certificate', lstSchool[0].Id, true, 'Application'), 
                TestFactory.createApplicationDoc('Transcript', lstSchool[0].Id, false, 'Acceptance'), 
                TestFactory.createApplicationDoc('Passport copy', lstSchool[0].Id, null, null), 
                TestFactory.createApplicationDoc('Health report' , lstSchool[1].Id, true, null), 
                TestFactory.createApplicationDoc('Transfert certificate', lstSchool[1].Id, false, 'Enrolled'), 
                TestFactory.createApplicationDoc('Resident proof', lstSchool[1].Id, null, 'Acceptance'), 
                TestFactory.createApplicationDoc('Application fee', lstSchool[1].Id, false, 'Application') 
            };
            insert lstAppDoc;
        }
    }

    @isTest
    static void getApplicationDocumentsTest() {
        System.runAs(testUserAdmin){            
            Test.startTest();
           		List<ApplicationDocument__c> lstAppDocs = new VFC03_ApplicationDocuments().getAppDocs();
            Test.stopTest();
            System.assertEquals(lstAppDocs.size(), 4);
        }
    }
}