force-app/main/default/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Account_Alternate_Email_Formula__c</fullName>
        <formula>Related_Contact_Record_P2__r.Contact_Alternate_Email__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Alternate Email (P2)</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Account_Alternate_Phone_Formula__c</fullName>
        <formula>Related_Contact_Record_P2__r.Contact_Alternate_Phone__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Alternate Phone (P2)</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Account_Main_Email_Formula__c</fullName>
        <formula>Related_Contact_Record_P2__r.Email</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Main Email (P2)</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Account_Mobile_Main_Phone_Formula__c</fullName>
        <formula>Related_Contact_Record_P2__r.MobilePhone</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Mobile/Main Phone (P2)</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>First_Parent_Full_Name__c</fullName>
        <formula>TEXT(Salutation) &amp;&quot; &quot;&amp; FirstName &amp;&quot; &quot;&amp;  LastName</formula>
        <label>Parent/Guardian 1 Full Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Primary_Contact__c</fullName>
        <description>Identifies which of the parents should be contacted first</description>
        <inlineHelpText>Which parent should be the first point of contact?</inlineHelpText>
        <label>Primary Contact</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>First Parent</fullName>
                    <default>true</default>
                    <label>First Parent</label>
                </value>
                <value>
                    <fullName>Second Parent</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Second_Parent_Full_Name__c</fullName>
        <formula>TEXT(Related_Contact_Record_P2__r.Salutation) &amp;&quot; &quot;&amp;  Related_Contact_Record_P2__r.FirstName &amp;&quot; &quot;&amp;  Related_Contact_Record_P2__r.LastName</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Parent/Guardian 2 Full Name</label>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Contact.object
<CustomObject>
    <recordTypes>
        <fullName>Contact</fullName>
        <active>true</active>
        <label>Contact</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/PortalContactPage_Controller.cls
/***
    Author: Kunal 
    Created Date: 06 July 2013
    Desc: VF controller for PortalContact Page
***/
public class PortalContactPage_Controller extends PortalReportFilter {
    public Account parentAccount {get;set;}
    //constructor
    public  PortalContactPage_Controller(){
        parentAccount  = [Select a.Account_Alternate_Phone_Formula__c, a.Account_Mobile_Main_Phone_Formula__c, a.Account_Alternate_Email_Formula__c, a.Primary_Contact__c, a.Phone, a.PersonEmail, a.Second_Parent_Full_Name__c, a.First_Parent_Full_Name__c, a.Contact_Alternate_Phone__pc, a.Contact_Alternate_Email__pc, a.Account_Main_Email_Formula__c From Account a where a.Id=:parentAccountId];
    }
    
    public PageReference saveAccount(){
        try{
            //validate parent selection
            String message ;
            if(parentAccount.Primary_Contact__c == 'First Parent' && parentAccount.PersonEmail == null){
                message = 'Invalid input: Please provide main email for First Parent !';
            }else if(parentAccount.Primary_Contact__c == 'Second Parent' && parentAccount.Account_Main_Email_Formula__c == null){
                message = 'Invalid input: Please provide main email for Second Parent !';
            }
            if(message == null){
                update parentAccount;
                ApexPages.Message successMessage = new ApexPages.Message(ApexPages.severity.CONFIRM, 'Changes Saved. Thanks for updating your contact details.');
                ApexPages.addMessage(successMessage);
            }else{
                ApexPages.Message errorMessage = new ApexPages.Message(ApexPages.severity.FATAL, message);
                ApexPages.addMessage(errorMessage);
            }
        }catch(Exception e){
            ApexPages.Message errorMessage = new ApexPages.Message(ApexPages.severity.FATAL, 'Ooops something went wrong. Error Message: '+e.getMessage());
            ApexPages.addMessage(errorMessage);
        }
        return null;
    }
}