force-app/main/default/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Error_Message__c</fullName>
        <label>Error Message</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>School__c</fullName>
        <description>Copies the value of SchoolText (which is a workflow copying from School Formula). A little long winded solution to avoid bigger changes in the Teacher/Parent portal.</description>
        <formula>SchoolText__pc</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>School</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Starting_Date__c</fullName>
        <label>Starting Date (Account)</label>
        <summarizedField>Opportunity.CloseDate</summarizedField>
        <summaryFilterItems>
            <field>Opportunity.Probability</field>
            <operation>equals</operation>
            <value>100</value>
        </summaryFilterItems>
        <summaryForeignKey>Opportunity.AccountId</summaryForeignKey>
        <summaryOperation>min</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <formula>IF( 
   Count_Active_Contracts__c &gt; 0, 
   &quot;Employed&quot;,
   IF(
      Count_Signed_Not_started_Contracts__c &gt; 0,
      &quot;Signed-On&quot;,
      IF(
         Count_Expired_Contracts__c &gt; 0,
         &quot;Left&quot;, 
         IF( 
            Unsuccessful_Applicant__c = TRUE, 
            &quot;Unsuccessful Applicant&quot;, 
            &quot;Applicant&quot;
            )
         )
      )
   )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Status</label>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice_Export__c.object
<CustomObject>
    <description>Invoices as exported from Xero. Used to clean up invoice numbers and xero ids.</description>
    <fields>
        <fullName>AmountDue__c</fullName>
        <label>AmountDue</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>AmountPaid__c</fullName>
        <label>AmountPaid</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ContactID__c</fullName>
        <label>ContactID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ContactName__c</fullName>
        <label>ContactName</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CurrencyCode__c</fullName>
        <label>CurrencyCode</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>DueDate__c</fullName>
        <label>DueDate</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>FullyPaidOnDate__c</fullName>
        <label>FullyPaidOnDate</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>InvoiceNumber__c</fullName>
        <label>InvoiceNumber</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IsMatched__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Matched</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>LineAmountTypes__c</fullName>
        <label>LineAmountTypes</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Reference_Short__c</fullName>
        <label>Reference Short</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Reference__c</fullName>
        <label>Reference</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>School__c</fullName>
        <label>School</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SubTotal__c</fullName>
        <label>SubTotal</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Total__c</fullName>
        <label>Total</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>UpdatedDate__c</fullName>
        <label>UpdatedDate</label>
        <type>DateTime</type>
    </fields>
    <label>Invoice Export</label>
    <nameField>
        <label>Invoice ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoice Exports</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice_Statement__c.object
<CustomObject>
    <fields>
        <fullName>Currency__c</fullName>
        <label>Currency</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Error_Message__c</fullName>
        <label>Error Message</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Generated_Date__c</fullName>
        <label>Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Invoice_Date__c</fullName>
        <label>Invoice Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Invoice_Export_Error__c</fullName>
        <label>Invoice Export Error</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Invoice_Export_Fixed__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Invoice Export Fixed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Invoice_Export__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Invoice Export</label>
        <referenceTo>Invoice_Export__c</referenceTo>
        <relationshipLabel>Invoices</relationshipLabel>
        <relationshipName>Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Link_to_Xero_Invoice__c</fullName>
        <formula>IF( Xero_Invoice_Status__c = &quot;Draft&quot;, HYPERLINK(&quot;https://go.xero.com/AccountsReceivable/Edit.aspx?InvoiceID=&quot;&amp; Xero_Id__c, &quot;Click Here&quot;), HYPERLINK(&quot;https://go.xero.com/AccountsReceivable/View.aspx?InvoiceID=&quot;&amp; Xero_Id__c, &quot;Click Here&quot;))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Link to Xero Invoice</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Owner_School__c</fullName>
        <formula>IF(Payer__r.RecordType.Name = &quot;Company&quot;, Payer__r.Company_School__c, Payer__r.SchoolText__pc)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Owner School</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Payer__c</fullName>
        <label>Parent/Company</label>
        <lookupFilter>
            <active>false</active>
            <booleanFilter>1 OR 2</booleanFilter>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Company</value>
            </filterItems>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Parent</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Invoices</relationshipLabel>
        <relationshipName>Invoice_Statements1</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Reference_Short__c</fullName>
        <label>Reference Short</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Reference__c</fullName>
        <label>Reference</label>
        <length>10000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>School__c</fullName>
        <label>School</label>
        <length>32</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Single_Invoice__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Single Invoice</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Starting_Date__c</fullName>
        <label>Starting Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Total_Invoice_Value_Calculated__c</fullName>
        <label>Total Invoice Value Calculated</label>
        <summarizedField>Line_Item__c.Unit_Price__c</summarizedField>
        <summaryForeignKey>Line_Item__c.Invoice_Statement__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Total_Invoice_Value__c</fullName>
        <formula>Currency__c &amp;&quot; &quot;&amp; 
IF(
Total_Invoice_Value_Calculated__c &gt;= 1000000,
TEXT(FLOOR(Total_Invoice_Value_Calculated__c / 1000000)) &amp; &quot;,&quot;,
&quot;&quot;) &amp;
IF(
Total_Invoice_Value_Calculated__c &gt;= 1000,
RIGHT(TEXT(FLOOR(Total_Invoice_Value_Calculated__c / 1000)), 3) &amp; &quot;,&quot;,
&quot;&quot;) &amp;
RIGHT(TEXT(FLOOR(Total_Invoice_Value_Calculated__c)), 3) &amp; &quot;.&quot; &amp;
IF(
MOD(Total_Invoice_Value_Calculated__c , 1) * 100 &lt; 10,
&quot;0&quot; &amp; TEXT(ROUND(MOD(Total_Invoice_Value_Calculated__c , 1), 2) * 100),
TEXT(MIN(ROUND(MOD(Total_Invoice_Value_Calculated__c , 1), 2) * 100, 99))
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Total Invoice Value</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Total_Xero_Payments_Calculated__c</fullName>
        <label>Total Xero Payments Calculated</label>
        <summarizedField>Xero_Payment__c.Payment_Amount__c</summarizedField>
        <summaryFilterItems>
            <field>Xero_Payment__c.Status__c</field>
            <operation>notEqual</operation>
            <value>DELETED</value>
        </summaryFilterItems>
        <summaryForeignKey>Xero_Payment__c.Invoice_Statement__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Total_Xero_Payments__c</fullName>
        <formula>Xero_Invoice_Currency__c &amp;&quot; &quot;&amp; 
IF( 
Total_Xero_Payments_Calculated__c &gt;= 1000000, 
TEXT(FLOOR(Total_Xero_Payments_Calculated__c / 1000000)) &amp; &quot;,&quot;, 
&quot;&quot;) &amp; 
IF( 
Total_Xero_Payments_Calculated__c &gt;= 1000, 
RIGHT(TEXT(FLOOR(Total_Xero_Payments_Calculated__c / 1000)), 3) &amp; &quot;,&quot;, 
&quot;&quot;) &amp; 
RIGHT(TEXT(FLOOR(Total_Xero_Payments_Calculated__c)), 3) &amp; &quot;.&quot; &amp; 
IF( 
MOD(Total_Xero_Payments_Calculated__c , 1) * 100 &lt; 10, 
&quot;0&quot; &amp; TEXT(ROUND(MOD(Total_Xero_Payments_Calculated__c , 1), 2) * 100), 
TEXT(MIN(ROUND(MOD(Total_Xero_Payments_Calculated__c , 1), 2) * 100, 99)) 
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Total Xero Payments</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Xero_Id__c</fullName>
        <inlineHelpText>The value in this field must be unique. If you need to manually link this invoice to a Xero invoice then please send the URL of both, in a spreadsheet, to the relevant member of the group management team</inlineHelpText>
        <label>Xero Id</label>
        <length>64</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Xero_Invoice_Currency__c</fullName>
        <label>Xero Invoice Currency</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Xero_Invoice_Date__c</fullName>
        <label>Xero Invoice Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Xero_Invoice_Number__c</fullName>
        <label>Xero Invoice Number</label>
        <length>64</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Xero_Invoice_Status__c</fullName>
        <formula>CASE( Xero_Status__c , &quot;DRAFT&quot;, &quot;Draft&quot;, &quot;SUBMITTED&quot;, &quot;Awaiting Approval&quot;, &quot;VOIDED&quot;, &quot;Voided&quot;, &quot;DELETED&quot;, &quot;Deleted&quot;, &quot;PAID&quot;, &quot;Paid&quot;, IF( AND ( Xero_Status__c = &quot;AUTHORISED&quot; , Total_Xero_Payments_Calculated__c = 0 ), &quot;Awaiting Payment&quot;, IF( AND ( Xero_Status__c = &quot;AUTHORISED&quot; , Total_Xero_Payments_Calculated__c &gt; 0 ), &quot;Partially Paid&quot;, &quot;ERROR&quot; ) ) )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Xero Invoice Status</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Xero_Invoice_Value__c</fullName>
        <formula>Xero_Invoice_Currency__c &amp;&quot; &quot;&amp; 
IF( 
Xero_Value__c &gt;= 1000000, 
TEXT(FLOOR(Xero_Value__c / 1000000)) &amp; &quot;,&quot;, 
&quot;&quot;) &amp; 
IF( 
Xero_Value__c &gt;= 1000, 
RIGHT(TEXT(FLOOR(Xero_Value__c / 1000)), 3) &amp; &quot;,&quot;, 
&quot;&quot;) &amp; 
RIGHT(TEXT(FLOOR(Xero_Value__c)), 3) &amp; &quot;.&quot; &amp; 
IF( 
MOD(Xero_Value__c , 1) * 100 &lt; 10, 
&quot;0&quot; &amp; TEXT(ROUND(MOD(Xero_Value__c , 1), 2) * 100), 
TEXT(MIN(ROUND(MOD(Xero_Value__c , 1), 2) * 100, 99)) 
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Xero Invoice Value</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Xero_Status__c</fullName>
        <label>Xero Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Xero_Value__c</fullName>
        <label>Xero Value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Invoice</label>
    <nameField>
        <displayFormat>{YY}-{00000}</displayFormat>
        <label>Salesforce UID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/School__c.object
<CustomObject>
    <label>School</label>
    <nameField>
        <label>School Code/UID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Schools</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/BatchFixInvoices.cls
global class BatchFixInvoices implements Database.Batchable<sObject> {
	
	String query;
	
	global BatchFixInvoices() {
		query = 'SELECT Id, OwnerId, IsDeleted, Name, CurrencyIsoCode, CreatedDate, CreatedById, LastModifiedDate, LastModifiedById, SystemModstamp, '
			+ 'Currency__c, Error_Message__c, Payer__c, Reference__c, Reference_Short__c, Starting_Date__c, Xero_Id__c, School__c, Generated_Date__c, Invoice_Date__c, '
			+ 'Total_Invoice_Value_Calculated__c, Total_Invoice_Value__c, Xero_Invoice_Number__c, Single_Invoice__c, Owner_School__c, Xero_Invoice_Date__c, '
			+ 'Xero_Status__c, Xero_Value__c, Xero_Invoice_Currency__c, Xero_Invoice_Status__c, Total_Xero_Payments_Calculated__c, Total_Xero_Payments__c, '
			+ 'Xero_Invoice_Value__c, Link_to_Xero_Invoice__c, Payer__r.Name '
			+ 'FROM Invoice_Statement__c '
			+ 'WHERE Xero_Invoice_Number__c = null AND Invoice_Export_Fixed__c = false AND Invoice_Export__c = null';
	}
	
	global Database.QueryLocator start(Database.BatchableContext BC) {
		return Database.getQueryLocator(query);
	}

	global void execute(Database.BatchableContext BC, List<Invoice_Statement__c> scope) {

		Invoice_Statement__c invoice = scope[0];

		List<Invoice_Export__c> queryMatches = [
			SELECT Id, OwnerId, IsDeleted, Name, CurrencyIsoCode, CreatedDate, CreatedById, LastModifiedDate, LastModifiedById, SystemModstamp,
				Status__c, LineAmountTypes__c, School__c, Reference__c, Date__c, DueDate__c, Type__c, SubTotal__c, Total__c,
				AmountDue__c, AmountPaid__c, InvoiceNumber__c, FullyPaidOnDate__c, CurrencyCode__c, ContactID__c, ContactName__c,
				Reference_Short__c, (
					SELECT Id FROM Invoices__r
				)
			FROM Invoice_Export__c
			WHERE Type__c = 'ACCREC'
			AND LineAmountTypes__c = 'Inclusive'
			//AND Status__c != 'DELETED'
			//AND Reference_Short__c = :invoice.Reference_Short__c
			AND ContactName__c = :invoice.Payer__r.Name
			//AND CurrencyCode__c = :invoice.Currency__c
			AND Date__c = :invoice.Invoice_Date__c
			//AND DueDate__c = :invoice.Generated_Date__c
			//AND InvoiceNumber__c = :invoice.Xero_Invoice_Number__c
			//AND School__c = :invoice.School__c
			AND School__c = :invoice.School__c
			//AND Total__c = :invoice.Total_Invoice_Value_Calculated__c
			AND IsMatched__c = false
			//AND UpdatedDate__c >= :invoice.CreatedDate
		];

		List<Invoice_Export__c> exactMatches = new List<Invoice_Export__c>();
		for(Invoice_Export__c exp : queryMatches) {
			if (exp.Invoices__r.size() == 0) {
				exactMatches.add(exp);
			}
		}
		if (exactMatches.size() == 1) {
			invoice.Invoice_Export__c = exactMatches[0].Id;
			invoice.Invoice_Export_Error__c = '';
		}
		else if (exactMatches.size() > 1) {
			invoice.Invoice_Export_Error__c = '';
			for (Invoice_Export__c exp : exactMatches) {
				if (invoice.Invoice_Export_Error__c != '') {
					invoice.Invoice_Export_Error__c += '\n';
				}
				invoice.Invoice_Export_Error__c += exp.Id;
			}
			if (invoice.Invoice_Export_Error__c.length() > 255) {
				invoice.Invoice_Export_Error__c = invoice.Invoice_Export_Error__c.left(255);
			}
		}
		else {
			invoice.Invoice_Export__c = null;
			invoice.Invoice_Export_Error__c = 'No Matches';
		}

		update invoice;

		/*List<Invoice_Export__c> fuzzyQuery = [
			SELECT Id, OwnerId, IsDeleted, Name, CurrencyIsoCode, CreatedDate, CreatedById, LastModifiedDate, LastModifiedById, SystemModstamp,
				Status__c, LineAmountTypes__c, School__c, Reference__c, Date__c, DueDate__c, Type__c, SubTotal__c, Total__c,
				AmountDue__c, AmountPaid__c, InvoiceNumber__c, FullyPaidOnDate__c, CurrencyCode__c, ContactID__c, ContactName__c,
				Reference_Short__c,
			(
				SELECT Id FROM Invoices__r
			)
			FROM Invoice_Export__c
			WHERE Type__c = 'ACCREC'
			//AND Status__c != 'DELETED'
			AND Reference_Short__c = :invoice.Reference_Short__c
			AND CurrencyCode__c = :invoice.Currency__c
			AND Date__c = :invoice.Invoice_Date__c
			AND School__c = :invoice.School__c
			AND Total__c = :invoice.Total_Invoice_Value_Calculated__c
		];

		List<Invoice_Export__c> fuzzyMatches = new List<Invoice_Export__c>();
		for (Invoice_Export__c exp : fuzzyQuery) {
			if (exp.Invoice_Statements__r.size() == 0) {
				fuzzyMatches.add(exp);
			}
		}

		if (exactMatches.size() == 1) {
			invoice.Invoice_Export__c = exactMatches[0].Id;
			invoice.Invoice_Export_Error__c = '';
		}
		else if (exactMatches.size() > 1) {
			invoice.Invoice_Export_Error__c = 'Multiple possible exact matches';
		}
		else if (fuzzyMatches.size() == 1) {
			invoice.Invoice_Export__c = fuzzyMatches[0].Id;
			invoice.Invoice_Export_Error__c = '';
		}
		else if (fuzzyMatches.size() > 1) {

			invoice.Invoice_Export_Error__c = 'Multiple possible fuzzy matches';
		}
		else if (fuzzyMatches.size() == 0) {
			invoice.Invoice_Export_Error__c = 'No fuzzy or exact matches';
		}*/

		//update invoice;

		//School -> Date -> Value -> Invoices

		/*List<String> schoolNames = new List<String>();
		List<String> invoiceNumbers = new List<String>();
		for (Invoice_Statement__c inv : scope) {
			schoolNames.add(inv.School__c);
			invoiceNumbers.add(inv.Xero_Invoice_Number__c);
		}

		List<Invoice_Export__c> matches = [
			SELECT Id, Name, School__c, InvoiceNumber__c, Reference__c
			FROM Invoice_Export__c
			WHERE School__c IN :schoolNames
			AND InvoiceNumber__c IN :invoiceNumbers
		];

		Map<String, Map<String, Map<String, List<Invoice_Export__c>>>> matchMap = new Map<String, Map<String, Map<String, List<Invoice_Export__c>>>>();
		for (Invoice_Export__c exp : matches) {
			Map<String, Map<String, List<Invoice_Export__c>>> schoolPart = matchMap.containsKey(exp.School__c) ? matchMap.get(exp.School__c) : new Map<String, Map<String, List<Invoice_Export__c>>>();
			Map<String, List<Invoice_Export__c>> referencePart = schoolPart.containsKey(exp.InvoiceNumber__c) ? schoolPart.get(exp.InvoiceNumber__c) : new Map<String, List<Invoice_Export__c>>();
			List<Invoice_Export__c> invoicePart = referencePart.containsKey(exp.Reference__c) ? referencePart.get(exp.Reference__c) : new List<Invoice_Export__c>();
			invoicePart.add(exp);
			referencePart.put(exp.Reference__c, invoicePart);
			schoolPart.put(exp.InvoiceNumber__c, referencePart);
			matchMap.put(exp.School__c, schoolPart);
		}

		List<Invoice_Statement__c> invoicesToUpdate = new List<Invoice_Statement__c>();

		for (Invoice_Statement__c inv : scope) {
			if (matchMap.containsKey(inv.School__c)) {
				Map<String, Map<String, List<Invoice_Export__c>>> schoolPart = matchMap.get(inv.School__c);
				if (schoolPart.containsKey(inv.Xero_Invoice_Number__c)) {
					Map<String, List<Invoice_Export__c>> referencePart = schoolPart.get(inv.Xero_Invoice_Number__c);
					if (referencePart.containsKey(inv.Reference__c)) {
						List<Invoice_Export__c> invoicePart = referencePart.get(inv.Reference__c);
						if (invoicePart != null) {
							if (invoicePart.size() == 1) {
								inv.Invoice_Export__c = invoicePart[0].Id;
								inv.Invoice_Export_Error__c = null;
								invoicesToUpdate.add(inv);
							}
							else if (invoicePart.size() > 1) {
								inv.Invoice_Export_Error__c = 'multiple possible matches;';
								for (Invoice_Export__c exp : invoicePart) {
									inv.Invoice_Export_Error__c += '\n' + exp.Id;
								}
								invoicesToUpdate.add(inv);
							}
						}
					}
				}
			}
		}

		if (invoicesToUpdate.size() > 0) {
			update invoicesToUpdate;
		}*/
		
		// Make direct matches... found none
		/*List<String> xeroIds = new List<String>();
		for (Invoice_Statement__c inv : scope) {
			xeroIds.add(inv.Xero_ID__c);
		}

		List<Invoice_Export__c> directMatches = [
			SELECT Id, Name
			FROM Invoice_Export__c
			WHERE Name IN :xeroIds
		];

		Map<String,Invoice_Export__c> exportMap = new Map<String,Invoice_Export__c>();
		for (Invoice_Export__c exp : directMatches) {
			exportMap.put(exp.Name, exp);
		}

		List<Invoice_Statement__c> invoicesToUpdate = new List<Invoice_Statement__c>();
		for (Invoice_Statement__c inv : scope) {
			if (exportMap.containsKey(inv.Xero_ID__c)) {
				inv.Invoice_Export__c = exportMap.get(inv.Xero_ID__c).Id;
				invoicesToUpdate.add(inv);
			}
		}

		if (invoicesToUpdate.size() > 0) {
			update invoicesToUpdate;
		}*/
	}
	
	global void finish(Database.BatchableContext BC) {
		
	}
	
	global static void run() {
		BatchFixInvoices batch = new BatchFixInvoices();
		ID batchprocessid = Database.executeBatch(batch, 1);
	}
}