force-app/main/default/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Primary_Contact__c</fullName>
        <description>Identifies which of the parents should be contacted first</description>
        <inlineHelpText>Which parent should be the first point of contact?</inlineHelpText>
        <label>Primary Contact</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>First Parent</fullName>
                    <default>true</default>
                    <label>First Parent</label>
                </value>
                <value>
                    <fullName>Second Parent</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>School__c</fullName>
        <description>Copies the value of SchoolText (which is a workflow copying from School Formula). A little long winded solution to avoid bigger changes in the Teacher/Parent portal.</description>
        <formula>SchoolText__pc</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>School</label>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Company_Account</fullName>
        <active>true</active>
        <label>Company</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Account_Owner_Mapping__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This setting is used to determine appropriate &quot;Mass Email&quot; or &quot;Catch All&quot; account for a given Account/Opportunity Owner. Name field contains &quot;Owner Name&quot; and Account Id field contains Id of associated account.. This setting is used in Opportunity trigger.</description>
    <fields>
        <fullName>Account_Id__c</fullName>
        <inlineHelpText>Id of the corresponding &quot;Mass Email &quot; OR &quot;Catch All&quot; Account.</inlineHelpText>
        <label>Account Id</label>
        <length>20</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>School_Name__c</fullName>
        <label>School Name</label>
        <type>TextArea</type>
    </fields>
    <label>Account Owner Mapping</label>
</CustomObject>

force-app/main/default/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Main_Parent_File__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Family File</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Value does not exist or is not a parent record.</errorMessage>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Parent</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Additional Parents &amp; Student Academic Files</relationshipLabel>
        <relationshipName>Emails</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>School__c</fullName>
        <formula>Admissions_File__r.School__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>School</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Year_Group__c</fullName>
        <formula>TEXT(Admissions_File__r.Year_Group__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Year Group</label>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Contact</fullName>
        <active>true</active>
        <label>Contact</label>
    </recordTypes>
    <recordTypes>
        <fullName>Mass_Email</fullName>
        <active>true</active>
        <label>Additional Parent Email</label>
    </recordTypes>
    <recordTypes>
        <fullName>Student</fullName>
        <active>true</active>
        <label>Student Academic File</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Group__c.object
<CustomObject>
    <fields>
        <fullName>Chatter_Group_Id__c</fullName>
        <inlineHelpText>System Field : Corresponding Chatter Group Id for this Student Group.</inlineHelpText>
        <label>Chatter Group Id</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Group_Type__c</fullName>
        <label>Group Type</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Year_Group_Control__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Tutor Group</fullName>
                </value>
                <value>
                    <fullName>Subject</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>School Group</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>School__c</fullName>
        <formula>TEXT(Owner:User.School__c)</formula>
        <label>School</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Year_Group_Control__c</fullName>
        <description>Set by means of a workflow rule to control the year group options available based on the school being a US school such as NYIS and also the group type i.e. a tutor group</description>
        <label>Year Group Control</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Tutor Group UK</fullName>
                </value>
                <value>
                    <fullName>Tutor Group US</fullName>
                </value>
                <value>
                    <fullName>Non-Tutor Group</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Student Group</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Student Groups</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Account_Id__c</fullName>
        <formula>Account.Id</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Account Id</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Primary_Contact__c</fullName>
        <formula>IF(ISPICKVAL(Account.Primary_Contact__c, &quot;First Parent&quot;), &quot;First Parent&quot;, IF(ISPICKVAL(Account.Primary_Contact__c, &quot;Second Parent&quot;), &quot;Second Parent&quot;, &quot;Please complete in parent record&quot;))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Primary Contact</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>School__c</fullName>
        <formula>Account.SchoolText__pc</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>School</label>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Student</fullName>
        <active>true</active>
        <businessProcess>Standard Admissions Process</businessProcess>
        <label>Student</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Registration__c.object
<CustomObject>
    <fields>
        <fullName>Chatter_Group_Id__c</fullName>
        <formula>IF( AND(!ISBLANK(Group__c), !ISBLANK(Group__r.Chatter_Group_Id__c)), (Group__r.Chatter_Group_Id__c), &quot;&quot;)</formula>
        <label>Chatter Group Id</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Group_Type__c</fullName>
        <formula>TEXT(Group__r.Group_Type__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Group Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Group__c</fullName>
        <inlineHelpText>select group against which assessment is done.</inlineHelpText>
        <label>Group</label>
        <referenceTo>Group__c</referenceTo>
        <relationshipLabel>Registrations</relationshipLabel>
        <relationshipName>Assessments_Registrations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>School__c</fullName>
        <formula>Group__r.School__c</formula>
        <label>School</label>
        <type>Text</type>
    </fields>
    <label>Registration</label>
    <nameField>
        <displayFormat>R-{000000}</displayFormat>
        <label>Registration #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Registrations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/School__c.object
<CustomObject>
    <fields>
        <fullName>School_Full_Name__c</fullName>
        <label>School Full Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>School</label>
    <nameField>
        <label>School Code/UID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Schools</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/School_Logo_Mapping__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>setting to store mapping of school name and school logo image URL</description>
    <fields>
        <fullName>Auto_Portal_User_Creation__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Auto Portal User Creation</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Logo_URL__c</fullName>
        <inlineHelpText>static resource URL for logo image</inlineHelpText>
        <label>Logo URL</label>
        <length>200</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>School_Full_Name__c</fullName>
        <label>School Full Name</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <label>School Mapping</label>
</CustomObject>

force-app/main/default/objects/User.object
<CustomObject>
    <fields>
        <fullName>School__c</fullName>
        <label>School</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>The British Schools Foundation</fullName>
                </value>
                <value>
                    <fullName>The British School of Guangzhou</fullName>
                </value>
                <value>
                    <fullName>The British School of Nanjing</fullName>
                </value>
                <value>
                    <fullName>The British International School of Marbella</fullName>
                </value>
                <value>
                    <fullName>The British School of Navarra</fullName>
                </value>
                <value>
                    <fullName>The British School of Tashkent</fullName>
                </value>
                <value>
                    <fullName>The British College of Brazil</fullName>
                </value>
                <value>
                    <fullName>The British International School of Kuala Lumpur</fullName>
                </value>
                <value>
                    <fullName>The International School of Moscow</fullName>
                </value>
                <value>
                    <fullName>Nord Anglia International School Manila</fullName>
                </value>
                <value>
                    <fullName>King&apos;s College Beijing</fullName>
                </value>
                <value>
                    <fullName>The British School Yangon</fullName>
                </value>
                <value>
                    <fullName>Ukraine International School</fullName>
                </value>
                <value>
                    <fullName>The New York International School</fullName>
                </value>
                <value>
                    <fullName>The British School of Brasilia</fullName>
                </value>
                <value>
                    <fullName>NAE</fullName>
                </value>
                <value>
                    <fullName>The British International School Yangon</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/classes/TestAccountContactProcesses.cls
@isTest
private class TestAccountContactProcesses {
    //test method for weekly attendance page
    static testMethod void testAccountEmailHandling(){
        Account a =  new Account();
        a.LastName = 'Last Name';
        a.RecordTypeId = [select Id from RecordType where SObjectType = 'Account' AND DeveloperName='PersonAccount'].Id;
        a.PersonEmail = 'p1@e1.com';
        a.Contact_Alternate_Email__pc = 'p1@e2.com';
        //a.Email_2__c = 'p2@e1.com';
        //a.Second_Parent_Email_1__c = 'p2@e2.com';
        insert a;
        
        Id massEmailRecordTypeId = [select Id from RecordType where SObjectType='Contact' AND DeveloperName = 'Mass_Email' limit 1].Id;
        Contact massEmail0 =  new Contact();
        massEmail0.LastName = 'LastName';
        massEmail0.Email = 'test@test.com';
        massEmail0.Main_Parent_File__c = a.Id;
        massEmail0.RecordTypeId = massEmailRecordTypeId;
        insert massEmail0;
        
        list<Contact> clist =  new List<Contact>();
        
        Contact massEmail1 =  new Contact();
        massEmail1.LastName = 'LastName';
        massEmail1.Email = 'p1@e1.com';
        massEmail1.Main_Parent_File__c = a.Id;
        massEmail1.RecordTypeId = massEmailRecordTypeId;
        clist.add(massEmail1);
        
        Contact massEmail2 =  new Contact();
        massEmail2.LastName = 'LastName';
        massEmail2.Email = 'p1@e2.com';
        massEmail2.Main_Parent_File__c = a.Id;
        massEmail2.RecordTypeId = massEmailRecordTypeId;
        clist.add(massEmail2);
        
        Contact massEmail3 =  new Contact();
        massEmail3.LastName = 'LastName';
        massEmail3.Email = 'p2@e1.com';
        massEmail3.Main_Parent_File__c = a.Id;
        massEmail3.RecordTypeId = massEmailRecordTypeId;
        clist.add(massEmail3);
        
        Contact massEmail4 =  new Contact();
        massEmail4.LastName = 'LastName';
        massEmail4.Email = 'p2@e2.com';
        massEmail4.Main_Parent_File__c = a.Id;
        massEmail4.RecordTypeId = massEmailRecordTypeId;
        clist.add(massEmail4);
        
        insert clist;
        
        delete massEmail4;
        
        undelete massEmail4;
        
    }
    
    //test method for portal user creation and chatter group membership
    static testMethod void testAccountPortalUser(){
        
        //create company account account
        Account companyAccount =  new Account();
        companyAccount.Name =  'Company Account';
        companyAccount.RecordTypeId = [Select Id from RecordType where SObjectType='Account' AND DeveloperName='Company_Account'].Id;
        insert companyAccount;
        System.debug('***TestAccountContactProcesses***testAccountPortalUser***1=');
        //create parent account account
        Account parentAccount =  new Account();
        parentAccount.FirstName =  'First Name1';
        parentAccount.LastName =  'Last Name2';
        parentAccount.PersonEmail = 'testunique1@test.com';
        parentAccount.Contact_Alternate_Email__pc = 'testunique2@test.com';
        parentAccount.RecordTypeId = [Select Id from RecordType where SObjectType='Account' AND DeveloperName='PersonAccount'].Id;
        parentAccount.Primary_Contact__c = 'First Parent';
        insert parentAccount;
        System.debug('***TestAccountContactProcesses***testAccountPortalUser***2=');
        //create custom setting values
        Account_Owner_Mapping__c mapping =  new Account_Owner_Mapping__c();
        mapping.Account_Id__c = companyAccount.Id;
        mapping.Name =  UserInfo.getName();
        mapping.School_Name__c = [select School__c,Id from User where Id=:UserInfo.getUserId()].School__c;
        insert mapping;
        System.debug('***TestAccountContactProcesses***testAccountPortalUser***3=');
        //create setting
        User u = [select School__c,Id from User where Id=:UserInfo.getUserId()];
        School_Logo_Mapping__c portal =  new School_Logo_Mapping__c();
        portal.Name = 'Test';
        portal.School_Full_Name__c = u.School__c;
        portal.Auto_Portal_User_Creation__c = true;
        portal.Logo_URL__c = 'test';
        portal.Auto_Portal_User_Creation__c = true;
        insert portal;
        System.debug('***TestAccountContactProcesses***testAccountPortalUser***4=');
        Id networkId;
        for(Network n:[Select Id,Name from Network limit 1]){
            networkId = n.Id;
        }
        System.debug('***TestAccountContactProcesses***testAccountPortalUser***5=');
        //create portal chatter group
        CollaborationGroup chatterGroup =  new CollaborationGroup();
        chatterGroup.Name = 'Test Group 99999';
        chatterGroup.NetworkId = networkId;
        chatterGroup.CollaborationType = 'Private';
        chatterGroup.OwnerId = UserInfo.getUserId();
        insert chatterGroup;
        System.debug('***TestAccountContactProcesses***testAccountPortalUser***6=');
        //create student group
        Group__c grp  =  new Group__c();
        grp.Name = 'Test Group';
        grp.Group_Type__c = 'Tutor Group';
        grp.Chatter_Group_Id__c = chatterGroup.Id;
        grp.Year_Group_Control__c = 'Tutor Group UK';
        grp.Year_Group__c = 'Year 1';
        insert grp;
        System.debug('***TestAccountContactProcesses***testAccountPortalUser***7=');
        //create student
        Opportunity o =  new Opportunity();
        o.Student_Surname__c =  'Surname';
        o.Name = 'First Name';
        o.Gender__c = 'Male';
        o.Year_Group__c = 'PN1';
        o.Birth_Date__c =  Date.today().addYears(-10);
        o.Application_Date__c = Date.today().addDays(-20);
        o.Starting_Date__c =  Date.today().addDays(-10);
        o.StageName = 'A/ Testing';
        o.AccountId = parentAccount.Id;
        //o.Payer__c = companyAccount.Id;
        o.CloseDate =  Date.today();
        o.Student_Name__c = 'SN';
        o.Class__c = 'A';
        insert o;
        o.StageName = 'Enrolled';
        update o;
        System.debug('***TestAccountContactProcesses***testAccountPortalUser***8=');
        Contact c = [select Id from Contact where AccountId=:parentAccount.Id];
        
        Test.startTest();
        /*
        //create registration record
        Registration__c r = new Registration__c();
        r.Student__c = c.Id;
        r.Group__c = grp.Id;
        r.Active__c = true;
        
        insert r;
        
        */ 
        System.debug('***TestAccountContactProcesses***testAccountPortalUser***parentAccount='+[select Id,Portal_User_Creation_Error__c,Family_Status__c,Trigger_Parent_User_Creation__c, User__pc from Account where Id=:parentAccount.Id]);
        update parentAccount;
        System.debug('***TestAccountContactProcesses***testAccountPortalUser***9');
        Test.stopTest();
    }
}