force-app/main/default/objects/Account.object
<CustomObject>
    <fields>
        <fullName>School__c</fullName>
        <description>Copies the value of SchoolText (which is a workflow copying from School Formula). A little long winded solution to avoid bigger changes in the Teacher/Parent portal.</description>
        <formula>SchoolText__pc</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>School</label>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/School__c.object
<CustomObject>
    <fields>
        <fullName>School_Full_Name__c</fullName>
        <label>School Full Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>School</label>
    <nameField>
        <label>School Code/UID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Schools</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/School_Logo_Mapping__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>setting to store mapping of school name and school logo image URL</description>
    <fields>
        <fullName>School_Full_Name__c</fullName>
        <label>School Full Name</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>School_Logo_URL__c</fullName>
        <label>School Logo URL</label>
        <type>TextArea</type>
    </fields>
    <label>School Mapping</label>
</CustomObject>

force-app/main/default/objects/User.object
<CustomObject>
    <fields>
        <fullName>Has_Profile_Photo__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Populated by means of a trigger, indicates whether or not the user has added a profile photo. NB. Is only accurate for records that have been edited since the photo was uploaded.</description>
        <label>Has Profile Photo</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Is_Chatter_Free_User__c</fullName>
        <formula>Profile.Name == &quot;Chatter Free User&quot;</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Is Chatter Free User</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Link_to_Related_Contact__c</fullName>
        <formula>HYPERLINK(&quot;https://ap4.salesforce.com/&quot;&amp;Related_Contact_ID__c, &quot;Click Here&quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Link to Related Staff Member Record</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Manage_Chatter_Free_Users__c</fullName>
        <label>Manage Chatter Free Users</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>As Admin</fullName>
                </value>
                <value>
                    <fullName>As Academic</fullName>
                </value>
                <value>
                    <fullName>As Web Dev</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Override_Manually__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Used to prevent the relevant workflow rules from automatically generating a &apos;Positioning&apos; value for the staff directory record</description>
        <label>Override Manually</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Photo_Attachment_Id__c</fullName>
        <label>Photo Attachment Id</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Publish_on_School_Site__c</fullName>
        <formula>AND(
    S_Dir_Profile_Approved_by_Admin__c = TRUE, 
    Profile.Name != &quot;Parent Portal User - High Volume&quot;, 
    Profile.Name != &quot;Overage High Volume Customer Portal User&quot;, 
    Profile.Name != &quot;Customer Community Plus User&quot;, 
    S_Dir_Status__c = &quot;Employed&quot;, 
    NOT(ISBLANK(S_Dir_Positioning__c)), 
    S_Dir_Positioning__c != 0, 
    S_Dir_Positioning__c != 9999, 
    S_Dir_Personal_Interests_Not_Blank__c = &quot;True&quot;
    )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>A Visible profile must meet the following criteria: 
1) Be approved by Admin
2) Be that of an employed Staff Member and properly linked
3) &apos;Positioning&apos; must not be blank, 0 or 9999
4) &apos;Personal Interests&apos; must not be blank</inlineHelpText>
        <label>Profile Visible on Website</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Related_Contact_ID__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>Used to capture the ID of the relevant contact when a new staff member user is created so that the contact and the user can be connected</description>
        <label>Related Contact ID (Staff Member)</label>
        <length>20</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>S_Dir_Degree__c</fullName>
        <label>Qualifications</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>S_Dir_Department__c</fullName>
        <label>School Department</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Academic</fullName>
                </value>
                <value>
                    <fullName>Administration</fullName>
                </value>
                <value>
                    <fullName>Support Staff</fullName>
                </value>
                <value>
                    <fullName>Undetermined</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>S_Dir_Name__c</fullName>
        <formula>TEXT(S_Dir_Salutation__c) &amp; &quot; &quot; &amp;  FirstName &amp; &quot; &quot; &amp;  LastName</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>S_Dir_Origin__c</fullName>
        <description>Populated via an a-sync job based on updates made to the relevant staff member record</description>
        <label>Origin</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>S_Dir_Personal_Interests__c</fullName>
        <label>Staff Bio</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>S_Dir_Positioning__c</fullName>
        <description>Defines the positioning on the website: lowest number from left to right, top to bottom</description>
        <label>Positioning</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>S_Dir_Profile_Approved_by_Admin__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates whether or not a profile is approved and published on the school website (new site only)</description>
        <label>Profile Approved by Admin</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>S_Dir_Status__c</fullName>
        <label>Status</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>S_Dir_Title_New__c</fullName>
        <label>Title</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>S_Dir_Years_of_Experience__c</fullName>
        <label>Years of Experience</label>
        <precision>3</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>School__c</fullName>
        <label>School</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>The British Schools Foundation</fullName>
                </value>
                <value>
                    <fullName>The British School of Guangzhou</fullName>
                </value>
                <value>
                    <fullName>The British School of Nanjing</fullName>
                </value>
                <value>
                    <fullName>The British International School of Marbella</fullName>
                </value>
                <value>
                    <fullName>The British School of Navarra</fullName>
                </value>
                <value>
                    <fullName>The British School of Tashkent</fullName>
                </value>
                <value>
                    <fullName>The British College of Brazil</fullName>
                </value>
                <value>
                    <fullName>The British International School of Kuala Lumpur</fullName>
                </value>
                <value>
                    <fullName>The International School of Moscow</fullName>
                </value>
                <value>
                    <fullName>Nord Anglia International School Manila</fullName>
                </value>
                <value>
                    <fullName>King&apos;s College Beijing</fullName>
                </value>
                <value>
                    <fullName>The British School Yangon</fullName>
                </value>
                <value>
                    <fullName>Ukraine International School</fullName>
                </value>
                <value>
                    <fullName>The New York International School</fullName>
                </value>
                <value>
                    <fullName>The British School of Brasilia</fullName>
                </value>
                <value>
                    <fullName>NAE</fullName>
                </value>
                <value>
                    <fullName>The British International School Yangon</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Staff_Directory_Info_Additional_Notes__c</fullName>
        <description>Captures any additional notes that are entered by the user on the staff directory information form</description>
        <label>Staff Directory Info Additional Notes</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Staff_Directory_Info_Received__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Staff Directory Info Received</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/classes/UserStaffDirectory_Controller.cls
//controller class for User sub-tab for staff directory
public without sharing class UserStaffDirectory_Controller{
    
    public User contextUser {get;set;}
    public boolean hasEditAccess {get;set;}
    public list<SelectOption> departmentOptions {get;set;}
    public boolean canEdit {get{
        boolean flag = false;
        if(hasEditAccess || (loggedInUser.Manage_Chatter_Free_Users__c != null && loggedInUser.School__c == contextUser.School__c) || loggedInUser.Manage_Chatter_Free_Users__c == 'As Web Dev'){
            flag = true;
        }
        return flag;
    }}
    public boolean isEditMode {get;set;}
    public Attachment photo {get;set;}
    public string reload {get;set;}
    public User loggedInUser {get;set;}
    public UserFields userField {get;set;}
    public Account userAccount {get;set;}
    public boolean calledFromWebsite {get;set;}
    public boolean updateFlag {get;set;}
    public string schoolLogoURL {get;set;}
    public boolean allowUpdate {get{
        return !contextUser.Staff_Directory_Info_Received__c || updateFlag;
    }}
    
    public boolean showDefaultView{get{
        boolean flag = false;
        if(isEditMode && !calledFromWebsite &&contextUser != null && (!contextUser.Is_Chatter_Free_User__c || loggedInUser.Profile.Name == 'System Administrator')){
            flag = true;
        }
        return flag;
    }}
    
    public boolean showOverriddenView{get{
        boolean flag = false;
        if(isEditMode && ((contextUser != null && contextUser.Is_Chatter_Free_User__c && loggedInUser.Profile.Name != 'System Administrator') || calledFromWebsite)){
            flag = true;
        }
        return flag;
    }}
    
    public UserStaffDirectory_Controller(ApexPages.StandardController controller){
        reload = '0';
        isEditMode = false;
        hasEditAccess = false;
        calledFromWebsite = false;
        updateFlag = false;
        photo = new Attachment();
        loggedInUser = [select Id, School__c, Profile.Name ,Manage_Chatter_Free_Users__c from User where Id =:UserInfo.getUserId()];
        //system.debug('****UserStaffDirectory_Controller***constructor***params='+system.currentPageReference().getParameters());
        string userId = system.currentPageReference().getParameters().get('sfdc.userId');
        string webrequest = system.currentPageReference().getParameters().get('w');
        string isUpdate = system.currentPageReference().getParameters().get('uf');
        if(webrequest == '1'){
            calledFromWebsite = true;
            isEditMode = true;
        }
        if(isUpdate == '1'){
            updateFlag = true;
        }
        if(userId != null){
            contextUser = [select Staff_Directory_Info_Received__c, Is_Chatter_Free_User__c, Profile.Name, Staff_Directory_Info_Additional_Notes__c, Related_Contact_Id__c, Id,School__c, Override_Manually__c, Link_to_Related_Contact__c, S_Dir_Department__c,S_Dir_Profile_Approved_by_Admin__c,S_Dir_Status__c,S_Dir_Name__c,Publish_on_School_Site__c,S_Dir_Title_New__c,S_Dir_Positioning__c ,S_Dir_Degree__c, S_Dir_Personal_Interests__c from User where Id=:userId];
            hasEditAccess = [SELECT RecordId, HasEditAccess FROM UserRecordAccess WHERE UserId =: UserInfo.getUserId() AND RecordId = :contextUser.Id].HasEditAccess;
            try{
                userAccount = [select Id from Account where User__pc =: contextUser.Id];
            }catch(Exception e){}
            initialize();
        }
    }
    
    
    private void initialize(){ 
        //fetch school's logo
        for(School_Logo_Mapping__c setting:School_Logo_Mapping__c.getall().values()){
            if(contextUser.School__c == setting.School_Full_Name__c){
                schoolLogoURL = setting.School_Logo_URL__c;
                break;
            }
        }
        
        userField = new UserFields();
        userField.name = new Field_Text(contextUser.S_Dir_Name__c);
        userField.positioning = new Field_Decimal(contextUser.S_Dir_Positioning__c);
        userField.override_manually = new Field_Boolean(contextUser.Override_Manually__c);
        userField.title = new Field_Text(contextUser.S_Dir_Title_New__c);
        userField.status = new Field_Text(contextUser.S_Dir_Status__c);
        userField.school_department = new Field_Text(contextUser.S_Dir_Department__c);
        userField.profile_approved = new Field_Boolean(contextUser.S_Dir_Profile_Approved_by_Admin__c);
        //userField.origin = new Field_Text(contextUser.S_Dir_Origin__c);
        //userField.expirience = new Field_Decimal(contextUser.S_Dir_Years_of_Experience__c);
        userField.degree = new Field_Text(contextUser.S_Dir_Degree__c);
        //userField.other_qualifications = new Field_Text(contextUser.S_Dir_Other_Qualifications__c);
        userField.personal_Interest = new Field_Text(contextUser.S_Dir_Personal_Interests__c);
        
        userField.notes = new Field_Text(contextUser.Staff_Directory_Info_Additional_Notes__c);
        
        //check for access
        if(!calledFromWebsite && (hasEditAccess || (loggedInUser.Manage_Chatter_Free_Users__c == 'As Admin' && loggedInUser.School__c == contextUser.School__c) || loggedInUser.Manage_Chatter_Free_Users__c == 'As Web Dev')){
            userField.positioning.editAccess = true;
            userField.override_manually.editAccess = true;
            userField.title.editAccess = true;
            if(hasEditAccess && loggedInUser.Profile.Name == 'System Administrator'){
                userField.status.editAccess = true;
                userField.school_department.editAccess = true;
                //userField.origin.editAccess = true;
            }else{
                userField.status.editAccess = false;
                userField.school_department.editAccess = false;
                //userField.origin.editAccess = false;
            }
            userField.profile_approved.editAccess = true;
            //userField.origin.editAccess = true;
            //userField.expirience.editAccess = true;
            userField.degree.editAccess = true;
            //userField.other_qualifications.editAccess = true;
            userField.personal_Interest.editAccess = true;
        }else if(!calledFromWebsite && loggedInUser.Manage_Chatter_Free_Users__c == 'As Academic' && loggedInUser.School__c == contextUser.School__c){
            userField.positioning.editAccess = false;
            userField.override_manually.editAccess = false;
            userField.title.editAccess = true;
            userField.status.editAccess = false;
            userField.school_department.editAccess = false;
            userField.profile_approved.editAccess = false;
            //userField.origin.editAccess = false;
            //userField.expirience.editAccess = true;
            userField.degree.editAccess = true;
            //userField.other_qualifications.editAccess = true;
            userField.personal_Interest.editAccess = true;
        }else if(calledFromWebsite){
            userField.positioning.editAccess = false;
            userField.override_manually.editAccess = false;
            userField.title.editAccess = false;
            userField.status.editAccess = false;
            userField.school_department.editAccess = false;
            userField.profile_approved.editAccess = false;
            //userField.origin.editAccess = false;
            //userField.expirience.editAccess = true;
            userField.degree.editAccess = true;
            //userField.other_qualifications.editAccess = true;
            userField.personal_Interest.editAccess = true;
        }
        
        //check department options
        departmentOptions = new list<SelectOption>();
        for(Schema.PicklistEntry entry:User.S_Dir_Department__c.getDescribe().getPicklistValues()){
            departmentOptions.add(new SelectOption(entry.getValue(),entry.getLabel()));
        }
    }
    
    public PageReference showEditMode(){
        isEditMode = true;
        return null;
    }
    
    public PageReference saveUser(){
        try{
            string successMessageStr;
            
            if(calledFromWebsite){
                successMessageStr = 'Your details have been successfully submitted to the school. Thank you for taking the time to complete this form.';
            }else{
                successMessageStr = 'Your details have been successfully submitted to the school. Thank you for taking the time to complete this form.';
            }
            reload = '1';
            if(!showDefaultView){
                isEditMode = false;
                //populate user fields
                contextUser.S_Dir_Positioning__c = userField.positioning.value;
                contextUser.Override_Manually__c = userField.override_manually.value;
                contextUser.S_Dir_Title_New__c = userField.title.value;
                contextUser.S_Dir_Status__c = userField.status.value;
                contextUser.S_Dir_Department__c = userField.school_department.value;
                contextUser.S_Dir_Profile_Approved_by_Admin__c = userField.profile_approved.value;
                //contextUser.S_Dir_Origin__c = userField.origin.value;
                //contextUser.S_Dir_Years_of_Experience__c = userField.expirience.value;
                contextUser.S_Dir_Degree__c = userField.degree.value;
                //contextUser.S_Dir_Other_Qualifications__c = userField.other_qualifications.value;
                contextUser.S_Dir_Personal_Interests__c = userField.personal_Interest.value;
                if(calledFromWebsite){
                    contextUser.Staff_Directory_Info_Additional_Notes__c = userField.notes.value;
                    contextUser.Staff_Directory_Info_Received__c = true; 
                }
                //check for photo
                system.debug('****UserStaffDirectory_Controller***saveUser***photo.ContentType='+photo.ContentType);
                if(photo.body != null && photo.ContentType != null){
                    //check for content type
                    
                    if(photo.ContentType.equalsIgnoreCase('image/gif') || photo.ContentType.equalsIgnoreCase('image/jpeg') || photo.ContentType.equalsIgnoreCase('image/jpg' ) || photo.ContentType.equalsIgnoreCase('image/png')){
                        
                        
                        //ConnectApi.BinaryInput bi =  new ConnectApi.BinaryInput(photo.body,photo.ContentType,photo.Name);
                        //ConnectApi.Photo cPhoto = ConnectApi.ChatterUsers.setPhoto(null, contextUser.Id , bi);
                        
                        
                        //check for account
                        try{
                            
                            if(userAccount != null){
                                Attachment att = new Attachment();
                                att.ParentId = userAccount.Id;
                                att.Body = photo.body;
                                att.Name = photo.Name;
                                att.ContentType = photo.ContentType;
                                insert att;
                                //update user
                                contextUser.Photo_Attachment_Id__c = att.Id; 
                                contextUser.Has_Profile_Photo__c = true;
                                
                            }
                        }catch(Exception e){
                            ApexPages.Message errorMessage = new ApexPages.Message(ApexPages.severity.FATAL, 'Failed to process uploaded photo.  - '+e.getMessage());
                            ApexPages.addMessage(errorMessage);
                        }
                        
                        //PortalUtility.updateProfilePhoto(photo.body,photo.ContentType,photo.Name,contextUser.Id);
                        //contextUser.Has_Profile_Photo__c = true;
                        update contextUser; 
                        
                        ApexPages.Message successMessage = new ApexPages.Message(ApexPages.severity.CONFIRM, successMessageStr);
                        ApexPages.addMessage(successMessage);
                        //photo = new Attachment();
                         
                    }else{
                        update contextUser; 
                        ApexPages.Message successMessage = new ApexPages.Message(ApexPages.severity.WARNING, successMessageStr+' Failed to update photo as provided file is a invalid photo.');
                        ApexPages.addMessage(successMessage);
                        reload = '0';
                        //photo = new Attachment();
                    }
                }else{
                    update contextUser; 
                    ApexPages.Message successMessage = new ApexPages.Message(ApexPages.severity.CONFIRM, successMessageStr);
                    ApexPages.addMessage(successMessage);
                    //photo = new Attachment();
                    
                }
            }else{
                if(photo.body != null && photo.ContentType != null){
                    //check for content type
                    
                    if(photo.ContentType.equalsIgnoreCase('image/gif') || photo.ContentType.equalsIgnoreCase('image/jpeg') || photo.ContentType.equalsIgnoreCase('image/jpg' ) || photo.ContentType.equalsIgnoreCase('image/png')){
                        ConnectApi.BinaryInput bi =  new ConnectApi.BinaryInput(photo.body,photo.ContentType,photo.Name);
                        ConnectApi.Photo cPhoto = ConnectApi.ChatterUsers.setPhoto(null, contextUser.Id , bi);
                        
                        contextUser.Has_Profile_Photo__c = true;
                        update contextUser; 
                        ApexPages.Message successMessage = new ApexPages.Message(ApexPages.severity.CONFIRM, successMessageStr);
                        ApexPages.addMessage(successMessage);
                        //photo = new Attachment();
                         
                    }else{
                        update contextUser; 
                        ApexPages.Message successMessage = new ApexPages.Message(ApexPages.severity.WARNING, successMessageStr+' Failed to update photo as provided file is a invalid photo.');
                        ApexPages.addMessage(successMessage);
                        reload = '0';
                        //photo = new Attachment();
                    }
                }else{
                    update contextUser; 
                    ApexPages.Message successMessage = new ApexPages.Message(ApexPages.severity.CONFIRM, successMessageStr);
                    ApexPages.addMessage(successMessage);
                    //photo = new Attachment();
                    
                }
            }
             
        }catch(Exception e){
            isEditMode = true;
            ApexPages.Message errorMessage = new ApexPages.Message(ApexPages.severity.FATAL, 'Failure: Error - '+e.getMessage());
            ApexPages.addMessage(errorMessage);
            reload = '0';
            photo = new Attachment();
        }
        photo = new Attachment();
        updateFlag = false;
        return null;
    }
    
    public PageReference cancel(){
        isEditMode = false;
        reload = '0';
        return null;
    }
    
    public class UserFields{
        public Field_Text name {get;set;}
        public Field_Decimal positioning {get;set;}
        public Field_Boolean override_manually {get;set;} 
        public Field_Text title {get;set;}
        public Field_Text status {get;set;}
        public Field_Text school_department {get;set;}
        public Field_Boolean profile_approved {get;set;}
        //public Field_Text origin {get;set;}  
        //public Field_Decimal expirience {get;set;}  
        public Field_Text degree {get;set;}  
        //public Field_Text other_qualifications {get;set;}  
        public Field_Text personal_Interest {get;set;} 
        public  Field_Text notes {get;set;}
    }
    
    public class Field_Text{
        public string value {get;set;}
        public boolean editAccess {get;set;}
        public Field_Text(string v){
            value = v;
            editAccess = false;
        }
    }
    
    public class Field_Decimal{
        public decimal value {get;set;}
        public boolean editAccess {get;set;}
        public Field_Decimal(decimal v){
            value = v;
            editAccess = false;
        }
    }
    
    public class Field_Boolean{
        public boolean value {get;set;}
        public boolean editAccess {get;set;}
        public Field_Boolean(boolean v){
            value = v;
            editAccess = false;
        }
    }
    
}