force-app/main/default/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Gender__c</fullName>
        <label>Gender</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Male</fullName>
                </value>
                <value>
                    <fullName>Female</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>School__c</fullName>
        <description>Copies the value of SchoolText (which is a workflow copying from School Formula). A little long winded solution to avoid bigger changes in the Teacher/Parent portal.</description>
        <formula>SchoolText__pc</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>School</label>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Class__c/Class__c.object-meta.xml
<CustomObject>
    <label>Class</label>
    <nameField>
        <label>Class Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Classes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Class__c/fields/FemaleCount__c.field-meta.xml
<CustomField>
    <fullName>FemaleCount__c</fullName>
    <label>Female Count</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Class__c/fields/MaleCount__c.field-meta.xml
<CustomField>
    <fullName>MaleCount__c</fullName>
    <label>Male Count</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Class__c/fields/YearGrade__c.field-meta.xml
<CustomField>
    <fullName>YearGrade__c</fullName>
    <label>Year/Grade</label>
    <referenceTo>YearGrade__c</referenceTo>
    <relationshipLabel>Classes</relationshipLabel>
    <relationshipName>Classes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Class__c</fullName>
        <formula>TEXT(Admissions_File__r.Class__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Class</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Gender__c</fullName>
        <description>This field is configured in NPSP Settings &gt; Relationships &gt; Relationships as the Gender field. Do not delete this field unless you remove the reference or select another Gender field there.</description>
        <label>Gender</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Male</fullName>
                </value>
                <value>
                    <fullName>Female</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>School__c</fullName>
        <formula>Admissions_File__r.School__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>School</label>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Contact</fullName>
        <active>true</active>
        <label>Contact</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/EnrolmentPeriod__c/EnrolmentPeriod__c.object-meta.xml
<CustomObject>
    <label>Enrolment Period</label>
    <nameField>
        <label>Enrolment Period Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Enrolment Periods</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Class__c</fullName>
        <description>Defaults:
From Lead Convert: Will be &apos;Pending&apos; for schools without campus options and any of the 3 &apos;Pending&apos; options for schools with campus options (&apos;Not Sure&apos; = &apos;Pending&apos;)
From Student Clone: Will be copied from the record that is cloned as it cannot be blank and can therefore not revert to the default of &apos;Pending&apos;.</description>
        <inlineHelpText>A to H = Campus 1 (Krylatskoe/CF)
I to P = Campus 2 (Rosinka/ CJ)</inlineHelpText>
        <label>Class</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>School_Controlling_Picklist1__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                    <default>true</default>
                    <label>Pending</label>
                </value>
                <value>
                    <fullName>Pending (Campus 1: A-H)</fullName>
                </value>
                <value>
                    <fullName>Pending (Campus 2: I-P)</fullName>
                </value>
                <value>
                    <fullName>A</fullName>
                </value>
                <value>
                    <fullName>B</fullName>
                </value>
                <value>
                    <fullName>C</fullName>
                </value>
                <value>
                    <fullName>D</fullName>
                </value>
                <value>
                    <fullName>E</fullName>
                </value>
                <value>
                    <fullName>F</fullName>
                </value>
                <value>
                    <fullName>G</fullName>
                </value>
                <value>
                    <fullName>H</fullName>
                </value>
                <value>
                    <fullName>I</fullName>
                </value>
                <value>
                    <fullName>J</fullName>
                </value>
                <value>
                    <fullName>K</fullName>
                </value>
                <value>
                    <fullName>L</fullName>
                </value>
                <value>
                    <fullName>M</fullName>
                </value>
                <value>
                    <fullName>N</fullName>
                </value>
                <value>
                    <fullName>O</fullName>
                </value>
                <value>
                    <fullName>P</fullName>
                </value>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
                <value>
                    <fullName>4</fullName>
                </value>
                <value>
                    <fullName>5</fullName>
                </value>
                <value>
                    <fullName>[House] 1</fullName>
                </value>
                <value>
                    <fullName>[House] 2</fullName>
                </value>
                <value>
                    <fullName>[House] 3</fullName>
                </value>
                <value>
                    <fullName>[House] 4</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Gender__c</fullName>
        <label>Gender</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Gender_Options</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>School__c</fullName>
        <formula>Account.SchoolText__pc</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>School</label>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/School__c.object
<CustomObject>
    <label>School</label>
    <nameField>
        <label>School Code/UID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Schools</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/User.object
<CustomObject>
    <fields>
        <fullName>School__c</fullName>
        <label>School</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>The British Schools Foundation</fullName>
                </value>
                <value>
                    <fullName>The British School of Guangzhou</fullName>
                </value>
                <value>
                    <fullName>The British School of Nanjing</fullName>
                </value>
                <value>
                    <fullName>The British International School of Marbella</fullName>
                </value>
                <value>
                    <fullName>The British School of Navarra</fullName>
                </value>
                <value>
                    <fullName>The British School of Tashkent</fullName>
                </value>
                <value>
                    <fullName>The British College of Brazil</fullName>
                </value>
                <value>
                    <fullName>The British International School of Kuala Lumpur</fullName>
                </value>
                <value>
                    <fullName>The International School of Moscow</fullName>
                </value>
                <value>
                    <fullName>Nord Anglia International School Manila</fullName>
                </value>
                <value>
                    <fullName>King&apos;s College Beijing</fullName>
                </value>
                <value>
                    <fullName>The British School Yangon</fullName>
                </value>
                <value>
                    <fullName>Ukraine International School</fullName>
                </value>
                <value>
                    <fullName>The New York International School</fullName>
                </value>
                <value>
                    <fullName>The British School of Brasilia</fullName>
                </value>
                <value>
                    <fullName>NAE</fullName>
                </value>
                <value>
                    <fullName>The British International School Yangon</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/YearGrade__c/YearGrade__c.object-meta.xml
<CustomObject>
    <label>Year/Grade</label>
    <nameField>
        <label>Year/Grade Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Years/Grades</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/YearGrade__c/fields/EnrolmentPeriod__c.field-meta.xml
<CustomField>
    <fullName>EnrolmentPeriod__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Enrolment Period</label>
    <referenceTo>EnrolmentPeriod__c</referenceTo>
    <relationshipLabel>Years/Grades</relationshipLabel>
    <relationshipName>YearsGrades</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/YearGrade__c/fields/FemaleCount__c.field-meta.xml
<CustomField>
    <fullName>FemaleCount__c</fullName>
    <label>Female Count</label>
    <summarizedField>Class__c.FemaleCount__c</summarizedField>
    <summaryForeignKey>Class__c.YearGrade__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/YearGrade__c/fields/MaleCount__c.field-meta.xml
<CustomField>
    <fullName>MaleCount__c</fullName>
    <label>Male Count</label>
    <summarizedField>Class__c.MaleCount__c</summarizedField>
    <summaryForeignKey>Class__c.YearGrade__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/globalValueSets/Gender_Options.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Male</fullName>
    </customValue>
    <customValue>
        <fullName>Female</fullName>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
    </customValue>
    <customValue>
        <fullName>Prefer not to say</fullName>
    </customValue>
    <masterLabel>Gender Options</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/AP10_UpdateClass_TEST.cls
/**************************************************************************************
-- - Author        : Spoon Consulting
-- - Description   : Test class for AP10_UpdateClass
--
-- Maintenance History: 
--
-- Date         Name  Version  Remarks 
-- -----------  ----  -------  ------------------------------------------------------- 
-- 01-AUG-2018  AMU   1.0     Initial Version
--------------------------------------------------------------------------------------
**************************************************************************************/
@isTest
public with sharing class AP10_UpdateClass_TEST {
    static List<User> lstUser;
    static List<Class__c> lstClasses;
    static List<YearGrade__c> lstYearGrade;
    static List<EnrolmentPeriod__c> lstEnrolmentPeriod;
    static List<Contact> lstContact;
    static List<School__c> lstSchool;
    static List<Opportunity> lstOpp;
    static List<Account> lstAcc;

    static {
        Map<String,Id> mapRecordType = AP_Constant.getDeveloperIdMap(new Set<String>{AP_Constant.oppObject, AP_Constant.conObject});

        lstUser = new List<User>{TestFactory.createUser('Test', TestFactory.getProfileAdminId())};
        insert lstUser;

        System.runAs(lstUser[0]){
            lstSchool = new List<School__c>{
                TestFactory.createSchool('Test', 'Mauritius', false, 'TST')
            };
            insert lstSchool;

            lstAcc = new List<Account>{TestFactory.createAccount('test')};
            insert lstAcc;

             lstContact = new List<Contact>{
                TestFactory.createContact('test1', lstAcc[0].Id, mapRecordType.get(AP_Constant.conRecordTypeChild))
                ,TestFactory.createContact('test2', lstAcc[0].Id, mapRecordType.get(AP_Constant.conRecordTypeChild))
                ,TestFactory.createContact('test3', lstAcc[0].Id, mapRecordType.get(AP_Constant.conRecordTypeChild))
                ,TestFactory.createContact('test4', lstAcc[0].Id, mapRecordType.get(AP_Constant.conRecordTypeChild))
                ,TestFactory.createContact('test5', lstAcc[0].Id, mapRecordType.get(AP_Constant.conRecordTypeChild))
            };
            lstContact[0].Gender__c = AP_Constant.conGenderMale;
            lstContact[1].Gender__c = AP_Constant.conGenderMale;
            lstContact[2].Gender__c = AP_Constant.conGenderFemale;
            lstContact[3].Gender__c = AP_Constant.conGenderFemale;
            lstContact[4].Gender__c = AP_Constant.conGenderFemale;
            insert lstContact;

            lstEnrolmentPeriod = new List<EnrolmentPeriod__c>{
                TestFactory.createEnrolmentPeriod('Semester 1', lstSchool[0].Id, 'YR18', Date.newInstance(2018, 1, 1), Date.newInstance(2019, 1, 1))
            };
            insert lstEnrolmentPeriod;

            lstYearGrade = new List<YearGrade__c>{
                TestFactory.createYearGrade('Group 2018 Junior', lstSchool[0].Id, 10, 15, lstEnrolmentPeriod[0].Id)
            };
            insert lstYearGrade;

            lstClasses = new List<Class__c>{
                TestFactory.createClass('Test1',  50, lstYearGrade[0].Id, lstSchool[0].Id)
                ,TestFactory.createClass('Test2', 100, lstYearGrade[0].Id, lstSchool[0].Id)
            };
            insert lstClasses;

            lstOpp = new List<Opportunity>{
                TestFactory.createOpportunity('testopp1', lstAcc[0].Id, AP_Constant.oppStageNameVisit, 
                                                mapRecordType.get(AP_Constant.oppRecordTypeEnrolment), lstSchool[0].Id)

                ,TestFactory.createOpportunity('testopp2', lstAcc[0].Id, AP_Constant.oppStageNameOfferOut, 
                                                mapRecordType.get(AP_Constant.oppRecordTypeEnrolment), lstSchool[0].Id)

                ,TestFactory.createOpportunity('testopp3', lstAcc[0].Id, AP_Constant.oppStageNameStarted, 
                                                mapRecordType.get(AP_Constant.oppRecordTypeEnrolment), lstSchool[0].Id)

                ,TestFactory.createOpportunity('testopp4', lstAcc[0].Id, AP_Constant.oppStageNameDenied, 
                                                mapRecordType.get(AP_Constant.oppRecordTypeEnrolment), lstSchool[0].Id)

                ,TestFactory.createOpportunity('testopp5', lstAcc[0].Id, AP_Constant.oppStageNameLost, 
                                                mapRecordType.get(AP_Constant.oppRecordTypeEnrolment), lstSchool[0].Id)
            };
            
            lstOpp[0].Child__c = lstContact[0].Id;
            lstOpp[1].Child__c = lstContact[1].Id;
            lstOpp[2].Child__c = lstContact[2].Id;
            lstOpp[3].Child__c = lstContact[3].Id;
            lstOpp[4].Child__c = lstContact[4].Id;
            
            lstOpp[3].LostDeniedOnHoldReason__c = 'Financial';
            lstOpp[4].LostDeniedOnHoldReason__c = 'Financial';

            insert lstOpp;
        }
    }

    @isTest public static void updateclsNewTest(){
        for(Opportunity opp: lstOpp) {
            opp.Class__c = lstClasses[0].Id;
            opp.EnrolmentPeriod__c = lstEnrolmentPeriod[0].Id;
            opp.YearGrade__c = lstYearGrade[0].Id;
        }

        System.runAs(lstUser[0]){
            test.StartTest();
                update lstOpp;
            test.StopTest();

            Class__c cls = [SELECT Id, FemaleCount__c, MaleCount__c FROM Class__c WHERE 
                                                Id =: lstClasses[0].Id LIMIT 1];
            System.assertEquals(cls.FemaleCount__c, 3);
            System.assertEquals(cls.MaleCount__c, 2);
        }
    }

     @isTest public static void updateclsNewOldTest(){
        for(Opportunity opp: lstOpp) {
            opp.Class__c = lstClasses[0].Id;
            opp.EnrolmentPeriod__c = lstEnrolmentPeriod[0].Id;
            opp.YearGrade__c = lstYearGrade[0].Id;
        }
        update lstOpp;

        for(Opportunity opp: lstOpp) {
            opp.Class__c = lstClasses[1].Id;
        }

        System.runAs(lstUser[0]){
            test.StartTest();
                update lstOpp;
            test.StopTest();

            List<Class__c> lstClasses = [SELECT Id, FemaleCount__c, MaleCount__c FROM Class__c WHERE 
                                                        Id IN: lstClasses Order By Name];
            System.assertEquals(lstClasses[0].FemaleCount__c, 0);
            System.assertEquals(lstClasses[0].MaleCount__c, 0);
            System.assertEquals(lstClasses[1].FemaleCount__c, 3);
            System.assertEquals(lstClasses[1].MaleCount__c, 2);
        }
    }
}