force-app/main/default/objects/Account.object
<CustomObject>
    <fields>
        <fullName>School__c</fullName>
        <description>Copies the value of SchoolText (which is a workflow copying from School Formula). A little long winded solution to avoid bigger changes in the Teacher/Parent portal.</description>
        <formula>SchoolText__pc</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>School</label>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Case.object
<CustomObject>
    <fields>
        <fullName>School__c</fullName>
        <formula>Contact.SchoolText__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>School</label>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>School__c</fullName>
        <formula>Admissions_File__r.School__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>School</label>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Contact</fullName>
        <active>true</active>
        <label>Contact</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/School__c.object
<CustomObject>
    <label>School</label>
    <nameField>
        <label>School Code/UID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Schools</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/School__c/fields/SchoolCode__c.field-meta.xml
<CustomField>
    <fullName>SchoolCode__c</fullName>
    <label>School Code</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/AP15_UpdateSchoolOfInterest.cls
/**************************************************************************************
-- - Author        : Spoon Consulting
-- - Description   : Server-side controller for the component LC10_OpportunityRelatedList
--
-- Maintenance History: 
--
-- Date         Name  Version  Remarks 
-- -----------  ----  -------  -------------------------------------------------------
-- 11-10-2018   AMU    1.0     Initial version
-- 12-04-2021   FKH    1.1     Case 3305 FKH - business account contacts rule
--------------------------------------------------------------------------------------
***************************************************************************************/
public with sharing class AP15_UpdateSchoolOfInterest {
	
	public static void updateSchool(List<Contact> lstCon, Set<String> setAcc){
		try {
			//Set<String> setAcc = new Set<String>();
			Map<String, String> mapAccIdToSchoolId = new Map<String, String>();

			//for(Contact con: lstCon) {
			//	setAcc.add(con.AccountId);
			//}

			for(Account acc: [SELECT Id, SchoolOfInterest__c FROM Account WHERE Id IN: setAcc]) {
				mapAccIdToSchoolId.put(acc.Id, acc.SchoolOfInterest__c);
			}

			for(Contact con: lstCon) {
				con.SchoolOfInterest__c = mapAccIdToSchoolId.get(con.AccountId);
			}
		} catch(Exception e) {
			System.debug(e.getMessage());
		}
	}

	public static void updateSchoolBusinessAccount(List<Contact> lstCon, String schoolCode){ // Case 3305 FKH - business account contacts rule
		try {

			List<School__c> lstUserSchool = [SELECT id from School__c where schoolCode__c = :schoolCode];
            if (lstUserSchool[0]!=null){
                   for(Contact con: lstCon) {
                    con.SchoolOfInterest__c = lstUserSchool[0].id;
                	} 
            }
			
		} catch(Exception e) {
			System.debug(e.getMessage());
		}
	}
}