force-app/main/default/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Gender__c</fullName>
        <label>Gender</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Male</fullName>
                </value>
                <value>
                    <fullName>Female</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Financial_Information__c.object
<CustomObject>
    <description>To record the invoice/receipt requirements of parents/companies and the bank account information of employees</description>
    <fields>
        <fullName>Fees_Responsible_For__c</fullName>
        <label>Fees Responsible For</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>All Applicable</fullName>
                </value>
                <value>
                    <fullName>All Applicable (Shared)</fullName>
                </value>
                <value>
                    <fullName>Tuition</fullName>
                </value>
                <value>
                    <fullName>Tuition (Shared)</fullName>
                </value>
                <value>
                    <fullName>Lunch</fullName>
                </value>
                <value>
                    <fullName>Lunch (Shared)</fullName>
                </value>
                <value>
                    <fullName>Uniform</fullName>
                </value>
                <value>
                    <fullName>Uniform (Shared)</fullName>
                </value>
                <value>
                    <fullName>Bus</fullName>
                </value>
                <value>
                    <fullName>Bus (Shared)</fullName>
                </value>
                <value>
                    <fullName>EAL / Language Support</fullName>
                </value>
                <value>
                    <fullName>EAL / Language Support (Shared)</fullName>
                </value>
                <value>
                    <fullName>Extra Programmes (ASAs etc.)</fullName>
                </value>
                <value>
                    <fullName>Extra Programmes (ASAs etc.) (Shared)</fullName>
                </value>
                <value>
                    <fullName>Fee Required For Enrolment</fullName>
                </value>
                <value>
                    <fullName>Fee Required For Enrolment (Shared)</fullName>
                </value>
                <value>
                    <fullName>Annual Enrolment</fullName>
                </value>
                <value>
                    <fullName>Annual Enrolment (Shared)</fullName>
                </value>
                <value>
                    <fullName>Annual Capital Contribution</fullName>
                </value>
                <value>
                    <fullName>Annual Capital Contribution (Shared)</fullName>
                </value>
                <value>
                    <fullName>None</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Invoice_Currency__c</fullName>
        <label>Invoice Currency</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>BRL</fullName>
                </value>
                <value>
                    <fullName>CNY</fullName>
                </value>
                <value>
                    <fullName>EUR</fullName>
                </value>
                <value>
                    <fullName>GBP</fullName>
                </value>
                <value>
                    <fullName>MMK</fullName>
                </value>
                <value>
                    <fullName>MYR</fullName>
                </value>
                <value>
                    <fullName>PHP</fullName>
                </value>
                <value>
                    <fullName>RUB</fullName>
                </value>
                <value>
                    <fullName>USD</fullName>
                </value>
                <value>
                    <fullName>UZS</fullName>
                </value>
                <value>
                    <fullName>N/A</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Invoice_Frequency__c</fullName>
        <label>Invoice Frequency</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Monthly</fullName>
                </value>
                <value>
                    <fullName>Termly</fullName>
                </value>
                <value>
                    <fullName>Yearly</fullName>
                </value>
                <value>
                    <fullName>N/A</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Related_to__c</fullName>
        <label>Related to</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Financial Information</relationshipLabel>
        <relationshipName>Financial_Information</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Financial Information</label>
    <nameField>
        <displayFormat>FI-{YY}{00000}</displayFormat>
        <label>Financial Information</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Financial Information</pluralLabel>
    <recordTypes>
        <fullName>Company_Financial_Information</fullName>
        <active>true</active>
        <description>For the invoice and receipt information of companies</description>
        <label>Company Financial Information</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Gender__c</fullName>
        <label>Gender</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Gender_Options</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Student_Name__c</fullName>
        <label>Student Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Year_Group__c</fullName>
        <label>Year Group / Grade</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>US_Year_Group_Control__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>PN1</fullName>
                </value>
                <value>
                    <fullName>PN</fullName>
                </value>
                <value>
                    <fullName>N</fullName>
                </value>
                <value>
                    <fullName>R</fullName>
                </value>
                <value>
                    <fullName>Y1</fullName>
                </value>
                <value>
                    <fullName>Y2</fullName>
                </value>
                <value>
                    <fullName>Y3</fullName>
                </value>
                <value>
                    <fullName>Y4</fullName>
                </value>
                <value>
                    <fullName>Y5</fullName>
                </value>
                <value>
                    <fullName>Y6</fullName>
                </value>
                <value>
                    <fullName>Y7</fullName>
                </value>
                <value>
                    <fullName>Y8</fullName>
                </value>
                <value>
                    <fullName>Y9</fullName>
                </value>
                <value>
                    <fullName>Y10</fullName>
                </value>
                <value>
                    <fullName>Y11</fullName>
                </value>
                <value>
                    <fullName>Y12</fullName>
                </value>
                <value>
                    <fullName>Y13</fullName>
                </value>
                <value>
                    <fullName>PK</fullName>
                </value>
                <value>
                    <fullName>K</fullName>
                </value>
                <value>
                    <fullName>G1</fullName>
                </value>
                <value>
                    <fullName>G2</fullName>
                </value>
                <value>
                    <fullName>G3</fullName>
                </value>
                <value>
                    <fullName>G4</fullName>
                </value>
                <value>
                    <fullName>G5</fullName>
                </value>
                <value>
                    <fullName>G6</fullName>
                </value>
                <value>
                    <fullName>G7</fullName>
                </value>
                <value>
                    <fullName>G8</fullName>
                </value>
                <value>
                    <fullName>G9</fullName>
                </value>
                <value>
                    <fullName>G10</fullName>
                </value>
                <value>
                    <fullName>G11</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Student</fullName>
        <active>true</active>
        <businessProcess>Standard Admissions Process</businessProcess>
        <label>Student</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>Current__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Current</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Invoicing_Term__c</fullName>
        <label>Invoicing Term</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yearly</fullName>
                </value>
                <value>
                    <fullName>Termly</fullName>
                </value>
                <value>
                    <fullName>Monthly</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Months_In_Year__c</fullName>
        <label>Months In Year</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>10</fullName>
                </value>
                <value>
                    <fullName>12</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Payer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Payer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Opportunity Product</relationshipLabel>
        <relationshipName>Opportunity_Product</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Tuition__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Tuition</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

force-app/main/default/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Invoice_Currency__c</fullName>
        <label>Invoice Currency</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>EUR</fullName>
                    <default>true</default>
                    <label>EUR</label>
                </value>
                <value>
                    <fullName>BRL</fullName>
                </value>
                <value>
                    <fullName>CNY</fullName>
                </value>
                <value>
                    <fullName>GBP</fullName>
                </value>
                <value>
                    <fullName>MMK</fullName>
                </value>
                <value>
                    <fullName>MYR</fullName>
                </value>
                <value>
                    <fullName>PHP</fullName>
                </value>
                <value>
                    <fullName>RUB</fullName>
                </value>
                <value>
                    <fullName>USD</fullName>
                </value>
                <value>
                    <fullName>UZS</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Year_Group__c</fullName>
        <label>Year Group</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Description_of_fee__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>PN1</fullName>
                </value>
                <value>
                    <fullName>PN</fullName>
                </value>
                <value>
                    <fullName>N</fullName>
                </value>
                <value>
                    <fullName>R</fullName>
                </value>
                <value>
                    <fullName>Y1</fullName>
                </value>
                <value>
                    <fullName>Y2</fullName>
                </value>
                <value>
                    <fullName>Y3</fullName>
                </value>
                <value>
                    <fullName>Y4</fullName>
                </value>
                <value>
                    <fullName>Y5</fullName>
                </value>
                <value>
                    <fullName>Y6</fullName>
                </value>
                <value>
                    <fullName>Y7</fullName>
                </value>
                <value>
                    <fullName>Y8</fullName>
                </value>
                <value>
                    <fullName>Y9</fullName>
                </value>
                <value>
                    <fullName>Y10</fullName>
                </value>
                <value>
                    <fullName>Y11</fullName>
                </value>
                <value>
                    <fullName>Y12</fullName>
                </value>
                <value>
                    <fullName>Y13</fullName>
                </value>
                <value>
                    <fullName>PK</fullName>
                </value>
                <value>
                    <fullName>K</fullName>
                </value>
                <value>
                    <fullName>G1</fullName>
                </value>
                <value>
                    <fullName>G2</fullName>
                </value>
                <value>
                    <fullName>G3</fullName>
                </value>
                <value>
                    <fullName>G4</fullName>
                </value>
                <value>
                    <fullName>G5</fullName>
                </value>
                <value>
                    <fullName>G6</fullName>
                </value>
                <value>
                    <fullName>G7</fullName>
                </value>
                <value>
                    <fullName>G8</fullName>
                </value>
                <value>
                    <fullName>G9</fullName>
                </value>
                <value>
                    <fullName>G10</fullName>
                </value>
                <value>
                    <fullName>G11</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/globalValueSets/Gender_Options.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Male</fullName>
    </customValue>
    <customValue>
        <fullName>Female</fullName>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
    </customValue>
    <customValue>
        <fullName>Prefer not to say</fullName>
    </customValue>
    <masterLabel>Gender Options</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/AnnualRolloverTriggerTest.cls
public with sharing class AnnualRolloverTriggerTest {
        
        //Setup model
        /*Pricebook2 stdPB = [Select Id, isStandard from Pricebook2 Where isStandard =: true];
        Pricebook2 pb = new Pricebook2(Name = 'Test PB');
        insert pb;
        System.debug('## pb.Id : ' +pb.Id);
        
        Opportunity student = new Opportunity(Name = 'Test Student', StageName = 'Stage Name', Year_Group__c = 'Y1', CloseDate = System.today().addDays(10), 
                                                Student_Name__c = 'Morgan', Payer__c = payer.Id, Pricebook2Id = pb.Id);
        insert student;
        student = [Select Id, Year_Group__c, Payer__c From Opportunity Where Id =: student.Id];
        
        // Create a fee for year group 1
        Product2 prod1 = new Product2(
            IsActive = true,
            Name = 'prod1',
            Year_Group__c = 'Y1',
            Invoice_Currency__c = 'TEST'
        );
        insert prod1;
        prod1 = [select Id from Product2 Where Id =: prod1.Id];
        // the standard price book entry for Y1
        PricebookEntry stdPbe = new PriceBookEntry(
            isActive = true,
            UnitPrice = 1.0,
            Pricebook2Id = stdPB.Id,
            Product2Id = prod1.Id
        );
        insert stdPbe;
        // the test price book entry for Y1
        PricebookEntry pbe = new PriceBookEntry(
            isActive = true,
            UnitPrice = 1.0,
            Pricebook2Id = pb.Id,
            Product2Id = prod1.Id
        );
        insert pbe;
        pbe = [Select Id, UnitPrice from PriceBookEntry Where Id =: pbe.Id ];
        
        // Create a fee for year group 2
        Product2 prod2 = new Product2(
            IsActive = true,
            Name = 'prod2',
            Year_Group__c = 'Y2',
            Invoice_Currency__c = 'TEST'
        );
        insert prod2;
        System.debug('## prod2.Id : ' +prod2.Id);
        // the standard price book entry for Y2
        PricebookEntry stdPbe2 = new PriceBookEntry(
            isActive = true,
            UnitPrice = 1.0,
            Pricebook2Id = stdPb.Id,
            Product2Id = prod2.Id
        );
        insert stdPbe2;
        // the test price book entry for Y2
        PricebookEntry pbe2 = new PriceBookEntry(
            isActive = true,
            UnitPrice = 1.0,
            Pricebook2Id = pb.Id,
            Product2Id = prod2.Id
        );
        insert pbe2;*/
    
    @isTest(seeAllData=true)
    public static void feeAssignmentTest() {
        
        PricebookEntry pbe = [
            Select p.Product2.Invoice_Currency__c, p.Product2.Year_Group__c, p.Product2Id, UnitPrice, Pricebook2Id
            From PricebookEntry p 
            Where p.Product2.Year_Group__c = 'Y1' and p.Product2.Invoice_Currency__c = 'EUR' 
            limit 1
        ];
        
        Account payer = new Account(
            Name = 'Test'
        );
        insert payer;
        
        //insert related financial info
        Financial_Information__c fi = new Financial_Information__c();
        fi.Related_to__c = payer.Id;
        fi.Invoice_Currency__c = 'MYR';
        fi.Invoice_Frequency__c = 'Monthly';
        fi.Fees_Responsible_For__c = 'All Applicable;';
        fi.RecordTypeId = [select Id from RecordType where DeveloperName = 'Company_Financial_Information'].Id;
        insert fi;
        
        Opportunity student = new Opportunity(
            Name = 'Test Student',
            Gender__c = 'Male',
            StageName = 'A/ Testing', 
            Year_Group__c = 'Y1', 
            CloseDate = System.today().addDays(10),
            Student_Name__c = 'Morgan', 
            
            Pricebook2Id = pbe.Pricebook2Id
        );
        insert student;
        student.StageName = 'Enrolled';
        update student;
        
        OpportunityLineItem oli = new OpportunityLineItem(
            PricebookEntryId = pbe.Id,
            OpportunityId = student.Id,
            Quantity = 1,
            TotalPrice = pbe.UnitPrice,
            Current__c = true,
            Tuition__c = true,
            
            Months_In_Year__c = '10',
            Invoicing_Term__c = 'Monthly'
        );
        insert oli;
        
        //change the year.
        student.Year_Group__c = 'Y2';
        update student;
        
        List<OpportunityLineItem> studentOLIs = [
            Select Id, OpportunityId
            From OpportunityLineItem
            Where OpportunityId =: student.Id
        ]; 
        
        System.assertequals(2, studentOLIs.size());
    }
}