force-app/main/default/objects/Account.object
<CustomObject>
    <fields>
        <fullName>School__c</fullName>
        <description>Copies the value of SchoolText (which is a workflow copying from School Formula). A little long winded solution to avoid bigger changes in the Teacher/Parent portal.</description>
        <formula>SchoolText__pc</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>School</label>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>School__c</fullName>
        <formula>Admissions_File__r.School__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>School</label>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Contact</fullName>
        <active>true</active>
        <label>Contact</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/School__c.object
<CustomObject>
    <label>School</label>
    <nameField>
        <label>School Code/UID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Schools</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/School__c/fields/SchoolCode__c.field-meta.xml
<CustomField>
    <fullName>SchoolCode__c</fullName>
    <label>School Code</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User.object
<CustomObject>
    <fields>
        <fullName>School__c</fullName>
        <label>School</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>The British Schools Foundation</fullName>
                </value>
                <value>
                    <fullName>The British School of Guangzhou</fullName>
                </value>
                <value>
                    <fullName>The British School of Nanjing</fullName>
                </value>
                <value>
                    <fullName>The British International School of Marbella</fullName>
                </value>
                <value>
                    <fullName>The British School of Navarra</fullName>
                </value>
                <value>
                    <fullName>The British School of Tashkent</fullName>
                </value>
                <value>
                    <fullName>The British College of Brazil</fullName>
                </value>
                <value>
                    <fullName>The British International School of Kuala Lumpur</fullName>
                </value>
                <value>
                    <fullName>The International School of Moscow</fullName>
                </value>
                <value>
                    <fullName>Nord Anglia International School Manila</fullName>
                </value>
                <value>
                    <fullName>King&apos;s College Beijing</fullName>
                </value>
                <value>
                    <fullName>The British School Yangon</fullName>
                </value>
                <value>
                    <fullName>Ukraine International School</fullName>
                </value>
                <value>
                    <fullName>The New York International School</fullName>
                </value>
                <value>
                    <fullName>The British School of Brasilia</fullName>
                </value>
                <value>
                    <fullName>NAE</fullName>
                </value>
                <value>
                    <fullName>The British International School Yangon</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/classes/AP15_UpdateSchoolOfInterest_TEST.cls
/**************************************************************************************
-- - Author        : Spoon Consulting
-- - Description   : Test class for AP15_UpdateSchoolOfInterest
--
-- Maintenance History: 
--
-- Date         Name  Version  Remarks 
-- -----------  ----  -------  -------------------------------------------------------
-- 30-OCT-2018  KZE    1.0     Initial version
--------------------------------------------------------------------------------------
***************************************************************************************/
@isTest
public with sharing class AP15_UpdateSchoolOfInterest_TEST {
    static List<User> lstUser;
    static List<Account> lstAcc;
    static List<Contact> lstContact;
    static List<School__c> lstSchool;
    static Map<String,Id> mapRecordType;

    static {
        mapRecordType = AP_Constant.getDeveloperIdMap(new Set<String>{AP_Constant.oppObject, AP_Constant.conObject});

        lstUser = new List<User>{TestFactory.createUser('Test', TestFactory.getProfileAdminId())};
        lstUser[0].Schoolcode__c = 'XXX';
        insert lstUser;

        System.runAs(lstUser[0]){
        	lstSchool = new List<School__c>{
                TestFactory.createSchool('Test', 'Mauritius', false, 'TST'),
                TestFactory.createSchool('Test', 'Mauritius', false, 'XXX')
          
            };
            insert lstSchool;

            lstAcc = new List<Account>{
            	TestFactory.createAccount('test'),
            	TestFactory.createAccount('test1')
             };
            lstAcc[0].SchoolOfInterest__c = lstSchool[0].Id;
            lstAcc[1].SchoolOfInterest__c = lstSchool[0].Id;

            insert lstAcc;

            lstContact = new List<Contact>{
                TestFactory.createContact('Smith', lstAcc[0].Id, mapRecordType.get(AP_Constant.conRecordTypeChild)),
                TestFactory.createContact('Smith', lstAcc[0].Id, mapRecordType.get(AP_Constant.conRecordTypeChild)),
                TestFactory.createContact('SmithExtern', lstAcc[1].Id, mapRecordType.get(AP_Constant.conRecordTypeExternalRelationships))

            };
            lstContact[0].FirstName = 'John';
            lstContact[1].FirstName = 'Jane';
        }
    }

    @isTest public static void updateSchoolTest(){
        System.runAs(lstUser[0]){
            test.StartTest();
        	    insert lstContact;
            test.StopTest();

            List<Contact> lstContactGOT = [SELECT Id, SchoolOfInterest__c, AccountId FROM Contact WHERE AccountId =: lstAcc[0].Id];
            System.assertEquals(lstSchool[0].Id, lstContactGOT[0].SchoolOfInterest__c);
            System.assertEquals(lstSchool[0].Id, lstContactGOT[1].SchoolOfInterest__c);
        }
    }
    
    
        @isTest public static void updateSchoolBusinessTest(){
        System.runAs(lstUser[0]){
            test.StartTest();
        	    insert lstContact;
            test.StopTest();
            List<Contact> lstContactGOT = [SELECT Id, SchoolOfInterest__c, AccountId FROM Contact WHERE AccountId =: lstAcc[1].Id];
            
            System.assertEquals(lstSchool[1].Id, lstContactGOT[0].SchoolOfInterest__c);
        }
    }
}