force-app/main/default/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Error_Message__c</fullName>
        <label>Error Message</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Gender__c</fullName>
        <label>Gender</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Male</fullName>
                </value>
                <value>
                    <fullName>Female</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Leaving_Date__c</fullName>
        <label>Leaving Date (Account)</label>
        <summarizedField>Opportunity.Leaving_Date__c</summarizedField>
        <summaryForeignKey>Opportunity.AccountId</summaryForeignKey>
        <summaryOperation>max</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>School__c</fullName>
        <description>Copies the value of SchoolText (which is a workflow copying from School Formula). A little long winded solution to avoid bigger changes in the Teacher/Parent portal.</description>
        <formula>SchoolText__pc</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>School</label>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Company_Account</fullName>
        <active>true</active>
        <label>Company</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Gender__c</fullName>
        <description>This field is configured in NPSP Settings &gt; Relationships &gt; Relationships as the Gender field. Do not delete this field unless you remove the reference or select another Gender field there.</description>
        <label>Gender</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Male</fullName>
                </value>
                <value>
                    <fullName>Female</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Leaving_Date__c</fullName>
        <formula>Main_Parent_File__r.Leaving_Date__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Leaving Date (Contact)</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>School__c</fullName>
        <formula>Admissions_File__r.School__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>School</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Student_Name__c</fullName>
        <formula>IF(Admissions_File__r.Nickname__c &lt;&gt; &quot;&quot;, LastName&amp;&quot;, &quot;&amp;FirstName&amp;&quot; (&quot;&amp;Admissions_File__r.Nickname__c&amp;&quot;)&quot;,

LastName&amp;&quot;, &quot;&amp;FirstName)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Student Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Year_Group__c</fullName>
        <formula>TEXT(Admissions_File__r.Year_Group__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Year Group</label>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Contact</fullName>
        <active>true</active>
        <label>Contact</label>
    </recordTypes>
    <recordTypes>
        <fullName>Student</fullName>
        <active>true</active>
        <label>Student Academic File</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice_Statement__c.object
<CustomObject>
    <fields>
        <fullName>Currency__c</fullName>
        <label>Currency</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Error_Message__c</fullName>
        <label>Error Message</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Generated_Date__c</fullName>
        <label>Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Invoice_Date__c</fullName>
        <label>Invoice Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Payer__c</fullName>
        <label>Parent/Company</label>
        <lookupFilter>
            <active>false</active>
            <booleanFilter>1 OR 2</booleanFilter>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Company</value>
            </filterItems>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Parent</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Invoices</relationshipLabel>
        <relationshipName>Invoice_Statements1</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Reference__c</fullName>
        <label>Reference</label>
        <length>10000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>School__c</fullName>
        <label>School</label>
        <length>32</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Xero_Id__c</fullName>
        <inlineHelpText>The value in this field must be unique. If you need to manually link this invoice to a Xero invoice then please send the URL of both, in a spreadsheet, to the relevant member of the group management team</inlineHelpText>
        <label>Xero Id</label>
        <length>64</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Xero_Key__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contract Setup</label>
        <referenceTo>Xero_Key__c</referenceTo>
        <relationshipLabel>Invoices</relationshipLabel>
        <relationshipName>Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Invoice</label>
    <nameField>
        <displayFormat>{YY}-{00000}</displayFormat>
        <label>Salesforce UID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Line_Item__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Invoice_Statement__c</fullName>
        <label>Invoice Statement</label>
        <referenceTo>Invoice_Statement__c</referenceTo>
        <relationshipLabel>Line Items</relationshipLabel>
        <relationshipName>Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>School__c</fullName>
        <formula>Student__r.School__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>School</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Student__c</fullName>
        <label>Student</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Invoice Line Items</relationshipLabel>
        <relationshipName>Line_Items</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Line Item</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Line Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Gender__c</fullName>
        <label>Gender</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Gender_Options</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Leaving_Date__c</fullName>
        <label>Leaving Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Reason_Leaving__c</fullName>
        <label>Reason Leaving</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>StageName</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Relocation (out of city)</fullName>
                </value>
                <value>
                    <fullName>** Parent Decision **</fullName>
                </value>
                <value>
                    <fullName>a. Location</fullName>
                </value>
                <value>
                    <fullName>b. Early entry to University/higher education</fullName>
                </value>
                <value>
                    <fullName>c. Not satisfied with school</fullName>
                </value>
                <value>
                    <fullName>d. Change in family situation/Visa issues</fullName>
                </value>
                <value>
                    <fullName>e. Financial concern</fullName>
                </value>
                <value>
                    <fullName>f. Does not offer relevant product</fullName>
                </value>
                <value>
                    <fullName>g. Other</fullName>
                </value>
                <value>
                    <fullName>** School Decision **</fullName>
                </value>
                <value>
                    <fullName>a. Non-payment of Fees</fullName>
                </value>
                <value>
                    <fullName>b. Academic standards not achieved</fullName>
                </value>
                <value>
                    <fullName>c. Poor Behaviour</fullName>
                </value>
                <value>
                    <fullName>d. Other</fullName>
                </value>
                <value>
                    <fullName>Final school year</fullName>
                </value>
                <value>
                    <fullName>Switch to boarding or intra-school transfer</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>School__c</fullName>
        <formula>Account.SchoolText__pc</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>School</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Student_Name__c</fullName>
        <label>Student Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Year_Group__c</fullName>
        <label>Year Group / Grade</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>US_Year_Group_Control__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>PN1</fullName>
                </value>
                <value>
                    <fullName>PN</fullName>
                </value>
                <value>
                    <fullName>N</fullName>
                </value>
                <value>
                    <fullName>R</fullName>
                </value>
                <value>
                    <fullName>Y1</fullName>
                </value>
                <value>
                    <fullName>Y2</fullName>
                </value>
                <value>
                    <fullName>Y3</fullName>
                </value>
                <value>
                    <fullName>Y4</fullName>
                </value>
                <value>
                    <fullName>Y5</fullName>
                </value>
                <value>
                    <fullName>Y6</fullName>
                </value>
                <value>
                    <fullName>Y7</fullName>
                </value>
                <value>
                    <fullName>Y8</fullName>
                </value>
                <value>
                    <fullName>Y9</fullName>
                </value>
                <value>
                    <fullName>Y10</fullName>
                </value>
                <value>
                    <fullName>Y11</fullName>
                </value>
                <value>
                    <fullName>Y12</fullName>
                </value>
                <value>
                    <fullName>Y13</fullName>
                </value>
                <value>
                    <fullName>PK</fullName>
                </value>
                <value>
                    <fullName>K</fullName>
                </value>
                <value>
                    <fullName>G1</fullName>
                </value>
                <value>
                    <fullName>G2</fullName>
                </value>
                <value>
                    <fullName>G3</fullName>
                </value>
                <value>
                    <fullName>G4</fullName>
                </value>
                <value>
                    <fullName>G5</fullName>
                </value>
                <value>
                    <fullName>G6</fullName>
                </value>
                <value>
                    <fullName>G7</fullName>
                </value>
                <value>
                    <fullName>G8</fullName>
                </value>
                <value>
                    <fullName>G9</fullName>
                </value>
                <value>
                    <fullName>G10</fullName>
                </value>
                <value>
                    <fullName>G11</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Student</fullName>
        <active>true</active>
        <businessProcess>Standard Admissions Process</businessProcess>
        <label>Student</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Xero_Key__c.object
<CustomObject>
    <fields>
        <fullName>Consumer_Key__c</fullName>
        <label>Consumer Key</label>
        <length>32</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Contract Setup</label>
    <nameField>
        <label>Contract Setup</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contract Setup</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/globalValueSets/Gender_Options.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Male</fullName>
    </customValue>
    <customValue>
        <fullName>Female</fullName>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
    </customValue>
    <customValue>
        <fullName>Prefer not to say</fullName>
    </customValue>
    <masterLabel>Gender Options</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/BatchInvoiceSendingTest.cls
@isTest
private with sharing class BatchInvoiceSendingTest {
    
    static testMethod void testInvoiceNoLineItems() {
        //setup the model 
        Account payer = new Account(Name = 'Test');
        insert payer;
        payer = [Select Id From Account Where Id =: payer.Id];
        
        //create a Xero Key
        Xero_Key__c testKey = new Xero_Key__c(
            Name = 'Kuala Lumpur',
            Consumer_Key__c = '...'
        );
        insert testKey;
        
        //create an invoice
        Invoice_Statement__c invoice = new Invoice_Statement__c();
        invoice.payer__c = payer.Id;
        invoice.Reference__c = 'James,Miller';
        invoice.Invoice_Date__c = System.today().addDays(2);
        invoice.Generated_Date__c = System.today();
        invoice.Currency__c = 'USD';
        invoice.School__c = 'Kuala Lumpur';
        invoice.Xero_Key__c = testKey.Id;
        invoice.Xero_Id__c = 'testKey2unique';
        insert invoice;
        
        ApexPages.StandardController sc = new ApexPages.StandardController(invoice);
        SendSingleInvoiceController cont = new SendSingleInvoiceController(sc);
        cont.sendToXero();
        
        PageReference pageRef = Page.SendSingleInvoice;
        pageRef.getParameters().put('id', String.valueOf(invoice.Id));
        Test.setCurrentPage(pageRef);
        
        
        
        //run the batch test
        BatchInvoiceSending batch = new BatchInvoiceSending();
        
        List<Invoice_Statement__c> invoices = new List<Invoice_Statement__c>();
        invoices.add(invoice);
        batch.sendInvoices(invoices);
        
        //make the assertions
        invoice = [
            SELECT Id, Error_Message__c
              FROM Invoice_Statement__c
             WHERE Id =: invoice.Id
        ];
        System.assertEquals('No line items found.', invoice.Error_Message__c);
    }

    static testMethod void testNoXeroKey() {
        //setup the model 
        Account payer = new Account(Name = 'Test');
        insert payer;
        payer = [Select Id From Account Where Id =: payer.Id];

        Opportunity studentOne = new Opportunity(Name = 'Student', Gender__c = 'Male', StageName = 'A/ Testing', Year_Group__c = 'Y1', CloseDate = System.today().addDays(10), 
                                                    Student_Name__c = 'Morgan', //Payer__c = payer.Id,
                                                    Leaving_date__c = System.today().addYears(1), Reason_Leaving__c = 'Relocation (out of city)');
        insert studentOne;
        studentOne.StageName = 'Enrolled';
        update studentOne;
        
        //create a Xero Key
        Xero_Key__c testKey = new Xero_Key__c(
            Name = 'Kuala Lumpur',
            Consumer_Key__c = '...'
        );
        insert testKey;
        
        //create an invoice
        Invoice_Statement__c invoice = new Invoice_Statement__c();
        invoice.payer__c = payer.Id;
        invoice.Reference__c = 'James,Miller';
        invoice.Invoice_Date__c = System.today().addDays(2);
        invoice.Generated_Date__c = System.today();
        invoice.Currency__c = 'USD';
        invoice.School__c = 'Kuala Lumpur';
        invoice.Xero_Key__c = testKey.Id;
        invoice.Xero_Id__c = 'testKey2unique';
        insert invoice;
        
        Line_Item__c lineItem = new Line_Item__c(
            Invoice_Statement__c = invoice.Id,
            Student__c = studentOne.Id,
            Description__c = 'Monthly, Termly or Yearly '     
        );
        insert lineItem;
        
        ApexPages.StandardController sc = new ApexPages.StandardController(invoice);
        SendSingleInvoiceController cont = new SendSingleInvoiceController(sc);
        cont.sendToXero();
        
        PageReference pageRef = Page.SendSingleInvoice;
        pageRef.getParameters().put('id', String.valueOf(invoice.Id));
        Test.setCurrentPage(pageRef);
        
        //run the batch test
        BatchInvoiceSending batch = new BatchInvoiceSending();
        
        List<Invoice_Statement__c> invoices = new List<Invoice_Statement__c>();
        invoices.add(invoice);
        batch.sendInvoices(invoices);
        
        //make the assertions
        invoice = [
            SELECT Id, Error_Message__c
              FROM Invoice_Statement__c
             WHERE Id =: invoice.Id
        ];
        //System.assertEquals('Xero Credentials not found for ', invoice.Error_Message__c);
    }
    
    static testMethod void testInvoiceSendingFirstPrimary() {
        
        //create company account account
        Account companyAccount =  new Account();
        companyAccount.Name =  'Company Account';
        companyAccount.RecordTypeId = [Select Id from RecordType where SObjectType='Account' AND DeveloperName='Company_Account'].Id;
        insert companyAccount;
        
        //setup the model 
        Account payer = new Account(FirstName = 'Test', LastName = 'Name');
        payer.RecordTypeId = [select Id from RecordType where SObjectType = 'Account' AND DeveloperName = 'PersonAccount'].Id;
        payer.Email_Addresses_to_Include_in_Xero__c ='Parent 1 Main Email;Parent 1 Alternate Email;Parent 2 Main Email;Parent 2 Alternate Email';
        payer.PersonEmail = 'test1@test.com';
        payer.Contact_Alternate_Email__pc = 'test2@test.com';
        
        payer.Primary_Invoicing_Contact__c = 'First Parent'; 
        insert payer;
        
        //create contact
        Contact con =  new Contact();
        con.FirstName = 'test2';
        con.LastName = 'name 2';
        con.Email = 'test23@test.com';
        con.RecordTypeId = [select Id from RecordType where Name = 'Additional Parent' AND SObjectType = 'Contact'].Id;
        con.Contact_Alternate_Email__c = 'tet@vgfhf.com';
        con.AccountId = companyAccount.Id;
        con.Main_Parent_File__c = payer.Id;
        insert con;
        payer.Related_Contact_Record_P2__c = con.Id;
        update payer;
        
        
        payer = [Select Id From Account Where Id =: payer.Id];
        
        Opportunity studentOne = new Opportunity(Name = 'Student', Gender__c = 'Male', StageName = 'A/ Testing', Year_Group__c = 'Y1', CloseDate = System.today().addDays(10), 
                                                    Student_Name__c = 'Morgan', //Payer__c = payer.Id,
                                                    Leaving_date__c = System.today().addYears(1), Reason_Leaving__c = 'Relocation (out of city)');
        insert studentOne;
        studentOne.StageName = 'Enrolled';
        update studentOne;
        
         //create a Xero Key
        Xero_Key__c testKey = new Xero_Key__c(
            Name = 'Kuala Lumpur',
            Consumer_Key__c = '...'
        );
        insert testKey;
        
        //create an invoice and some line items
        Invoice_Statement__c invoice = new Invoice_Statement__c();
        invoice.payer__c = payer.Id;
        invoice.Reference__c = 'James,Miller';
        invoice.Invoice_Date__c = System.today().addDays(2);
        invoice.Generated_Date__c = System.today();
        invoice.Currency__c = 'USD';
        invoice.School__c = 'Kuala Lumpur';
        invoice.Xero_Key__c = testKey.Id;
        insert invoice;
        
        Line_Item__c lineItem = new Line_Item__c(
            Invoice_Statement__c = invoice.Id,
            Student__c = studentOne.Id,
            Description__c = 'Monthly, Termly or Yearly '         
        );
        insert lineItem;
        
        //run the batch test
        BatchInvoiceSending batch = new BatchInvoiceSending();
        
        List<Invoice_Statement__c> invoices = new List<Invoice_Statement__c>();
        invoices.add(invoice);
        batch.sendInvoices(invoices);
        
        //make the assertions
        invoice = [
            SELECT Id, Error_Message__c
              FROM Invoice_Statement__c
             WHERE Id =: invoice.Id
        ];
        System.assertEquals('Test Pass', invoice.Error_Message__c);
    }

    static testMethod void testInvoiceSendingSecondPrimary() {
        
        //create company account account
        Account companyAccount =  new Account();
        companyAccount.Name =  'Company Account';
        companyAccount.RecordTypeId = [Select Id from RecordType where SObjectType='Account' AND DeveloperName='Company_Account'].Id;
        insert companyAccount;
        
        //setup the model 
        Account acc = new Account(FirstName = 'Test', LastName = 'Name');
        acc.RecordTypeId = [select Id from RecordType where SObjectType = 'Account' AND DeveloperName = 'PersonAccount'].Id;
        acc.Email_Addresses_to_Include_in_Xero__c ='Parent 1 Main Email;Parent 1 Alternate Email;Parent 2 Main Email;Parent 2 Alternate Email';
        acc.PersonEmail = 'test1@test.com';
        acc.Contact_Alternate_Email__pc = 'test2@test.com';        
        insert acc;
        
        //create contact
        Contact payer =  new Contact();
        payer.FirstName = 'test2';
        payer.LastName = 'name 2';
        payer.Email = 'test23@test.com';
        payer.RecordTypeId = [select Id from RecordType where Name = 'Additional Parent' AND SObjectType = 'Contact'].Id;
        payer.Contact_Alternate_Email__c = 'tet@vgfhf.com';
        payer.AccountId = companyAccount.Id;
        payer.Main_Parent_File__c = acc.Id;
        insert payer;
        
        //update account
        acc.Related_Contact_Record_P2__c = payer.Id;
        acc.Primary_Invoicing_Contact__c = 'Second Parent';
        update acc;
        
        payer = [Select Id From Contact Where Id =: payer.Id];
        
        Opportunity studentOne = new Opportunity(Name = 'Student', Gender__c = 'Male', StageName = 'A/ Testing', Year_Group__c = 'Y1', CloseDate = System.today().addDays(10), 
                                                    Student_Name__c = 'Morgan', //Payer__c = payer.Id,
                                                    Leaving_date__c = System.today().addYears(1), Reason_Leaving__c = 'Relocation (out of city)');
        insert studentOne;
        studentOne.StageName = 'Enrolled';
        update studentOne;
        
         //create a Xero Key
        Xero_Key__c testKey = new Xero_Key__c(
            Name = 'Kuala Lumpur',
            Consumer_Key__c = '...'
        );
        insert testKey;
        
        //create an invoice and some line items
        Invoice_Statement__c invoice = new Invoice_Statement__c();
        invoice.payer__c = acc.Id;
        invoice.Reference__c = 'James,Miller';
        invoice.Invoice_Date__c = System.today().addDays(2);
        invoice.Generated_Date__c = System.today();
        invoice.Currency__c = 'USD';
        invoice.School__c = 'Kuala Lumpur';
        invoice.Xero_Key__c = testKey.Id;
        insert invoice;
        
        Line_Item__c lineItem = new Line_Item__c(
            Invoice_Statement__c = invoice.Id,
            Student__c = studentOne.Id,
            Description__c = 'Monthly, Termly or Yearly '
            
        );
        insert lineItem;
        
        //run the batch test
        BatchInvoiceSending batch = new BatchInvoiceSending();
        
        List<Invoice_Statement__c> invoices = new List<Invoice_Statement__c>();
        invoices.add(invoice);
        batch.sendInvoices(invoices);
        
        //make the assertions
        invoice = [
            SELECT Id, Error_Message__c
              FROM Invoice_Statement__c
             WHERE Id =: invoice.Id
        ];
        System.assertEquals('Test Pass', invoice.Error_Message__c);
    }

}