force-app/main/default/objects/Account.object
<CustomObject>
    <fields>
        <fullName>School__c</fullName>
        <description>Copies the value of SchoolText (which is a workflow copying from School Formula). A little long winded solution to avoid bigger changes in the Teacher/Parent portal.</description>
        <formula>SchoolText__pc</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>School</label>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>School__c</fullName>
        <formula>Admissions_File__r.School__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>School</label>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Contact</fullName>
        <active>true</active>
        <label>Contact</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>School__c</fullName>
        <formula>Account.SchoolText__pc</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>School</label>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/School__c.object
<CustomObject>
    <label>School</label>
    <nameField>
        <label>School Code/UID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Schools</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/School__c/fields/SchoolCode__c.field-meta.xml
<CustomField>
    <fullName>SchoolCode__c</fullName>
    <label>School Code</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User.object
<CustomObject>
    <fields>
        <fullName>School__c</fullName>
        <label>School</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>The British Schools Foundation</fullName>
                </value>
                <value>
                    <fullName>The British School of Guangzhou</fullName>
                </value>
                <value>
                    <fullName>The British School of Nanjing</fullName>
                </value>
                <value>
                    <fullName>The British International School of Marbella</fullName>
                </value>
                <value>
                    <fullName>The British School of Navarra</fullName>
                </value>
                <value>
                    <fullName>The British School of Tashkent</fullName>
                </value>
                <value>
                    <fullName>The British College of Brazil</fullName>
                </value>
                <value>
                    <fullName>The British International School of Kuala Lumpur</fullName>
                </value>
                <value>
                    <fullName>The International School of Moscow</fullName>
                </value>
                <value>
                    <fullName>Nord Anglia International School Manila</fullName>
                </value>
                <value>
                    <fullName>King&apos;s College Beijing</fullName>
                </value>
                <value>
                    <fullName>The British School Yangon</fullName>
                </value>
                <value>
                    <fullName>Ukraine International School</fullName>
                </value>
                <value>
                    <fullName>The New York International School</fullName>
                </value>
                <value>
                    <fullName>The British School of Brasilia</fullName>
                </value>
                <value>
                    <fullName>NAE</fullName>
                </value>
                <value>
                    <fullName>The British International School Yangon</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/classes/AP23_ListEmailOpportunity_TEST.cls
/**
 * @File Name          : AP23_ListEmailOpportunity_TEST.cls
 * @Description        : Test Class for AP23_ListEmailOpportunity
 * @Author             : Spoon Consulting
 * @Group              : 
 * @Last Modified By   : CRA
 * @Last Modified On   : 12/12/2019, 12:47:56
 * @Modification Log   : 
 * Ver       Date            Author                 Modification
 * 1.0    12/12/2019         CRA                    Initial Version
**/
@isTest
public with sharing class AP23_ListEmailOpportunity_TEST {
    static User testUserAdmin;
    static List<Account> lstAccount;
    static List<Contact> lstContact;
    static List<Opportunity> lstOpp;   
    static List<School__c> lstSchool;
    static Map<string,Id> mapRecordType = new Map<String, Id>();

    static{
        testUserAdmin = TestFactory.createUser('testUserAdmin',TestFactory.getProfileAdminId());
        testUserAdmin.SchoolCode__c = 'TST';
        insert testUserAdmin;

        System.runAs(testUserAdmin){
            lstSchool = new List<School__c>{
                TestFactory.createSchool('TestUser1', 'Mauritius', false, 'TST'),
                TestFactory.createSchool('TestUser2', 'Mauritius', false, 'LOL')
            };
            insert lstSchool;

            mapRecordType = AP_Constant.getDeveloperIdMap(new Set<String>{AP_Constant.oppObject, AP_Constant.conObject, AP_Constant.accObject});

            lstAccount = new List<Account> {
                 TestFactory.createAccount('testAcc1')
                ,TestFactory.createAccount('testAcc2')
            };
            insert lstAccount;

            lstOpp = new List<Opportunity> {
                TestFactory.createOpportunity('child1 opp', lstAccount[0].Id, AP_Constant.oppStageNameEnquiry, mapRecordType.get(AP_Constant.oppRecordTypeEnrolment), lstSchool[0].Id)
                ,TestFactory.createOpportunity('child2 opp', lstAccount[0].Id, AP_Constant.oppStageNameEnquiry, mapRecordType.get(AP_Constant.oppRecordTypeEnrolment), lstSchool[0].Id)
                ,TestFactory.createOpportunity('child1Acc2 opp', lstAccount[1].Id, AP_Constant.oppStageNameEnquiry, mapRecordType.get(AP_Constant.oppRecordTypeEnrolment), lstSchool[0].Id)
            };
            insert lstOpp;
        }
    }

    @IsTest
    static void testPage(){
        System.runAs(testUserAdmin){
            List<Opportunity> lstOppRes = [SELECT id, AccountId, Name FROM Opportunity];
            Test.startTest();
            Pagereference testPage = Page.VFP23_ListEmail;
            Test.setCurrentPage(testPage);
            //Apexpages.currentPage().getParameters().put('id', lstOpp[0].Id);
            ApexPages.StandardSetController pageCtrl = new ApexPages.StandardSetController(lstOppRes);
            pageCtrl.setSelected(lstOppRes);
            AP23_ListEmailOpportunity controller = new AP23_ListEmailOpportunity(pageCtrl);
            PageReference pageRes = controller.doSomething();
            Test.stopTest();

            System.assertEquals(null, pageRes);
        }
    }
}