force-app/main/default/objects/Account.object
<CustomObject>
    <fields>
        <fullName>School__c</fullName>
        <description>Copies the value of SchoolText (which is a workflow copying from School Formula). A little long winded solution to avoid bigger changes in the Teacher/Parent portal.</description>
        <formula>SchoolText__pc</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>School</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <formula>IF( 
   Count_Active_Contracts__c &gt; 0, 
   &quot;Employed&quot;,
   IF(
      Count_Signed_Not_started_Contracts__c &gt; 0,
      &quot;Signed-On&quot;,
      IF(
         Count_Expired_Contracts__c &gt; 0,
         &quot;Left&quot;, 
         IF( 
            Unsuccessful_Applicant__c = TRUE, 
            &quot;Unsuccessful Applicant&quot;, 
            &quot;Applicant&quot;
            )
         )
      )
   )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Status</label>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice_Statement__c.object
<CustomObject>
    <fields>
        <fullName>Account_Id__c</fullName>
        <formula>Payer__r.Id</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Account Id</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Reference__c</fullName>
        <label>Reference</label>
        <length>10000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>School__c</fullName>
        <label>School</label>
        <length>32</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Xero_Id__c</fullName>
        <inlineHelpText>The value in this field must be unique. If you need to manually link this invoice to a Xero invoice then please send the URL of both, in a spreadsheet, to the relevant member of the group management team</inlineHelpText>
        <label>Xero Id</label>
        <length>64</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Xero_Invoice_Currency__c</fullName>
        <label>Xero Invoice Currency</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Xero_Invoice_Date__c</fullName>
        <label>Xero Invoice Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Xero_Invoice_Number__c</fullName>
        <label>Xero Invoice Number</label>
        <length>64</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Xero_Key__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contract Setup</label>
        <referenceTo>Xero_Key__c</referenceTo>
        <relationshipLabel>Invoices</relationshipLabel>
        <relationshipName>Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Xero_Status__c</fullName>
        <label>Xero Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Xero_Value__c</fullName>
        <label>Xero Value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Invoice</label>
    <nameField>
        <displayFormat>{YY}-{00000}</displayFormat>
        <label>Salesforce UID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/School__c.object
<CustomObject>
    <label>School</label>
    <nameField>
        <label>School Code/UID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Schools</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Xero_Key__c.object
<CustomObject>
    <fields>
        <fullName>AccCode_Application__c</fullName>
        <label>AccCode Application</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AccCode_Bus__c</fullName>
        <label>AccCode Bus</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AccCode_EAL__c</fullName>
        <label>AccCode EAL</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AccCode_Enrolment__c</fullName>
        <label>AccCode Enrolment</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AccCode_Lunch__c</fullName>
        <label>AccCode Lunch</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AccCode_Other__c</fullName>
        <label>AccCode Other</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AccCode_Tuition__c</fullName>
        <label>AccCode Tuition</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Consumer_Key__c</fullName>
        <label>Consumer Key</label>
        <length>32</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Consumer_Secret__c</fullName>
        <label>Consumer Secret</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Private_Key__c</fullName>
        <label>Private Key</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Contract Setup</label>
    <nameField>
        <label>Contract Setup</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contract Setup</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Xero_Payment__c.object
<CustomObject>
    <description>A payment recorded on an invoice. This gets queried from Xero.</description>
    <fields>
        <fullName>Account_Id__c</fullName>
        <label>Account Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Currency_Rate__c</fullName>
        <label>Currency Rate</label>
        <precision>16</precision>
        <scale>10</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Invoice_Statement__c</fullName>
        <description>Lookup to the Invoice for which this payment is associated.</description>
        <label>Invoice</label>
        <referenceTo>Invoice_Statement__c</referenceTo>
        <relationshipLabel>Payments</relationshipLabel>
        <relationshipName>Payments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Payment_Amount__c</fullName>
        <label>Payment Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Payment_Currency__c</fullName>
        <label>Payment Currency (Xero)</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Payment_Date__c</fullName>
        <label>Payment Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Reference__c</fullName>
        <label>Reference</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>School__c</fullName>
        <formula>Invoice_Statement__r.School__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>School</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Xero_Account_Name__c</fullName>
        <label>Paid to</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Xero_Id__c</fullName>
        <description>Unique Id of payment record in Xero</description>
        <externalId>true</externalId>
        <label>Xero Id</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Payment</label>
    <nameField>
        <displayFormat>PAY{YY}{MM}-{0000}</displayFormat>
        <label>Payment Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/InvoiceUpdateFromXeroLogic.cls
/**
 * Logic to update an invoice from Xero. This code is run by clicking a button on the invoice view,
 * or by a batch job that updates many invoices.
 * 
 * @author Logan moore
 * @created July 2013
 * @modified July 2013
 * @testclass InvoiceUpdateFromXeroLogicTest
 */
public with sharing class InvoiceUpdateFromXeroLogic {

	/** Custom exception class for throwing nice error messages */
	public class UpdateFromXeroException extends Exception {}

	/**
	 * Fetches the related invoice from Xero, and updates information in the local record
	 * to reflect what's stored in Xero. Also updates a list of related payment records.
	 * 
	 * @param invoiceRecordId the id of an Invoice_Statement__c to be updated from Xero
	 * @return true if successfull, else false
	 */
	public static void updateSingleInvoice(Id invoiceRecordId) {

		// Get invoice record for which an update has been requested
		Invoice_Statement__c invoice = queryInvoice(invoiceRecordId);

		// Retrieve the Xero Credentials which depend on the school being used
		Xero_Key__c xeroKey = queryXeroKey(invoice.School__c);

		// Setup the Xero Credentials
		sfXero.XeroCredentials xeroCreds = xeroKeyToCredentials(xeroKey);

		// Fetch the invoice from Xero
		sfXero.XeroInvoiceResponse invoiceResponse = sfXero.XeroAPI.getInvoiceById(xeroCreds, invoice.Xero_Id__c);

		// If no invoices are returned from Xero
		if (invoiceResponse.invoices.size() == 0) {
			throw new UpdateFromXeroException('Invoice not found in xero with id ' + invoice.Xero_Id__c);
		}

		// Pull the invoice into it's own variable
		sfXero.XeroInvoice xeroInvoice = invoiceResponse.invoices[0];

		// Write the xero invoice details to the salesforce invoice record
		invoice.Xero_Id__c = xeroInvoice.invoiceId;
		invoice.Xero_Invoice_Number__c = xeroInvoice.invoiceNumber;
		invoice.Xero_Value__c = xeroInvoice.total;
		invoice.Xero_Status__c = String.valueOf(xeroInvoice.status);
		invoice.Xero_Invoice_Date__c = xeroInvoice.issuedDate;
		invoice.Xero_Invoice_Currency__c = xeroInvoice.currencyCode;
		
		if (invoice.Payments__r.size() == 0 && xeroInvoice.payments.size() == 0) { // There are no payments in SF or Xero... just update the invoice

			try {
				update invoice;
			}
			catch (Exception e) {
				throw new UpdateFromXeroException('Failed to update invoice with reason: ' + e.getMessage());
			}
		}
		else { // There are payments, so sync the payments as well

			// Fetch the payments related to the invoice
			sfXero.XeroPaymentResponse paymentsResponse = sfXero.XeroAPI.getPaymentsAll(
				xeroCreds,
				null,
				'Invoice.InvoiceID = Guid("' + xeroInvoice.invoiceID + '")',
				null
			);

			// Pull the payments into their own list
			List<sfXero.XeroPayment> xeroPayments = paymentsResponse.payments;
			system.debug(xeroPayments);

			// Lists of records to perform DML on
			List<Xero_Payment__c> paymentsToDelete = new List<Xero_Payment__c>();
			List<Xero_Payment__c> paymentsToUpsert = new List<Xero_Payment__c>();
			Set<String> xeroPaymentIds = new Set<String>();

			// Build a map of account ids to account names for assigning to payment records
			sfXero.XeroAccountResponse accountsResponse = sfXero.XeroAPI.getAccountsAll(xeroCreds,null,null,null);
			Map<String,sfXero.XeroAccount> accountsById = new Map<String,sfXero.XeroAccount>();
			for (sfXero.XeroAccount acc : accountsResponse.accounts) {
				accountsById.put(acc.accountID, acc);
			}

			// Add each payment from xero to the paymentsToUpsert list
			for (sfXero.XeroPayment xp : xeroPayments) {

				system.debug(xp);

				// Store the xero id in the xeroPaymentIds map to detect deleted payments later
				xeroPaymentIds.add(xp.paymentId);

				// Make a new payment record from the XeroPayment
				Xero_Payment__c payment = new Xero_Payment__c();
				payment.Invoice_Statement__c = invoice.Id;
				payment.Xero_Id__c = xp.paymentId;
				payment.Payment_Amount__c = xp.amount;
				payment.Payment_Date__c = xp.paymentDate;
				payment.Account_Id__c = xp.acc.accountId;
				payment.Reference__c = xp.reference;
				payment.Currency_Rate__c = xp.currencyrate;
				payment.Status__c = xp.status;
				if (xp.acc.accountId != null && accountsById.containsKey(xp.acc.accountId)) {
					payment.Xero_Account_Name__c = accountsById.get(xp.acc.accountId).name;
					payment.Payment_Currency__c = accountsById.get(xp.acc.accountId).currencyCode;
				}
				paymentsToUpsert.add(payment);
			}

			// Add any payments that don't exist in Xero to the paymentsToDelete list
			for (Xero_Payment__c sp : invoice.Payments__r) {
				if (!xeroPaymentIds.contains(sp.Xero_Id__c)) {
					paymentsToDelete.add(sp);
				}
			}

			try{
				// Perform DML
				update invoice;
				delete paymentsToDelete; // Delete records that don't exist in Xero
				upsert paymentsToUpsert Xero_Id__c; // Merge records on the Xero_Id__c
			}
			catch (Exception e) {
				throw new UpdateFromXeroException('Failed to sync xero payments for "' + invoice.Id + '" with reason: ' + e.getMessage());
			}
		}
	}

	/**
	 * Attempts to query an invoice for a given an invoice Id, along with all required fields.
	 * 
	 * @param invoiceRecordId
	 * @return the queried Invoice_Statement__c record, null if error or not found
	 */
	private static Invoice_Statement__c queryInvoice(Id invoiceRecordId) {

		List<Invoice_Statement__c> invoices = null;

		try {
			invoices = [
				SELECT School__c, Xero_Id__c, Xero_Invoice_Number__c,
				(
					SELECT Xero_Id__c, Payment_Amount__c, Payment_Date__c 
					FROM Payments__r 
				)
				FROM Invoice_Statement__c
				WHERE Id = :invoiceRecordId
			];
		}
		catch(DMLException e) {
			throw new UpdateFromXeroException('Failed to query Invoice_Statement__c record for "' + invoiceRecordId + '" with reason: ' + e.getMessage());
		}

		if (invoices == null || invoices.size() != 1) { // Invoice not found
			throw new UpdateFromXeroException('Invoice not found for record id ' + invoiceRecordId);
		}

		return invoices[0];
	}

	/**
	 * Attempts to query a Xero Key record for a given school name.
	 * 
	 * @param school The name of a school for which we need to find a xero key
	 * @return the matching xero key for the school, null if error or not found
	 */
	private static Xero_Key__c queryXeroKey(String school) {

		List<Xero_Key__c> xeroKeys = null;

		// The school Pamplona uses the same xero org as Navarra
		if (school == 'Pamplona') {
			school =  'Navarra';
		}

		// Get the Xero key for the given school
		try {
			xeroKeys = [
				SELECT Id, Name, Private_Key__c, Consumer_Key__c, Consumer_Secret__c, 
					AccCode_Tuition__c, AccCode_Lunch__c, AccCode_Bus__c, AccCode_Other__c, 
					AccCode_Enrolment__c, AccCode_Application__c, AccCode_EAL__c 
				FROM Xero_Key__c 
				WHERE Name =: school
			];
		}
		catch(Exception e) {
			throw new UpdateFromXeroException('Failed to query Xero_Key__c records for "' + school + '" with reason: ' + e.getMessage());
		}	

		if(xeroKeys == null || xeroKeys.size() == 0) { // Xero key not found
			throw new UpdateFromXeroException('Xero Credentials not found for ' + school);
		}

		return xeroKeys[0];
	}

	/**
	 * Converts a Xero Key record to a XeroCredentials object.
	 * 
	 * @param xeroKey A Xero_Key__c record for a Xero instance
	 * @return A XeroCredentials object created from the passed in xero key details, null if error or not found
	 */
	private static sfXero.XeroCredentials xeroKeyToCredentials(Xero_Key__c xeroKey) {

		String consumerSecret = (xeroKey.Consumer_Secret__c == null) ? '' : xeroKey.Consumer_Secret__c;
		sfXero.XeroCredentials xeroCreds = new sfXero.XeroCredentials(xeroKey.Consumer_Key__c, consumerSecret, xeroKey.Private_Key__c);
		return xeroCreds;
	}
}