force-app/main/default/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Account_Relationship_Formula__c</fullName>
        <formula>TEXT(Related_Contact_Record_P2__r.Contact_Relationship__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Relationship (P2)</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Additional_Comments__c</fullName>
        <description>Shows comments submitted via the online application</description>
        <label>Additional Comments</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Address__c</fullName>
        <label>Address</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Contact_Note__c</fullName>
        <label>General Contact Note</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Family_Status__c</fullName>
        <formula>IF( 
   Enrolled__c = &quot;Yes&quot;, 
   IF( 
      Starting_Date__c &lt;= TODAY(), 
      &quot;In School&quot;, 
      &quot;Future Enrolment&quot;
      ), 
   IF( 
      Enrolled__c = &quot;Waiting List&quot;, 
      &quot;Waiting List&quot;,
      IF( 
         AND(
             Leaving_Date__c &lt;= TODAY(), 
             Percentage_Enrolled__c = 0
             ),
             &quot;Left&quot;, 
          IF(
             Percentage_Enrolled__c = 0, 
             &quot;Rejected/Terminated&quot;,
             &quot;Applying&quot;
             )
         )
      )
   )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Family Status (Account)</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Gender__c</fullName>
        <label>Gender</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Male</fullName>
                </value>
                <value>
                    <fullName>Female</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Main_Address__c</fullName>
        <description>The main address field for a company record only. Temporarily also holds the old address information for &apos;Parent&apos; records, although this is being phased out and should only be edited by system admin on those records during the transition, therefore is only shown on the system admin page layout for parents.</description>
        <label>Main Address</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Nationality__c</fullName>
        <label>Nationality (Staff)</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Afghanistan</fullName>
                </value>
                <value>
                    <fullName>Albania</fullName>
                </value>
                <value>
                    <fullName>Algeria</fullName>
                </value>
                <value>
                    <fullName>American Samoa</fullName>
                </value>
                <value>
                    <fullName>Andorra</fullName>
                </value>
                <value>
                    <fullName>Angola</fullName>
                </value>
                <value>
                    <fullName>Anguilla</fullName>
                </value>
                <value>
                    <fullName>Antarctica</fullName>
                </value>
                <value>
                    <fullName>Antigua And Barbuda</fullName>
                </value>
                <value>
                    <fullName>Argentina</fullName>
                </value>
                <value>
                    <fullName>Armenia</fullName>
                </value>
                <value>
                    <fullName>Aruba</fullName>
                </value>
                <value>
                    <fullName>Australia</fullName>
                </value>
                <value>
                    <fullName>Austria</fullName>
                </value>
                <value>
                    <fullName>Azerbaijan</fullName>
                </value>
                <value>
                    <fullName>Bahamas</fullName>
                </value>
                <value>
                    <fullName>Bahrain</fullName>
                </value>
                <value>
                    <fullName>Bangladesh</fullName>
                </value>
                <value>
                    <fullName>Barbados</fullName>
                </value>
                <value>
                    <fullName>Belarus</fullName>
                </value>
                <value>
                    <fullName>Belgium</fullName>
                </value>
                <value>
                    <fullName>Belize</fullName>
                </value>
                <value>
                    <fullName>Benin</fullName>
                </value>
                <value>
                    <fullName>Bermuda</fullName>
                </value>
                <value>
                    <fullName>Bhutan</fullName>
                </value>
                <value>
                    <fullName>Bolivia</fullName>
                </value>
                <value>
                    <fullName>Bosnia And Herzegovina</fullName>
                </value>
                <value>
                    <fullName>Botswana</fullName>
                </value>
                <value>
                    <fullName>Brazil</fullName>
                </value>
                <value>
                    <fullName>British Indian Ocean Territory</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Other_Responsabilities__c</fullName>
        <label>Other Responsibilities</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Personal_Statement__c</fullName>
        <label>Personal Statement</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Primary_Contact__c</fullName>
        <description>Identifies which of the parents should be contacted first</description>
        <inlineHelpText>Which parent should be the first point of contact?</inlineHelpText>
        <label>Primary Contact</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>First Parent</fullName>
                    <default>true</default>
                    <label>First Parent</label>
                </value>
                <value>
                    <fullName>Second Parent</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>RT_Developer_Name__c</fullName>
        <formula>RecordType.DeveloperName</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>RT Developer Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Related_Contact_Record_P2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Click this link to edit/view the related contact</inlineHelpText>
        <label>Related Contact Record</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>The second parent must be of type &apos;Additional Parent&apos; and must be a contact created under this parent account.</errorMessage>
            <filterItems>
                <field>Contact.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Additional_Parent</value>
            </filterItems>
            <filterItems>
                <field>Contact.Main_Parent_File__r.Id</field>
                <operation>equals</operation>
                <valueField>$Source.Id</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Family Account</relationshipLabel>
        <relationshipName>FamilyAccount</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <formula>IF( 
   Count_Active_Contracts__c &gt; 0, 
   &quot;Employed&quot;,
   IF(
      Count_Signed_Not_started_Contracts__c &gt; 0,
      &quot;Signed-On&quot;,
      IF(
         Count_Expired_Contracts__c &gt; 0,
         &quot;Left&quot;, 
         IF( 
            Unsuccessful_Applicant__c = TRUE, 
            &quot;Unsuccessful Applicant&quot;, 
            &quot;Applicant&quot;
            )
         )
      )
   )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Status</label>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Contact_Employer__c</fullName>
        <label>Employer</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact_Employment_Sector__c</fullName>
        <label>Occupation</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact_Mobile_Main_Phone_Country_CodePL__c</fullName>
        <label>Mobile/Main Phone Country Code</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Phone_Country_Codes</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Contact_Nationality__c</fullName>
        <label>Nationality</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Nationalities</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Family_Status__c</fullName>
        <formula>Main_Parent_File__r.Family_Status__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Family Status (Contact)</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Gender__c</fullName>
        <description>This field is configured in NPSP Settings &gt; Relationships &gt; Relationships as the Gender field. Do not delete this field unless you remove the reference or select another Gender field there.</description>
        <label>Gender</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Male</fullName>
                </value>
                <value>
                    <fullName>Female</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Main_Parent_File__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Family File</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Value does not exist or is not a parent record.</errorMessage>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Parent</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Additional Parents &amp; Student Academic Files</relationshipLabel>
        <relationshipName>Emails</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Nationality__c</fullName>
        <formula>TEXT(Admissions_File__r.Nationality__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Nationality</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Portal_Contact_Page_Accessed__c</fullName>
        <label>My Contact Details Accessed</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Primary_Parent__c</fullName>
        <formula>IF(TEXT(Main_Parent_File__r.Primary_Contact__c)=&quot;&quot;, &quot;Not Defined&quot;, Main_Parent_File__r.Primary_Contact_Name__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Primary Parent Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RT_Developer_Name__c</fullName>
        <formula>RecordType.DeveloperName</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>RT Developer Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Employed</fullName>
                </value>
                <value>
                    <fullName>Applicant</fullName>
                </value>
                <value>
                    <fullName>Left</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Contact</fullName>
        <active>true</active>
        <label>Contact</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/User.object
<CustomObject>
    <fields>
        <fullName>Family_File_Id__c</fullName>
        <formula>IF( Contact.RecordType.DeveloperName == &quot;Additional_Parent&quot;, CASESAFEID(Contact.Main_Parent_File__c) , CASESAFEID(Contact.AccountId))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Family File Id</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Primary_Parent__c</fullName>
        <formula>IF((Contact.Account.Year1__c + Contact.Account.Year2__c +Contact.Account.Year3__c+Contact.Account.Year4__c+Contact.Account.Year5__c+Contact.Account.Year6__c+ Contact.Account.Reception1__c + Contact.Account.Nursery1__c +Contact.Account.PreNursery__c)&gt;0,&quot;Yes&quot;,&quot;No&quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Primary Parent</label>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/globalValueSets/Nationalities.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Afghani</fullName>
    </customValue>
    <customValue>
        <fullName>Alandic</fullName>
    </customValue>
    <customValue>
        <fullName>Albanian</fullName>
    </customValue>
    <customValue>
        <fullName>Algerian</fullName>
    </customValue>
    <customValue>
        <fullName>American</fullName>
    </customValue>
    <customValue>
        <fullName>Andorran</fullName>
    </customValue>
    <customValue>
        <fullName>Angolan</fullName>
    </customValue>
    <customValue>
        <fullName>Anguillan</fullName>
    </customValue>
    <customValue>
        <fullName>Antarctic</fullName>
    </customValue>
    <customValue>
        <fullName>Antiguan</fullName>
    </customValue>
    <customValue>
        <fullName>Argentine</fullName>
    </customValue>
    <customValue>
        <fullName>Armenian</fullName>
    </customValue>
    <customValue>
        <fullName>Arubian</fullName>
    </customValue>
    <customValue>
        <fullName>Australian</fullName>
    </customValue>
    <customValue>
        <fullName>Austrian</fullName>
    </customValue>
    <customValue>
        <fullName>Azerbaijani</fullName>
    </customValue>
    <customValue>
        <fullName>Bahameese</fullName>
    </customValue>
    <customValue>
        <fullName>Bahrainian</fullName>
    </customValue>
    <customValue>
        <fullName>Bangladeshi</fullName>
    </customValue>
    <customValue>
        <fullName>Barbadian</fullName>
    </customValue>
    <customValue>
        <fullName>Barthelemois</fullName>
    </customValue>
    <customValue>
        <fullName>Belarusian</fullName>
    </customValue>
    <customValue>
        <fullName>Belgian</fullName>
    </customValue>
    <customValue>
        <fullName>Belizean</fullName>
    </customValue>
    <customValue>
        <fullName>Beninese</fullName>
    </customValue>
    <customValue>
        <fullName>Bermudan</fullName>
    </customValue>
    <customValue>
        <fullName>Bhutanese</fullName>
    </customValue>
    <customValue>
        <fullName>Bolivian</fullName>
    </customValue>
    <customValue>
        <fullName>Bosnian</fullName>
    </customValue>
    <customValue>
        <fullName>Bouvet Island</fullName>
    </customValue>
    <description>Note that this global value set isn&apos;t used in all nationality picklist fields as yet, though it is used in the core of them.</description>
    <masterLabel>Nationalities</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

force-app/main/default/globalValueSets/Phone_Country_Codes.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Afghanistan (+93)</fullName>
    </customValue>
    <customValue>
        <fullName>Albania (+355)</fullName>
    </customValue>
    <customValue>
        <fullName>Algeria (+213)</fullName>
    </customValue>
    <customValue>
        <fullName>American Samoa (+1-684)</fullName>
    </customValue>
    <customValue>
        <fullName>Andorra (+376)</fullName>
    </customValue>
    <customValue>
        <fullName>Angola (+244)</fullName>
    </customValue>
    <customValue>
        <fullName>Anguilla (+1-264)</fullName>
    </customValue>
    <customValue>
        <fullName>Antarctica (+672)</fullName>
    </customValue>
    <customValue>
        <fullName>Antigua and Barbuda (+1-268)</fullName>
    </customValue>
    <customValue>
        <fullName>Argentina (+54)</fullName>
    </customValue>
    <customValue>
        <fullName>Armenia (+374)</fullName>
    </customValue>
    <customValue>
        <fullName>Aruba (+297)</fullName>
    </customValue>
    <customValue>
        <fullName>Australia (+61)</fullName>
    </customValue>
    <customValue>
        <fullName>Austria (+43)</fullName>
    </customValue>
    <customValue>
        <fullName>Azerbaijan (+994)</fullName>
    </customValue>
    <customValue>
        <fullName>Bahamas (+1-242)</fullName>
    </customValue>
    <customValue>
        <fullName>Bahrain (+973)</fullName>
    </customValue>
    <customValue>
        <fullName>Bangladesh (+880)</fullName>
    </customValue>
    <customValue>
        <fullName>Barbados (+1-246)</fullName>
    </customValue>
    <customValue>
        <fullName>Belarus (+375)</fullName>
    </customValue>
    <customValue>
        <fullName>Belgium (+32)</fullName>
    </customValue>
    <customValue>
        <fullName>Belize (+501)</fullName>
    </customValue>
    <customValue>
        <fullName>Benin (+229)</fullName>
    </customValue>
    <customValue>
        <fullName>Bermuda (+1-441)</fullName>
    </customValue>
    <customValue>
        <fullName>Bhutan (+975)</fullName>
    </customValue>
    <customValue>
        <fullName>Bolivia (+591)</fullName>
    </customValue>
    <customValue>
        <fullName>Bosnia and Herzegovina (+387)</fullName>
    </customValue>
    <customValue>
        <fullName>Botswana (+267)</fullName>
    </customValue>
    <customValue>
        <fullName>Brazil (+55)</fullName>
    </customValue>
    <customValue>
        <fullName>British Indian Ocean Territory (+246)</fullName>
    </customValue>
    <masterLabel>Phone Country Codes</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/PortalMyContactDetail_Controller.cls
//controller class to PortalMyContactDetail VF page
//created on 15 Aoril 2014
public class PortalMyContactDetail_Controller {      
    
    //variables
    private Id mainParentId {get;set;}
    private User portalUser {get;set;}
    public Account parentAccount {get;set;}
    public Contact parentContact {get;set;}
    public boolean isPersonAccountContact {get;set;}
    public list<SelectOption> firstPointOfContact {get;set;}
    public Id selectedFirstPointOfContact {get;set;}
    public boolean doNotReceiveEmail {get;set;}
    public string currentEmail {get;set;}
    //constructor
    public PortalMyContactDetail_Controller(){
        //check for test parameters
        string portalUserParam =  System.currentPageReference().getParameters().get('uid');
        Id portalUserId;
        if(portalUserParam != null){
            portalUserId = portalUserParam;
        }else{
            portalUserId = UserInfo.getUserId();
        }
        //check for success
        string isSuccess = System.currentPageReference().getParameters().get('s');
        if(isSuccess ==  '1'){
            ApexPages.Message successMessage = new ApexPages.Message(ApexPages.severity.CONFIRM, 'Changes Saved. Thanks for updating your contact details.');
            ApexPages.addMessage(successMessage);
        }
        
        //check for portal account id and contact id
        portalUser =  [Select u.UserPreferencesDisableAllFeedsEmail, u.Name, u.Family_File_Id__c ,u.ContactId, u.AccountId From User u where Id=:portalUserId];
        doNotReceiveEmail = portalUser.UserPreferencesDisableAllFeedsEmail;
        initialize();
    }
    
    //create click event
    public PageReference createClickEvent(){
        Contact con = new Contact(Id=portalUser.ContactId);
        con.Portal_Contact_Page_Accessed__c = DateTime.now();
        update con;
        return null;
    }

    //intialize
    private void initialize(){
        if(portalUser.Family_File_Id__c != null && portalUser.Family_File_Id__c != ''){
            Id familyFileId = portalUser.Family_File_Id__c;
            if(familyFileId != portalUser.AccountId){
                parentAccount = [Select  a.Contact_Note__c, a.Related_Contact_Record_P2__c, a.Main_Address__c, a.Contact_Employer__pc, a.Contact_Employment_Sector__pc, a.PersonMobilePhone, a.IsPersonAccount, a.Nationality__pc, a.Contact_Mobile_Main_Phone_Country_CodePL__pc, a.Salutation, a.RT_Developer_Name__pc, a.Primary_Contact__c, a.Personal_Statement__c, a.PersonHomePhone, a.PersonHasOptedOutOfEmail, a.PersonEmail, a.Other_Responsabilities__c, a.Main_Parent_File__pc, a.LastName, a.Gender__c, a.FirstName, a.Contact_Relationship__pc, a.Contact_Nationality__pc, a.Contact_Alternate_Phone__pc, a.Contact_Alternate_Phone_Country_CodePL__pc, a.Contact_Alternate_Email__pc, a.Contact_Alternate_Email_Opt_Out__pc, a.Address__c, a.Additional_Parent__pc, a.Additional_Comments__c, a.Account_Relationship_Formula__c From Account a where a.Id=:portalUser.Family_File_Id__c];
                //parentAccount = [Select  a.Contact_Note__c, a.Related_Contact_Record_P2__c, a.Main_Address__c, a.Contact_Employer__pc,  a.PersonMobilePhone, a.IsPersonAccount, a.Nationality__pc, a.xsms__Mobile_Phone_Country_Code__pc, a.Salutation, a.RT_Developer_Name__pc, a.Primary_Contact__c, a.Personal_Statement__c, a.PersonHomePhone, a.PersonHasOptedOutOfEmail, a.PersonEmail, a.Other_Responsabilities__c, a.Main_Parent_File__pc, a.Main_Address__pc, a.LastName, a.Gender__c, a.FirstName, a.Contact_Relationship__pc, a.Contact_Nationality__pc, a.Contact_Alternate_Phone__pc, a.Contact_Alternate_Phone_Country_Code__pc, a.Contact_Alternate_Email__pc, a.Contact_Alternate_Email_Opt_Out__pc, a.Address__c, a.Additional_Parent__pc, a.Additional_Comments__c, a.Account_Relationship_Formula__c From Account a where a.Id=:portalUser.Family_File_Id__c];
                mainParentId = parentAccount.Id;
                isPersonAccountContact = false; 
                parentContact = [Select  Contact_Nationality__c, Contact_Employer__c, Contact_Employment_Sector__c, c.Nationality__c, c.Contact_Mobile_Main_Phone_Country_CodePL__c, c.Title, c.Status__c, c.Salutation, c.RT_Developer_Name__c, c.Primary_Parent__c, c.Phone, c.MobilePhone, c.Main_Parent_File__c, c.LastName, c.IsPersonAccount, c.Id, c.HasOptedOutOfEmail, c.FirstName, c.Family_Status__c, c.Email, c.Contact_Relationship__c, c.Contact_Alternate_Phone__c, c.Contact_Alternate_Phone_Country_CodePL__c, c.Contact_Alternate_Email__c, c.Contact_Alternate_Email_Opt_Out__c, c.Admissions_File__c, c.AccountId From Contact c where c.Id=:portalUser.ContactId];
                //parentContact = [Select  Contact_Nationality__c, Contact_Employer__c,  c.Nationality__c, c.xsms__Mobile_Phone_Country_Code__c, c.Title, c.Status__c, c.Salutation, c.RT_Developer_Name__c, c.Primary_Parent__c, c.Phone, c.MobilePhone, c.Main_Parent_File__c, c.LastName, c.IsPersonAccount, c.Id, c.HasOptedOutOfEmail, c.FirstName, c.Family_Status__c, c.Email, c.Contact_Relationship__c, c.Contact_Alternate_Phone__c, c.Contact_Alternate_Phone_Country_Code__c, c.Contact_Alternate_Email__c, c.Contact_Alternate_Email_Opt_Out__c, c.Admissions_File__c, c.AccountId From Contact c where c.Id=:portalUser.ContactId];
                currentEmail = parentContact.Email;
            }else{
                parentAccount = [Select  a.Contact_Note__c, a.Related_Contact_Record_P2__c, a.Main_Address__c, a.Contact_Employer__pc, a.Contact_Employment_Sector__pc, a.PersonMobilePhone, a.IsPersonAccount, a.Nationality__pc, a.Contact_Mobile_Main_Phone_Country_CodePL__pc, a.Salutation, a.RT_Developer_Name__pc, a.Primary_Contact__c, a.Personal_Statement__c, a.PersonHomePhone, a.PersonHasOptedOutOfEmail, a.PersonEmail, a.Other_Responsabilities__c,  a.Main_Parent_File__pc, a.LastName, a.Gender__c, a.FirstName, a.Contact_Relationship__pc, a.Contact_Nationality__pc, a.Contact_Alternate_Phone__pc, a.Contact_Alternate_Phone_Country_CodePL__pc, a.Contact_Alternate_Email__pc, a.Contact_Alternate_Email_Opt_Out__pc, a.Address__c, a.Additional_Parent__pc, a.Additional_Comments__c, a.Account_Relationship_Formula__c From Account a where a.Id=:portalUser.AccountId];
                //parentAccount = [Select  a.Contact_Note__c, a.Related_Contact_Record_P2__c, a.Main_Address__c, a.Contact_Employer__pc,  a.PersonMobilePhone, a.IsPersonAccount, a.Nationality__pc, a.xsms__Mobile_Phone_Country_Code__pc, a.Salutation, a.RT_Developer_Name__pc, a.Primary_Contact__c, a.Personal_Statement__c, a.PersonHomePhone, a.PersonHasOptedOutOfEmail, a.PersonEmail, a.Other_Responsabilities__c,  a.Main_Parent_File__pc, a.Main_Address__pc, a.LastName, a.Gender__c, a.FirstName, a.Contact_Relationship__pc, a.Contact_Nationality__pc, a.Contact_Alternate_Phone__pc, a.Contact_Alternate_Phone_Country_Code__pc, a.Contact_Alternate_Email__pc, a.Contact_Alternate_Email_Opt_Out__pc, a.Address__c, a.Additional_Parent__pc, a.Additional_Comments__c, a.Account_Relationship_Formula__c From Account a where a.Id=:portalUser.AccountId];
                currentEmail = parentAccount.PersonEmail;
                isPersonAccountContact = true;
                mainParentId = parentAccount.Id;
            }
            
        }/*else{
            parentAccount = [Select  a.Contact_Note__c, a.Related_Contact_Record_P2__c, a.Main_Address__c, a.Contact_Employer__pc, a.Contact_Employment_Sector__pc, a.PersonMobilePhone, a.IsPersonAccount, a.Nationality__pc, a.xsms__Mobile_Phone_Country_Code__pc, a.Salutation, a.RT_Developer_Name__pc, a.Primary_Contact__c, a.Personal_Statement__c, a.PersonHomePhone, a.PersonHasOptedOutOfEmail, a.PersonEmail, a.Other_Responsabilities__c,  a.Main_Parent_File__pc, a.LastName, a.Gender__c, a.FirstName, a.Contact_Relationship__pc, a.Contact_Nationality__pc, a.Contact_Alternate_Phone__pc, a.Contact_Alternate_Phone_Country_Code__pc, a.Contact_Alternate_Email__pc, a.Contact_Alternate_Email_Opt_Out__pc, a.Address__c, a.Additional_Parent__pc, a.Additional_Comments__c, a.Account_Relationship_Formula__c From Account a where a.Id=:portalUser.AccountId];
            currentEmail = parentAccount.PersonEmail;
            isPersonAccountContact = true;
            mainParentId = parentAccount.Id;
        }*/
        // identify first point of contact
        firstPointOfContact = new list<SelectOption>();
        Account tempParentAccount = [select Name, Salutation, FirstName, LastName, Related_Contact_Record_P2__c, Related_Contact_Record_P2__r.Name ,Related_Contact_Record_P2__r.Salutation , Related_Contact_Record_P2__r.FirstName, Related_Contact_Record_P2__r.LastName from Account where Id=:mainParentId];
        string firstParentName ;
        string secondParentName ;
        if(tempParentAccount.Salutation != null){
            firstParentName = tempParentAccount.Salutation+' '+tempParentAccount.Name;
        }else{
            firstParentName = tempParentAccount.Name;
        }
        if(tempParentAccount.Related_Contact_Record_P2__c != null){
            if(tempParentAccount.Related_Contact_Record_P2__r.Salutation != null){
                secondParentName = tempParentAccount.Related_Contact_Record_P2__r.Salutation+' '+tempParentAccount.Related_Contact_Record_P2__r.Name;
            }else{
                secondParentName = tempParentAccount.Related_Contact_Record_P2__r.Name;
            }
        }       
        firstPointOfContact.add(new SelectOption('First Parent', firstParentName));
        if(tempParentAccount.Related_Contact_Record_P2__c != null){
            firstPointOfContact.add(new SelectOption('Second Parent', secondParentName));
        }
        /*if(parentAccount.Primary_Contact__c == 'First Parent'){
            selectedFirstPointOfContact = tempParentAccount.Id;
        }else if(parentAccount.Primary_Contact__c == 'Second Parent'){
            selectedFirstPointOfContact = tempParentAccount.Additional_Parent__pc;
        }*/
    }
    
    public PageReference saveDetails(){
        try{
            if(parentAccount.PersonHasOptedOutOfEmail == true){
                parentAccount.Contact_Alternate_Email_Opt_Out__pc = true;
            }else{
                parentAccount.Contact_Alternate_Email_Opt_Out__pc = false;
            }
            //update account
            
            //update parentAccount;
            
            //list<Database.Saveresult> svResultList = DataBase.update(accList, false);
            Database.Saveresult svResult = DataBase.update(parentAccount, false);
            if(!svResult.isSuccess()){
                ApexPages.Message errorMessage = new ApexPages.Message(ApexPages.severity.FATAL, svResult.getErrors()[0].getMessage());
                ApexPages.addMessage(errorMessage);
                return null;
            }
            //update contact
            if(parentContact != null){
                if(parentContact.HasOptedOutOfEmail == true){
                    parentContact.Contact_Alternate_Email_Opt_Out__c = true;
                }else{
                    parentContact.Contact_Alternate_Email_Opt_Out__c = false;
                }
                //update parentContact;
                Database.Saveresult svResultCon = DataBase.update(parentContact, false);
                if(!svResultCon.isSuccess()){
                    ApexPages.Message errorMessage = new ApexPages.Message(ApexPages.severity.FATAL, svResultCon.getErrors()[0].getMessage());
                    ApexPages.addMessage(errorMessage);
                    return null;
                }
            }
            //update user
            //if(portalUser.UserPreferencesDisableAllFeedsEmail != doNotReceiveEmail){
                portalUser.UserPreferencesDisableAllFeedsEmail = doNotReceiveEmail;
                //update portalUser;
                Database.Saveresult svResultUser = DataBase.update(portalUser, false);
                if(!svResultUser.isSuccess()){
                    ApexPages.Message errorMessage = new ApexPages.Message(ApexPages.severity.FATAL, svResultUser.getErrors()[0].getMessage());
                    ApexPages.addMessage(errorMessage);
                    return null;
                }
            //}
            
            PageReference pg =  new PageReference('/parents/PortalMyContactDetail');
            pg.setRedirect(true);
            pg.getParameters().put('s','1');
            return pg;
            
        }catch(Exception e){
            ApexPages.Message errorMessage = new ApexPages.Message(ApexPages.severity.FATAL, 'Ooops something went wrong. Error Message: '+e.getMessage());
            ApexPages.addMessage(errorMessage);
        }
        return null;
    }

}