force-app/main/default/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Primary_Contact__c</fullName>
        <description>Identifies which of the parents should be contacted first</description>
        <inlineHelpText>Which parent should be the first point of contact?</inlineHelpText>
        <label>Primary Contact</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>First Parent</fullName>
                    <default>true</default>
                    <label>First Parent</label>
                </value>
                <value>
                    <fullName>Second Parent</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>School__c</fullName>
        <description>Copies the value of SchoolText (which is a workflow copying from School Formula). A little long winded solution to avoid bigger changes in the Teacher/Parent portal.</description>
        <formula>SchoolText__pc</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>School</label>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Company_Account</fullName>
        <active>true</active>
        <label>Company</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Account_Owner_Mapping__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This setting is used to determine appropriate &quot;Mass Email&quot; or &quot;Catch All&quot; account for a given Account/Opportunity Owner. Name field contains &quot;Owner Name&quot; and Account Id field contains Id of associated account.. This setting is used in Opportunity trigger.</description>
    <fields>
        <fullName>Account_Id__c</fullName>
        <inlineHelpText>Id of the corresponding &quot;Mass Email &quot; OR &quot;Catch All&quot; Account.</inlineHelpText>
        <label>Account Id</label>
        <length>20</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>School_Name__c</fullName>
        <label>School Name</label>
        <type>TextArea</type>
    </fields>
    <label>Account Owner Mapping</label>
</CustomObject>

force-app/main/default/objects/Group__c.object
<CustomObject>
    <fields>
        <fullName>Chatter_Group_Id__c</fullName>
        <inlineHelpText>System Field : Corresponding Chatter Group Id for this Student Group.</inlineHelpText>
        <label>Chatter Group Id</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Group_Type__c</fullName>
        <label>Group Type</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Year_Group_Control__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Tutor Group</fullName>
                </value>
                <value>
                    <fullName>Subject</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>School Group</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>School__c</fullName>
        <formula>TEXT(Owner:User.School__c)</formula>
        <label>School</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Year_Group_Control__c</fullName>
        <description>Set by means of a workflow rule to control the year group options available based on the school being a US school such as NYIS and also the group type i.e. a tutor group</description>
        <label>Year Group Control</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Tutor Group UK</fullName>
                </value>
                <value>
                    <fullName>Tutor Group US</fullName>
                </value>
                <value>
                    <fullName>Non-Tutor Group</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Year_Group__c</fullName>
        <inlineHelpText>The lowest Year Group / Grade of any student within the group.</inlineHelpText>
        <label>Year Group (Lowest)</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Year_Group_Control__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Pre-Nursery</fullName>
                </value>
                <value>
                    <fullName>Nursery</fullName>
                </value>
                <value>
                    <fullName>Reception</fullName>
                </value>
                <value>
                    <fullName>Year 1</fullName>
                </value>
                <value>
                    <fullName>Year 2</fullName>
                </value>
                <value>
                    <fullName>Year 3</fullName>
                </value>
                <value>
                    <fullName>Year 4</fullName>
                </value>
                <value>
                    <fullName>Year 5</fullName>
                </value>
                <value>
                    <fullName>Year 6</fullName>
                </value>
                <value>
                    <fullName>Year 7</fullName>
                </value>
                <value>
                    <fullName>Year 8</fullName>
                </value>
                <value>
                    <fullName>Year 9</fullName>
                </value>
                <value>
                    <fullName>Year 10</fullName>
                </value>
                <value>
                    <fullName>Year 11</fullName>
                </value>
                <value>
                    <fullName>Year 12</fullName>
                </value>
                <value>
                    <fullName>Year 13</fullName>
                </value>
                <value>
                    <fullName>Pre-Kindergarten</fullName>
                </value>
                <value>
                    <fullName>Kindergarten</fullName>
                </value>
                <value>
                    <fullName>Grade 1</fullName>
                </value>
                <value>
                    <fullName>Grade 2</fullName>
                </value>
                <value>
                    <fullName>Grade 3</fullName>
                </value>
                <value>
                    <fullName>Grade 4</fullName>
                </value>
                <value>
                    <fullName>Grade 5</fullName>
                </value>
                <value>
                    <fullName>Grade 6</fullName>
                </value>
                <value>
                    <fullName>Grade 7</fullName>
                </value>
                <value>
                    <fullName>Grade 8</fullName>
                </value>
                <value>
                    <fullName>Grade 9</fullName>
                </value>
                <value>
                    <fullName>Grade 10</fullName>
                </value>
                <value>
                    <fullName>Grade 11</fullName>
                </value>
                <value>
                    <fullName>Grade 12</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Student Group</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Student Groups</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/News_Events__c.object
<CustomObject>
    <fields>
        <fullName>Event_Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Post_Entry_in_Related_Blog__c</fullName>
        <inlineHelpText>Use this option to create a post in the community chatter group to invite parents to comment/ask questions about the event. NB. Will only work if &apos;Related Class Blog Available?&apos; = TRUE</inlineHelpText>
        <label>Post Entry in Related Blog?</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>No</fullName>
                    <default>true</default>
                    <label>No</label>
                </value>
                <value>
                    <fullName>Yes - Standard Post</fullName>
                </value>
                <value>
                    <fullName>Yes - And tag as Essential Communication</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Publish_in_Portal_School_Hub__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Publish in Portal Calendar</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>School__c</fullName>
        <formula>IF(
   AND(
       TEXT(Share_with_Admin_Dept_of__c) != &quot;&quot;, 
       TEXT(Share_with_Admin_Dept_of__c) != &quot;Do Not Share&quot;
       ),
   TEXT(Share_with_Admin_Dept_of__c), 
   TEXT(Owner:User.School__c)
   )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>School</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Student_Group__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Student Group</label>
        <referenceTo>Group__c</referenceTo>
        <relationshipLabel>Calendar</relationshipLabel>
        <relationshipName>News_Events</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Subtitle__c</fullName>
        <inlineHelpText>- For portal dates, please include any essential info (inc. time) in this field. This text will be visible under the title by default. (i.e. unlike the &apos;main text&apos; field, no extra clicks are required to view).
- For News, please add a short teaser</inlineHelpText>
        <label>Essential Info (inc time, if any)/Teaser</label>
        <type>TextArea</type>
    </fields>
    <label>News &amp; Events</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>News &amp; Events</pluralLabel>
    <recordTypes>
        <fullName>Event</fullName>
        <active>true</active>
        <label>Event</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/PersonAccount.object
<CustomObject>
    <recordTypes>
        <fullName>PersonAccount</fullName>
        <active>true</active>
        <label>Parent</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/School__c.object
<CustomObject>
    <fields>
        <fullName>School_Full_Name__c</fullName>
        <label>School Full Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>School</label>
    <nameField>
        <label>School Code/UID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Schools</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/School_Logo_Mapping__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>setting to store mapping of school name and school logo image URL</description>
    <fields>
        <fullName>Auto_Portal_User_Creation__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Auto Portal User Creation</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Automated_Calendar_Emails_On__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Automated Calendar Emails On</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Community_Id__c</fullName>
        <inlineHelpText>Id of the school&apos;s parent community Id.</inlineHelpText>
        <label>Community Id</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Logo_URL__c</fullName>
        <inlineHelpText>static resource URL for logo image</inlineHelpText>
        <label>Logo URL</label>
        <length>200</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>School_Full_Name__c</fullName>
        <label>School Full Name</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <label>School Mapping</label>
</CustomObject>

force-app/main/default/objects/User.object
<CustomObject>
    <fields>
        <fullName>School__c</fullName>
        <label>School</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>The British Schools Foundation</fullName>
                </value>
                <value>
                    <fullName>The British School of Guangzhou</fullName>
                </value>
                <value>
                    <fullName>The British School of Nanjing</fullName>
                </value>
                <value>
                    <fullName>The British International School of Marbella</fullName>
                </value>
                <value>
                    <fullName>The British School of Navarra</fullName>
                </value>
                <value>
                    <fullName>The British School of Tashkent</fullName>
                </value>
                <value>
                    <fullName>The British College of Brazil</fullName>
                </value>
                <value>
                    <fullName>The British International School of Kuala Lumpur</fullName>
                </value>
                <value>
                    <fullName>The International School of Moscow</fullName>
                </value>
                <value>
                    <fullName>Nord Anglia International School Manila</fullName>
                </value>
                <value>
                    <fullName>King&apos;s College Beijing</fullName>
                </value>
                <value>
                    <fullName>The British School Yangon</fullName>
                </value>
                <value>
                    <fullName>Ukraine International School</fullName>
                </value>
                <value>
                    <fullName>The New York International School</fullName>
                </value>
                <value>
                    <fullName>The British School of Brasilia</fullName>
                </value>
                <value>
                    <fullName>NAE</fullName>
                </value>
                <value>
                    <fullName>The British International School Yangon</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/classes/Test_NewsEvents.cls
@IsTest(SeeAllData=true)
private class Test_NewsEvents{
    //test method for portal user creation and chatter group membership
    static testMethod void testBlogPostCreation(){
        
        //create company account account
        Account companyAccount =  new Account();
        companyAccount.Name =  'Company Account';
        companyAccount.RecordTypeId = [Select Id from RecordType where SObjectType='Account' AND DeveloperName='Company_Account'].Id;
        insert companyAccount;
        System.debug('***Test_NewsEvents***testBlogPostCreation***1=');
        //create parent account account
        Account parentAccount =  new Account();
        parentAccount.FirstName =  'First Name1';
        parentAccount.LastName =  'Last Name2';
        parentAccount.PersonEmail = 'testunique1@test.com';
        parentAccount.Contact_Alternate_Email__pc = 'testunique2@test.com';
        parentAccount.RecordTypeId = [Select Id from RecordType where SObjectType='Account' AND DeveloperName='PersonAccount'].Id;
        parentAccount.Primary_Contact__c = 'First Parent';
        insert parentAccount;
        System.debug('***Test_NewsEvents***testBlogPostCreation***2=');
        //create custom setting values
        Account_Owner_Mapping__c mapping =  new Account_Owner_Mapping__c();
        mapping.Account_Id__c = companyAccount.Id;
        mapping.Name =  UserInfo.getName();
        mapping.School_Name__c = [select School__c,Id from User where Id=:UserInfo.getUserId()].School__c;
        insert mapping;
        System.debug('***Test_NewsEvents***testBlogPostCreation***3=');
        Id networkId;
        for(Network n:[Select Id,Name from Network limit 1]){
            networkId = n.Id;
        }
      
        
        //create setting
        User u = [select School__c,Id from User where Id=:UserInfo.getUserId()];
        School_Logo_Mapping__c portal =  new School_Logo_Mapping__c();
        portal.Name = 'Test';
        portal.School_Full_Name__c = u.School__c;
        portal.Auto_Portal_User_Creation__c = true;
        portal.Logo_URL__c = 'test';
        portal.Auto_Portal_User_Creation__c = true;
        portal.Community_Id__c = networkId;
        portal.Automated_Calendar_Emails_On__c = true;
        insert portal;
        System.debug('***Test_NewsEvents***testBlogPostCreation***4=');
        
        System.debug('***Test_NewsEvents***testBlogPostCreation***5=');
        //create portal chatter group
        CollaborationGroup chatterGroup =  new CollaborationGroup();
        chatterGroup.Name = 'Test Group 99999';
        chatterGroup.NetworkId = networkId;
        chatterGroup.CollaborationType = 'Private'; 
        chatterGroup.OwnerId = UserInfo.getUserId();
        insert chatterGroup;
        System.debug('***Test_NewsEvents***testBlogPostCreation***6=');
        //create student group
        Group__c grp  =  new Group__c();
        grp.Name = 'Test Group';
        grp.Group_Type__c = 'Tutor Group';
        grp.Chatter_Group_Id__c = chatterGroup.Id;
        grp.Year_Group_Control__c = 'Tutor Group UK';
        grp.Year_Group__c = 'Year 1';
        insert grp;
        System.debug('***Test_NewsEvents***testBlogPostCreation***7=');
        Test.startTest();
            News_Events__c newsEvent = new News_Events__c();
            newsEvent.RecordTypeId = [select Id from RecordType where SObjectType='News_Events__c' AND DeveloperName='Event'].Id;
            newsEvent.Name = 'Test Event';
            newsEvent.Student_Group__c = grp.Id;
            newsEvent.Event_Start_Date__c = date.today();
            newsEvent.Publish_in_Portal_School_Hub__c = true;
            newsEvent.Post_Entry_in_Related_Blog__c = 'Yes - And tag as Essential Communication'; 
            newsEvent.Subtitle__c = 'Teaser Text';          
            insert newsEvent;
        Test.stopTest();
        
        
    }
}