force-app/main/default/objects/Account.object
<CustomObject>
    <fields>
        <fullName>PrimaryContactEmail__c</fullName>
        <formula>IF( AND(TEXT(Primary_Contact__c) =&quot;First Parent&quot;, Contact_Alternate_Email_Opt_Out__pc &lt;&gt; TRUE, Contact_Alternate_Email__pc &lt;&gt; &quot;&quot;, OR(PersonEmail = &quot;&quot;,  PersonHasOptedOutOfEmail = TRUE)), Contact_Alternate_Email__pc,

IF( AND(TEXT(Primary_Contact__c) =&quot;First Parent&quot;, PersonEmail &lt;&gt; &quot;&quot;, PersonHasOptedOutOfEmail &lt;&gt; TRUE), PersonEmail,

IF( AND(TEXT(Primary_Contact__c) =&quot;Second Parent&quot;,  Account_Alternate_Email_Opt_Out_Formula__c &lt;&gt; TRUE, Account_Alternate_Email_Formula__c &lt;&gt; &quot;&quot;, OR(Account_Main_Email_Formula__c = &quot;&quot;, Account_Email_Opt_Out_Formula__c = TRUE)), Account_Alternate_Email_Formula__c,

IF( AND(TEXT(Primary_Contact__c) =&quot;Second Parent&quot;, Account_Main_Email_Formula__c &lt;&gt; &quot;&quot;, Account_Email_Opt_Out_Formula__c &lt;&gt; TRUE), Account_Main_Email_Formula__c, 

&quot;Not Defined or Opted Out&quot;))))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Primary Contact Email</label>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Main_Parent_File__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Family File</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Value does not exist or is not a parent record.</errorMessage>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Parent</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Additional Parents &amp; Student Academic Files</relationshipLabel>
        <relationshipName>Emails</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Primary_Parent_Email__c</fullName>
        <formula>Main_Parent_File__r.PrimaryContactEmail__c</formula>
        <label>Primary Parent Email</label>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Contact</fullName>
        <active>true</active>
        <label>Contact</label>
    </recordTypes>
    <recordTypes>
        <fullName>Student</fullName>
        <active>true</active>
        <label>Student Academic File</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Group__c.object
<CustomObject>
    <label>Student Group</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Student Groups</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Registration__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>whether registration is active or not</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Group__c</fullName>
        <inlineHelpText>select group against which assessment is done.</inlineHelpText>
        <label>Group</label>
        <referenceTo>Group__c</referenceTo>
        <relationshipLabel>Registrations</relationshipLabel>
        <relationshipName>Assessments_Registrations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Primary_Parent_Email__c</fullName>
        <formula>Student__r.Primary_Parent_Email__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Primary Parent Email</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Student__c</fullName>
        <inlineHelpText>select student for this enrolment</inlineHelpText>
        <label>Student</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Registrations</relationshipLabel>
        <relationshipName>Registrations</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Registration</label>
    <nameField>
        <displayFormat>R-{000000}</displayFormat>
        <label>Registration #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Registrations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/SendEmailToGroupParents_Controller.cls
/**
    Author: Kunal Sharma
    Created Date: 07 Mar 2012
    Desc: VF controller used to send email to all active students parent's in a group.
**/
public with sharing class SendEmailToGroupParents_Controller {

    private Id groupId ;
    private Group__c grp;
    private String emailPageURLprefix ;
    public SendEmailToGroupParents_Controller(ApexPages.StandardController controller) {
        groupId = controller.getId();
        grp =  [Select Id,Name from Group__c where Id=:groupId];
        
        emailPageURLprefix = '/_ui/core/email/author/EmailAuthor';
        
    }
    
    public PageReference reDirectToEmailPage(){
        //fetch all active student registration against selected group
        String emailString ;
        Set<String> emailSet =  new Set<String>();
        Set<Id> parentIds =  new Set<Id>();
        for(Registration__c registration:[Select a.Student__r.Main_Parent_File__c, a.Student__r.Primary_Parent_Email__c ,a.Student__c, a.Id, a.Group__c, a.Active__c From Registration__c a where Active__c = true AND Group__c=:groupId order by Student__r.Name]){
            //if(registration.Student__r.Primary_Parent_Email__c != null && registration.Student__r.Primary_Parent_Email__c != ''){
                //emailSet.add(registration.Student__r.Primary_Parent_Email__c);
                parentIds.add(registration.Student__r.Main_Parent_File__c);
            //}
        }
        
        for(Account acc:[Select a.PrimaryContactEmail__c, a.PersonEmail, a.PersonHasOptedOutOfEmail ,(Select Email, HasOptedOutOfEmail From Emails__r where  HasOptedOutOfEmail = false AND RecordType.DeveloperName != 'Student') From Account a where a.Id IN:parentIds]){
            //if(acc.PrimaryContactEmail__c != null && acc.PrimaryContactEmail__c != ''){
                //emailSet.add(acc.PrimaryContactEmail__c);
            //}
            if(acc.PersonHasOptedOutOfEmail == false && acc.PersonEmail != null){
                emailSet.add(acc.PersonEmail);
            }
            //fetch from mass email records
            for(Contact c:acc.Emails__r){
                if(c.Email != null){
                    emailSet.add(c.Email);
                }
            } 
        }
        
        for(String email:emailSet){
            if(emailString == null){
                emailString = email;
            }else{
                emailString += ';'+email;
            }
        }
        //fetch email template 
        Id templateId ; 
        for(EmailTemplate e:[Select e.Name, e.Id, e.DeveloperName From EmailTemplate e where e.DeveloperName = 'Generic_Parent_Email_Template']){
            templateId = e.Id;
        }
        //fetch current user's email
        String userEmail = [Select Id, Email from User where Id=:UserInfo.getUserId()].Email;
        //create pageReference
        PageReference pg =  new PageReference(emailPageURLprefix);
        pg.getParameters().put('p24',userEmail);
        pg.getParameters().put('p5',emailString);
        pg.getParameters().put('p3_lkid',groupId);
        pg.getParameters().put('p3',grp.Name);
        if(templateId != null){
            pg.getParameters().put('template_id',templateId);
        }
        pg.getParameters().put('retURL','/'+groupId);
        return pg;
        
    }
     
}