force-app/main/default/objects/Account.object
<CustomObject>
    <fields>
        <fullName>School__c</fullName>
        <description>Copies the value of SchoolText (which is a workflow copying from School Formula). A little long winded solution to avoid bigger changes in the Teacher/Parent portal.</description>
        <formula>SchoolText__pc</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>School</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <formula>IF( 
   Count_Active_Contracts__c &gt; 0, 
   &quot;Employed&quot;,
   IF(
      Count_Signed_Not_started_Contracts__c &gt; 0,
      &quot;Signed-On&quot;,
      IF(
         Count_Expired_Contracts__c &gt; 0,
         &quot;Left&quot;, 
         IF( 
            Unsuccessful_Applicant__c = TRUE, 
            &quot;Unsuccessful Applicant&quot;, 
            &quot;Applicant&quot;
            )
         )
      )
   )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Status</label>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice_Statement__c.object
<CustomObject>
    <fields>
        <fullName>Account_Id__c</fullName>
        <formula>Payer__r.Id</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Account Id</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Currency__c</fullName>
        <label>Currency</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Payer__c</fullName>
        <label>Parent/Company</label>
        <lookupFilter>
            <active>false</active>
            <booleanFilter>1 OR 2</booleanFilter>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Company</value>
            </filterItems>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Parent</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Invoices</relationshipLabel>
        <relationshipName>Invoice_Statements1</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Reference__c</fullName>
        <label>Reference</label>
        <length>10000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>School__c</fullName>
        <label>School</label>
        <length>32</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Xero_Id__c</fullName>
        <inlineHelpText>The value in this field must be unique. If you need to manually link this invoice to a Xero invoice then please send the URL of both, in a spreadsheet, to the relevant member of the group management team</inlineHelpText>
        <label>Xero Id</label>
        <length>64</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Xero_Invoice_Currency__c</fullName>
        <label>Xero Invoice Currency</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Xero_Invoice_Date__c</fullName>
        <label>Xero Invoice Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Xero_Invoice_Number__c</fullName>
        <label>Xero Invoice Number</label>
        <length>64</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Xero_Key__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contract Setup</label>
        <referenceTo>Xero_Key__c</referenceTo>
        <relationshipLabel>Invoices</relationshipLabel>
        <relationshipName>Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Xero_Status__c</fullName>
        <label>Xero Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Xero_Value__c</fullName>
        <label>Xero Value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Invoice</label>
    <nameField>
        <displayFormat>{YY}-{00000}</displayFormat>
        <label>Salesforce UID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/School__c.object
<CustomObject>
    <label>School</label>
    <nameField>
        <label>School Code/UID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Schools</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Xero_Key__c.object
<CustomObject>
    <fields>
        <fullName>Consumer_Key__c</fullName>
        <label>Consumer Key</label>
        <length>32</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Consumer_Secret__c</fullName>
        <label>Consumer Secret</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Private_Key__c</fullName>
        <label>Private Key</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Contract Setup</label>
    <nameField>
        <label>Contract Setup</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contract Setup</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Xero_Payment__c.object
<CustomObject>
    <description>A payment recorded on an invoice. This gets queried from Xero.</description>
    <fields>
        <fullName>Account_Id__c</fullName>
        <label>Account Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Currency_Rate__c</fullName>
        <label>Currency Rate</label>
        <precision>16</precision>
        <scale>10</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Currency__c</fullName>
        <formula>Invoice_Statement__r.Currency__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Currency</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Invoice_Statement__c</fullName>
        <description>Lookup to the Invoice for which this payment is associated.</description>
        <label>Invoice</label>
        <referenceTo>Invoice_Statement__c</referenceTo>
        <relationshipLabel>Payments</relationshipLabel>
        <relationshipName>Payments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Payment_Amount__c</fullName>
        <label>Payment Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Payment_Currency__c</fullName>
        <label>Payment Currency (Xero)</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Payment_Date__c</fullName>
        <label>Payment Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Reference__c</fullName>
        <label>Reference</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>School__c</fullName>
        <formula>Invoice_Statement__r.School__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>School</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Xero_Account_Name__c</fullName>
        <label>Paid to</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Xero_Id__c</fullName>
        <description>Unique Id of payment record in Xero</description>
        <externalId>true</externalId>
        <label>Xero Id</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Payment</label>
    <nameField>
        <displayFormat>PAY{YY}{MM}-{0000}</displayFormat>
        <label>Payment Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/XeroSyncTest.cls
/**
 * Tests for XeroSyncLogic and XeroSyncSchedule
 *
 * @author Logan Moore
 * @created August 2013
 */
@isTest
private class XeroSyncTest {
	
	@isTest static void testSync() {

		sfXero.XeroAPI.startTesting();

		Account payerAcc = new Account(name='acc');
		insert payerAcc;
		
		Xero_Key__c xeroKey = new Xero_Key__c();
		xeroKey.Name = 'TestSchool';
		xeroKey.Private_Key__c = ''
			+ 'MIICXAIBAAKBgQCv2NPOk4/UfpMPsOl9DOWoKSS+EDh/g/nFQ+JIHePe2T1wOsrn'
			+ '9ywuh/QLrl984OeHMvJMYg8YDpRr15XCcgbQ66br0WjuJMldt4LbxPj6nta7tyDx'
			+ 't4SLg+38IO5MRDzvf73/BJvoKyNAQRJeJL1YO/JIsp7vLYmdDlsYXNlWSQIDAQAB'
			+ 'AoGADa/VxJVts39qmOUPN2GCmpUhO/3tN9eg4D7JZQ2Wh+jmxE5/LpDpinGgiCw5'
			+ 'WHH082v+uf1D6X5xBPfRu0G+z/EOyeUk36RBLhUZQgrXRwOFGQ3eSWn2n0i+3ghz'
			+ 'uG9fMjX4hiPpPj2+NB1euhCWUOIrr3wxAm8quulihouhtzUCQQDYIjZ5fkDMTyrl'
			+ '4AM4bgXw1pGCKd1No6nWzSG3w8BXUzTyjd7pozxRA1OFMByYCfIgpZcsa8INK+c/'
			+ 'KUF5HKejAkEA0EhJWJSrLmFKCoe8/eW//otAl3awbhefT8Y6WdJTKQEi7jYXjUbA'
			+ '4XrRtHbV7z9YOxbPirEcwcG6OFAa7yqZIwJBAMJk2zwhCyT326yP9DWP97XrN0qs'
			+ 'XsiS+JIjRD1lSh0A0LGMWr8nO3veEwPLBxzUbTth1Ht2nD1+jGnpsGK/HCMCQHXj'
			+ 'VFBk5Xb87hGDvr7emYsTel3Aeh/2Et/uTPymBRfCYuj9iNsX3vhAsg047eHasq/P'
			+ 'O20+zg4E/sf83yHbtI0CQCAQZCz+H9tbfP8NCegkH0shgrm1Ic3qHgEAt3Sm7kRH'
			+ 'Fm4JU0LB/BMdoo3mqJZtN4N16WN68DoC0g8/3mtfTUE=';
		xeroKey.Consumer_Key__c = 'HPED7CKJXLMDO1TR15A5MPF12G4ORH';
		xeroKey.Consumer_Secret__c = 'XFAFUUMMXA58IESPKDP3PG8KADL2DL';
		insert xeroKey;
		
		Invoice_Statement__c invoice = new Invoice_Statement__c();
		invoice.Xero_Id__c = 'DEC9A69C-E6F1-4E66-B925-F5FDCD204F7E';
		invoice.Currency__c = 'USD';
		invoice.School__c = 'Kuala Lumpur';
		invoice.Xero_Key__c = xeroKey.Id;
		invoice.Payer__c = payerAcc.Id;
		insert invoice;

		Xero_Payment__c payment = new Xero_Payment__c();
		payment.Invoice_Statement__c = invoice.Id;
		payment.Xero_Id__c = '6af48534-c0cd-40bb-ba0a-ad2039895fba';
		insert payment;
		
		//Test.setMock(HttpCalloutMock.class, new ServiceMock());
		
		Test.startTest();
		XeroSyncLogic.sync(xeroKey.Id);
		Test.stopTest();

		invoice = [
			SELECT Id, Xero_Invoice_Number__c, Xero_Value__c, Xero_Status__c, Xero_Invoice_Date__c, Xero_Invoice_Currency__c, Reference__c,
			(
				SELECT Id, Xero_Id__c, Payment_Amount__c, Payment_Date__c, Account_Id__c, Reference__c, Currency_Rate__c, Status__c, Xero_Account_Name__c, Payment_Currency__c
				FROM Payments__r
			)
			FROM Invoice_Statement__c
			WHERE Id = :invoice.Id
		];

		System.debug(invoice.Xero_Invoice_Number__c);
		System.debug(invoice.Xero_Value__c);
		System.debug(invoice.Xero_Status__c);
		System.debug(invoice.Xero_Invoice_Date__c);
		System.debug(invoice.Xero_Invoice_Currency__c);
		System.debug(invoice.Reference__c);
		System.debug(invoice.Payments__r.size());

		System.debug(invoice.Payments__r[0].Xero_Id__c);
		System.debug(invoice.Payments__r[0].Payment_Amount__c);
		System.debug(invoice.Payments__r[0].Payment_Date__c);
		System.debug(invoice.Payments__r[0].Account_Id__c);
		System.debug(invoice.Payments__r[0].Reference__c);
		System.debug(invoice.Payments__r[0].Currency_Rate__c);
		System.debug(invoice.Payments__r[0].Status__c);
		System.debug(invoice.Payments__r[0].Xero_Account_Name__c);
		System.debug(invoice.Payments__r[0].Payment_Currency__c);

		sfXero.XeroAPI.stopTesting();
	}

	@isTest static void testSchedule() {

		sfXero.XeroAPI.startTesting();

		Xero_Key__c xeroKey = new Xero_Key__c();
		xeroKey.Name = 'TestSchool';
		xeroKey.Private_Key__c = ''
			+ 'MIICXAIBAAKBgQCv2NPOk4/UfpMPsOl9DOWoKSS+EDh/g/nFQ+JIHePe2T1wOsrn'
			+ '9ywuh/QLrl984OeHMvJMYg8YDpRr15XCcgbQ66br0WjuJMldt4LbxPj6nta7tyDx'
			+ 't4SLg+38IO5MRDzvf73/BJvoKyNAQRJeJL1YO/JIsp7vLYmdDlsYXNlWSQIDAQAB'
			+ 'AoGADa/VxJVts39qmOUPN2GCmpUhO/3tN9eg4D7JZQ2Wh+jmxE5/LpDpinGgiCw5'
			+ 'WHH082v+uf1D6X5xBPfRu0G+z/EOyeUk36RBLhUZQgrXRwOFGQ3eSWn2n0i+3ghz'
			+ 'uG9fMjX4hiPpPj2+NB1euhCWUOIrr3wxAm8quulihouhtzUCQQDYIjZ5fkDMTyrl'
			+ '4AM4bgXw1pGCKd1No6nWzSG3w8BXUzTyjd7pozxRA1OFMByYCfIgpZcsa8INK+c/'
			+ 'KUF5HKejAkEA0EhJWJSrLmFKCoe8/eW//otAl3awbhefT8Y6WdJTKQEi7jYXjUbA'
			+ '4XrRtHbV7z9YOxbPirEcwcG6OFAa7yqZIwJBAMJk2zwhCyT326yP9DWP97XrN0qs'
			+ 'XsiS+JIjRD1lSh0A0LGMWr8nO3veEwPLBxzUbTth1Ht2nD1+jGnpsGK/HCMCQHXj'
			+ 'VFBk5Xb87hGDvr7emYsTel3Aeh/2Et/uTPymBRfCYuj9iNsX3vhAsg047eHasq/P'
			+ 'O20+zg4E/sf83yHbtI0CQCAQZCz+H9tbfP8NCegkH0shgrm1Ic3qHgEAt3Sm7kRH'
			+ 'Fm4JU0LB/BMdoo3mqJZtN4N16WN68DoC0g8/3mtfTUE=';
		xeroKey.Consumer_Key__c = 'HPED7CKJXLMDO1TR15A5MPF12G4ORH';
		xeroKey.Consumer_Secret__c = 'XFAFUUMMXA58IESPKDP3PG8KADL2DL';
		insert xeroKey;

		
		Test.startTest();
		XeroSyncSchedule.schedule();
		Test.stopTest();

		sfXero.XeroAPI.stopTesting();
	}
}