force-app/main/default/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Account_Alternate_Email_Formula__c</fullName>
        <formula>Related_Contact_Record_P2__r.Contact_Alternate_Email__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Alternate Email (P2)</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Account_Alternate_Email_Opt_Out_Formula__c</fullName>
        <formula>Related_Contact_Record_P2__r.Contact_Alternate_Email_Opt_Out__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Alternate Email Opt Out (P2)</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Account_Email_Opt_Out_Formula__c</fullName>
        <formula>Related_Contact_Record_P2__r.HasOptedOutOfEmail</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Email Opt Out (P2)</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Account_Main_Email_Formula__c</fullName>
        <formula>Related_Contact_Record_P2__r.Email</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Main Email (P2)</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Account_UID_Formula__c</fullName>
        <description>A temporary field using only during migration to allow the auto-number field to be referenced indirectly in apex so that it can be changed to/from an auto-number field as required</description>
        <formula>Account_UID__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Account UID (Formula)</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Company_Contact_Person_1_First_Name__c</fullName>
        <label>Contact Person 1 First Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Company_Contact_Person_1_Last_Name__c</fullName>
        <label>Contact Person 1 Last Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Company_Contact_Person_2_First_Name__c</fullName>
        <label>Contact Person 2 First Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Company_Contact_Person_2_Last_Name__c</fullName>
        <label>Contact Person 2 Last Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Company_Email_2__c</fullName>
        <label>Company Email 2</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Company_Email__c</fullName>
        <label>Company Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Email_Addresses_to_Include_in_Xero__c</fullName>
        <description>Defines the email addresses to by synced with person contacts under the related Salesforce contact. Apex code checks that emails are not opted out and ensures there are no duplicates.</description>
        <inlineHelpText>Select the email addresses for the emailing of invoices directly from Xero. Note that emails selected will not be synced with Xero if the parent has opted out of email.</inlineHelpText>
        <label>Additional Email Add. to Include in Xero</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Parent 1 Main Email</fullName>
                </value>
                <value>
                    <fullName>Parent 1 Alternate Email</fullName>
                </value>
                <value>
                    <fullName>Parent 2 Main Email</fullName>
                </value>
                <value>
                    <fullName>Parent 2 Alternate Email</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Main_Address__c</fullName>
        <description>The main address field for a company record only. Temporarily also holds the old address information for &apos;Parent&apos; records, although this is being phased out and should only be edited by system admin on those records during the transition, therefore is only shown on the system admin page layout for parents.</description>
        <label>Main Address</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Primary_Invoicing_Contact_Country_Code__c</fullName>
        <formula>IF(RecordType.DeveloperName = &quot;Company_Account&quot;, &quot;&quot;, 

IF(AND(TEXT(Primary_Invoicing_Contact__c) = &quot;First Parent&quot;, xsms__Mobile_Phone_Country_Code__pc != &quot;&quot;, PersonMobilePhone != &quot;&quot;), xsms__Mobile_Phone_Country_Code__pc, 

IF(AND(TEXT(Primary_Invoicing_Contact__c) = &quot;First Parent&quot;, Contact_Alternate_Phone_Country_Code__pc != &quot;&quot;, Contact_Alternate_Phone__pc != &quot;&quot;, OR(xsms__Mobile_Phone_Country_Code__pc = &quot;&quot;, PersonMobilePhone = &quot;&quot;)), Contact_Alternate_Phone_Country_Code__pc, 

IF(AND(TEXT(Primary_Invoicing_Contact__c) = &quot;Second Parent&quot;, Related_Contact_Record_P2__r.xsms__Mobile_Phone_Country_Code__c != &quot;&quot;, Account_Mobile_Main_Phone_Formula__c != &quot;&quot;), Related_Contact_Record_P2__r.xsms__Mobile_Phone_Country_Code__c, 

IF(AND(TEXT(Primary_Invoicing_Contact__c) = &quot;Second Parent&quot;, Related_Contact_Record_P2__r.Contact_Alternate_Phone_Country_Code__c &lt;&gt; &quot;&quot;, Account_Alternate_Phone_Formula__c &lt;&gt; &quot;&quot;, OR(Related_Contact_Record_P2__r.xsms__Mobile_Phone_Country_Code__c = &quot;&quot;, Account_Mobile_Main_Phone_Formula__c = &quot;&quot;)), Related_Contact_Record_P2__r.Contact_Alternate_Phone_Country_Code__c, 

&quot;&quot;)))))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Primary Invoicing Contact Country Code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Primary_Invoicing_Contact_Email__c</fullName>
        <formula>IF(RecordType.DeveloperName = &quot;Company_Account&quot;, Company_Email__c,

IF(AND(TEXT(Primary_Invoicing_Contact__c) = &quot;First Parent&quot;, Contact_Alternate_Email__pc != &quot;&quot;, PersonEmail = &quot;&quot;), Contact_Alternate_Email__pc, 

IF(AND(TEXT(Primary_Invoicing_Contact__c) = &quot;First Parent&quot;, PersonEmail != &quot;&quot;), PersonEmail, 

IF(AND(TEXT(Primary_Invoicing_Contact__c) = &quot;Second Parent&quot;, Account_Alternate_Email_Formula__c != &quot;&quot;, Account_Main_Email_Formula__c = &quot;&quot;), Account_Alternate_Email_Formula__c, 

IF(AND(TEXT(Primary_Invoicing_Contact__c) = &quot;Second Parent&quot;, Account_Main_Email_Formula__c != &quot;&quot;), Account_Main_Email_Formula__c, 

&quot;&quot;)))))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Primary Invoicing Contact Email</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Primary_Invoicing_Contact_First_Name__c</fullName>
        <formula>IF(RecordType.DeveloperName = &quot;Company_Account&quot;, Company_Contact_Person_1_First_Name__c, 

IF(AND(TEXT(Primary_Invoicing_Contact__c) = &quot;Second Parent&quot;, Related_Contact_Record_P2__c &lt;&gt; &quot;&quot;),  Related_Contact_Record_P2__r.FirstName, FirstName))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Primary Invoicing Contact First Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Primary_Invoicing_Contact_Full_Name__c</fullName>
        <formula>IF(RecordType.DeveloperName = &quot;Company_Account&quot;, Name,

IF(TEXT(Primary_Invoicing_Contact__c) = &quot;Second Parent&quot;, Related_Contact_Record_P2__r.FirstName &amp; IF(Related_Contact_Record_P2__r.FirstName != &quot;&quot;, &quot; &quot;, &quot;&quot;) &amp; Related_Contact_Record_P2__r.LastName, FirstName &amp; IF(FirstName != &quot;&quot;, &quot; &quot;, &quot;&quot;) &amp; LastName))</formula>
        <label>Primary Invoicing Contact Full Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Primary_Invoicing_Contact_Last_Name__c</fullName>
        <formula>IF(RecordType.DeveloperName = &quot;Company_Account&quot;, Company_Contact_Person_1_Last_Name__c, 

IF(AND(TEXT(Primary_Invoicing_Contact__c) = &quot;Second Parent&quot;, Related_Contact_Record_P2__c &lt;&gt; &quot;&quot;),  Related_Contact_Record_P2__r.LastName, LastName))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Primary Invoicing Contact Last Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Primary_Invoicing_Contact_Phone_Number__c</fullName>
        <formula>IF(RecordType.DeveloperName = &quot;Company_Account&quot;, Company_Phone__c,

IF(AND(TEXT(Primary_Invoicing_Contact__c) = &quot;First Parent&quot;, xsms__Mobile_Phone_Country_Code__pc != &quot;&quot;, PersonMobilePhone != &quot;&quot;), PersonMobilePhone, 

IF(AND(TEXT(Primary_Invoicing_Contact__c) = &quot;First Parent&quot;, Contact_Alternate_Phone_Country_Code__pc != &quot;&quot;, Contact_Alternate_Phone__pc != &quot;&quot;, OR(xsms__Mobile_Phone_Country_Code__pc = &quot;&quot;, PersonMobilePhone = &quot;&quot;)), Contact_Alternate_Phone__pc, 

IF(AND(TEXT(Primary_Invoicing_Contact__c) = &quot;Second Parent&quot;, Related_Contact_Record_P2__r.xsms__Mobile_Phone_Country_Code__c != &quot;&quot;, Account_Mobile_Main_Phone_Formula__c != &quot;&quot;), Account_Mobile_Main_Phone_Formula__c, 

IF(AND(TEXT(Primary_Invoicing_Contact__c) = &quot;Second Parent&quot;, Related_Contact_Record_P2__r.Contact_Alternate_Phone_Country_Code__c &lt;&gt; &quot;&quot;, Account_Alternate_Phone_Formula__c &lt;&gt; &quot;&quot;, OR(Related_Contact_Record_P2__r.xsms__Mobile_Phone_Country_Code__c = &quot;&quot;, Account_Mobile_Main_Phone_Formula__c = &quot;&quot;)), Account_Alternate_Phone_Formula__c, 

&quot;&quot;)))))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Primary Invoicing Contact Phone Number</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Related_Contact_Record_P2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Click this link to edit/view the related contact</inlineHelpText>
        <label>Related Contact Record</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>The second parent must be of type &apos;Additional Parent&apos; and must be a contact created under this parent account.</errorMessage>
            <filterItems>
                <field>Contact.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Additional_Parent</value>
            </filterItems>
            <filterItems>
                <field>Contact.Main_Parent_File__r.Id</field>
                <operation>equals</operation>
                <valueField>$Source.Id</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Family Account</relationshipLabel>
        <relationshipName>FamilyAccount</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>School__c</fullName>
        <description>Copies the value of SchoolText (which is a workflow copying from School Formula). A little long winded solution to avoid bigger changes in the Teacher/Parent portal.</description>
        <formula>SchoolText__pc</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>School</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Xero_Contact_ID__c</fullName>
        <label>Xero Contact ID</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice_Statement__c.object
<CustomObject>
    <fields>
        <fullName>Currency__c</fullName>
        <label>Currency</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Generated_Date__c</fullName>
        <label>Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Invoice_Date__c</fullName>
        <label>Invoice Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Payer__c</fullName>
        <label>Parent/Company</label>
        <lookupFilter>
            <active>false</active>
            <booleanFilter>1 OR 2</booleanFilter>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Company</value>
            </filterItems>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Parent</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Invoices</relationshipLabel>
        <relationshipName>Invoice_Statements1</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Reference__c</fullName>
        <label>Reference</label>
        <length>10000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>School__c</fullName>
        <label>School</label>
        <length>32</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Single_Invoice__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Single Invoice</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Xero_Id__c</fullName>
        <inlineHelpText>The value in this field must be unique. If you need to manually link this invoice to a Xero invoice then please send the URL of both, in a spreadsheet, to the relevant member of the group management team</inlineHelpText>
        <label>Xero Id</label>
        <length>64</length>
        <type>Text</type>
    </fields>
    <label>Invoice</label>
    <nameField>
        <displayFormat>{YY}-{00000}</displayFormat>
        <label>Salesforce UID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/SendSingleInvoiceController.cls
public class SendSingleInvoiceController{
    
    public ApexPages.StandardController controller {get; set;} 
    
    public SendSingleInvoiceController(ApexPages.StandardController sc){
        this.controller = sc;
    }
    
    public PageReference sendToXero(){
        
        try {
            Invoice_Statement__c invoice = [
                Select Payer__r.Primary_Invoicing_Contact_Full_Name__c, Payer__r.Primary_Invoicing_Contact_First_Name__c, Payer__r.Primary_Invoicing_Contact_Last_Name__c, Payer__r.Primary_Invoicing_Contact_Email__c, Payer__r.Primary_Invoicing_Contact_Country_Code__c, Payer__r.Primary_Invoicing_Contact_Phone_Number__c,  Id, Payer__r.Xero_Contact_Id__c, Xero_Id__c, Payer__c, Payer__r.Account_UID_Formula__c, Reference__c, Generated_Date__c, Invoice_Date__c, School__c, Single_Invoice__c,
                    //Payer__r.Add_Invoicing_Contact_Email__c,  Payer__r.Add_Invoicing_Contact_First_Name__c, Payer__r.Add_Invoicing_Contact_Last_Name__c,
                    Payer__r.RecordType.DeveloperName, Payer__r.Email_Addresses_to_Include_in_Xero__c, Payer__r.PersonEmail, Payer__r.Contact_Alternate_Email__pc, Payer__r.PersonHasOptedOutOfEmail, Payer__r.Contact_Alternate_Email_Opt_Out__pc, Payer__r.Account_Main_Email_Formula__c, Payer__r.Account_Email_Opt_Out_Formula__c, Payer__r.Account_Alternate_Email_Formula__c, Payer__r.Account_Alternate_Email_Opt_Out_Formula__c, 
                    Payer__r.Company_Contact_Person_1_First_Name__c, Payer__r.Company_Contact_Person_1_Last_Name__c, Payer__r.Company_Contact_Person_2_First_Name__c, Payer__r.Company_Contact_Person_2_Last_Name__c, Payer__r.Company_Email__c, Payer__r.Company_Email_2__c, 
                    Payer__r.RecordTypeId, Payer__r.RecordType.Name,Payer__r.Phone, Payer__r.Main_Address__c, Currency__c,
                    //Payer__r.FirstName, Payer__r.LastName, Payer__r.Name, Payer__r.PersonEmail, Payer__r.Account_Main_Email_Formula__c, Payer__r.Company_Email__c 
                    Payer__r.FirstName, Payer__r.LastName, Payer__r.Name, Payer__r.Related_Contact_Record_P2__r.FirstName, Payer__r.Related_Contact_Record_P2__r.LastName,  
                    Payer__r.Address_Apartment_Condo_Name_Number__pc, Payer__r.Address_Street_Name_Number__pc, Payer__r.Address_Line_2__pc,  Payer__r.Address_City__pc, Payer__r.Address_State_Province__pc, Payer__r.Address_Zip_Postal_Code__pc, Payer__r.Address_Country__pc
                  From Invoice_Statement__c 
                 Where Id =: this.controller.getId()
            ];
            if(invoice.Xero_Id__c != null){
                //fetch invoice status
                String school = invoice.School__c;
                if(school == 'Pamplona') {
                    school = 'Navarra'; 
                }
                // Get the Xero key for the given school
                Xero_Key__c xeroKey = [
                    SELECT Id, Name, Private_Key__c, Consumer_Key__c, Consumer_Secret__c, 
                        AccCode_Tuition__c, AccCode_Lunch__c, AccCode_Bus__c, AccCode_Other__c,
                        AccCode_Enrolment__c, AccCode_Application__c, AccCode_EAL__c, Tracking_Category_1_Company__c, Tracking_Category_2_Campus_Misc__c
                      FROM Xero_Key__c 
                     WHERE Name =: school limit 1
                 ];
                String consumerSecret = (xeroKey.Consumer_Secret__c == null) ? '' : xeroKey.Consumer_Secret__c;
                sfXero.XeroCredentials xeroCreds = new sfXero.XeroCredentials(xeroKey.Consumer_Key__c, consumerSecret, xeroKey.Private_Key__c);
                sfXero.XeroInvoiceResponse response = sfXero.XeroAPI.getInvoiceById(xeroCreds,invoice.Xero_Id__c );
                System.debug('### ***SendSingleInvoiceController**response ' +response);
                if(response.status == 'OK' && !test.isRunningTest()) {
                    string invoiceStatus = String.valueOf(response.invoices[0].status);
                    if(invoiceStatus != null){
                        if(!invoiceStatus.equalsIgnoreCase('voided') && !invoiceStatus.equalsIgnoreCase('deleted')){
                            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 'You cannot send this invoice to Xero again until the current one is deleted or voided in Xero. To view the Xero invoice you can use the \'Link to Xero Invoice\' field on invoice record.'));
                            return null;
                        }
                    }
                }
            }
            
            
            List<Invoice_Statement__c> invoices = new List<Invoice_Statement__c>();
            invoices.add(invoice);
            
            BatchInvoiceSending bis = new BatchInvoiceSending();
            bis.sendInvoices(invoices);
            
            return new PageReference('/' + invoice.Id);
        }
        catch(Exception e) {
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 'Failure during sending : ' + e.getMessage()));
            return null;
        }
    }    
    
    public PageReference returnToInvoice(){
        return this.controller.view();
    }
    
    
    
}