force-app/main/default/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Company_School__c</fullName>
        <formula>TEXT(Owner.School__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Company School</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Xero_Contact_ID__c</fullName>
        <label>Xero Contact ID</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Account_Owner_Mapping__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This setting is used to determine appropriate &quot;Mass Email&quot; or &quot;Catch All&quot; account for a given Account/Opportunity Owner. Name field contains &quot;Owner Name&quot; and Account Id field contains Id of associated account.. This setting is used in Opportunity trigger.</description>
    <fields>
        <fullName>School_Name__c</fullName>
        <label>School Name</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>School_Short_Name__c</fullName>
        <description>short name for school. used in accounting processes.</description>
        <inlineHelpText>short name for school. used in accounting processes.</inlineHelpText>
        <label>School Short Name</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Account Owner Mapping</label>
</CustomObject>

force-app/main/default/objects/Xero_Key__c.object
<CustomObject>
    <fields>
        <fullName>AccCode_Application__c</fullName>
        <label>AccCode Application</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AccCode_Bus__c</fullName>
        <label>AccCode Bus</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AccCode_EAL__c</fullName>
        <label>AccCode EAL</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AccCode_Enrolment__c</fullName>
        <label>AccCode Enrolment</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AccCode_Lunch__c</fullName>
        <label>AccCode Lunch</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AccCode_Other__c</fullName>
        <label>AccCode Other</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AccCode_Tuition__c</fullName>
        <label>AccCode Tuition</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Consumer_Key__c</fullName>
        <label>Consumer Key</label>
        <length>32</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Consumer_Secret__c</fullName>
        <label>Consumer Secret</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Private_Key__c</fullName>
        <label>Private Key</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Tracking_Category_1_Company__c</fullName>
        <inlineHelpText>Specify the &apos;TrackingCategoryID&apos; taken from Xero for this tracking category. Leave blank if not in use.</inlineHelpText>
        <label>Tracking Category 1 (Company)</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Tracking_Category_2_Campus_Misc__c</fullName>
        <inlineHelpText>Specify the &apos;TrackingCategoryID&apos; taken from Xero for this tracking category. Leave blank if not in use.</inlineHelpText>
        <label>Tracking Category 2 (Campus/Misc)</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Contract Setup</label>
    <nameField>
        <label>Contract Setup</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contract Setup</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/Batch_PostContactsToXero.cls
global with sharing class Batch_PostContactsToXero implements Database.Batchable<sObject>, Database.AllowsCallouts{
    global string query;
    global string school;
    global list<Id> accountIds;
    global Batch_PostContactsToXero(string s) {
    	accountIds = new list<Id>();
    	accountIds.add('001D000001iKbck');
    	accountIds.add('001D000001dah43');
    	school = s;
        query = 'select Id, Xero_Contact_Id__c from Account where Xero_Contact_Id__c != null AND Company_School__c=:school AND Id IN:accountIds limit 1';
    
    }
    
    global Database.QueryLocator start(Database.BatchableContext BC) {
        return Database.getQueryLocator(query);
    }
    
    global void execute(Database.BatchableContext BC, List<Account> scope) {
    	Map<String,String> schoolAssignment = new Map<String,String>();
        List<Account_Owner_Mapping__c> settings = Account_Owner_Mapping__c.getall().values(); 
        for(Account_Owner_Mapping__c sttng:settings){
            if(sttng.School_Name__c != null && sttng.School_Short_Name__c != null){
                schoolAssignment.put(sttng.School_Name__c,sttng.School_Short_Name__c);
            }
        }
        string schoolShortName = schoolAssignment.get(school);
        if(schoolShortName == 'Pamplona') {
                    schoolShortName = 'Navarra'; 
                }
        Xero_Key__c xeroKey = [
                    SELECT Id, Name, Private_Key__c, Consumer_Key__c, Consumer_Secret__c, 
                        AccCode_Tuition__c, AccCode_Lunch__c, AccCode_Bus__c, AccCode_Other__c,
                        AccCode_Enrolment__c, AccCode_Application__c, AccCode_EAL__c, Tracking_Category_1_Company__c, Tracking_Category_2_Campus_Misc__c
                      FROM Xero_Key__c 
                     WHERE Name =: schoolShortName limit 1
                 ];
        list<sfXero.XeroContact> xeroContactList = new list<sfXero.XeroContact>();
        /*for(Account acc:scope){
        	sfXero.XeroContact xcon = new sfXero.XeroContact();
        	xcon.contactId = acc.Xero_Contact_Id__c;
        	xcon.contactNumber = acc.Id;
        	xeroContactList.add(xcon);
        }*/
        sfXero.XeroContact xcon = new sfXero.XeroContact();
    	xcon.contactId = '9accb7fb-5683-46b9-afc3-3ea7dc644dbf';
    	xcon.contactNumber = '';
    	xeroContactList.add(xcon);
        if(xeroContactList.size() > 0){
        	String consumerSecret = (xeroKey.Consumer_Secret__c == null) ? '' : xeroKey.Consumer_Secret__c;
            sfXero.XeroCredentials xeroCreds = new sfXero.XeroCredentials(xeroKey.Consumer_Key__c, consumerSecret, xeroKey.Private_Key__c);
            sfXero.XeroContactResponse response = sfXero.XeroAPI.postContacts(xeroContactList , xeroCreds);
            System.debug('### *****response ' +response);
        }
    }
    
    global void finish(Database.BatchableContext BC) {
    }
}