force-app/main/default/objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>Company_Account</fullName>
        <active>true</active>
        <label>Company</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Student_Name__c</fullName>
        <label>Student Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Year_Group__c</fullName>
        <label>Year Group / Grade</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>US_Year_Group_Control__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>PN1</fullName>
                </value>
                <value>
                    <fullName>PN</fullName>
                </value>
                <value>
                    <fullName>N</fullName>
                </value>
                <value>
                    <fullName>R</fullName>
                </value>
                <value>
                    <fullName>Y1</fullName>
                </value>
                <value>
                    <fullName>Y2</fullName>
                </value>
                <value>
                    <fullName>Y3</fullName>
                </value>
                <value>
                    <fullName>Y4</fullName>
                </value>
                <value>
                    <fullName>Y5</fullName>
                </value>
                <value>
                    <fullName>Y6</fullName>
                </value>
                <value>
                    <fullName>Y7</fullName>
                </value>
                <value>
                    <fullName>Y8</fullName>
                </value>
                <value>
                    <fullName>Y9</fullName>
                </value>
                <value>
                    <fullName>Y10</fullName>
                </value>
                <value>
                    <fullName>Y11</fullName>
                </value>
                <value>
                    <fullName>Y12</fullName>
                </value>
                <value>
                    <fullName>Y13</fullName>
                </value>
                <value>
                    <fullName>PK</fullName>
                </value>
                <value>
                    <fullName>K</fullName>
                </value>
                <value>
                    <fullName>G1</fullName>
                </value>
                <value>
                    <fullName>G2</fullName>
                </value>
                <value>
                    <fullName>G3</fullName>
                </value>
                <value>
                    <fullName>G4</fullName>
                </value>
                <value>
                    <fullName>G5</fullName>
                </value>
                <value>
                    <fullName>G6</fullName>
                </value>
                <value>
                    <fullName>G7</fullName>
                </value>
                <value>
                    <fullName>G8</fullName>
                </value>
                <value>
                    <fullName>G9</fullName>
                </value>
                <value>
                    <fullName>G10</fullName>
                </value>
                <value>
                    <fullName>G11</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Student</fullName>
        <active>true</active>
        <businessProcess>Standard Admissions Process</businessProcess>
        <label>Student</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/PersonAccount.object
<CustomObject>
    <recordTypes>
        <fullName>PersonAccount</fullName>
        <active>true</active>
        <label>Parent</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/AccountUpdateChildOpportunities.cls
public class AccountUpdateChildOpportunities{
	/*
    public static void UpdatePayerField(List<Account> oldAccs, List<Account> newAccs){

        Map<String, Account> accsForUpdate = new Map<String, Account>();
        for (Integer i = 0; i < oldAccs.size(); i++){
            if (oldAccs[i].F_Info_Company_Name__c != newAccs[i].F_Info_Company_Name__c){
                accsForUpdate.put(newAccs[i].Id, newAccs[i]);
            }
        }
        Set<String> accIds = accsForUpdate.keySet();
        List<Opportunity> oppsForUpdate = [Select Id, AccountId, Payer__c
                                             From Opportunity
                                             Where AccountId IN :accIds];
        
        for (Opportunity o : oppsForUpdate){
        	o.Payer__c = accsForUpdate.get(o.AccountId).F_Info_Company_Name__c;   
        }
        
        List<Database.SaveResult> results = Database.update(oppsForUpdate,false);
        
    }
    
    @isTest
        public static void testUpdatePayerField(){
           
            Account parent =  new Account();
			parent.FirstName =  'First Name';
			parent.LastName =  'Last Name';
			parent.PersonEmail = 'test@test.com';
			parent.RecordTypeId = [Select Id from RecordType where SObjectType='Account' AND DeveloperName='PersonAccount'].Id;
			insert parent;
            
            //create company account account
			Account company =  new Account();
			company.Name =  'Company Account';
			company.RecordTypeId = [Select Id from RecordType where SObjectType='Account' AND DeveloperName='Company_Account'].Id;
			insert company;  
		
		
            
            Opportunity student = new Opportunity(Name = 'Student',
                                                  Payer__c = company.Id,
                                                  AccountId = parent.Id,
                                                  Year_Group__c='Y3',
                                                  StageName = 'A/ Testing', 
                                                  CloseDate = Date.Today(), 
                                                  Student_Name__c = 'Student');
                
            insert student;
            student.StageName = 'Enrolled';
            update student;
            
            parent.F_Info_Company_Name__c = company.Id;
            update parent;
            
            System.assertEquals(company.Id, [Select Payer__c from Opportunity Where Id = :student.Id].Payer__c);
                
        }
    
    */
}