force-app/main/default/objects/Account.object
<CustomObject>
    <fields>
        <fullName>School__c</fullName>
        <description>Copies the value of SchoolText (which is a workflow copying from School Formula). A little long winded solution to avoid bigger changes in the Teacher/Parent portal.</description>
        <formula>SchoolText__pc</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>School</label>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Class__c/Class__c.object-meta.xml
<CustomObject>
    <label>Class</label>
    <nameField>
        <label>Class Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Classes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Class__c/fields/CapacityAvailable__c.field-meta.xml
<CustomField>
    <fullName>CapacityAvailable__c</fullName>
    <formula>CapacityTotal__c -  CapacityUsed__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Capacity Available</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Class__c/fields/CapacityTotal__c.field-meta.xml
<CustomField>
    <fullName>CapacityTotal__c</fullName>
    <label>Capacity Total</label>
    <summarizedField>ClassCapacity__c.CapacityTotal__c</summarizedField>
    <summaryFilterItems>
        <field>ClassCapacity__c.CurrentYear__c</field>
        <operation>equals</operation>
        <value>True</value>
    </summaryFilterItems>
    <summaryForeignKey>ClassCapacity__c.Class__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Class__c/fields/CapacityUsed__c.field-meta.xml
<CustomField>
    <fullName>CapacityUsed__c</fullName>
    <label>Capacity Used</label>
    <summarizedField>ClassCapacity__c.CapacityUsed__c</summarizedField>
    <summaryFilterItems>
        <field>ClassCapacity__c.CurrentYear__c</field>
        <operation>equals</operation>
        <value>True</value>
    </summaryFilterItems>
    <summaryForeignKey>ClassCapacity__c.Class__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Class__c/fields/SchoolName__c.field-meta.xml
<CustomField>
    <fullName>SchoolName__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>School Name</label>
    <referenceTo>School__c</referenceTo>
    <relationshipLabel>Classes</relationshipLabel>
    <relationshipName>Classes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Class__c/fields/YearGrade__c.field-meta.xml
<CustomField>
    <fullName>YearGrade__c</fullName>
    <label>Year/Grade</label>
    <referenceTo>YearGrade__c</referenceTo>
    <relationshipLabel>Classes</relationshipLabel>
    <relationshipName>Classes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ClassCapacity__c/ClassCapacity__c.object-meta.xml
<CustomObject>
    <description>NDM: Class capacity/ enrolment year</description>
    <label>Class Capacity</label>
    <nameField>
        <label>Class Capacity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Class Capacities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ClassCapacity__c/fields/CapacityTotal__c.field-meta.xml
<CustomField>
    <fullName>CapacityTotal__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Capacity Total</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ClassCapacity__c/fields/CapacityUsed__c.field-meta.xml
<CustomField>
    <fullName>CapacityUsed__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Capacity Used</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ClassCapacity__c/fields/Class__c.field-meta.xml
<CustomField>
    <fullName>Class__c</fullName>
    <label>Class</label>
    <referenceTo>Class__c</referenceTo>
    <relationshipLabel>Class Capacities</relationshipLabel>
    <relationshipName>Class_Capacities</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Class__c</fullName>
        <formula>TEXT(Admissions_File__r.Class__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Class</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>School__c</fullName>
        <formula>Admissions_File__r.School__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>School</label>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Contact</fullName>
        <active>true</active>
        <label>Contact</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/EnrolmentPeriod__c/EnrolmentPeriod__c.object-meta.xml
<CustomObject>
    <label>Enrolment Period</label>
    <nameField>
        <label>Enrolment Period Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Enrolment Periods</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/EnrolmentPeriod__c/fields/SchoolName__c.field-meta.xml
<CustomField>
    <fullName>SchoolName__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>School Name</label>
    <referenceTo>School__c</referenceTo>
    <relationshipLabel>Enrolment Periods</relationshipLabel>
    <relationshipName>Enrolment_Periods</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Class__c</fullName>
        <description>Defaults:
From Lead Convert: Will be &apos;Pending&apos; for schools without campus options and any of the 3 &apos;Pending&apos; options for schools with campus options (&apos;Not Sure&apos; = &apos;Pending&apos;)
From Student Clone: Will be copied from the record that is cloned as it cannot be blank and can therefore not revert to the default of &apos;Pending&apos;.</description>
        <inlineHelpText>A to H = Campus 1 (Krylatskoe/CF)
I to P = Campus 2 (Rosinka/ CJ)</inlineHelpText>
        <label>Class</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>School_Controlling_Picklist1__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                    <default>true</default>
                    <label>Pending</label>
                </value>
                <value>
                    <fullName>Pending (Campus 1: A-H)</fullName>
                </value>
                <value>
                    <fullName>Pending (Campus 2: I-P)</fullName>
                </value>
                <value>
                    <fullName>A</fullName>
                </value>
                <value>
                    <fullName>B</fullName>
                </value>
                <value>
                    <fullName>C</fullName>
                </value>
                <value>
                    <fullName>D</fullName>
                </value>
                <value>
                    <fullName>E</fullName>
                </value>
                <value>
                    <fullName>F</fullName>
                </value>
                <value>
                    <fullName>G</fullName>
                </value>
                <value>
                    <fullName>H</fullName>
                </value>
                <value>
                    <fullName>I</fullName>
                </value>
                <value>
                    <fullName>J</fullName>
                </value>
                <value>
                    <fullName>K</fullName>
                </value>
                <value>
                    <fullName>L</fullName>
                </value>
                <value>
                    <fullName>M</fullName>
                </value>
                <value>
                    <fullName>N</fullName>
                </value>
                <value>
                    <fullName>O</fullName>
                </value>
                <value>
                    <fullName>P</fullName>
                </value>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
                <value>
                    <fullName>4</fullName>
                </value>
                <value>
                    <fullName>5</fullName>
                </value>
                <value>
                    <fullName>[House] 1</fullName>
                </value>
                <value>
                    <fullName>[House] 2</fullName>
                </value>
                <value>
                    <fullName>[House] 3</fullName>
                </value>
                <value>
                    <fullName>[House] 4</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>School__c</fullName>
        <formula>Account.SchoolText__pc</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>School</label>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/School__c.object
<CustomObject>
    <label>School</label>
    <nameField>
        <label>School Code/UID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Schools</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/School__c/fields/CapacityTotal__c.field-meta.xml
<CustomField>
    <fullName>CapacityTotal__c</fullName>
    <label>Capacity Total</label>
    <summarizedField>YearGrade__c.CapacityTotal__c</summarizedField>
    <summaryForeignKey>YearGrade__c.SchoolName__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/School__c/fields/CapacityUsed__c.field-meta.xml
<CustomField>
    <fullName>CapacityUsed__c</fullName>
    <label>Capacity Used</label>
    <summarizedField>YearGrade__c.CapacityUsed__c</summarizedField>
    <summaryForeignKey>YearGrade__c.SchoolName__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/School__c/fields/Reference_Date__c.field-meta.xml
<CustomField>
    <fullName>Reference_Date__c</fullName>
    <inlineHelpText>Update this to be the first day of your school year, this is used in the calculation of the Enrolment year on the opportunity</inlineHelpText>
    <label>Reference Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/User.object
<CustomObject>
    <fields>
        <fullName>School__c</fullName>
        <label>School</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>The British Schools Foundation</fullName>
                </value>
                <value>
                    <fullName>The British School of Guangzhou</fullName>
                </value>
                <value>
                    <fullName>The British School of Nanjing</fullName>
                </value>
                <value>
                    <fullName>The British International School of Marbella</fullName>
                </value>
                <value>
                    <fullName>The British School of Navarra</fullName>
                </value>
                <value>
                    <fullName>The British School of Tashkent</fullName>
                </value>
                <value>
                    <fullName>The British College of Brazil</fullName>
                </value>
                <value>
                    <fullName>The British International School of Kuala Lumpur</fullName>
                </value>
                <value>
                    <fullName>The International School of Moscow</fullName>
                </value>
                <value>
                    <fullName>Nord Anglia International School Manila</fullName>
                </value>
                <value>
                    <fullName>King&apos;s College Beijing</fullName>
                </value>
                <value>
                    <fullName>The British School Yangon</fullName>
                </value>
                <value>
                    <fullName>Ukraine International School</fullName>
                </value>
                <value>
                    <fullName>The New York International School</fullName>
                </value>
                <value>
                    <fullName>The British School of Brasilia</fullName>
                </value>
                <value>
                    <fullName>NAE</fullName>
                </value>
                <value>
                    <fullName>The British International School Yangon</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/YearGrade__c/YearGrade__c.object-meta.xml
<CustomObject>
    <label>Year/Grade</label>
    <nameField>
        <label>Year/Grade Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Years/Grades</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/YearGrade__c/fields/CapacityTotal__c.field-meta.xml
<CustomField>
    <fullName>CapacityTotal__c</fullName>
    <label>Capacity Total</label>
    <summarizedField>Class__c.CapacityTotal__c</summarizedField>
    <summaryForeignKey>Class__c.YearGrade__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/YearGrade__c/fields/CapacityUsed__c.field-meta.xml
<CustomField>
    <fullName>CapacityUsed__c</fullName>
    <label>Capacity Used</label>
    <summarizedField>Class__c.CapacityUsed__c</summarizedField>
    <summaryForeignKey>Class__c.YearGrade__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/YearGrade__c/fields/EnrolmentPeriod__c.field-meta.xml
<CustomField>
    <fullName>EnrolmentPeriod__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Enrolment Period</label>
    <referenceTo>EnrolmentPeriod__c</referenceTo>
    <relationshipLabel>Years/Grades</relationshipLabel>
    <relationshipName>YearsGrades</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/YearGrade__c/fields/SchoolName__c.field-meta.xml
<CustomField>
    <fullName>SchoolName__c</fullName>
    <label>School Name</label>
    <referenceTo>School__c</referenceTo>
    <relationshipLabel>Years/Grades</relationshipLabel>
    <relationshipName>Year_Groups2</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/BAT26_ClassCapacityUpdate_TEST.cls
/**
 * @description       : BAT25 Test Class
 * @author            : Spoon Consulting
 * @group             : 
 * @last modified on  : 01-12-2021
 * @last modified by  : Spoon Consulting
 * Modifications Log 
 * Ver   Date         Author             Modification
 * 1.0   30-03-2021   FKH                Initial Version
**/
@isTest
public with sharing class BAT26_ClassCapacityUpdate_TEST {

    static List<User> lstUser;
    static List<School__c> lstSchool;
    static List<YearGrade__c> lstYearGrade;
    static List<Class__c> lstClass;
    static List<ClassCapacity__c> lstClassCapacity;
    static List<EnrolmentPeriod__c> lstEnrolmentPeriod;
    static List<Account> lstAcc;
    static List<Contact> lstContact;
    static List<Opportunity> lstOpp; 
    static Map<string,Id> mapRecordType = new Map<String, Id>();
    static {
        lstUser = new List<User>{TestFactory.createUser('Test', TestFactory.getProfileAdminId())};
        insert lstUser;        
        System.runAs(lstUser[0]){         
            mapRecordType = AP_Constant.getDeveloperIdMap(new Set<String>{AP_Constant.oppObject, AP_Constant.conObject});

            lstSchool = new List<School__c>{
                TestFactory.createSchool('School1', 'Address1', true, 'SC1'),
                TestFactory.createSchool('School2', 'Address2', true, 'SC2'),
                TestFactory.createSchool('School3', 'Address3', true, 'SC3')
            }; 
            lstSchool[0].Reference_Date__c = Date.newInstance(2012, 2, 2);
            lstSchool[1].Reference_Date__c = Date.newInstance(2012, 2, 2);
            
            insert lstSchool;
    
            lstAcc = new List<Account>{
                TestFactory.createAccount('test Acc 0')
                ,TestFactory.createAccount('test Acc 1')
                ,TestFactory.createAccount('test Acc 2')
            };
            
            insert lstAcc;

            lstEnrolmentPeriod = new List<EnrolmentPeriod__c>{
                TestFactory.createEnrolmentPeriod('EP1', lstSchool[0].id,'SC1EP1', Date.newInstance(2010, 2, 2), Date.newInstance(2011, 2, 2)),
                TestFactory.createEnrolmentPeriod('EP2', lstSchool[1].id,'SC2EP1', Date.newInstance(2010, 2, 2), Date.newInstance(2011, 2, 2)),
                TestFactory.createEnrolmentPeriod('EP3', lstSchool[2].id,'SC2EP3', Date.newInstance(2010, 2, 2), Date.newInstance(2011, 2, 2))
            };

            insert lstEnrolmentPeriod;

            lstYearGrade = new List<YearGrade__c>{
                TestFactory.createYearGrade('YG1',lstSchool[0].id,12,14,lstEnrolmentPeriod[0].id),
                TestFactory.createYearGrade('YG2',lstSchool[1].id,13,15,lstEnrolmentPeriod[1].id),
                TestFactory.createYearGrade('YG3',lstSchool[2].id,13,15,lstEnrolmentPeriod[2].id)
            }; 

            insert lstYearGrade;

            lstClass = new List<Class__c>{
                TestFactory.createClass('Class1S1',30 , lstYearGrade[0].id,lstSchool[0].id),
                TestFactory.createClass('Class2S2',60 , lstYearGrade[1].id,lstSchool[1].id),
                TestFactory.createClass('Class3S3',10 , lstYearGrade[2].id,lstSchool[2].id)
            }; 

            insert lstClass;

            lstClassCapacity = new List<ClassCapacity__c>{
                TestFactory.createClassCapacity('Class1S1Cap1',30 , lstClass[0].id,Date.newInstance(2026, 1, 1),Date.newInstance(2025, 1, 1)),
                TestFactory.createClassCapacity('Class3S3Cap1',30 , lstClass[1].id,Date.newInstance(2026, 2, 2),Date.newInstance(2025, 2, 2))
            }; 
            insert lstClassCapacity;
  
            lstOpp = new List<Opportunity>{
                TestFactory.createOpportunity('testOpp01', lstAcc[0].Id, AP_Constant.oppStageNameStarted,
                                                mapRecordType.get(AP_Constant.oppRecordTypeEnrolment), lstSchool[0].Id)

                ,TestFactory.createOpportunity('testOpp02', lstAcc[0].Id, AP_Constant.oppStageNameEnrolled,
                                                mapRecordType.get(AP_Constant.oppRecordTypeEnrolment), lstSchool[0].Id)

                ,TestFactory.createOpportunity('testOpp03', lstAcc[0].Id, AP_Constant.oppStageNameAcceptance,
                                                mapRecordType.get(AP_Constant.oppRecordTypeEnrolment), lstSchool[1].Id)

                ,TestFactory.createOpportunity('testOpp04', lstAcc[0].Id, AP_Constant.oppStageNameApplication,
                                                mapRecordType.get(AP_Constant.oppRecordTypeEnrolment), lstSchool[1].Id)

                ,TestFactory.createOpportunity('testOpp05', lstAcc[0].Id, AP_Constant.oppStageNameActive,
                                                mapRecordType.get(AP_Constant.oppRecordTypeEnrolment), lstSchool[1].Id)
                ,TestFactory.createOpportunity('testOpp06', lstAcc[0].Id, AP_Constant.oppStageNameActive,
                mapRecordType.get(AP_Constant.oppRecordTypeEnrolment), lstSchool[1].Id)
            };

            lstOpp[3].Waitlisted__c= true;

            lstOpp[0].YearGrade__c = lstYearGrade[0].id;
            lstOpp[1].YearGrade__c = lstYearGrade[0].id;
            lstOpp[2].YearGrade__c = lstYearGrade[1].id;
            lstOpp[3].YearGrade__c = lstYearGrade[1].id;
            lstOpp[4].YearGrade__c = lstYearGrade[1].id;

            lstOpp[0].Class__c = lstClass[0].id;
            lstOpp[1].Class__c = lstClass[0].id;
            lstOpp[2].Class__c = lstClass[1].id;
            lstOpp[3].Class__c = lstClass[1].id;
            lstOpp[4].Class__c = lstClass[1].id;

            lstOpp[0].CloseDate= Date.newInstance(2025, 12, 12);
            lstOpp[1].CloseDate= Date.newInstance(2025, 12, 12);
            lstOpp[2].CloseDate= Date.newInstance(2025, 12, 12);
            lstOpp[3].CloseDate= Date.newInstance(2025, 12, 12);            
            lstOpp[4].CloseDate= Date.newInstance(2025, 12, 12);

            insert lstOpp;
        }
           
    }

    @isTest public static void test1() { // run batch usual method
        System.runAs(lstUser[0]) {

            Test.StartTest();  
                BAT26_ClassCapacityUpdate batchObj = new BAT26_ClassCapacityUpdate();
                Database.executeBatch(batchObj , 10);
            Test.StopTest();

            List<Class__c> lstInsertedClassClass= [SELECT Id, Name, SchoolName__c, SchoolName__r.Reference_Date__c, (SELECT Id, Name, StartDate__c, EndDate__c, CapacityUsed__c, CapacityTotal__c, CapacityAvailable__c, CurrentYear__c,EnrolmentYear__c  FROM Class_Capacities__r ORDER BY EndDate__c Desc), (SELECT Id, StageName, Enrolment_Year__c,EnrolledStartDate__c FROM Opportunities1__r) FROM Class__c WHERE SchoolName__c != null AND SchoolName__r.IsNAESchool__c = true];
            System.assertEquals(2, lstInsertedClassClass[0].Class_Capacities__r[0].CapacityUsed__c);
            System.assertEquals(1, lstInsertedClassClass[1].Class_Capacities__r[0].CapacityUsed__c);

        
        }
    }

    @isTest public static void test2() { // on update
        System.runAs(lstUser[0]) {

            Test.StartTest();  
                lstOpp[4].StageName = AP_Constant.oppStageNameAcceptance;
                update lstOpp;
            Test.StopTest();

            List<Class__c> lstInsertedClassClass= [SELECT Id, Name, SchoolName__c, SchoolName__r.Reference_Date__c, (SELECT Id, Name, StartDate__c, EndDate__c, CapacityUsed__c, CapacityTotal__c, CapacityAvailable__c, CurrentYear__c,EnrolmentYear__c  FROM Class_Capacities__r ORDER BY EndDate__c Desc), (SELECT Id, StageName, Enrolment_Year__c,EnrolledStartDate__c FROM Opportunities1__r) FROM Class__c WHERE SchoolName__c != null AND SchoolName__r.IsNAESchool__c = true];
            System.assertEquals(2, lstInsertedClassClass[0].Class_Capacities__r[0].CapacityUsed__c);
            System.assertEquals(2, lstInsertedClassClass[1].Class_Capacities__r[0].CapacityUsed__c);
        }
    }

    @isTest public static void test3() { // on update
        System.runAs(lstUser[0]) {

            Test.StartTest();  
                lstOpp[3].Class__c = null;
                lstOpp[3].YearGrade__c = null;
                update lstOpp;
            Test.StopTest();

            List<Class__c> lstInsertedClassClass= [SELECT Id, Name, SchoolName__c, SchoolName__r.Reference_Date__c, (SELECT Id, Name, StartDate__c, EndDate__c, CapacityUsed__c, CapacityTotal__c, CapacityAvailable__c, CurrentYear__c,EnrolmentYear__c  FROM Class_Capacities__r ORDER BY EndDate__c Desc), (SELECT Id, StageName, Enrolment_Year__c,EnrolledStartDate__c FROM Opportunities1__r) FROM Class__c WHERE SchoolName__c != null AND SchoolName__r.IsNAESchool__c = true];
            System.assertEquals(2, lstInsertedClassClass[0].Class_Capacities__r[0].CapacityUsed__c);
            System.assertEquals(1, lstInsertedClassClass[1].Class_Capacities__r[0].CapacityUsed__c);
        }
    }

    @isTest public static void test4() { // on update
        System.runAs(lstUser[0]) {

            Test.StartTest();  
                lstOpp[0].Class__c = null;
                lstOpp[0].YearGrade__c = null;
                lstOpp[1].Class__c = null;
                lstOpp[1].YearGrade__c = null;
                lstOpp[2].Class__c = null;
                lstOpp[2].YearGrade__c = null;
                lstOpp[3].Class__c = null;
                lstOpp[3].YearGrade__c = null;
                lstOpp[4].Class__c = null;
                lstOpp[4].YearGrade__c = null;
            update lstOpp;
            Test.StopTest();

            List<Class__c> lstInsertedClassClass= [SELECT Id, Name, SchoolName__c, SchoolName__r.Reference_Date__c, (SELECT Id, Name, StartDate__c, EndDate__c, CapacityUsed__c, CapacityTotal__c, CapacityAvailable__c, CurrentYear__c,EnrolmentYear__c  FROM Class_Capacities__r ORDER BY EndDate__c Desc), (SELECT Id, StageName, Enrolment_Year__c,EnrolledStartDate__c FROM Opportunities1__r) FROM Class__c WHERE SchoolName__c != null AND SchoolName__r.IsNAESchool__c = true];
            System.assertEquals(0, lstInsertedClassClass[0].Class_Capacities__r[0].CapacityUsed__c);
            System.assertEquals(0, lstInsertedClassClass[1].Class_Capacities__r[0].CapacityUsed__c);
        }
    }
}