force-app/main/default/objects/Account.object
<CustomObject>
    <fields>
        <fullName>School__c</fullName>
        <description>Copies the value of SchoolText (which is a workflow copying from School Formula). A little long winded solution to avoid bigger changes in the Teacher/Parent portal.</description>
        <formula>SchoolText__pc</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>School</label>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice_Statement__c.object
<CustomObject>
    <fields>
        <fullName>Currency__c</fullName>
        <label>Currency</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Payer__c</fullName>
        <label>Parent/Company</label>
        <lookupFilter>
            <active>false</active>
            <booleanFilter>1 OR 2</booleanFilter>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Company</value>
            </filterItems>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Parent</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Invoices</relationshipLabel>
        <relationshipName>Invoice_Statements1</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>School__c</fullName>
        <label>School</label>
        <length>32</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Xero_Key__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contract Setup</label>
        <referenceTo>Xero_Key__c</referenceTo>
        <relationshipLabel>Invoices</relationshipLabel>
        <relationshipName>Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Invoice</label>
    <nameField>
        <displayFormat>{YY}-{00000}</displayFormat>
        <label>Salesforce UID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/School__c.object
<CustomObject>
    <label>School</label>
    <nameField>
        <label>School Code/UID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Schools</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Xero_Key__c.object
<CustomObject>
    <fields>
        <fullName>Consumer_Key__c</fullName>
        <label>Consumer Key</label>
        <length>32</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Contract Setup</label>
    <nameField>
        <label>Contract Setup</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contract Setup</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/InvoiceUpdateFromXeroControllerTest.cls
@isTest
private class InvoiceUpdateFromXeroControllerTest {
    
    @isTest static void testPositive() {
        Xero_Key__c key = new Xero_Key__c();
        key.Name = 'Kuala Lumpur';
        key.Consumer_Key__c = 'test';
        insert key;

        Account payerAcc = new Account(name='acc');
        insert payerAcc;

        Invoice_Statement__c inv = new Invoice_Statement__c();
        inv.Currency__c = 'EUR';
        inv.School__c = key.Name;
        inv.Payer__c = payerAcc.Id;
        insert inv;

        Test.startTest();

        PageReference testPage = Page.InvoiceUpdateFromXero;
        testPage.getParameters().put('id', inv.Id);
        Test.setCurrentPage(testPage);

        ApexPages.StandardController ctl = new ApexPages.StandardController(inv);
        InvoiceUpdateFromXeroController ext = new InvoiceUpdateFromXeroController(ctl);

        sfXero.XeroAPI.startTesting();
        PageReference redirect = ext.doUpdate();
        System.assertNotEquals(null, redirect);
        sfXero.XeroAPI.stopTesting();

        Test.stopTest();
    }

    @isTest static void testException() {
        Xero_Key__c key = new Xero_Key__c();
        key.Name = 'Kuala Lumpur';
        key.Consumer_Key__c = 'test';
        insert key;

        Account payerAcc = new Account(name='acc');
        insert payerAcc;

        Invoice_Statement__c inv = new Invoice_Statement__c();
        inv.Currency__c = 'EUR';
        inv.School__c = key.Name;
        inv.Payer__c = payerAcc.Id;
        insert inv;

        Test.startTest();

        PageReference testPage = Page.InvoiceUpdateFromXero;
        testPage.getParameters().put('id', inv.Id);
        Test.setCurrentPage(testPage);

        ApexPages.StandardController ctl = new ApexPages.StandardController(inv);
        InvoiceUpdateFromXeroController ext = new InvoiceUpdateFromXeroController(ctl);

        // deleting the invoice causes an exception
        delete inv;

        sfXero.XeroAPI.startTesting();
        PageReference redirect = ext.doUpdate();
        system.assertEquals(null, redirect);
        sfXero.XeroAPI.stopTesting();

        Test.stopTest();
    }
}