force-app/main/default/objects/Account.object
<CustomObject>
    <fields>
        <fullName>School__c</fullName>
        <description>Copies the value of SchoolText (which is a workflow copying from School Formula). A little long winded solution to avoid bigger changes in the Teacher/Parent portal.</description>
        <formula>SchoolText__pc</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>School</label>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>School__c</fullName>
        <formula>Account.SchoolText__pc</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>School</label>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/School__c.object
<CustomObject>
    <label>School</label>
    <nameField>
        <label>School Code/UID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Schools</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/School__c/fields/AdmissionsQueueCoordinator__c.field-meta.xml
<CustomField>
    <fullName>AdmissionsQueueCoordinator__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>The person named in this field is who the Online Forms will be assigned too.</inlineHelpText>
    <label>Admissions Queue Coordinator</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Schools</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/User.object
<CustomObject>
    <fields>
        <fullName>School__c</fullName>
        <label>School</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>The British Schools Foundation</fullName>
                </value>
                <value>
                    <fullName>The British School of Guangzhou</fullName>
                </value>
                <value>
                    <fullName>The British School of Nanjing</fullName>
                </value>
                <value>
                    <fullName>The British International School of Marbella</fullName>
                </value>
                <value>
                    <fullName>The British School of Navarra</fullName>
                </value>
                <value>
                    <fullName>The British School of Tashkent</fullName>
                </value>
                <value>
                    <fullName>The British College of Brazil</fullName>
                </value>
                <value>
                    <fullName>The British International School of Kuala Lumpur</fullName>
                </value>
                <value>
                    <fullName>The International School of Moscow</fullName>
                </value>
                <value>
                    <fullName>Nord Anglia International School Manila</fullName>
                </value>
                <value>
                    <fullName>King&apos;s College Beijing</fullName>
                </value>
                <value>
                    <fullName>The British School Yangon</fullName>
                </value>
                <value>
                    <fullName>Ukraine International School</fullName>
                </value>
                <value>
                    <fullName>The New York International School</fullName>
                </value>
                <value>
                    <fullName>The British School of Brasilia</fullName>
                </value>
                <value>
                    <fullName>NAE</fullName>
                </value>
                <value>
                    <fullName>The British International School Yangon</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/classes/BAT29_UpdateOppOriginalOwner_TEST.cls
/**
 * @description       : BAT29 Test Class
 * @author            : Spoon Consulting
 * @group             : 
 * @last modified on  : 02-12-2021
 * @last modified by  : Spoon Consulting
 * Modifications Log 
 * Ver   Date         Author             Modification
 * 1.0   02-12-2021   YRA                Initial Version
**/
@isTest
public with sharing class BAT29_UpdateOppOriginalOwner_TEST {
    static List<User> lstUser;
    static List<Account> lstAcc;
    static List<Opportunity> lstOpp;
    static List<School__c> lstSchool;
    static Map<String,Id> mapRecordType;

    static {
        //creating user
        mapRecordType = AP_Constant.getDeveloperIdMap(new Set<String>{AP_Constant.oppObject});
        lstUser = new List<User>{TestFactory.createUser('Test', TestFactory.getProfileAdminId()),
                                TestFactory.createUser('Test2', TestFactory.getProfileAdminId())
        };
        insert lstUser;
        
        System.runAs(lstUser[0]){
            lstSchool = new List<School__c>{
                TestFactory.createSchool('TestSchool', 'Mauritius', false, 'TST')
            };
            lstSchool[0].AdmissionsQueueCoordinator__c = lstUser[0].Id;
            insert lstSchool;
            //creating account
            lstAcc = new List<Account>{TestFactory.createAccount('test')};
            insert lstAcc;
            //creating opportunity
            lstOpp= new List<Opportunity>{
                TestFactory.createOpportunity('testopp1', lstAcc[0].Id, AP_Constant.oppStageEnquiry,mapRecordType.get(AP_Constant.oppRecordTypeEnrolment), lstSchool[0].Id),
                TestFactory.createOpportunity('testopp2', lstAcc[0].Id, AP_Constant.oppStageEnquiry,mapRecordType.get(AP_Constant.oppRecordTypeEnrolment), lstSchool[0].Id)
            };
			lstOpp[0].OwnerId =lstUser[0].Id;
            lstOpp[1].OwnerId =lstUser[0].Id;
			lstOpp[1].OriginalOwner__c =lstUser[1].Id;
            insert lstOpp;    
        }
    }
	
	@isTest
    static void testUpdateOriginalOwnerField(){
	    System.runAs(lstUser[0]) {
            Test.StartTest();  
            BAT29_UpdateOppOriginalOwner batchObj = new BAT29_UpdateOppOriginalOwner();
            Database.executeBatch(batchObj , 10);
            Test.StopTest();
            List<Opportunity> lstUpdatedOpp = [SELECT  id,OwnerId, OriginalOwner__c FROM Opportunity];
            System.assertEquals(lstUpdatedOpp[0].OriginalOwner__c,lstOpp[0].OwnerId);   
	    }
    }

    @isTest
    static void testUpdateOriginalOwnerField2(){
	    System.runAs(lstUser[0]) {
            Test.StartTest();  
            BAT29_UpdateOppOriginalOwner batchObj = new BAT29_UpdateOppOriginalOwner();
            Database.executeBatch(batchObj , 10);
            Test.StopTest();
            List<Opportunity> lstUpdatedOpp = [SELECT  id,OwnerId, OriginalOwner__c FROM Opportunity];
            System.assertEquals(lstUpdatedOpp[1].OriginalOwner__c,lstUser[1].Id);   
	    }
    }

}