force-app/main/default/objects/Account.object
<CustomObject>
    <fields>
        <fullName>School__c</fullName>
        <description>Copies the value of SchoolText (which is a workflow copying from School Formula). A little long winded solution to avoid bigger changes in the Teacher/Parent portal.</description>
        <formula>SchoolText__pc</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>School</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Send_School_Kompanion_Outbound_Message__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Send School Kompanion Outbound Message</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Main_Parent_File__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Family File</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Value does not exist or is not a parent record.</errorMessage>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Parent</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Additional Parents &amp; Student Academic Files</relationshipLabel>
        <relationshipName>Emails</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>School__c</fullName>
        <formula>Admissions_File__r.School__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>School</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Send_School_Kompanion_Outbound_Message__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Send School Kompanion Outbound Message</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Trigger_Time_Based_Send_to_Kompanion__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Checked by means of the daily batch job that sends new students to Kompanion 14 days before their start date. Subsequently triggers a time-based workflow rule that will send the related Parent Account and Additional Parent records to Kompanion to accompany the recently sent student record</description>
        <label>Trigger Time-Based Send to Kompanion</label>
        <type>Checkbox</type>
    </fields>
    <recordTypes>
        <fullName>Additional_Parent</fullName>
        <active>true</active>
        <label>Additional Parent</label>
    </recordTypes>
    <recordTypes>
        <fullName>Contact</fullName>
        <active>true</active>
        <label>Contact</label>
    </recordTypes>
    <recordTypes>
        <fullName>Student</fullName>
        <active>true</active>
        <label>Student Academic File</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>EAL_Status_Change_to_Kompanion__c</fullName>
        <description>Result checked daily, by means of a batch job, to trigger date related updates in School Kompanion where formula evaluates to TRUE</description>
        <formula>IF(  
   AND(
       EAL_Start_Date__c &lt;= TODAY(), 
       OR(
          EAL_End_Date__c &gt;= TODAY(),
          ISBLANK(EAL_End_Date__c)
          )
       ), 
   &quot;Current&quot;,
   IF(
      AND(
          EAL_Start_Date__c &gt; TODAY(), 
          NOT(ISBLANK(EAL_Start_Date__c))
          ), 
      &quot;Future&quot;,
      IF(
         AND(
             NOT(ISBLANK(EAL_End_Date__c)),
             EAL_End_Date__c &lt; TODAY() 
             ), 
         &quot;Finished&quot;,
         &quot;No EAL&quot;
         )
      )
   ) 

!=

IF(  
   AND(
       EAL_Start_Date__c &lt;= TODAY()-1, 
       OR(
          EAL_End_Date__c &gt;= TODAY()-1,
          ISBLANK(EAL_End_Date__c)
          )
       ), 
   &quot;Current&quot;,
   IF(
      AND(
          EAL_Start_Date__c &gt; TODAY()-1, 
          NOT(ISBLANK(EAL_Start_Date__c))
          ), 
      &quot;Future&quot;,
      IF(
         AND(
             NOT(ISBLANK(EAL_End_Date__c)),
             EAL_End_Date__c &lt; TODAY()-1 
             ), 
         &quot;Finished&quot;,
         &quot;No EAL&quot;
         )
      )
   )</formula>
        <label>EAL Status Change to Kompanion</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>On_Roll_Change_to_Kompanion__c</fullName>
        <description>Result checked daily, by means of a batch job, to trigger date related updates in School Kompanion where formula evaluates to TRUE</description>
        <formula>School_Kompanion_On_Roll__c !=

IF(
   OR( 
      Kompanion_Keep_On_Roll_Formula__c = TRUE, 
      AND(
          Make_Off_Roll_In_Kompanion__c != TRUE,
          CloseDate - 14 &lt;= TODAY()-1,
          CloseDate &gt; TODAY()-1,
          OR(
             AND(
                 TEXT(Add_to_Register__c)=&quot;Yes&quot;, 
                 TEXT(StageName) = &quot;A/ Deposit&quot;
                 ),
             TEXT(StageName) = &quot;Enrolled&quot;
             )
          )
      ),
   &quot;Yes&quot;,
   IF(
      AND(
          Make_Off_Roll_In_Kompanion__c != TRUE,
          CloseDate &lt;= TODAY()-1,
          OR(
             AND(
                 TEXT(Add_to_Register__c)=&quot;Yes&quot;, 
                 TEXT(StageName) = &quot;A/ Deposit&quot;
                 ),
             TEXT(StageName) = &quot;Enrolled&quot;
             )
          ),
      &quot;Yes&quot;,
      IF(
         OR(
            Make_Off_Roll_In_Kompanion__c = TRUE,
            TEXT(StageName) = &quot;Left&quot;,
            AND(
                Has_Been_Enrolled__c = TRUE,
                School_Kompanion_Student_Created__c = TRUE
                )
            ),
         &quot;No&quot;,
         &quot;Doesn&apos;t Qualify&quot;
         )
      )
   )</formula>
        <label>On Roll Change to Kompanion</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Qualifies_for_SK_Outbound_Message__c</fullName>
        <description>BEN 02-Sep-17: When launching for a new school this formula will need to be edited to include specific student numbers together with &apos;NOT(CONTAINS(Student_Number_New__c, &quot;-&quot;))&apos; in an or statement in cases where left students have a student number that contains a &quot;-&quot; but still need to be sent to Kompanion as they are left students who have joined another school, not rejoined the current one. For the purpose of student creation/sync with Kompanion the &quot;-&quot; suffix is removed from the SF student number to create a Kompanion specific student number that is numeric only.</description>
        <formula>AND(
    /*OR(
       CONTAINS(Student_Number_New__c, &quot;-0&quot;), Commented out on 23/02/2017 as SK would strip the -0 out as student ID must be an integer and a newer record e.g. change of campus could start overwriting details of an existing, active record in the current campus */
    NOT(CONTAINS(Student_Number_New__c, &quot;-&quot;)),
    School_Kompanion_On_Roll__c != &quot;Doesn&apos;t Qualify&quot;,
    AccountId != null,
    OR(
       CONTAINS(TEXT(Test_Student_Type__c), &quot;School Kompanion&quot;),
       School__c = &quot;The British School of Brasilia&quot;,
       School__c = &quot;The British International School of Kuala Lumpur&quot;
       )
    )</formula>
        <label>Qualifies for SK Outbound Message?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>School__c</fullName>
        <formula>Account.SchoolText__pc</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>School</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Send_School_Kompanion_Outbound_Message__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Checked and Unchecked by means of a batch job running every day, based on the value in certain Salesforce time-based formula fields changing since the previous day</description>
        <label>Send School Kompanion Outbound Message</label>
        <type>Checkbox</type>
    </fields>
    <recordTypes>
        <fullName>Student</fullName>
        <active>true</active>
        <businessProcess>Standard Admissions Process</businessProcess>
        <label>Student</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/School__c.object
<CustomObject>
    <label>School</label>
    <nameField>
        <label>School Code/UID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Schools</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/Batch_SendKompanionOutboundMessage.cls
/*
Daily batch job for pushing/updating records that newly meet criteria (based on date/time) to School Kompanion. Spec as follows:
1.Set ‘Opportunity.Send_School_Kompanion_Outbound_Message__c’ = TRUE WHERE (‘Opportunity.Qualifies_for_SK_Outbound_Message__c’ = TRUE AND (‘Opportunity.EAL_Status_Change_to_Kompanion__c’ = TRUE OR ‘Opportunity.On_Roll_Change_to_Kompanion__c’ = TRUE))
2.Set ‘Contact.Trigger_Time_Based_Send_to_Kompanion__c = TRUE‘ for Additional Parent record OR ‘Account.Trigger_Time_Based_Send_to_Kompanion__pc’ = TRUE for parent account records related to the opportunities updated in part ‘a.’ above.
3.All ‘Send_School_Kompanion_Outbound_Message__c’ fields on all objects will be set to FALSE by a workflow rule/field update that’s already in place and active in both production and sandbox, so no need to worry about this within the job itself.
4. Schedule job to run aforementioned Apex class as ‘Group Administrator’ daily @ 08:00 MYT

*/
global with sharing class Batch_SendKompanionOutboundMessage implements Database.Batchable<sObject>, Database.Stateful{
    global string errorMessage {get;set;}
    global boolean errorOccured {get;set;}
    global set<Id> studentIds {get;set;}
    global Batch_SendKompanionOutboundMessage(){
    	initialize();
    }
    
    global Batch_SendKompanionOutboundMessage(set<Id> sIds){
    	initialize();
    	studentIds = sIds;
    }
    
    private void initialize(){
    	errorMessage = 'Errors Occurred during the Batch_SendKompanionOutboundMessage batch process. The records that could not be updated will not have triggered an outbound message to School Kompanion and records may now be out of sync. The record IDs and error messages are as follows: <br/>';
    	errorOccured = false;
    }
    
    global Database.Querylocator start(Database.BatchableContext BC){
        string query = 'select Id, AccountId from Opportunity where Qualifies_for_SK_Outbound_Message__c = TRUE AND (EAL_Status_Change_to_Kompanion__c = TRUE OR On_Roll_Change_to_Kompanion__c = TRUE) order by School__c';
        if(studentIds != null){query = 'select Id, AccountId from Opportunity where Qualifies_for_SK_Outbound_Message__c = TRUE AND Id =: studentIds';}
        if(Test.isRunningTest()){query = 'select Id, AccountId from Opportunity limit 1';}
        return Database.getQueryLocator(query);
    }
    
    global void execute(Database.BatchableContext BC, List<sObject> scope){
    	list<Opportunity> studentList = scope;
    	list<Contact> additionalParentsToBeUpdated = new list<Contact>();
    	list<Account> parentsToBeUpdated = new list<Account>();
    	list<Opportunity> studentsToBeUpdated = new list<Opportunity>();
    	//fetch associated additonal parents
    	set<Id> accountIds =  new set<Id>();
    	for(Opportunity student:studentList){
    		accountIds.add(student.AccountId);
    	}
    	map<Id,Account> parentMap = new map<Id,Account>([Select a.Id, (Select Id From Emails__r where RecordType.DeveloperName = 'Additional_Parent') From Account a where Id IN:accountIds]);
    	//check fields
    	for(Opportunity student:studentList){
    		student.Send_School_Kompanion_Outbound_Message__c = true;
    		studentsToBeUpdated.add(student);
    		Account parentAccount = new Account(Id=student.AccountId);
    		parentAccount.Trigger_Time_Based_Send_to_Kompanion__pc = true;
    		parentsToBeUpdated.add(parentAccount);
    		for(Contact additionalParent:parentMap.get(student.AccountId).Emails__r){
    			additionalParentsToBeUpdated.add(new Contact(Id=additionalParent.Id, Trigger_Time_Based_Send_to_Kompanion__c = true));
    		}
    		//assumption batch size as 1, do update now instead of bulk
    		System.Savepoint sp;
    		try{
    			sp = Database.setSavepoint();
    			update studentsToBeUpdated;
    			update parentsToBeUpdated;
    			if(additionalParentsToBeUpdated.size() > 0){
    				update additionalParentsToBeUpdated;
    			}
    		}catch(Exception e){
    			Database.rollback(sp);
    			errorMessage += '<br/> Failed to update student: '+student.Id+' ('+e.getMessage()+') <br/>';
    			errorOccured = true;
    		}
    		
    	}
    }
    
    global void finish(Database.BatchableContext BC){
   		if(errorOccured || Test.isRunningTest()){
   		   Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
           set<String> emailSet = new set<String>();
           emailSet.add('ben.hails@britishschools.co.uk');
           list<String> toAddresses =  new list<String>();
           for(string e:emailSet){
            toAddresses.add(e);
           }
           string emailText = '';
           mail.setToAddresses(toAddresses);
           mail.setSubject('Error in Batch_SendKompanionOutboundMessage - '+datetime.now());
           emailText += errorMessage;
           mail.setHtmlBody(emailText);
           if(!Test.isRunningTest()){Messaging.sendEmail(new Messaging.SingleEmailMessage[] { mail });} 
   		}	 	
    }
    
    //static method for button
    webService static string sendStudentToKompanion(list<Id> sIds) { 
        string message = 'Request was submitted successfully. You should receive an email only if any error occurs in the process.';
        try{
        	set<Id> temp = new set<Id>();
        	for(Id sid:sIds){
        		temp.add(sid);
        	}
        	Batch_SendKompanionOutboundMessage b = new Batch_SendKompanionOutboundMessage(temp);
        	database.executeBatch(b,1);
        }catch(Exception e){
        	message = 'Failed to process request. Error message: '+e.getMessage();
        }
        return message;
        
    }
    
}