force-app/main/default/objects/Account.object
<CustomObject>
    <fields>
        <fullName>School__c</fullName>
        <description>Copies the value of SchoolText (which is a workflow copying from School Formula). A little long winded solution to avoid bigger changes in the Teacher/Parent portal.</description>
        <formula>SchoolText__pc</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>School</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <formula>IF( 
   Count_Active_Contracts__c &gt; 0, 
   &quot;Employed&quot;,
   IF(
      Count_Signed_Not_started_Contracts__c &gt; 0,
      &quot;Signed-On&quot;,
      IF(
         Count_Expired_Contracts__c &gt; 0,
         &quot;Left&quot;, 
         IF( 
            Unsuccessful_Applicant__c = TRUE, 
            &quot;Unsuccessful Applicant&quot;, 
            &quot;Applicant&quot;
            )
         )
      )
   )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Status</label>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/ApplicationDocument__c/ApplicationDocument__c.object-meta.xml
<CustomObject>
    <label>Application Document</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Application Documents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ApplicationDocument__c/fields/School__c.field-meta.xml
<CustomField>
    <fullName>School__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>School</label>
    <referenceTo>School__c</referenceTo>
    <relationshipLabel>Application Documents</relationshipLabel>
    <relationshipName>ApplicationDocuments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ApplicationDocument__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Enquiry</fullName>
            </value>
            <value>
                <fullName>Application</fullName>
            </value>
            <value>
                <fullName>Acceptance</fullName>
            </value>
            <value>
                <fullName>Enrolled</fullName>
            </value>
            <value>
                <fullName>Visit</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>School__c</fullName>
        <formula>Admissions_File__r.School__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>School</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <formula>IF(AND(TEXT(Admissions_File__r.Add_to_Register__c)=&quot;Yes&quot;, TEXT(Admissions_File__r.StageName) = &quot;A/ Deposit&quot;), &quot;Enrolled&quot;, Text(Admissions_File__r.StageName))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Stage</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Employed</fullName>
                </value>
                <value>
                    <fullName>Applicant</fullName>
                </value>
                <value>
                    <fullName>Left</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Contact</fullName>
        <active>true</active>
        <label>Contact</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/DocumentChecklist__c/DocumentChecklist__c.object-meta.xml
<CustomObject>
    <label>Document Checklist</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Document Checklists</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/DocumentChecklist__c/fields/ApplicationDocument__c.field-meta.xml
<CustomField>
    <fullName>ApplicationDocument__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Application Document</label>
    <referenceTo>ApplicationDocument__c</referenceTo>
    <relationshipLabel>Document Checklists</relationshipLabel>
    <relationshipName>DocumentChecklists</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DocumentChecklist__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Document Checklists</relationshipLabel>
    <relationshipName>DocumentChecklists</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/DocumentChecklist__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Enquiry</fullName>
            </value>
            <value>
                <fullName>Application</fullName>
            </value>
            <value>
                <fullName>Acceptance</fullName>
            </value>
            <value>
                <fullName>Enrolled</fullName>
            </value>
            <value>
                <fullName>Visit</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DocumentChecklist__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Requested</fullName>
                <default>true</default>
                <label>Requested</label>
            </value>
            <value>
                <fullName>Received</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>School__c</fullName>
        <formula>Account.SchoolText__pc</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>School</label>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/School__c.object
<CustomObject>
    <label>School</label>
    <nameField>
        <label>School Code/UID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Schools</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/User.object
<CustomObject>
    <fields>
        <fullName>School__c</fullName>
        <label>School</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>The British Schools Foundation</fullName>
                </value>
                <value>
                    <fullName>The British School of Guangzhou</fullName>
                </value>
                <value>
                    <fullName>The British School of Nanjing</fullName>
                </value>
                <value>
                    <fullName>The British International School of Marbella</fullName>
                </value>
                <value>
                    <fullName>The British School of Navarra</fullName>
                </value>
                <value>
                    <fullName>The British School of Tashkent</fullName>
                </value>
                <value>
                    <fullName>The British College of Brazil</fullName>
                </value>
                <value>
                    <fullName>The British International School of Kuala Lumpur</fullName>
                </value>
                <value>
                    <fullName>The International School of Moscow</fullName>
                </value>
                <value>
                    <fullName>Nord Anglia International School Manila</fullName>
                </value>
                <value>
                    <fullName>King&apos;s College Beijing</fullName>
                </value>
                <value>
                    <fullName>The British School Yangon</fullName>
                </value>
                <value>
                    <fullName>Ukraine International School</fullName>
                </value>
                <value>
                    <fullName>The New York International School</fullName>
                </value>
                <value>
                    <fullName>The British School of Brasilia</fullName>
                </value>
                <value>
                    <fullName>NAE</fullName>
                </value>
                <value>
                    <fullName>The British International School Yangon</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/classes/AP11_OppCheckRequiredDocument_TEST.cls
/**************************************************************************************
-- - Author        : Spoon Consulting
-- - Description   : Test class for AP11_OppCheckRequiredDocument
--
-- Maintenance History: 
--
-- Date         Name  Version  Remarks 
-- -----------  ----  -------  ------------------------------------------------------- 
-- 17-JULY-2018  AMU   1.0     Initial Version
-- 08-AUG-2018   KZE   1.1     Added test method
--------------------------------------------------------------------------------------
**************************************************************************************/
@isTest
public with sharing class AP11_OppCheckRequiredDocument_TEST {
    static Map<string,Id> mapRecordType = new Map<String, Id>();
    static User testUserAdmin;
    static Account account;
    static List<Contact> lstContact;
    static List<School__c> lstSchool;
    static List<ApplicationDocument__c> lstAppDoc;
    static List<Opportunity> lstOpp;
    static List<DocumentChecklist__c> lstDocChecklist;
    static Opportunity oppToTest;
    static {
        //creating user
        testUserAdmin = TestFactory.createUser('testUserAdmin',TestFactory.getProfileAdminId());
        insert testUserAdmin;

        System.runAs(testUserAdmin){
            mapRecordType = AP_Constant.getDeveloperIdMap(new Set<String>{AP_Constant.oppObject, AP_Constant.conObject});

            //creating account
            account = TestFactory.createAccount('Henry Family');
            insert account;

            //creating school
            lstSchool = new List<School__c> {
                TestFactory.createSchool('Petit Verger School', 'Petit Verger', false, 'PVS'),
                TestFactory.createSchool('Le Petit Pouce Elementary School', 'Vivéa Business Park', false, 'PPE')
            };
            insert lstSchool;

            // creating application document
            lstAppDoc = new List<ApplicationDocument__c> {
                TestFactory.createApplicationDoc('Birth Certificate', lstSchool[0].Id, true, AP_Constant.docChklstStageApplication), //PVS //Document checklist order : 1
                TestFactory.createApplicationDoc('Transcript', lstSchool[0].Id, false, AP_Constant.docChklstStageAcceptance), //PVS //Document checklist order : 5
                TestFactory.createApplicationDoc('Passport copy', lstSchool[0].Id, null, null), //PVS //Document checklist order : 3
                TestFactory.createApplicationDoc('Health report' , lstSchool[1].Id, true, null), //PPE //Document checklist order : 2
                TestFactory.createApplicationDoc('Transfert certificate', lstSchool[1].Id, false, AP_Constant.docChklstStageEnrolled), //PPE //Document checklist order : 6
                TestFactory.createApplicationDoc('Resident proof', lstSchool[1].Id, null, AP_Constant.docChklstStageAcceptance), //PPE //Document checklist order : 4
                TestFactory.createApplicationDoc('Application fee', lstSchool[1].Id, false, AP_Constant.docChklstStageApplication) //PPE //Document checklist order : 0
            };
            insert lstAppDoc;

            //creating opportunities
            //creating primary contact in account for opportunity
            lstContact = new List<Contact>{
                TestFactory.createContact('parent1', account.Id, mapRecordType.get(AP_Constant.conRecordTypeParent))
                ,TestFactory.createContact('child1', account.Id, mapRecordType.get(AP_Constant.conRecordTypeChild))};
            insert lstContact; 
            
            account.PrimaryContact__c = lstContact[0].Id;
            update account; 

            lstOpp = new List<Opportunity> {
                TestFactory.createOpportunity('Junior Henry - Enrolment', account.Id, AP_Constant.oppStageNameApplication,
                                              mapRecordType.get(AP_Constant.oppRecordTypeEnrolment), lstSchool[0].Id), //PVS
                TestFactory.createOpportunity('Joe Henry - Enrolment', account.Id, AP_Constant.oppStageNameEnquiry,
                                              mapRecordType.get(AP_Constant.oppRecordTypeEnrolment), lstSchool[0].Id), //PVS
                TestFactory.createOpportunity('Lucy Henry - Enrolment', account.Id, AP_Constant.oppStageNameEnquiry,
                                              mapRecordType.get(AP_Constant.oppRecordTypeEnrolment), lstSchool[1].Id) //PPE
            };

            lstOpp[0].Child__c = lstContact[1].Id;
            lstOpp[1].Child__c = lstContact[1].Id;
            lstOpp[2].Child__c = lstContact[1].Id;
            insert lstOpp;
        }
    }

    @isTest
    static void checkReqDocChecklistFailTest() {
        lstOpp[0].StageName = AP_Constant.oppStageNameAcceptance;
        lstOpp[0].AssessmentOutcome__c = AP_Constant.oppAssessOutcomePassed;
        System.runAs(testUserAdmin){            
            Test.startTest();
            try {
                update lstOpp;
            } catch(Exception e) {
                System.assertNotEquals(e.getMessage(), null);
            }               
            Test.stopTest();
        }
    }

    @isTest
    static void checkReqDocChecklistPassTest() {
        lstDocChecklist = [SELECT Id, Name, Stage__c, Status__c, Required__c FROM DocumentChecklist__c 
                                                 WHERE Opportunity__r.id =: lstOpp[0].Id ORDER BY Name ASC ];

        for(DocumentChecklist__c doc: lstDocChecklist) {
            doc.Status__c = AP_Constant.docChklstStatusSubmitted;
        }

        update lstDocChecklist;

        lstOpp[0].StageName = AP_Constant.oppStageNameAcceptance;
        lstOpp[0].AssessmentOutcome__c = AP_Constant.oppAssessOutcomePassed;
        System.runAs(testUserAdmin){            
            Test.startTest();
            try {
                update lstOpp;
            } catch(Exception e) {
                System.assertEquals(e.getMessage(), null);
            }
                
            Test.stopTest();
        }
    }
    @isTest
    static void checkReqDocForClosedLost() {
        lstOpp[0].StageName = AP_Constant.oppStageNameLost;
        lstOpp[0].LostDeniedOnHoldReason__c = 'Financial';
        lstOpp[0].ReasonLostCategory__c = 'Price';
        
        System.runAs(testUserAdmin){            
            Test.startTest();
            try {
                update lstOpp;
            } catch(Exception e) {
                System.assertEquals(e.getMessage(), null);
            }
                
            Test.stopTest();
        }
        
        oppToTest = [SELECT Id, Name, StageName FROM Opportunity 
                                 WHERE Id =: lstOpp[0].Id];
        System.assertEquals(oppToTest.StageName, AP_Constant.oppStageNameLost);        
    }
    @isTest
    static void checkReqDocForClosedDenied() {
        lstOpp[0].StageName = AP_Constant.oppStageNameDenied;
        lstOpp[0].LostDeniedOnHoldReason__c = AP_Constant.oppLostDeniedReasonQuotaReached;
        
        System.runAs(testUserAdmin){            
            Test.startTest();
            try {
                update lstOpp;
            } catch(Exception e) {
                System.assertEquals(e.getMessage(), null);
            }
                
            Test.stopTest();
        }
        
        oppToTest = [SELECT Id, Name, StageName FROM Opportunity 
                                 WHERE Id =: lstOpp[0].Id];
        System.assertEquals(oppToTest.StageName, AP_Constant.oppStageNameDenied);
    }
}