force-app/main/default/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Application_Date__c</fullName>
        <formula>CreatedDate</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Application Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Email_1__c</fullName>
        <description>Required so that the main email stored on the person account (contact) can be used in email alerts on the account object</description>
        <label>Copy Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Gender__c</fullName>
        <label>Gender</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Male</fullName>
                </value>
                <value>
                    <fullName>Female</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Primary_Contact__c</fullName>
        <description>Identifies which of the parents should be contacted first</description>
        <inlineHelpText>Which parent should be the first point of contact?</inlineHelpText>
        <label>Primary Contact</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>First Parent</fullName>
                    <default>true</default>
                    <label>First Parent</label>
                </value>
                <value>
                    <fullName>Second Parent</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>School__c</fullName>
        <description>Copies the value of SchoolText (which is a workflow copying from School Formula). A little long winded solution to avoid bigger changes in the Teacher/Parent portal.</description>
        <formula>SchoolText__pc</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>School</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Starting_Date__c</fullName>
        <label>Starting Date (Account)</label>
        <summarizedField>Opportunity.CloseDate</summarizedField>
        <summaryFilterItems>
            <field>Opportunity.Probability</field>
            <operation>equals</operation>
            <value>100</value>
        </summaryFilterItems>
        <summaryForeignKey>Opportunity.AccountId</summaryForeignKey>
        <summaryOperation>min</summaryOperation>
        <type>Summary</type>
    </fields>
    <recordTypes>
        <fullName>Company_Account</fullName>
        <active>true</active>
        <label>Company</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Account_Owner_Mapping__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This setting is used to determine appropriate &quot;Mass Email&quot; or &quot;Catch All&quot; account for a given Account/Opportunity Owner. Name field contains &quot;Owner Name&quot; and Account Id field contains Id of associated account.. This setting is used in Opportunity trigger.</description>
    <fields>
        <fullName>Account_Id__c</fullName>
        <inlineHelpText>Id of the corresponding &quot;Mass Email &quot; OR &quot;Catch All&quot; Account.</inlineHelpText>
        <label>Account Id</label>
        <length>20</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>School_Name__c</fullName>
        <label>School Name</label>
        <type>TextArea</type>
    </fields>
    <label>Account Owner Mapping</label>
</CustomObject>

force-app/main/default/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Class__c</fullName>
        <formula>TEXT(Admissions_File__r.Class__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Class</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Gender__c</fullName>
        <description>This field is configured in NPSP Settings &gt; Relationships &gt; Relationships as the Gender field. Do not delete this field unless you remove the reference or select another Gender field there.</description>
        <label>Gender</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Male</fullName>
                </value>
                <value>
                    <fullName>Female</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Main_Parent_File__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Family File</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Value does not exist or is not a parent record.</errorMessage>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Parent</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Additional Parents &amp; Student Academic Files</relationshipLabel>
        <relationshipName>Emails</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>School__c</fullName>
        <formula>Admissions_File__r.School__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>School</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Student_Name__c</fullName>
        <formula>IF(Admissions_File__r.Nickname__c &lt;&gt; &quot;&quot;, LastName&amp;&quot;, &quot;&amp;FirstName&amp;&quot; (&quot;&amp;Admissions_File__r.Nickname__c&amp;&quot;)&quot;,

LastName&amp;&quot;, &quot;&amp;FirstName)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Student Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Year_Group__c</fullName>
        <formula>TEXT(Admissions_File__r.Year_Group__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Year Group</label>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Additional_Parent</fullName>
        <active>true</active>
        <label>Additional Parent</label>
    </recordTypes>
    <recordTypes>
        <fullName>Contact</fullName>
        <active>true</active>
        <label>Contact</label>
    </recordTypes>
    <recordTypes>
        <fullName>Student</fullName>
        <active>true</active>
        <label>Student Academic File</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Account_Id__c</fullName>
        <formula>Account.Id</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Account Id</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Application_Date__c</fullName>
        <label>Application Date (Initial)</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Birth_Date__c</fullName>
        <label>Date of Birth</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Gender__c</fullName>
        <label>Gender</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Gender_Options</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Primary_Contact__c</fullName>
        <formula>IF(ISPICKVAL(Account.Primary_Contact__c, &quot;First Parent&quot;), &quot;First Parent&quot;, IF(ISPICKVAL(Account.Primary_Contact__c, &quot;Second Parent&quot;), &quot;Second Parent&quot;, &quot;Please complete in parent record&quot;))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Primary Contact</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>School__c</fullName>
        <formula>Account.SchoolText__pc</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>School</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Starting_Date__c</fullName>
        <label>Starting Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Student_Name__c</fullName>
        <label>Student Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Student_Surname__c</fullName>
        <label>Student Surname</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Year_Group__c</fullName>
        <label>Year Group / Grade</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>US_Year_Group_Control__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>PN1</fullName>
                </value>
                <value>
                    <fullName>PN</fullName>
                </value>
                <value>
                    <fullName>N</fullName>
                </value>
                <value>
                    <fullName>R</fullName>
                </value>
                <value>
                    <fullName>Y1</fullName>
                </value>
                <value>
                    <fullName>Y2</fullName>
                </value>
                <value>
                    <fullName>Y3</fullName>
                </value>
                <value>
                    <fullName>Y4</fullName>
                </value>
                <value>
                    <fullName>Y5</fullName>
                </value>
                <value>
                    <fullName>Y6</fullName>
                </value>
                <value>
                    <fullName>Y7</fullName>
                </value>
                <value>
                    <fullName>Y8</fullName>
                </value>
                <value>
                    <fullName>Y9</fullName>
                </value>
                <value>
                    <fullName>Y10</fullName>
                </value>
                <value>
                    <fullName>Y11</fullName>
                </value>
                <value>
                    <fullName>Y12</fullName>
                </value>
                <value>
                    <fullName>Y13</fullName>
                </value>
                <value>
                    <fullName>PK</fullName>
                </value>
                <value>
                    <fullName>K</fullName>
                </value>
                <value>
                    <fullName>G1</fullName>
                </value>
                <value>
                    <fullName>G2</fullName>
                </value>
                <value>
                    <fullName>G3</fullName>
                </value>
                <value>
                    <fullName>G4</fullName>
                </value>
                <value>
                    <fullName>G5</fullName>
                </value>
                <value>
                    <fullName>G6</fullName>
                </value>
                <value>
                    <fullName>G7</fullName>
                </value>
                <value>
                    <fullName>G8</fullName>
                </value>
                <value>
                    <fullName>G9</fullName>
                </value>
                <value>
                    <fullName>G10</fullName>
                </value>
                <value>
                    <fullName>G11</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Student</fullName>
        <active>true</active>
        <businessProcess>Standard Admissions Process</businessProcess>
        <label>Student</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/User.object
<CustomObject>
    <fields>
        <fullName>School__c</fullName>
        <label>School</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>The British Schools Foundation</fullName>
                </value>
                <value>
                    <fullName>The British School of Guangzhou</fullName>
                </value>
                <value>
                    <fullName>The British School of Nanjing</fullName>
                </value>
                <value>
                    <fullName>The British International School of Marbella</fullName>
                </value>
                <value>
                    <fullName>The British School of Navarra</fullName>
                </value>
                <value>
                    <fullName>The British School of Tashkent</fullName>
                </value>
                <value>
                    <fullName>The British College of Brazil</fullName>
                </value>
                <value>
                    <fullName>The British International School of Kuala Lumpur</fullName>
                </value>
                <value>
                    <fullName>The International School of Moscow</fullName>
                </value>
                <value>
                    <fullName>Nord Anglia International School Manila</fullName>
                </value>
                <value>
                    <fullName>King&apos;s College Beijing</fullName>
                </value>
                <value>
                    <fullName>The British School Yangon</fullName>
                </value>
                <value>
                    <fullName>Ukraine International School</fullName>
                </value>
                <value>
                    <fullName>The New York International School</fullName>
                </value>
                <value>
                    <fullName>The British School of Brasilia</fullName>
                </value>
                <value>
                    <fullName>NAE</fullName>
                </value>
                <value>
                    <fullName>The British International School Yangon</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/globalValueSets/Gender_Options.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Male</fullName>
    </customValue>
    <customValue>
        <fullName>Female</fullName>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
    </customValue>
    <customValue>
        <fullName>Prefer not to say</fullName>
    </customValue>
    <masterLabel>Gender Options</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/Test_Batch_SendKompanionOutboundMessage.cls
@isTest
private class Test_Batch_SendKompanionOutboundMessage{
    //test method for Batch_SendKompanionOutboundMessage
    static testMethod void testBatch_SendKompanionOutboundMessage1(){
       //create test data 
        //create company account account
        Account companyAccount =  new Account();
        companyAccount.Name =  'Company Account';
        companyAccount.RecordTypeId = [Select Id from RecordType where SObjectType='Account' AND DeveloperName='Company_Account'].Id;
        insert companyAccount;
        
        //create parent account account
        Account parentAccount =  new Account();
        parentAccount.FirstName =  'First Name1';
        parentAccount.LastName =  'Last Name2';
        parentAccount.PersonEmail = 'testunique1@test.com';
        parentAccount.Contact_Alternate_Email__pc = 'testunique2@test.com';
        parentAccount.RecordTypeId = [Select Id from RecordType where SObjectType='Account' AND DeveloperName='PersonAccount'].Id;
        parentAccount.Primary_Contact__c = 'First Parent';
        insert parentAccount;
        
        //create additional parent
        Contact additionalParent = new Contact();
        additionalParent.Main_Parent_File__c = parentAccount.Id;
        additionalParent.AccountId = companyAccount.Id;
        additionalParent.FirstName = 'Test';
        additionalParent.LastName = 'Additional Parent';
        additionalParent.Email = 'testhgg@test.com';
        additionalParent.RecordTypeId = [Select Id from RecordType where SObjectType='Contact' AND DeveloperName='Additional_Parent'].Id;
        insert additionalParent;
        
        //create custom setting values
        Account_Owner_Mapping__c mapping =  new Account_Owner_Mapping__c();
        mapping.Account_Id__c = companyAccount.Id;
        mapping.Name =  UserInfo.getName();
        mapping.School_Name__c = [select School__c,Id from User where Id=:UserInfo.getUserId()].School__c;
        insert mapping;
        
        //create student opportunities
        List<Opportunity> oppList =  new List<Opportunity>();
        for(integer i=1;i<5;i++){
            Opportunity o =  new Opportunity();
            o.Student_Surname__c =  'Surname'+i;
            o.Name = 'First Name'+i;
            o.Gender__c = 'Male';
            o.Year_Group__c = 'PN1';
            o.Birth_Date__c =  Date.today().addYears(-10);
            o.Application_Date__c = Date.today().addMonths(-3);
            o.Starting_Date__c =  Date.today().addMonths(-3);
            o.StageName = 'A/ Testing';
            o.AccountId = parentAccount.Id;
            //o.Payer__c = companyAccount.Id;
            //o.Email_1__c = 'test@test.com';
            o.CloseDate =  Date.today();
            o.Student_Name__c = 'SN';
            o.Class__c = 'A';
            oppList.add(o);
        }
        
        insert oppList;
        
        
        Test.startTest();
            Batch_SendKompanionOutboundMessage b = new Batch_SendKompanionOutboundMessage();
            database.executeBatch(b,1);
        Test.stopTest();
        
    }   
    
    //test method for Batch_SendKompanionOutboundMessage
    static testMethod void testBatch_SendKompanionOutboundMessage2(){
       //create test data 
        //create company account account
        Account companyAccount =  new Account();
        companyAccount.Name =  'Company Account';
        companyAccount.RecordTypeId = [Select Id from RecordType where SObjectType='Account' AND DeveloperName='Company_Account'].Id;
        insert companyAccount;
        
        //create parent account account
        Account parentAccount =  new Account();
        parentAccount.FirstName =  'First Name1';
        parentAccount.LastName =  'Last Name2';
        parentAccount.PersonEmail = 'testunique1@test.com';
        parentAccount.Contact_Alternate_Email__pc = 'testunique2@test.com';
        parentAccount.RecordTypeId = [Select Id from RecordType where SObjectType='Account' AND DeveloperName='PersonAccount'].Id;
        parentAccount.Primary_Contact__c = 'First Parent';
        insert parentAccount;
        
        //create additional parent
        Contact additionalParent = new Contact();
        additionalParent.Main_Parent_File__c = parentAccount.Id;
        additionalParent.AccountId = companyAccount.Id;
        additionalParent.FirstName = 'Test';
        additionalParent.LastName = 'Additional Parent';
        additionalParent.Email = 'testhgg@test.com';
        additionalParent.RecordTypeId = [Select Id from RecordType where SObjectType='Contact' AND DeveloperName='Additional_Parent'].Id;
        insert additionalParent;
        
        //create custom setting values
        Account_Owner_Mapping__c mapping =  new Account_Owner_Mapping__c();
        mapping.Account_Id__c = companyAccount.Id;
        mapping.Name =  UserInfo.getName();
        mapping.School_Name__c = [select School__c,Id from User where Id=:UserInfo.getUserId()].School__c;
        insert mapping;
        
        //create student opportunities
        List<Opportunity> oppList =  new List<Opportunity>();
        for(integer i=1;i<5;i++){
            Opportunity o =  new Opportunity();
            o.Student_Surname__c =  'Surname'+i;
            o.Name = 'First Name'+i;
            o.Gender__c = 'Male';
            o.Year_Group__c = 'PN1';
            o.Birth_Date__c =  Date.today().addYears(-10);
            o.Application_Date__c = Date.today().addMonths(-3);
            o.Starting_Date__c =  Date.today().addMonths(-3);
            o.StageName = 'A/ Testing';
            o.AccountId = parentAccount.Id;
            //o.Payer__c = companyAccount.Id;
            //o.Email_1__c = 'test@test.com';
            o.CloseDate =  Date.today();
            o.Student_Name__c = 'SN';
            o.Class__c = 'A';
            oppList.add(o);
        }
        
        insert oppList;
        
        
        Test.startTest();
            list<Id> temp = new list<Id>();
            temp.add(oppList[0].Id);
            Batch_SendKompanionOutboundMessage.sendStudentToKompanion(temp) ;
            
        Test.stopTest();
        
    }   
    
    //test method for Schedule_SendKompanionOutboundMessage
    static testMethod void testSchedule_SendKompanionOutboundMessage(){
       
        Test.startTest();
            Schedule_SendKompanionOutboundMessage      sh1 = new Schedule_SendKompanionOutboundMessage();
            String sch = '0 0 23 * * ?'; 
            system.schedule('Test', sch, sh1); 
            
        Test.stopTest();
        
    }   
    
    
}