force-app/main/default/objects/Account.object
<CustomObject>
    <fields>
        <fullName>School__c</fullName>
        <description>Copies the value of SchoolText (which is a workflow copying from School Formula). A little long winded solution to avoid bigger changes in the Teacher/Parent portal.</description>
        <formula>SchoolText__pc</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>School</label>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice_Statement__c.object
<CustomObject>
    <fields>
        <fullName>Currency__c</fullName>
        <label>Currency</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Payer__c</fullName>
        <label>Parent/Company</label>
        <lookupFilter>
            <active>false</active>
            <booleanFilter>1 OR 2</booleanFilter>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Company</value>
            </filterItems>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Parent</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Invoices</relationshipLabel>
        <relationshipName>Invoice_Statements1</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>School__c</fullName>
        <label>School</label>
        <length>32</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Xero_Invoice_Date__c</fullName>
        <label>Xero Invoice Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Xero_Key__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contract Setup</label>
        <referenceTo>Xero_Key__c</referenceTo>
        <relationshipLabel>Invoices</relationshipLabel>
        <relationshipName>Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Xero_Status__c</fullName>
        <label>Xero Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Xero_Value__c</fullName>
        <label>Xero Value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Invoice</label>
    <nameField>
        <displayFormat>{YY}-{00000}</displayFormat>
        <label>Salesforce UID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/School__c.object
<CustomObject>
    <label>School</label>
    <nameField>
        <label>School Code/UID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Schools</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Xero_Key__c.object
<CustomObject>
    <fields>
        <fullName>Consumer_Key__c</fullName>
        <label>Consumer Key</label>
        <length>32</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Contract Setup</label>
    <nameField>
        <label>Contract Setup</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contract Setup</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Xero_Payment__c.object
<CustomObject>
    <description>A payment recorded on an invoice. This gets queried from Xero.</description>
    <fields>
        <fullName>Currency__c</fullName>
        <formula>Invoice_Statement__r.Currency__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Currency</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Invoice_Statement__c</fullName>
        <description>Lookup to the Invoice for which this payment is associated.</description>
        <label>Invoice</label>
        <referenceTo>Invoice_Statement__c</referenceTo>
        <relationshipLabel>Payments</relationshipLabel>
        <relationshipName>Payments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>School__c</fullName>
        <formula>Invoice_Statement__r.School__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>School</label>
        <type>Text</type>
    </fields>
    <label>Payment</label>
    <nameField>
        <displayFormat>PAY{YY}{MM}-{0000}</displayFormat>
        <label>Payment Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/InvoiceUpdateFromXeroLogicTest.cls
@isTest
private class InvoiceUpdateFromXeroLogicTest {

    @isTest private static void testPositive() {

        Xero_Key__c key = new Xero_Key__c();
        key.Name = 'Kuala Lumpur';
        key.Consumer_Key__c = 'test';
        insert key;

        Account payerAcc = new Account(name='acc');
        insert payerAcc;

        Invoice_Statement__c inv = new Invoice_Statement__c();
        inv.Currency__c = 'EUR';
        inv.School__c = key.Name;
        inv.Payer__c = payerAcc.Id;
        inv.Xero_Key__c = key.Id;
        insert inv;

        sfXero.XeroApi.startTesting();

        InvoiceUpdateFromXeroLogic.updateSingleInvoice(inv.Id);

        sfXero.XeroApi.stopTesting();

        inv = [
            SELECT Xero_Value__c, Xero_Invoice_Date__c, Xero_Status__c,
            ( SELECT Id FROM Payments__r )
            FROM Invoice_Statement__c
            WHERE Id = :inv.Id
        ];

        system.assertNotEquals(null, inv.Xero_Value__c);
        system.assertNotEquals(null, inv.Xero_Invoice_Date__c);
        system.assertNotEquals(null, inv.Xero_Status__c);
    }

    @isTest private static void testNullInvoiceId() {

        sfXero.XeroApi.startTesting();

        Boolean exceptionThrown = false;
        try {
            // Use a valid id, that doesn't exist
            InvoiceUpdateFromXeroLogic.updateSingleInvoice('a0dM00000029Qz5');
        }
        catch (InvoiceUpdateFromXeroLogic.UpdateFromXeroException e) {
            // Ensure it's our own exception that was caught
            exceptionThrown = true;
        }
        system.assert(exceptionThrown);

        sfXero.XeroApi.stopTesting();
    }

    @isTest private static void testNoMatchingKey() {

        Xero_Key__c key = new Xero_Key__c();
        key.Name = 'Unmatched';
        key.Consumer_Key__c = 'test';
        insert key;

        Account payerAcc = new Account(name='acc');
        insert payerAcc;

        Invoice_Statement__c inv = new Invoice_Statement__c();
        inv.Currency__c = 'EUR';
        inv.School__c = 'Kuala Lumpur';
        inv.Payer__c = payerAcc.Id;
        inv.Xero_Key__c = key.Id;
        insert inv;

        sfXero.XeroApi.startTesting();

        Boolean exceptionThrown = false;
        try {
            // Use a valid id, that doesn't exist
            InvoiceUpdateFromXeroLogic.updateSingleInvoice('a0dM00000029Qz5');
        }
        catch (InvoiceUpdateFromXeroLogic.UpdateFromXeroException e) {
            // Ensure it's our own exception that was caught
            exceptionThrown = true;
        }
        system.assert(exceptionThrown);

        sfXero.XeroApi.stopTesting();
    }
}