force-app/main/default/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Gender__c</fullName>
        <label>Gender</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Male</fullName>
                </value>
                <value>
                    <fullName>Female</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Company_Account</fullName>
        <active>true</active>
        <label>Company</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Financial_Information__c.object
<CustomObject>
    <description>To record the invoice/receipt requirements of parents/companies and the bank account information of employees</description>
    <fields>
        <fullName>Fees_Responsible_For__c</fullName>
        <label>Fees Responsible For</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>All Applicable</fullName>
                </value>
                <value>
                    <fullName>All Applicable (Shared)</fullName>
                </value>
                <value>
                    <fullName>Tuition</fullName>
                </value>
                <value>
                    <fullName>Tuition (Shared)</fullName>
                </value>
                <value>
                    <fullName>Lunch</fullName>
                </value>
                <value>
                    <fullName>Lunch (Shared)</fullName>
                </value>
                <value>
                    <fullName>Uniform</fullName>
                </value>
                <value>
                    <fullName>Uniform (Shared)</fullName>
                </value>
                <value>
                    <fullName>Bus</fullName>
                </value>
                <value>
                    <fullName>Bus (Shared)</fullName>
                </value>
                <value>
                    <fullName>EAL / Language Support</fullName>
                </value>
                <value>
                    <fullName>EAL / Language Support (Shared)</fullName>
                </value>
                <value>
                    <fullName>Extra Programmes (ASAs etc.)</fullName>
                </value>
                <value>
                    <fullName>Extra Programmes (ASAs etc.) (Shared)</fullName>
                </value>
                <value>
                    <fullName>Fee Required For Enrolment</fullName>
                </value>
                <value>
                    <fullName>Fee Required For Enrolment (Shared)</fullName>
                </value>
                <value>
                    <fullName>Annual Enrolment</fullName>
                </value>
                <value>
                    <fullName>Annual Enrolment (Shared)</fullName>
                </value>
                <value>
                    <fullName>Annual Capital Contribution</fullName>
                </value>
                <value>
                    <fullName>Annual Capital Contribution (Shared)</fullName>
                </value>
                <value>
                    <fullName>None</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Invoice_Currency__c</fullName>
        <label>Invoice Currency</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>BRL</fullName>
                </value>
                <value>
                    <fullName>CNY</fullName>
                </value>
                <value>
                    <fullName>EUR</fullName>
                </value>
                <value>
                    <fullName>GBP</fullName>
                </value>
                <value>
                    <fullName>MMK</fullName>
                </value>
                <value>
                    <fullName>MYR</fullName>
                </value>
                <value>
                    <fullName>PHP</fullName>
                </value>
                <value>
                    <fullName>RUB</fullName>
                </value>
                <value>
                    <fullName>USD</fullName>
                </value>
                <value>
                    <fullName>UZS</fullName>
                </value>
                <value>
                    <fullName>N/A</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Invoice_Frequency__c</fullName>
        <label>Invoice Frequency</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Monthly</fullName>
                </value>
                <value>
                    <fullName>Termly</fullName>
                </value>
                <value>
                    <fullName>Yearly</fullName>
                </value>
                <value>
                    <fullName>N/A</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Related_to__c</fullName>
        <label>Related to</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Financial Information</relationshipLabel>
        <relationshipName>Financial_Information</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Financial Information</label>
    <nameField>
        <displayFormat>FI-{YY}{00000}</displayFormat>
        <label>Financial Information</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Financial Information</pluralLabel>
    <recordTypes>
        <fullName>Parent_Financial_Information</fullName>
        <active>true</active>
        <description>For the invoice and receipt information of parents</description>
        <label>Parent Financial Information</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Gender__c</fullName>
        <label>Gender</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Gender_Options</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Price_Book_to_Allocate__c</fullName>
        <formula>CASE(
     School__c, 
     &quot;The British School of Guangzhou&quot;, &quot;Guangzhou&quot;, 
     &quot;The British School of Nanjing&quot;, &quot;Nanjing&quot;,    
     &quot;The British International School of Marbella&quot;, &quot;Marbella&quot;, 
     &quot;The British School of Navarra&quot;, &quot;Pamplona&quot;, 
     &quot;The British School of Tashkent&quot;, &quot;Tashkent&quot;, 
     &quot;The British College of Brazil&quot;, &quot;Sao Paulo&quot;, 
     &quot;The British International School of Kuala Lumpur&quot;, &quot;Kuala Lumpur&quot;, 
     &quot;The British School Yangon&quot;, &quot;Yangon&quot;, 
     &quot;Ukraine International School&quot;, &quot;Kiev&quot;, 
     &quot;The International School of Moscow&quot;, &quot;Moscow&quot;, 
     &quot;Nord Anglia International School Manila&quot;, &quot;Manila&quot;,
     &quot;King&apos;s College Beijing&quot;, &quot;Beijing&quot;, 
     &quot;The New York International School&quot;, &quot;New York&quot;, 
     &quot;The British School of Brasilia&quot;, &quot;Brasilia&quot;, 
     &quot;Standard Price Book&quot;
     )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Price Book to Allocate</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Student_Name__c</fullName>
        <label>Student Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Year_Group__c</fullName>
        <label>Year Group / Grade</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>US_Year_Group_Control__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>PN1</fullName>
                </value>
                <value>
                    <fullName>PN</fullName>
                </value>
                <value>
                    <fullName>N</fullName>
                </value>
                <value>
                    <fullName>R</fullName>
                </value>
                <value>
                    <fullName>Y1</fullName>
                </value>
                <value>
                    <fullName>Y2</fullName>
                </value>
                <value>
                    <fullName>Y3</fullName>
                </value>
                <value>
                    <fullName>Y4</fullName>
                </value>
                <value>
                    <fullName>Y5</fullName>
                </value>
                <value>
                    <fullName>Y6</fullName>
                </value>
                <value>
                    <fullName>Y7</fullName>
                </value>
                <value>
                    <fullName>Y8</fullName>
                </value>
                <value>
                    <fullName>Y9</fullName>
                </value>
                <value>
                    <fullName>Y10</fullName>
                </value>
                <value>
                    <fullName>Y11</fullName>
                </value>
                <value>
                    <fullName>Y12</fullName>
                </value>
                <value>
                    <fullName>Y13</fullName>
                </value>
                <value>
                    <fullName>PK</fullName>
                </value>
                <value>
                    <fullName>K</fullName>
                </value>
                <value>
                    <fullName>G1</fullName>
                </value>
                <value>
                    <fullName>G2</fullName>
                </value>
                <value>
                    <fullName>G3</fullName>
                </value>
                <value>
                    <fullName>G4</fullName>
                </value>
                <value>
                    <fullName>G5</fullName>
                </value>
                <value>
                    <fullName>G6</fullName>
                </value>
                <value>
                    <fullName>G7</fullName>
                </value>
                <value>
                    <fullName>G8</fullName>
                </value>
                <value>
                    <fullName>G9</fullName>
                </value>
                <value>
                    <fullName>G10</fullName>
                </value>
                <value>
                    <fullName>G11</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Student</fullName>
        <active>true</active>
        <businessProcess>Standard Admissions Process</businessProcess>
        <label>Student</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/PersonAccount.object
<CustomObject>
    <recordTypes>
        <fullName>PersonAccount</fullName>
        <active>true</active>
        <label>Parent</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/globalValueSets/Gender_Options.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Male</fullName>
    </customValue>
    <customValue>
        <fullName>Female</fullName>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
    </customValue>
    <customValue>
        <fullName>Prefer not to say</fullName>
    </customValue>
    <masterLabel>Gender Options</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/SelectDefaultPricebookTest.cls
/**
 * Tests for SelectDefaultPricebookTest.
 * 
 * @author Logan (Trineo)
 * @date September 2013
 */
@isTest
private class SelectDefaultPricebookTest {
    
    @isTest(SeeAllData=True) static void testPositive() {
        //create company account account
        Account companyAccount =  new Account();
        companyAccount.Name =  'Company Account';
        companyAccount.RecordTypeId = [Select Id from RecordType where SObjectType='Account' AND DeveloperName='Company_Account'].Id;
        insert companyAccount;
        
        //create parent account account
        Account parentAccount =  new Account();
        parentAccount.FirstName =  'First Name';
        parentAccount.LastName =  'Last Name';
        parentAccount.PersonEmail = 'test@test.com';
        parentAccount.RecordTypeId = [Select Id from RecordType where SObjectType='Account' AND DeveloperName='PersonAccount'].Id;
        insert parentAccount;
        
        //insert related financial info
        Financial_Information__c fi = new Financial_Information__c();
        fi.Related_to__c = parentAccount.Id;
        fi.Invoice_Currency__c = 'MYR';
        fi.Invoice_Frequency__c = 'Monthly';
        fi.Fees_Responsible_For__c = 'All Applicable;';
        fi.RecordTypeId = [select Id from RecordType where DeveloperName = 'Parent_Financial_Information'].Id;
        //fi.Company_Name__c = companyAccount.Id;
        insert fi;
        

        // Insert a new student
        Opportunity student = new Opportunity(
            Name = 'Test Student', 
            Gender__c = 'Male',
            StageName = 'A/ Testing', 
            Year_Group__c = 'Y1', 
            CloseDate = System.today().addDays(10), 
            Student_Name__c = 'Morgan', 
            AccountId = parentAccount.Id
        );
        insert student;

        // Assert that the pricebook has been set correctly
        student = [Select Id, Price_Book_to_Allocate__c, Pricebook2.Name From Opportunity Where Id =: student.Id];
        System.assertEquals(student.Price_Book_to_Allocate__c, student.Pricebook2.Name, 'Expected Pricebook to match Price_Book_to_Allocate__c after student created');
    }
}