force-app/main/default/objects/Account.object
<CustomObject>
    <fields>
        <fullName>School__c</fullName>
        <description>Copies the value of SchoolText (which is a workflow copying from School Formula). A little long winded solution to avoid bigger changes in the Teacher/Parent portal.</description>
        <formula>SchoolText__pc</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>School</label>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Activity.object
<CustomObject>
    <fields>
        <fullName>Student__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Mirrors the value in the standard &apos;Name&apos; field by means of a trigger. This field cannot be changed directly as it will always revert to the value shown in the &apos;Name&apos; field. To make a change, change the value in the &apos;Name&apos; field instead. Should not be on page layout.</description>
        <inlineHelpText>Mirrors the value in the standard &apos;Name&apos; field by means of a trigger. This field cannot be changed directly as it will always revert to the value shown in the &apos;Name&apos; field. To make a change, change the value in the &apos;Name&apos; field instead.</inlineHelpText>
        <label>Student</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Value does not exist or is not a &apos;Student Academic File&apos;.</errorMessage>
            <filterItems>
                <field>Contact.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Student</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Attendance Records</relationshipLabel>
        <relationshipName>Activities</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Assesment__c.object
<CustomObject>
    <fields>
        <fullName>Group__c</fullName>
        <label>Group</label>
        <referenceTo>Group__c</referenceTo>
        <relationshipLabel>Assessments</relationshipLabel>
        <relationshipName>Assessments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>School__c</fullName>
        <formula>Text( Group__r.Owner:User.School__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>School</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Student__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Student</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Assessments</relationshipLabel>
        <relationshipName>Assessments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Assessment</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assessments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Assessment_Reports_Accessed__c</fullName>
        <label>Progress Tab Accessed</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Attendance_Report_Accessed__c</fullName>
        <label>Attendance Tab Accessed</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Chatter_Favorite_Added__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>checked by system when logic a</inlineHelpText>
        <label>Chatter Favorite Added</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Class_Name__c</fullName>
        <formula>Admissions_File__r.Class_Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Admin Dept. Class Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EAL__c</fullName>
        <formula>IF(  Admissions_File__r.EAL_Status__c  =&quot;Current&quot;,&quot;Yes&quot;, &quot;No&quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>EAL</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Main_Parent_File__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Family File</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Value does not exist or is not a parent record.</errorMessage>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Parent</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Additional Parents &amp; Student Academic Files</relationshipLabel>
        <relationshipName>Emails</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>NewsEvents_Report_Accessed__c</fullName>
        <label>Calendar Tab Accessed</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Pastoral_Report_Accessed__c</fullName>
        <label>Pastoral Tab Accessed</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>School__c</fullName>
        <formula>Admissions_File__r.School__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>School</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <formula>IF(AND(TEXT(Admissions_File__r.Add_to_Register__c)=&quot;Yes&quot;, TEXT(Admissions_File__r.StageName) = &quot;A/ Deposit&quot;), &quot;Enrolled&quot;, Text(Admissions_File__r.StageName))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Stage</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Student_Name_in_Portal__c</fullName>
        <formula>If(Admissions_File__r.Nickname__c =&quot;&quot;, Admissions_File__r.Student_Name__c, Admissions_File__r.Nickname__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Student Name in Portal</label>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Contact</fullName>
        <active>true</active>
        <label>Contact</label>
    </recordTypes>
    <recordTypes>
        <fullName>Student</fullName>
        <active>true</active>
        <label>Student Academic File</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Group__c.object
<CustomObject>
    <fields>
        <fullName>Class_Name__c</fullName>
        <formula>IF( TEXT(Combined_Year_Group__c)=&quot;&quot;, TEXT(Year_Group__c) &amp; TEXT(Class__c) ,TEXT(Year_Group__c)&amp;&quot;/&quot;&amp; Combined_Year_Group_Abb__c  &amp; TEXT(Class__c))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Class Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>School__c</fullName>
        <formula>TEXT(Owner:User.School__c)</formula>
        <label>School</label>
        <type>Text</type>
    </fields>
    <label>Student Group</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Student Groups</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Registration__c.object
<CustomObject>
    <fields>
        <fullName>EAL__c</fullName>
        <formula>IF( Student__r.Admissions_File__r.EAL_Status__c=&quot;Current&quot; , &apos;YES&apos;, &apos;NO&apos;)</formula>
        <label>EAL</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Group__c</fullName>
        <inlineHelpText>select group against which assessment is done.</inlineHelpText>
        <label>Group</label>
        <referenceTo>Group__c</referenceTo>
        <relationshipLabel>Registrations</relationshipLabel>
        <relationshipName>Assessments_Registrations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>School__c</fullName>
        <formula>Group__r.School__c</formula>
        <label>School</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Student__c</fullName>
        <inlineHelpText>select student for this enrolment</inlineHelpText>
        <label>Student</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Registrations</relationshipLabel>
        <relationshipName>Registrations</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Registration</label>
    <nameField>
        <displayFormat>R-{000000}</displayFormat>
        <label>Registration #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Registrations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/School__c.object
<CustomObject>
    <fields>
        <fullName>School_Full_Name__c</fullName>
        <label>School Full Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>School</label>
    <nameField>
        <label>School Code/UID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Schools</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/School_Logo_Mapping__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>setting to store mapping of school name and school logo image URL</description>
    <fields>
        <fullName>Community_Id__c</fullName>
        <inlineHelpText>Id of the school&apos;s parent community Id.</inlineHelpText>
        <label>Community Id</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Logo_URL__c</fullName>
        <inlineHelpText>static resource URL for logo image</inlineHelpText>
        <label>Logo URL</label>
        <length>200</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>School_Full_Name__c</fullName>
        <label>School Full Name</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Topic_Id__c</fullName>
        <description>Id for the important topic tag for this school.</description>
        <inlineHelpText>Id for the important topic tag for this school.</inlineHelpText>
        <label>Topic Id</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>School Mapping</label>
</CustomObject>

force-app/main/default/objects/User.object
<CustomObject>
    <fields>
        <fullName>Family_File_Id__c</fullName>
        <formula>IF( Contact.RecordType.DeveloperName == &quot;Additional_Parent&quot;, CASESAFEID(Contact.Main_Parent_File__c) , CASESAFEID(Contact.AccountId))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Family File Id</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>School__c</fullName>
        <label>School</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>The British Schools Foundation</fullName>
                </value>
                <value>
                    <fullName>The British School of Guangzhou</fullName>
                </value>
                <value>
                    <fullName>The British School of Nanjing</fullName>
                </value>
                <value>
                    <fullName>The British International School of Marbella</fullName>
                </value>
                <value>
                    <fullName>The British School of Navarra</fullName>
                </value>
                <value>
                    <fullName>The British School of Tashkent</fullName>
                </value>
                <value>
                    <fullName>The British College of Brazil</fullName>
                </value>
                <value>
                    <fullName>The British International School of Kuala Lumpur</fullName>
                </value>
                <value>
                    <fullName>The International School of Moscow</fullName>
                </value>
                <value>
                    <fullName>Nord Anglia International School Manila</fullName>
                </value>
                <value>
                    <fullName>King&apos;s College Beijing</fullName>
                </value>
                <value>
                    <fullName>The British School Yangon</fullName>
                </value>
                <value>
                    <fullName>Ukraine International School</fullName>
                </value>
                <value>
                    <fullName>The New York International School</fullName>
                </value>
                <value>
                    <fullName>The British School of Brasilia</fullName>
                </value>
                <value>
                    <fullName>NAE</fullName>
                </value>
                <value>
                    <fullName>The British International School Yangon</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/classes/PortalReportFilter.cls
/***
    Author: Kunal 
    Created Date: 28 April 2013
    Desc: Master class for parent portal filters
***/

public virtual class PortalReportFilter{ 
    public Id parentAccountId {get;set;}
    public Set<Id> studentIds {get;set;}    
    public User portalUser {get;set;}
    
    //filters
    //for student selection
    public List<SelectOption> studentList {get;set;}
    public String selectedStudentId {get;set;}
    //for academic year selection
    public List<SelectOption> academicYearOptions {get;set;}
    public String selectedAcademicYear {get;set;}
    /*//for term selection
    public List<SelectOption> termOptions {get;set;}
    public List<String> selectedTerm {get;set;}*/
    //for assessment type selection
    public List<ReportTypeWrapper> assessmentTypeOptions {get;set;}
    
    public List<ReportTypeWrapper> attendanceTypeOptions {get;set;}
    
    public List<ReportTypeWrapper> conductTypeOptions {get;set;}
    
    public List<ReportTypeWrapper> newsEventTypeOptions {get;set;}
    //for subject type
    public List<SelectOption> subjectTypeOptions {get;set;}
    public String selectedSubjectType {get;set;} 
    //for parent name 
    public String familyName {get;set;}
    public Map<String,String> schoolLogoMap;
    private Id accId {get;set;}
    //constructor
    public  PortalReportFilter(){
        Id loggedInUserId =  UserInfo.getUserId();
        //fetch account id 
        //parentAccountId =  [Select u.Name, Family_File_Id__c, u.ContactId, u.AccountId From User u where Id=:loggedInUserId].AccountId;
        portalUser =  [Select u.LocaleSidKey,  u.School__c, u.Name, Family_File_Id__c ,u.ContactId, u.AccountId From User u where Id=:loggedInUserId];
        if(portalUser.Family_File_Id__c != null && portalUser.Family_File_Id__c != ''){
            parentAccountId = portalUser.Family_File_Id__c ;
        }else{
            parentAccountId = portalUser.AccountId;
        }  
        
        //check for testing
        if(parentAccountId == null){
            //fetch parentaccount id from URL 
            string a_id = System.currentPageReference().getParameters().get('accid');
            if(a_id != null & a_id != ''){
            	accId = a_id;
            	parentAccountId =  accId;
            }
        }      
        if(parentAccountId != null){
            Account parentAcc = [Select a.FirstName,a.LastName From Account a where a.Id=:parentAccountId];
            familyName = parentAcc.LastName+' - '+parentAcc.FirstName;
            initialize();
        }else{
            //add error to page
        }
    }
    
    public void createTabClickEvent(string tab){
        if(portalUser != null && accId == null){
            if(portalUser.ContactId != null){
                Contact con = [select Id, Chatter_Favorite_Added__c from Contact where Id=:portalUser.ContactId];
                if(tab == 'assessment'){
                    con.Assessment_Reports_Accessed__c = DateTime.now();
                    //update con;
                }else if(tab == 'attendance'){
                    con.Attendance_Report_Accessed__c = DateTime.now();
                    //update con;
                }else if(tab == 'pastoral'){
                    con.Pastoral_Report_Accessed__c = DateTime.now();
                    //update con;
                }else if(tab == 'newsevents'){
                    con.NewsEvents_Report_Accessed__c = DateTime.now();
                }
                try{
                    //check for chatter favorite
                    if(con.Chatter_Favorite_Added__c ==  false){
                        Map<String,School_Logo_Mapping__c>schoolSettingMap =  new Map<String,School_Logo_Mapping__c>();
                        List<School_Logo_Mapping__c> settings = School_Logo_Mapping__c.getall().values(); 
                        for(School_Logo_Mapping__c setting:settings){
                            schoolSettingMap.put(setting.School_Full_Name__c,setting);
                        }
                        if(schoolSettingMap.get(portalUser.School__c) != null){
                            if(schoolSettingMap.get(portalUser.School__c).Community_Id__c != null){
                                if(schoolSettingMap.get(portalUser.School__c).Topic_Id__c != null){
                                    ConnectApi.FeedFavorite feedFavoriteResult = ConnectApi.ChatterFavorites.addRecordFavorite(schoolSettingMap.get(portalUser.School__c).Community_Id__c , portalUser.Id, schoolSettingMap.get(portalUser.School__c).Topic_Id__c);
                                    con.Chatter_Favorite_Added__c = true;
                                }
                            }
                        }
                    }
                    update con;
                }catch(Exception e){
                    //do nothing
                }
            }
        }
        
    }
    
    private void initialize(){
        //check for student cookie
        Cookie cookie_sid_prf = ApexPages.currentPage().getCookies().get('sid');
        
        //populate schools logo map
        schoolLogoMap =  new Map<String,String>();
        List<School_Logo_Mapping__c> settings = School_Logo_Mapping__c.getall().values(); 
        for(School_Logo_Mapping__c setting:settings){
            if(accId == null){
            	schoolLogoMap.put(setting.School_Full_Name__c,setting.Logo_URL__c);
            }else{
            	string logo_URL = setting.Logo_URL__c;
            	if(logo_URL != null){
            		logo_URL = logo_URL.replace('/parents','');
            	}
            	schoolLogoMap.put(setting.School_Full_Name__c,logo_URL);
            }
        }
        //initialze report filters
        initializeStudentList();
        initializeYearSubject();
        initializeAssessmentReportTypes();
        initializeAttendanceReportTypes();
        initializeConductReportTypes();
        initializeNewsEventTypeOptions();
        if(studentList != null){
             //check if cookie is not null and student is there is student list
            boolean isSelectedStudent = false;
            if(cookie_sid_prf != null){
                string cookie_value = cookie_sid_prf.getValue();
                if(cookie_value != null && cookie_value != ''){
                    for(Id sid : studentIds){
                        string str_id = sid;
                        if(sid == cookie_value){
                               isSelectedStudent = true;
                               break;                   
                        }
                    }
                }
            } 
            if(isSelectedStudent){ 
                selectedStudentId = cookie_sid_prf.getValue();
            }else if(studentList.size() > 0){
                selectedStudentId = studentList[0].getValue();
            }
        }
        
        if(academicYearOptions != null){
            if(academicYearOptions.size() > 0 && selectedAcademicYear == null){
                selectedAcademicYear = academicYearOptions[0].getValue();
            }
        }
        
        selectedSubjectType = '-';
        
        /*
        //initialize group list
        groupList = new List<String>();
        groupList.add('All');
        for(AssessmentWrapper a:assessmentList){
            if(a.isTutorGroup){
                groupList.add('Tutor Group - '+a.groupName);    
            }
        }
        for(AssessmentWrapper a:assessmentList){
            if(!a.isTutorGroup){
                groupList.add(a.groupName); 
            }
        }*/
    }
    
    //helper function to initialize student list
    private void initializeStudentList(){
        studentList = new List<SelectOption>();
        studentIds =  new Set<Id>();
        for(Contact c:[Select c.RecordTypeId, c.Student_Name_in_Portal__c, c.Name, c.Main_Parent_File__c, c.LastName, c.FirstName, c.Email, c.EAL__c, c.Class_Name__c, c.AccountId From Contact c where c.RecordType.DeveloperName = 'Student' AND c.Main_Parent_File__c=:parentAccountId AND (Stage__c = 'Enrolled' OR Stage__c = 'Left') order by Name]){
            studentList.add(new SelectOption(c.Id,c.Student_Name_in_Portal__c));
            studentIds.add(c.Id);
        }
        System.debug('***PortalReportFilter*****initialize***studentIds='+studentIds);
    }
    
    //helper function to initialize academic year & subject type
    private void initializeYearSubject(){
        //fetch all acdemic year options  & subject Type
        Set<String> aYear =  new Set<String>();
        Set<String> subjectList =  new Set<String>();
        for(Registration__c r:[Select r.Student__c, r.Id, r.Group__r.Subject_Name__c, r.Group__r.Academic_Year__c, r.Group__r.Group_Type__c, r.Group__r.Name, r.Group__r.Id, r.Group__c, r.Active__c From Registration__c r where r.Student__c IN:studentIds AND r.Group__r.Group_Type__c = 'Tutor Group'  order by r.Group__r.CreatedDate desc]){
                if(selectedAcademicYear == null){
                    selectedAcademicYear = r.Group__r.Academic_Year__c;
                }
                aYear.add(r.Group__r.Academic_Year__c);
                if(r.Group__r.Group_Type__c.equalsIgnoreCase('subject') && r.Group__r.Subject_Name__c != null && r.Group__r.Subject_Name__c != ''){
                    subjectList.add(r.Group__r.Subject_Name__c);
                }
        }
        academicYearOptions = new List<SelectOption>();
        list<string> years =  new list<string>();
        for(String s:aYear){
            years.add(s);
        }
        years.sort();
        for(integer i = years.size() -1; i >=0 ; i--){
            academicYearOptions.add(new SelectOption(years[i],years[i]));
        }
        //for(String s:aYear){
            //academicYearOptions.add(new SelectOption(s,s));
        //}
        subjectTypeOptions = new List<SelectOption>();
        subjectTypeOptions.add(new SelectOption('-','All Subjects'));
        //subjectList.sort();
        for(String s:subjectList){
            subjectTypeOptions.add(new SelectOption(s,s));
        }
        System.debug('***PortalReportFilter*****initialize***academicYearOptions='+academicYearOptions);
    }
    /*
    //helper function to initialize terom  options
    private void initializeTermOptions(){
        //fetch all term options
        Set<String> terms =  new Set<String>();
        for(Assesment__c a:[Select a.Student__c, a.Id, a.Assessment_Folder__r.Term__c, a.Assessment_Folder__r.Mid_Term_Report__c, a.Assessment_Folder__r.Type__c, a.Assessment_Folder__r.Auto_Publish__c, a.Assessment_Folder__r.Id, a.Assessment_Folder__c From Assesment__c a where a.Student__c IN:studentIds AND a.Assessment_Folder__r.Auto_Publish__c = true order by a.Assessment_Folder__r.Term__c]){
            terms.add(a.Assessment_Folder__r.Term__c);
        }
        termOptions = new List<SelectOption>();
        for(String s:terms){
            termOptions.add(new SelectOption(s,s));
        }
    }*/
    
    //helper function to initialize assessment report types
    private void initializeAssessmentReportTypes(){
        //fetch all assessment type options
        assessmentTypeOptions = new List<ReportTypeWrapper>();
    
        List<String> assessmentType =  new List<String>();
        for(Schema.PicklistEntry entry: Assesment__c.Type__c.getDescribe().getPicklistValues()){
            if(!entry.getValue().equalsIgnoreCase('Tracking')){
                assessmentType.add(entry.getValue());
            }
        }
        assessmentTypeOptions = new List<ReportTypeWrapper>();
        for(String s:assessmentType){
            assessmentTypeOptions.add(new ReportTypeWrapper(s,assessmentTypeOptions.size()));
        }
        System.debug('***PortalReportFilter*****initialize***assessmentTypeOptions='+assessmentTypeOptions);
    }
    
    //helper function to initialize attendance report types
    private void initializeAttendanceReportTypes(){     
        attendanceTypeOptions =  new List<ReportTypeWrapper>();
        attendanceTypeOptions.add(new ReportTypeWrapper('Lates',attendanceTypeOptions.size()));
        attendanceTypeOptions.add(new ReportTypeWrapper('Absences',attendanceTypeOptions.size()));
        attendanceTypeOptions.add(new ReportTypeWrapper('Partials',attendanceTypeOptions.size()));
        attendanceTypeOptions.add(new ReportTypeWrapper('External Activities',attendanceTypeOptions.size()));
        System.debug('***PortalReportFilter*****initialize***attendanceTypeOptions='+attendanceTypeOptions);
    }
    
    //helper function to initialize attendance report types
    private void initializeConductReportTypes(){        
        conductTypeOptions =  new List<ReportTypeWrapper>();
        conductTypeOptions.add(new ReportTypeWrapper('Incidents',conductTypeOptions.size()));
        conductTypeOptions.add(new ReportTypeWrapper('Achievements',conductTypeOptions.size()));
        //conductTypeOptions.add(new ReportTypeWrapper('Leadership Roles',conductTypeOptions.size()));
        conductTypeOptions.add(new ReportTypeWrapper('Effort & Attitude',conductTypeOptions.size()));
        System.debug('***PortalReportFilter*****initialize***conductTypeOptions='+conductTypeOptions);
    }
    
    //helper function to initialize attendance report types
    private void initializeNewsEventTypeOptions(){        
        newsEventTypeOptions =  new List<ReportTypeWrapper>();
        PortalReportFilter.ReportTypeWrapper termsHolidays = new ReportTypeWrapper('Term / Holidays',newsEventTypeOptions.size());
        termsHolidays.reportTypeValue = 'Term;Holiday';
        newsEventTypeOptions.add(termsHolidays);
        
        PortalReportFilter.ReportTypeWrapper events = new ReportTypeWrapper('Events',newsEventTypeOptions.size());
        events.reportTypeValue = 'Event';
        newsEventTypeOptions.add(events);
        
        PortalReportFilter.ReportTypeWrapper reminders = new ReportTypeWrapper('Notices',newsEventTypeOptions.size());
        reminders.reportTypeValue = 'Notice';
        newsEventTypeOptions.add(reminders);
        
        System.debug('***PortalReportFilter*****initialize***newsEventTypeOptions='+newsEventTypeOptions); 
    }
    
    //wrapper class for report type
    public class ReportTypeWrapper{
        public String reportType {get;set;}
        public String reportTypeValue {get;set;}
        public boolean selected {get;set;}
        public Integer index {get;set;}
        public Integer rt {get;set;}
        public ReportTypeWrapper(String s, Integer i){
            index =  i+1;
            reportType =  s;
            selected =  true;
            if(reportType.equalsIgnoreCase('Progress Report') || reportType.equalsIgnoreCase('Partials') || reportType.equalsIgnoreCase('Partial') || reportType.equalsIgnoreCase('Effort & Attitude') || reportType.equalsIgnoreCase('Term / Holidays')){
                rt = 1;
            }else if(reportType.equalsIgnoreCase('Assignment') || reportType.equalsIgnoreCase('External Activities') || reportType.equalsIgnoreCase('External Activity') || reportType.equalsIgnoreCase('Achievements') || reportType.equalsIgnoreCase('Events')){
                rt = 2;
            }else if(reportType.equalsIgnoreCase('Examination') || reportType.equalsIgnoreCase('Late') || reportType.equalsIgnoreCase('Lates') ){
                rt = 3;
            }else if(reportType.equalsIgnoreCase('Test') || reportType.equalsIgnoreCase('Incidents') || reportType.equalsIgnoreCase('Notices') || reportType.equalsIgnoreCase('Absent') || reportType.equalsIgnoreCase('Absences')){
                rt = 4;
            }
        } 
    }
}