force-app/main/default/objects/Activity.object
<CustomObject>
    <fields>
        <fullName>Academic_Year__c</fullName>
        <formula>IF(
   AND(
       MONTH(DATEVALUE(CreatedDate))&gt;7,
       MONTH(DATEVALUE(CreatedDate))&lt;13
       ),
   TEXT(YEAR(DATEVALUE(CreatedDate)))&amp;&quot;/&quot;&amp;TEXT(CreatedDate_plus_1__c),
   TEXT(CreatedDate_minus_1__c)&amp;&quot;/&quot;&amp;TEXT(YEAR(DATEVALUE(CreatedDate)))
   )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Academic Year</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Attendance_Type__c</fullName>
        <label>Attendance Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>First</fullName>
                    <default>true</default>
                    <label>First</label>
                </value>
                <value>
                    <fullName>Second</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Display_Date__c</fullName>
        <description>Defines the display format for attendance record in the parent portal based on the user locale of the person creating the record</description>
        <formula>IF($User.Is_US_Locale__c = TRUE, 

Display_Month__c&amp;&quot; &quot;&amp; TEXT(DAY(ActivityDate)) &amp;&quot;, &quot;&amp;TEXT(YEAR(ActivityDate)), 

TEXT(DAY(ActivityDate))&amp;&quot; &quot;&amp;Display_Month__c&amp;&quot; &quot;&amp;TEXT(YEAR(ActivityDate)))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Display Date</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Display_Name__c</fullName>
        <formula>IF(
   AND( 
       $User.Is_US_Locale__c = TRUE,
       Subject = &quot;Authorised Absence&quot;
       ),
   &quot;Authorized Absence&quot;,
   IF(
      AND( 
          $User.Is_US_Locale__c = TRUE,
          Subject = &quot;Unauthorised Absence&quot;
          ),
      &quot;Unauthorized Absence&quot;,
      Subject
      )
   )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Display Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Is_Tutor_Group_Attendance__c</fullName>
        <description>Identifies an attendance record as belonging to a tutor group to be used as a filter in the relevant attendance reports</description>
        <formula>IF(TEXT(Student_Group__r.Group_Type__c) = &quot;Tutor Group&quot;, True, False)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Is Tutor Group Attendance</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Student__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Mirrors the value in the standard &apos;Name&apos; field by means of a trigger. This field cannot be changed directly as it will always revert to the value shown in the &apos;Name&apos; field. To make a change, change the value in the &apos;Name&apos; field instead. Should not be on page layout.</description>
        <inlineHelpText>Mirrors the value in the standard &apos;Name&apos; field by means of a trigger. This field cannot be changed directly as it will always revert to the value shown in the &apos;Name&apos; field. To make a change, change the value in the &apos;Name&apos; field instead.</inlineHelpText>
        <label>Student</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Value does not exist or is not a &apos;Student Academic File&apos;.</errorMessage>
            <filterItems>
                <field>Contact.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Student</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Attendance Records</relationshipLabel>
        <relationshipName>Activities</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Admissions_File__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Admissions File</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>School__c</fullName>
        <formula>Admissions_File__r.School__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>School</label>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Contact</fullName>
        <active>true</active>
        <label>Contact</label>
    </recordTypes>
    <recordTypes>
        <fullName>Student</fullName>
        <active>true</active>
        <label>Student Academic File</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Event.object
<CustomObject>
    <recordTypes>
        <fullName>Attendance</fullName>
        <active>true</active>
        <description>For capturing Student&apos;s attendance.</description>
        <label>Attendance</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Group__c.object
<CustomObject>
    <fields>
        <fullName>Academic_Year__c</fullName>
        <formula>IF(
   TEXT(Group_Type__c)=&quot;School Group&quot;, 
   Current_Academic_Year__c, 
   IF(
      AND(
          MONTH(DATEVALUE(CreatedDate))&lt;=12, 
          MONTH(DATEVALUE(CreatedDate))&gt;=8
          ), 
      TEXT(YEAR(DATEVALUE(CreatedDate)))&amp;&quot;/&quot;&amp; TEXT(CreatedDate_plus_1__c ),  
      TEXT(CreatedDate_minus_1__c)&amp;&quot;/&quot;&amp;TEXT(YEAR(DATEVALUE(CreatedDate)))
      )
   )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Academic Year</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Group_Type__c</fullName>
        <label>Group Type</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Year_Group_Control__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Tutor Group</fullName>
                </value>
                <value>
                    <fullName>Subject</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>School Group</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>School__c</fullName>
        <formula>TEXT(Owner:User.School__c)</formula>
        <label>School</label>
        <type>Text</type>
    </fields>
    <label>Student Group</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Student Groups</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>School__c</fullName>
        <formula>Account.SchoolText__pc</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>School</label>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Student</fullName>
        <active>true</active>
        <businessProcess>Standard Admissions Process</businessProcess>
        <label>Student</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Registration__c.object
<CustomObject>
    <fields>
        <fullName>Academic_Year__c</fullName>
        <description>For the purpose of deactivating registration records at the end of the year, identifies the academic year of the records so only the correct ones are deactivated.</description>
        <formula>IF(Group__r.Is_Whole_School_Group__c = TRUE, &quot;All - Whole School Group&quot;, 

IF(Group__r.Is_Secondary_School_Group__c = TRUE, &quot;All - Secondary School Group&quot;, 

IF(TEXT(Group__r.Group_Type__c) = &quot;School Group&quot;, &quot;All - Other School Group&quot;,

Group__r.Academic_Year__c)))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Academic Year</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Group_Type__c</fullName>
        <formula>TEXT(Group__r.Group_Type__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Group Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Group__c</fullName>
        <inlineHelpText>select group against which assessment is done.</inlineHelpText>
        <label>Group</label>
        <referenceTo>Group__c</referenceTo>
        <relationshipLabel>Registrations</relationshipLabel>
        <relationshipName>Assessments_Registrations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>School__c</fullName>
        <formula>Group__r.School__c</formula>
        <label>School</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Student__c</fullName>
        <inlineHelpText>select student for this enrolment</inlineHelpText>
        <label>Student</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Registrations</relationshipLabel>
        <relationshipName>Registrations</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Registration</label>
    <nameField>
        <displayFormat>R-{000000}</displayFormat>
        <label>Registration #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Registrations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/School__c.object
<CustomObject>
    <label>School</label>
    <nameField>
        <label>School Code/UID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Schools</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/PortalAttendancePage_Controller.cls
/***
    Author: Kunal 
    Created Date: 28 April 2013
    Desc: VF controller for PortaAttendancePage
***/
public class PortalAttendancePage_Controller extends PortalReportFilter{
	public String schoolName {get;set;}
    public Integer totalAbsent {get;set;}
    public Integer totalLate {get;set;}
    public Integer totalPartial {get;set;}
    public Integer totalUnauthorizedAbsence {get;set;}
    public Integer totalExternalActivity {get;set;}
    public List<AttendanceWrapper> attendanceWrapperList {get;set;}
	public boolean hasItems{get{boolean flag = false;if(attendanceWrapperList != null){if(attendanceWrapperList.size() > 0){flag = true;}}return flag;}}
    //constructor
    public  PortalAttendancePage_Controller(){
        
    	
    }
    
    //function to search attendances
	public PageReference filterAttendances(){ 
		createTabClickEvent('attendance');
		attendanceWrapperList =  new List<AttendanceWrapper>();
		totalAbsent = 0;
    	totalLate = 0;
    	totalPartial = 0;
    	totalUnauthorizedAbsence = 0;
    	totalExternalActivity = 0;
		System.debug('*****PortalAttendancePage_Controller**filterAttendances**selectedStudentId='+selectedStudentId);
		System.debug('*****PortalAttendancePage_Controller**filterAttendances**selectedAcademicYear='+selectedAcademicYear);
		System.debug('*****PortalAttendancePage_Controller**filterAttendances**attendanceTypeOptions='+attendanceTypeOptions);
		//set cookie to current selected student
		Cookie cookie_sid = new Cookie('sid', selectedStudentId,null,-1,false);
		ApexPages.currentPage().setCookies(new Cookie[]{cookie_sid});
		//make list of assessment report types
		List<String> selectedReportTypes =  new List<String>();
		for(PortalReportFilter.ReportTypeWrapper rt:attendanceTypeOptions){
			if(rt.selected){
				if(rt.reportType == 'Absent' || rt.reportType == 'Authorised Absence' || rt.reportType == 'Absences' ){
					selectedReportTypes.add('Absent');
					selectedReportTypes.add('Authorised Absence');
					selectedReportTypes.add('Unauthorised Absence');	
				}else if(rt.reportType == 'Late' || rt.reportType == 'Lates'){
					selectedReportTypes.add('Late');
				}else if(rt.reportType == 'Partials' || rt.reportType == 'Partial'){
					selectedReportTypes.add('Partial');
				}else if(rt.reportType == 'External Activity' || rt.reportType == 'External Activities'){
					selectedReportTypes.add('External Activity');
				}else{
					selectedReportTypes.add(rt.reportType);
				}
			}
		}
		//System.debug('*****ParentPortalAttendance_Controller**filterAttendances**events'+Database.query('Select Id from Event where WhoId=\'003c000000LhmmoAAB\''));
		//fetch school name basis student selection
		if(selectedStudentId != null && selectedStudentId != '' && selectedAcademicYear != null && selectedAcademicYear != ''){
			//fetch are active registartion against tutor group for selected student
			/*set<Id> tutorGroupIds =  new set<Id>();
			for(Registration__c r:[Select Id, Group__c from Registration__c where Group__r.Group_Type__c = 'Tutor Group' AND Student__c=:selectedStudentId AND Group__r.Academic_Year__c=:selectedAcademicYear]){
				tutorGroupIds.add(r.Group__c);
			}*/
			schoolName = [Select c.Admissions_File__r.School__c, c.Admissions_File__r.Id, c.Admissions_File__c From Contact c where c.Id=:selectedStudentId].Admissions_File__r.School__c;
			//fetch attendances
			//for(Event e: [Select e.Display_Name__c, e.Display_Date__c, e.WhoId, e.WhatId, e.What.Name, e.Description,  e.Subject, e.RecordType.DeveloperName, e.RecordTypeId, e.Attendance_Type__c, e.ActivityDate, e.Academic_Year__c From Event e where e.RecordType.DeveloperName='Attendance' AND e.WhoId=:selectedStudentId AND e.Academic_Year__c=:selectedAcademicYear AND e.Subject IN:selectedReportTypes AND e.WhatId IN:tutorGroupIds AND e.IsDeleted =  false AND e.ActivityDate <=:date.today() order by e.ActivityDate desc ALL ROWS]){
			for(Event e: [Select e.Display_Name__c, e.Display_Date__c, e.WhoId, e.WhatId, e.What.Name, e.Description,  e.Subject, e.RecordType.DeveloperName, e.RecordTypeId, e.Attendance_Type__c, e.ActivityDate, e.Academic_Year__c From Event e where e.RecordType.DeveloperName='Attendance' AND e.WhoId=:selectedStudentId AND e.Academic_Year__c=:selectedAcademicYear AND e.Subject IN:selectedReportTypes AND e.Is_Tutor_Group_Attendance__c = true AND e.IsDeleted =  false AND e.ActivityDate <=:date.today() order by e.ActivityDate desc ALL ROWS]){
				if(e.Subject.equalsIgnoreCase('Absent') || e.Subject.equalsIgnoreCase('Authorised Absence') || e.Subject.equalsIgnoreCase('Absences') ){
					totalAbsent++;
				}else if(e.Subject.equalsIgnoreCase('Late')){
					totalLate++;
				}else if(e.Subject.equalsIgnoreCase('Partial')){
					totalPartial++;
				}else if(e.Subject.equalsIgnoreCase('Unauthorised Absence')){
					totalUnauthorizedAbsence++;
				}else if(e.Subject.equalsIgnoreCase('External Activity')){
					totalExternalActivity++;
				}
				attendanceWrapperList.add(new AttendanceWrapper(e.What.Name, e.Subject, e.ActivityDate, e.Description, e.Display_Date__c, e.Display_Name__c));
			}
			
		}	
		return null;
	}
	 
	//function to search attendances
	public PageReference reset(){
		PageReference pg = Page.PortalAttendancePage;
		pg.setRedirect(true);
		return pg;
	}
    
    public class AttendanceWrapper{
    	public String groupName{get;set;}
    	public String status {get;set;}
    	//public Task t{get;set;}
    	//public Date attendanceDate {get;set;}
    	public String dateString {get;set;}
    	public String comments {get;set;}
    	public Integer rt {get;set;}
    	public string displayName {get;set;}
    	public AttendanceWrapper(String gn, String s, Date d, String c, string displayDate, string dName){
    		groupName = gn;
    		status =  s;
    		displayName = dName;
    		//dateString = d.format();
    		dateString = displayDate;
    		comments = c;
    		if(s.equalsIgnoreCase('Absent') || s.equalsIgnoreCase('Unauthorised Absence') || s.equalsIgnoreCase('Authorised Absence')){
    			rt = 4;
    		}else if(s.equalsIgnoreCase('Late')){
    			rt = 3;
    		}else if(s.equalsIgnoreCase('Partial')){
    			rt = 1;
    		}else if(s.equalsIgnoreCase('External Activity')){
    			rt = 2;
    		}
    		if(comments == null || comments == ''){
    			comments = 'No comments available.';
    		}
    	}
    } 
    
    
	
}