force-app/main/default/objects/Assesment__c.object
<CustomObject>
    <fields>
        <fullName>Achievement__c</fullName>
        <inlineHelpText>★★★★ = highest</inlineHelpText>
        <label>Achievement</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>----EYFS/PRIMARY----</fullName>
                </value>
                <value>
                    <fullName>★★★★</fullName>
                </value>
                <value>
                    <fullName>★★★</fullName>
                </value>
                <value>
                    <fullName>★★</fullName>
                </value>
                <value>
                    <fullName>★</fullName>
                </value>
                <value>
                    <fullName>A</fullName>
                </value>
                <value>
                    <fullName>B</fullName>
                </value>
                <value>
                    <fullName>C</fullName>
                </value>
                <value>
                    <fullName>D</fullName>
                </value>
                <value>
                    <fullName>-------------</fullName>
                </value>
                <value>
                    <fullName>Excellent</fullName>
                </value>
                <value>
                    <fullName>Good</fullName>
                </value>
                <value>
                    <fullName>Satisfactory</fullName>
                </value>
                <value>
                    <fullName>Improvement Needed</fullName>
                </value>
                <value>
                    <fullName>Cause for Concern</fullName>
                </value>
                <value>
                    <fullName>------------</fullName>
                </value>
                <value>
                    <fullName>Above Expected Level</fullName>
                </value>
                <value>
                    <fullName>Meeting Expectations</fullName>
                </value>
                <value>
                    <fullName>Below Expected Level</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Approval_Comments__c</fullName>
        <label>Comments for Parents</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Assessment_Date__c</fullName>
        <label>Assessment Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Assessment_Folder__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Assessment Folder</label>
        <referenceTo>Assesment__c</referenceTo>
        <relationshipLabel>Assessments</relationshipLabel>
        <relationshipName>Assessments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Assessment_Name__c</fullName>
        <formula>Assessment_Folder__r.Title__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Assessment Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Auto_Approve__c</fullName>
        <formula>IF(
   OR(
      TEXT(Assessment_Folder__r.Type__c) = &quot;Assignment&quot;, 
      TEXT(Assessment_Folder__r.Type__c) = &quot;Test&quot;
      ), 
   TRUE, 
   IF(
      TEXT(Assessment_Folder__r.Type__c) = &quot;Tracking&quot;, 
      FALSE, 
      Is_Approved__c
      )
   )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Visible in Parent Portal</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Auto_Publish__c</fullName>
        <description>Defines the parameters on which an assessment is published</description>
        <formula>IF(TEXT(Type__c) = &quot;Tracking&quot;, FALSE, TRUE)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Published</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Comment__c</fullName>
        <label>Comment</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <inlineHelpText>Folder Description</inlineHelpText>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Effort__c</fullName>
        <description>Primary: ★★★★ = highest
Secondary: 1 = highest</description>
        <inlineHelpText>ATL is only used for EYFS reports that include grades. &apos;ATTITUDE TO LEARNING&apos; or &apos;EFFORT&apos; will appear in the parent portal based on the Year Group a student is in when an assessment is added.</inlineHelpText>
        <label>Effort/ATL</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>----EYFS/PRIMARY----</fullName>
                </value>
                <value>
                    <fullName>★★★★</fullName>
                </value>
                <value>
                    <fullName>★★★</fullName>
                </value>
                <value>
                    <fullName>★★</fullName>
                </value>
                <value>
                    <fullName>★</fullName>
                </value>
                <value>
                    <fullName>------SECONDARY------</fullName>
                </value>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
                <value>
                    <fullName>4</fullName>
                </value>
                <value>
                    <fullName>--------------</fullName>
                </value>
                <value>
                    <fullName>A</fullName>
                </value>
                <value>
                    <fullName>B</fullName>
                </value>
                <value>
                    <fullName>C</fullName>
                </value>
                <value>
                    <fullName>D</fullName>
                </value>
                <value>
                    <fullName>-------------</fullName>
                </value>
                <value>
                    <fullName>Excellent</fullName>
                </value>
                <value>
                    <fullName>Good</fullName>
                </value>
                <value>
                    <fullName>Satisfactory</fullName>
                </value>
                <value>
                    <fullName>Improvement Needed</fullName>
                </value>
                <value>
                    <fullName>Cause for Concern</fullName>
                </value>
                <value>
                    <fullName>------------</fullName>
                </value>
                <value>
                    <fullName>Above Expected Level</fullName>
                </value>
                <value>
                    <fullName>Meeting Expectations</fullName>
                </value>
                <value>
                    <fullName>Below Expected Level</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Grade__c</fullName>
        <label>Grade</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Group__c</fullName>
        <label>Group</label>
        <referenceTo>Group__c</referenceTo>
        <relationshipLabel>Assessments</relationshipLabel>
        <relationshipName>Assessments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>School__c</fullName>
        <formula>Text( Group__r.Owner:User.School__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>School</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Student__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Student</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Assessments</relationshipLabel>
        <relationshipName>Assessments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Term__c</fullName>
        <formula>IF(
   Term_Manual_Override__c = TRUE,
   TEXT(Manual_Term__c),
   IF(
      RecordType.Name = &quot;Assessment Folder&quot;, 
      IF(
         AND(
             MONTH(Assessment_Date__c)&gt;7,
             MONTH(Assessment_Date__c)&lt;13
             ),
         &quot;Term 1&quot;,
         IF(
            AND(
                MONTH(Assessment_Date__c)&gt;=1,
                (OR(
                    MONTH(Assessment_Date__c)&lt;4,
                    (AND(
                         MONTH(Assessment_Date__c)=4,
                         DAY(Assessment_Date__c)&lt;11
                         )
                     )
                     )
                 )
             ),
          &quot;Term 2&quot;,
          &quot;Term 3&quot;)
       ),  
    Assessment_Folder__r.Term_Copy__c )
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Term</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <label>Title</label>
        <length>65</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <inlineHelpText>Parent Portal Visibility
1) Progress Reports &amp; Examinations: Require Headteacher Approval
2) Tests &amp; Assignments: Visible in Portal on Save
3) Tracking: Never Visible in Portal</inlineHelpText>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Progress Report</fullName>
                </value>
                <value>
                    <fullName>Examination</fullName>
                </value>
                <value>
                    <fullName>Test</fullName>
                </value>
                <value>
                    <fullName>Assignment</fullName>
                </value>
                <value>
                    <fullName>Tracking</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Assessment</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assessments</pluralLabel>
    <recordTypes>
        <fullName>Assessment_Folder</fullName>
        <active>true</active>
        <label>Assessment Folder</label>
    </recordTypes>
    <recordTypes>
        <fullName>Assessment_Record</fullName>
        <active>true</active>
        <label>Assessment Record</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>School__c</fullName>
        <formula>Admissions_File__r.School__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>School</label>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Contact</fullName>
        <active>true</active>
        <label>Contact</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Group__c.object
<CustomObject>
    <fields>
        <fullName>Approver__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Approver</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2</booleanFilter>
            <filterItems>
                <field>User.Profile.Name</field>
                <operation>equals</operation>
                <value>Teacher</value>
            </filterItems>
            <filterItems>
                <field>User.Profile.Name</field>
                <operation>equals</operation>
                <value>Headteacher / of Admin / of Finance</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>Student_Groups</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <description>Used to define the name of a student group (standard naming convention)</description>
        <inlineHelpText>Usually not required. Add any text here that you want to append to the standard group name.</inlineHelpText>
        <label>Group Name Extension</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>School__c</fullName>
        <formula>TEXT(Owner:User.School__c)</formula>
        <label>School</label>
        <type>Text</type>
    </fields>
    <label>Student Group</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Student Groups</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/User.object
<CustomObject>
    <fields>
        <fullName>School__c</fullName>
        <label>School</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>The British Schools Foundation</fullName>
                </value>
                <value>
                    <fullName>The British School of Guangzhou</fullName>
                </value>
                <value>
                    <fullName>The British School of Nanjing</fullName>
                </value>
                <value>
                    <fullName>The British International School of Marbella</fullName>
                </value>
                <value>
                    <fullName>The British School of Navarra</fullName>
                </value>
                <value>
                    <fullName>The British School of Tashkent</fullName>
                </value>
                <value>
                    <fullName>The British College of Brazil</fullName>
                </value>
                <value>
                    <fullName>The British International School of Kuala Lumpur</fullName>
                </value>
                <value>
                    <fullName>The International School of Moscow</fullName>
                </value>
                <value>
                    <fullName>Nord Anglia International School Manila</fullName>
                </value>
                <value>
                    <fullName>King&apos;s College Beijing</fullName>
                </value>
                <value>
                    <fullName>The British School Yangon</fullName>
                </value>
                <value>
                    <fullName>Ukraine International School</fullName>
                </value>
                <value>
                    <fullName>The New York International School</fullName>
                </value>
                <value>
                    <fullName>The British School of Brasilia</fullName>
                </value>
                <value>
                    <fullName>NAE</fullName>
                </value>
                <value>
                    <fullName>The British International School Yangon</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/classes/AssessmentApproval_Controller.cls
/***
 	Author: Kunal Sharma 
 	Date: 17th June 2013
 	Desc: VF page to be used  by HeadMasters for assessmnents approval
***/

public class AssessmentApproval_Controller {
	public List<SelectOption> groupList {get;set;}
	public List<SelectOption> assessmentFolderList {get;set;}
	public String selectedGroup {get;set;}
	public String selectedFolder {get;set;}
	public boolean selectAll {get;set;}
	public List<Assesment__c> assessments {get;set;}
	private Set<Id> groupIds {get;set;}
	private Set<Id> folderIds {get;set;}
	private String loggedInUserSchool {get;set;}
	//constructor
	public AssessmentApproval_Controller(){
		selectedGroup= '-';
		selectedFolder = '-';
		//check for logged in user
		Id uid  =  UserInfo.getUserId();
		loggedInUserSchool =  [Select School__c from User where Id=:uid].School__c;
		
		fetchGroups();
		//check for URL parameters
		String gid = System.currentPageReference().getParameters().get('gid');
		if(gid != null && gid != ''){
			//fetch 18 char group id
			selectedGroup = [select Id from Group__c where Id=:gid].Id;
			fetchFolders();
		}
		String fid = System.currentPageReference().getParameters().get('fid');
		if(fid != null && fid != ''){
			Assesment__c defaultAssessmet = [select Id,Auto_Publish__c from Assesment__c where Id=:fid];
			if(defaultAssessmet.Auto_Publish__c == true){
				selectedFolder = defaultAssessmet.Id;
				fetchAssessments();
			}
			
		}	
	}
	
	//fetch groups
	private void fetchGroups(){
		//fetch all groups against school for which assessments are pending for approval
		groupIds =  new Set<Id>();
		folderIds = new Set<Id>();
		for(Assesment__c a:[Select a.Term__c, a.Student__c, a.Name, a.Auto_Approve__c, a.Id, a.Group__c, a.Grade__c, a.Effort__c, a.Description__c, a.Comment__c, a.Assessment_Name__c, a.Assessment_Folder__c, a.Assessment_Date__c, a.Achievement__c,a.Approval_Comments__c, a.CreatedDate From Assesment__c a where a.RecordType.DeveloperName = 'Assessment_Record' AND a.Auto_Approve__c =  false AND a.Group__r.Approver__c=:UserInfo.getUserId() AND a.Assessment_Folder__r.Auto_Publish__c = true order by a.Group__r.Name]){
			groupIds.add(a.Group__c);
			folderIds.add(a.Assessment_Folder__c);
		}
		groupList =  new List<SelectOption>();
		groupList.add(new SelectOption('-','--Select Group--'));
		for(Group__c g:[Select Id,Name from Group__c where School__c=:loggedInUserSchool AND Approver__c=:UserInfo.getUserId() AND Id IN:groupIds order by Name]){
			groupList.add(new SelectOption(g.Id,g.Name));
		}
		assessmentFolderList = 	new List<SelectOption>();
		assessmentFolderList.add(new SelectOption('-','--Select Folder--'));
	}
	
	public PageReference fetchFolders(){
		assessments = new List<Assesment__c>();
		assessmentFolderList = 	new List<SelectOption>();
		assessmentFolderList.add(new SelectOption('-','--Select Folder--'));
		//fetch selected group 
		if(selectedGroup ==  null || selectedGroup == '-'){
				
		}else{
			List<String> assessmentType =  new List<String>();
			assessmentType.add('Progress Report');
			assessmentType.add('Examination');
			//fetch folders
			for(Assesment__c a:[Select Id,Name,Title__c from Assesment__c where RecordType.DeveloperName='Assessment_Folder' AND Auto_Publish__c = true AND Type__c IN:assessmentType AND Group__c=:selectedGroup AND Id IN:folderIds order by Name ]){
				assessmentFolderList.add(new SelectOption(a.Id,a.Title__c));
			}
		}
		selectedFolder = '-';
		return null;
	}
	
	public PageReference fetchAssessments(){
		assessments = new List<Assesment__c>();
		if(selectedGroup == '-' || selectedFolder == '-'){
			ApexPages.Message errorMessage = new ApexPages.Message(ApexPages.severity.FATAL, 'Error: Please select Group and Assessment Folder !');
			ApexPages.addMessage(errorMessage);	
			return null;	
		}else{
			for(Assesment__c a:[Select a.Term__c, a.Student__c, a.Name, a.Auto_Approve__c, a.Id, a.Group__c, a.Grade__c, a.Effort__c, a.Description__c, a.Comment__c, a.Assessment_Name__c, a.Assessment_Folder__c, a.Assessment_Date__c, a.Achievement__c,a.Approval_Comments__c ,a.CreatedDate,a.Comments_for_Teacher__c From Assesment__c a where a.RecordType.DeveloperName = 'Assessment_Record' AND a.Auto_Approve__c =  false AND a.Assessment_Folder__c=:selectedFolder order by a.Student__r.Name]){
				assessments.add(a);
			}
		}	
		return null;
	}
	
	public PageReference saveAssessments(){
		try{
			update assessments;
			ApexPages.Message successMessage = new ApexPages.Message(ApexPages.severity.CONFIRM, 'Success: All Assessments are successfully updated !');
			ApexPages.addMessage(successMessage);
		}catch(Exception e){
			ApexPages.Message errorMessage = new ApexPages.Message(ApexPages.severity.FATAL, 'Data Error: Ooops something went wrong ! If error persists please contact system administrator with following error message :'+e.getMessage());
			ApexPages.addMessage(errorMessage);
		} 	
		return null;
	}
	
	public PageReference selectAllAssessments(){
		If(assessments != null){
			for(Assesment__c a:assessments){
				a.Is_Approved__c = selectAll;
			}
		}
		return null;
	}
}