force-app/main/default/objects/Assesment__c.object
<CustomObject>
    <fields>
        <fullName>Achievement__c</fullName>
        <inlineHelpText>★★★★ = highest</inlineHelpText>
        <label>Achievement</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>----EYFS/PRIMARY----</fullName>
                </value>
                <value>
                    <fullName>★★★★</fullName>
                </value>
                <value>
                    <fullName>★★★</fullName>
                </value>
                <value>
                    <fullName>★★</fullName>
                </value>
                <value>
                    <fullName>★</fullName>
                </value>
                <value>
                    <fullName>A</fullName>
                </value>
                <value>
                    <fullName>B</fullName>
                </value>
                <value>
                    <fullName>C</fullName>
                </value>
                <value>
                    <fullName>D</fullName>
                </value>
                <value>
                    <fullName>-------------</fullName>
                </value>
                <value>
                    <fullName>Excellent</fullName>
                </value>
                <value>
                    <fullName>Good</fullName>
                </value>
                <value>
                    <fullName>Satisfactory</fullName>
                </value>
                <value>
                    <fullName>Improvement Needed</fullName>
                </value>
                <value>
                    <fullName>Cause for Concern</fullName>
                </value>
                <value>
                    <fullName>------------</fullName>
                </value>
                <value>
                    <fullName>Above Expected Level</fullName>
                </value>
                <value>
                    <fullName>Meeting Expectations</fullName>
                </value>
                <value>
                    <fullName>Below Expected Level</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Approval_Comments__c</fullName>
        <label>Comments for Parents</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Assessment_Date__c</fullName>
        <label>Assessment Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Assessment_Folder__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Assessment Folder</label>
        <referenceTo>Assesment__c</referenceTo>
        <relationshipLabel>Assessments</relationshipLabel>
        <relationshipName>Assessments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Auto_Approve__c</fullName>
        <formula>IF(
   OR(
      TEXT(Assessment_Folder__r.Type__c) = &quot;Assignment&quot;, 
      TEXT(Assessment_Folder__r.Type__c) = &quot;Test&quot;
      ), 
   TRUE, 
   IF(
      TEXT(Assessment_Folder__r.Type__c) = &quot;Tracking&quot;, 
      FALSE, 
      Is_Approved__c
      )
   )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Visible in Parent Portal</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Comment__c</fullName>
        <label>Comment</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Comments_for_Teacher__c</fullName>
        <label>Comments for Teachers</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Effort__c</fullName>
        <description>Primary: ★★★★ = highest
Secondary: 1 = highest</description>
        <inlineHelpText>ATL is only used for EYFS reports that include grades. &apos;ATTITUDE TO LEARNING&apos; or &apos;EFFORT&apos; will appear in the parent portal based on the Year Group a student is in when an assessment is added.</inlineHelpText>
        <label>Effort/ATL</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>----EYFS/PRIMARY----</fullName>
                </value>
                <value>
                    <fullName>★★★★</fullName>
                </value>
                <value>
                    <fullName>★★★</fullName>
                </value>
                <value>
                    <fullName>★★</fullName>
                </value>
                <value>
                    <fullName>★</fullName>
                </value>
                <value>
                    <fullName>------SECONDARY------</fullName>
                </value>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
                <value>
                    <fullName>4</fullName>
                </value>
                <value>
                    <fullName>--------------</fullName>
                </value>
                <value>
                    <fullName>A</fullName>
                </value>
                <value>
                    <fullName>B</fullName>
                </value>
                <value>
                    <fullName>C</fullName>
                </value>
                <value>
                    <fullName>D</fullName>
                </value>
                <value>
                    <fullName>-------------</fullName>
                </value>
                <value>
                    <fullName>Excellent</fullName>
                </value>
                <value>
                    <fullName>Good</fullName>
                </value>
                <value>
                    <fullName>Satisfactory</fullName>
                </value>
                <value>
                    <fullName>Improvement Needed</fullName>
                </value>
                <value>
                    <fullName>Cause for Concern</fullName>
                </value>
                <value>
                    <fullName>------------</fullName>
                </value>
                <value>
                    <fullName>Above Expected Level</fullName>
                </value>
                <value>
                    <fullName>Meeting Expectations</fullName>
                </value>
                <value>
                    <fullName>Below Expected Level</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Grade__c</fullName>
        <label>Grade</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Group__c</fullName>
        <label>Group</label>
        <referenceTo>Group__c</referenceTo>
        <relationshipLabel>Assessments</relationshipLabel>
        <relationshipName>Assessments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Include_Target_Predicted_Grade__c</fullName>
        <inlineHelpText>Optional; select &apos;Target&apos; or &apos;Predicted&apos; if you wish to record one of these grade types for the assessments in this folder. Only available for &apos;Progress Reports&apos; and &apos;Examinations&apos;</inlineHelpText>
        <label>Include Target/Predicted Grade?</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Target</fullName>
                </value>
                <value>
                    <fullName>Predicted</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Is_Approved__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Approved</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Student__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Student</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Assessments</relationshipLabel>
        <relationshipName>Assessments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Target_Predicted_Grade__c</fullName>
        <label>Target/Predicted Grade</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <label>Title</label>
        <length>65</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <inlineHelpText>Parent Portal Visibility
1) Progress Reports &amp; Examinations: Require Headteacher Approval
2) Tests &amp; Assignments: Visible in Portal on Save
3) Tracking: Never Visible in Portal</inlineHelpText>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Progress Report</fullName>
                </value>
                <value>
                    <fullName>Examination</fullName>
                </value>
                <value>
                    <fullName>Test</fullName>
                </value>
                <value>
                    <fullName>Assignment</fullName>
                </value>
                <value>
                    <fullName>Tracking</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Assessment</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assessments</pluralLabel>
    <recordTypes>
        <fullName>Assessment_Record</fullName>
        <active>true</active>
        <label>Assessment Record</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Stage__c</fullName>
        <formula>IF(AND(TEXT(Admissions_File__r.Add_to_Register__c)=&quot;Yes&quot;, TEXT(Admissions_File__r.StageName) = &quot;A/ Deposit&quot;), &quot;Enrolled&quot;, Text(Admissions_File__r.StageName))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Stage</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Starting_Date_from_student__c</fullName>
        <formula>Admissions_File__r.CloseDate</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Student Starting Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Student_Full_Name__c</fullName>
        <formula>Admissions_File__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Student Full Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Student_Name__c</fullName>
        <formula>IF(Admissions_File__r.Nickname__c &lt;&gt; &quot;&quot;, LastName&amp;&quot;, &quot;&amp;FirstName&amp;&quot; (&quot;&amp;Admissions_File__r.Nickname__c&amp;&quot;)&quot;,

LastName&amp;&quot;, &quot;&amp;FirstName)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Student Name</label>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Contact</fullName>
        <active>true</active>
        <label>Contact</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Group__c.object
<CustomObject>
    <fields>
        <fullName>Approver__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Approver</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2</booleanFilter>
            <filterItems>
                <field>User.Profile.Name</field>
                <operation>equals</operation>
                <value>Teacher</value>
            </filterItems>
            <filterItems>
                <field>User.Profile.Name</field>
                <operation>equals</operation>
                <value>Headteacher / of Admin / of Finance</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>Student_Groups</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Student Group</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Student Groups</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Registration__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>whether registration is active or not</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Group__c</fullName>
        <inlineHelpText>select group against which assessment is done.</inlineHelpText>
        <label>Group</label>
        <referenceTo>Group__c</referenceTo>
        <relationshipLabel>Registrations</relationshipLabel>
        <relationshipName>Assessments_Registrations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Include_in_Assessment_Folder__c</fullName>
        <formula>OR(
   Active__c = TRUE,  
   AND(
       Active__c = FALSE, 
       OR(
          Registration_Deactivated_Date__c + 30 &gt;= TODAY(),
          Student__r.Admissions_File__r.Include_in_Reports_if_Left__c = TRUE),
       NOT(ISBLANK(Student__r.Admissions_File__r.Leaving_Date__c)), 
       NOT(ISBLANK(Registration_Deactivated_Date__c)),
       OR(       
          Registration_Deactivated_Date__c = Student__r.Admissions_File__r.Leaving_Date__c,
          Registration_Deactivated_Date__c = Student__r.Admissions_File__r.Leaving_Date__c+1
          ) 
       )
   )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Include in Assessment Folder</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Student_Name__c</fullName>
        <formula>Student__r.Student_Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Student Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Student__c</fullName>
        <inlineHelpText>select student for this enrolment</inlineHelpText>
        <label>Student</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Registrations</relationshipLabel>
        <relationshipName>Registrations</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Registration</label>
    <nameField>
        <displayFormat>R-{000000}</displayFormat>
        <label>Registration #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Registrations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/BulkAssessments_Controller.cls
/***
	Author: Kunal Sharma
	Created Date: 01 April 2013
	Desc: VF controller to handle bulk assessments
***/

public with sharing class BulkAssessments_Controller {   
	public Id groupId{get;set;}
	public Group__c grp{get;set;}
	public Assesment__c folder {get;set;}
	private boolean warningMessageDisplayed;
    private Id assessmentRTId;
    private Map<Id,Assesment__c> studentAssessmentMap ;
     private Map<Id,Assesment__c> studentAssessmentMapForComparison ;
    public List<AssessmentRecord> assessments {get;set;}
    //constructor
    public BulkAssessments_Controller(ApexPages.StandardController controller) {
		warningMessageDisplayed = false;
		groupId = controller.getId();
		grp = [Select Id,Name,Approver__c from Group__c where Id=:groupId];
		folder = [Select Include_Target_Predicted_Grade__c, Id,Name,Title__c,Type__c,Assessment_Date__c from Assesment__c where Id=:System.currentPageReference().getParameters().get('fid')];
		assessmentRTId = [Select Id from RecordType where SObjectType='Assesment__c' AND DeveloperName='Assessment_Record' limit 1].Id;
    	string s_param = system.currentPageReference().getParameters().get('s');
    	if(s_param != null && s_param == '1'){
    		ApexPages.Message successMessage = new ApexPages.Message(ApexPages.severity.CONFIRM, 'Success: All assessments are successfully updated.');
			ApexPages.addMessage(successMessage);
    	}
    	initialize();
    }
    
    //function to fetch all existing assessment records 
    private void initialize(){
    	studentAssessmentMap =  new  Map<Id,Assesment__c>();
    	//studentAssessmentMapForComparison  =  new  Map<Id,Assesment__c>();
    	//for(Assesment__c a:[Select Id,Approval_Comments__c,Auto_Approve__c,Name,Achievement__c,Comment__c,Effort__c,Grade__c,Group__c,Student__c,Student__r.Name,Student__r.Student_Full_Name__c, Student__r.Student_Name__c, Comments_for_Teacher__c from Assesment__c where Assessment_Folder__c=:folder.Id AND Group__c=:groupId order by Student__r.Student_Name__c asc]){
    	for(Assesment__c a:[Select Target_Predicted_Grade__c, Id,Approval_Comments__c,Auto_Approve__c,Name,Achievement__c,Comment__c,Effort__c,Grade__c,Group__c,Student__c,Student__r.Name,Student__r.Student_Full_Name__c, Student__r.Stage__c , Student__r.Student_Name__c, Comments_for_Teacher__c from Assesment__c where Assessment_Folder__c=:folder.Id AND Group__c=:groupId  order by Student__r.Student_Name__c asc]){
    		studentAssessmentMap.put(a.Student__c,a);
    		//studentAssessmentMapForComparison.put(a.Student__c,a);
    	}
    	//fetch all active registrations under group 
    	assessments =  new List<AssessmentRecord>();
    	//for(Registration__c r:[Select r.Student__c, r.Student__r.Student_Name__c ,r.Student__r.Student_Full_Name__c,  r.Student__r.Name, r.Name, r.Id, r.Group__c, r.Active__c From Registration__c r where r.Group__c=:groupId AND r.Active__c= true AND r.Student__r.Starting_Date_from_student__c <=:folder.Assessment_Date__c  order by r.Student__r.Student_Name__c asc]){
    	for(Registration__c r:[Select Student__r.Stage__c, r.Student__c, r.Student__r.Student_Name__c ,r.Student__r.Student_Full_Name__c,  r.Student__r.Name, r.Name, r.Id, r.Group__c, r.Active__c From Registration__c r where r.Group__c=:groupId AND r.Include_in_Assessment_Folder__c = true AND r.Student__r.Starting_Date_from_student__c <=:folder.Assessment_Date__c  order by r.Student__r.Student_Name__c asc]){
    		//for each active registration , create a assessment record
    		AssessmentRecord ar =  new AssessmentRecord();
    		ar.studentRegistration =  r;
    		if(studentAssessmentMap.get(r.Student__c) != null){
    			ar.assessment = studentAssessmentMap.get(r.Student__c);
    		}else{
    			ar.assessment =  new Assesment__c();
    			ar.assessment.RecordTypeId = assessmentRTId;
    			ar.assessment.Assessment_Folder__c = folder.Id;
    			ar.assessment.Group__c = groupId;
    			ar.assessment.Student__c = r.Student__c;
    			/*//ar.assessment.Is_Approved__c = true;
    			else if(grp.Approver__c == UserInfo.getUserId()){
    				ar.assessment.Is_Approved__c = true;
    			}*/
    			
    		}
    		/*if(folder.Type__c == 'Assignment' || folder.Type__c == 'Test'){
				ar.assessment.Is_Approved__c = true;
			}else{
				ar.assessment.Is_Approved__c = false;
			}*/
    		assessments.add(ar);
    	}
    }  
	
	private boolean compareComments(){
		studentAssessmentMapForComparison  =  new  Map<Id,Assesment__c>();
		for(Assesment__c a:[Select Id,Approval_Comments__c,Auto_Approve__c,Name,Achievement__c,Comment__c,Effort__c,Grade__c,Group__c,Student__c,Student__r.Name,Student__r.Student_Full_Name__c, Student__r.Stage__c , Student__r.Student_Name__c, Comments_for_Teacher__c from Assesment__c where Assessment_Folder__c=:folder.Id AND Group__c=:groupId  order by Student__r.Student_Name__c asc]){
    		studentAssessmentMapForComparison.put(a.Student__c,a);
    	}
		boolean flag = false;
		for(AssessmentRecord a:assessments){
			Assesment__c existingAssessment = studentAssessmentMapForComparison.get(a.assessment.Student__c);
			if(existingAssessment != null){
				if(a.assessment.Comment__c == null || a.assessment.Comment__c == ''){
					if(existingAssessment.Comment__c != null && existingAssessment.Comment__c != ''){
						flag = true;
						break;
					}
				}
			}
		}
		return flag;
	}
	
	//function to save assessments 
	public PageReference saveAssessments(){
		PageReference pg;
		try{
			if(compareComments() && !warningMessageDisplayed){
				ApexPages.Message warningMessage = new ApexPages.Message(ApexPages.severity.WARNING, 'Warning: One or more of the assessment comment fields has been changed to blank. If you continue this will delete the previous assessment comment that was in the relevant cell. Changes once made can not be reverted! Please click \'Save\' if you are sure you want to continue.');
				ApexPages.addMessage(warningMessage);
				warningMessageDisplayed = true;	
				return null;
			}
			List<Assesment__c> updatedAssessments =  new List<Assesment__c>();
			List<Assesment__c> deletedAssessments =  new List<Assesment__c>();
			//iterate all assessements to 
			for(AssessmentRecord a:assessments){
				boolean isComment = false;
				String assessmentComment = a.assessment.Comment__c;
				if(assessmentComment != null){
					if(assessmentComment.trim() != ''){
						isComment = true;
					}
				}
				if(a.assessment.Id == null){ //for new assessments
					if(a.assessment.Achievement__c != null || a.assessment.Effort__c != null || a.assessment.Grade__c != null || isComment){
						updatedAssessments.add(a.assessment);
					}
				}else{ //for existing assessments
					if(a.assessment.Achievement__c != null || a.assessment.Effort__c != null || a.assessment.Grade__c != null || isComment){
						updatedAssessments.add(a.assessment);
					}else{
						deletedAssessments.add(a.assessment);
					}
				}
			}
			if(updatedAssessments.size() > 0){
				upsert updatedAssessments;
				pg = Page.BulkAssessments;
				pg.getParameters().put('id',groupId);
				pg.getParameters().put('fid',folder.Id);
				pg.getParameters().put('s','1');
				pg.setRedirect(true);
			}
			if(deletedAssessments.size() > 0){
				delete deletedAssessments;
				pg = Page.BulkAssessments;
				pg.getParameters().put('id',groupId);
				pg.getParameters().put('fid',folder.Id);
				pg.getParameters().put('s','1');
				pg.setRedirect(true);
			}
			
			//ApexPages.Message successMessage = new ApexPages.Message(ApexPages.severity.CONFIRM, 'Success: All assessments are successfully updated.');
			//ApexPages.addMessage(successMessage);
		}catch(Exception e){
			ApexPages.Message errorMessage = new ApexPages.Message(ApexPages.severity.FATAL, 'Failure: Ooops ..Failed to update assessments. Please contact admin@britishschools.co.uk and provide follwing error message: '+e.getMessage());
			ApexPages.addMessage(errorMessage);	
			pg =null;
		}
		
		return pg;
	}
	
	//wrapper class for assesments records
	public class AssessmentRecord{
		public Registration__c studentRegistration{get;set;}
		public Assesment__c assessment{get;set;}
	}
}