force-app/main/default/objects/Assesment__c.object
<CustomObject>
    <fields>
        <fullName>Assessment_Date__c</fullName>
        <label>Assessment Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Auto_Publish__c</fullName>
        <description>Defines the parameters on which an assessment is published</description>
        <formula>IF(TEXT(Type__c) = &quot;Tracking&quot;, FALSE, TRUE)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Published</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <inlineHelpText>Folder Description</inlineHelpText>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Exam_Type__c</fullName>
        <label>Exam Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>SAT</fullName>
                </value>
                <value>
                    <fullName>GCSE</fullName>
                </value>
                <value>
                    <fullName>A-Level</fullName>
                </value>
                <value>
                    <fullName>Internal</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Grade_Type__c</fullName>
        <label>Exam Sub-Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Exam</fullName>
                </value>
                <value>
                    <fullName>Mock Exam</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Group__c</fullName>
        <label>Group</label>
        <referenceTo>Group__c</referenceTo>
        <relationshipLabel>Assessments</relationshipLabel>
        <relationshipName>Assessments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Include_Target_Predicted_Grade__c</fullName>
        <inlineHelpText>Optional; select &apos;Target&apos; or &apos;Predicted&apos; if you wish to record one of these grade types for the assessments in this folder. Only available for &apos;Progress Reports&apos; and &apos;Examinations&apos;</inlineHelpText>
        <label>Include Target/Predicted Grade?</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Target</fullName>
                </value>
                <value>
                    <fullName>Predicted</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <label>Title</label>
        <length>65</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <inlineHelpText>Parent Portal Visibility
1) Progress Reports &amp; Examinations: Require Headteacher Approval
2) Tests &amp; Assignments: Visible in Portal on Save
3) Tracking: Never Visible in Portal</inlineHelpText>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Progress Report</fullName>
                </value>
                <value>
                    <fullName>Examination</fullName>
                </value>
                <value>
                    <fullName>Test</fullName>
                </value>
                <value>
                    <fullName>Assignment</fullName>
                </value>
                <value>
                    <fullName>Tracking</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Assessment</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assessments</pluralLabel>
    <recordTypes>
        <fullName>Assessment_Folder</fullName>
        <active>true</active>
        <label>Assessment Folder</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Group__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <description>Used to define the name of a student group (standard naming convention)</description>
        <inlineHelpText>Usually not required. Add any text here that you want to append to the standard group name.</inlineHelpText>
        <label>Group Name Extension</label>
        <type>TextArea</type>
    </fields>
    <label>Student Group</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Student Groups</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/NewUpdateFolder_Controller.cls
public with sharing class NewUpdateFolder_Controller {
	private Id folderId;
	public Id groupId {get;set;}
	public boolean isNew {get;set;}
	
	public Assesment__c folder{get;set;}
    public NewUpdateFolder_Controller(ApexPages.StandardController controller) {
		folderId = controller.getId();
		groupId = System.currentPageReference().getParameters().get('grpid');
		Id folderRTId = [Select Id from RecordType where SObjectType='Assesment__c' AND DeveloperName='Assessment_Folder' limit 1].Id;
		if(folderId ==  null){
			isNew =  true;
			folder =  new Assesment__c();
			folder.RecordTypeId = folderRTId;
			folder.Group__c = groupId;
		}else{
			isNew =  false;
			folder = [Select Include_Target_Predicted_Grade__c,Grade_Type__c, Exam_Type__c,Id,Assessment_Date__c, Name, Auto_Publish__c, Group__c, Title__c, Type__c ,Description__c from Assesment__c where Id=:folderId];			
		}
		
    }
    
    public PageReference folderTypeChange(){
    	
    	folder.Type__c = system.currentPageReference().getParameters().get('ft');
    	
    	system.debug('****NewUpdateFolder_Controller***folderTypeChange***folder.Type__c='+folder.Type__c);
    	return null;
    }
    
    //navigation to be changed
    public PageReference saveNewFolder(){
    	
    	try{
    		insert folder;
    	}catch(Exception e){
    		ApexPages.Message errorMessage = new ApexPages.Message(ApexPages.severity.FATAL, e.getMessage());
			ApexPages.addMessage(errorMessage);	
    	}
    	
    	return null;
    }
    //navigation to be changed
    public PageReference updateExistingFolder(){
    	
    	try{
    		if(folder.Type__c != 'Examination' && folder.Type__c != 'Progress Report'){
    			folder.Include_Target_Predicted_Grade__c = null;
    		}
    		update folder;
    	}catch(Exception e){
    		ApexPages.Message errorMessage = new ApexPages.Message(ApexPages.severity.FATAL, e.getMessage());
			ApexPages.addMessage(errorMessage);	
    	}
    	
    	return null;
    }
    
    
    public PageReference editExistingFolder(){
    	PageReference pg  =  Page.NewUpdateFolder;
    	pg.getParameters().put('id',folder.Id);
    	pg.getParameters().put('grpid',groupId);
    	pg.setRedirect(true);
    	return pg;
    }
	
}