force-app/main/default/objects/Assesment__c.object
<CustomObject>
    <fields>
        <fullName>External_Examination__c</fullName>
        <label>External Examination</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Type__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>SAT</fullName>
                </value>
                <value>
                    <fullName>IGCSE</fullName>
                </value>
                <value>
                    <fullName>AS Level</fullName>
                </value>
                <value>
                    <fullName>A Level</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Folder_Order__c</fullName>
        <formula>IF(
   Folder_Order_Manual_Override__c = FALSE,
   VALUE(Folder_Order_Text__c),
   VALUE(Manual_Folder_Order__c)
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Folder Order</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Grade__c</fullName>
        <label>Grade</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Group_Name__c</fullName>
        <formula>IF( RecordType.Name = &quot;Assessment Record&quot;, Assessment_Folder__r.Group__r.Name, Group__r.Name )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Group Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Group_Type__c</fullName>
        <formula>TEXT(Group__r.Group_Type__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Group Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Group__c</fullName>
        <label>Group</label>
        <referenceTo>Group__c</referenceTo>
        <relationshipLabel>Assessments</relationshipLabel>
        <relationshipName>Assessments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Is_Approved__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Approved</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Mid_Term_Report__c</fullName>
        <label>Mid Term Report</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Number_of_Approved_Assessments_in_Folder__c</fullName>
        <label>Number of Approved Assessments in Folder</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Number_of_Assessments_in_Folder__c</fullName>
        <label>Number of Assessments in Folder</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Order_Text__c</fullName>
        <formula>TEXT(YEAR(Assessment_Folder__r.Assessment_Date__c))&amp; 

CASE(Assessment_Folder__r.Term_Copy__c,&quot;Term 1&quot;,&quot;3&quot;,&quot;Term 3&quot;,&quot;2&quot;,&quot;1&quot;)&amp; 

IF(Assessment_Folder__r.Mid_Term_Report__c =&quot;YES&quot;,&quot;0&quot;,&quot;1&quot;)&amp; 

CASE(TEXT(Assessment_Folder__r.Type__c),&quot;Progress Report&quot;,&quot;1&quot;,&quot;Examination&quot;,&quot;1&quot;,&quot;0&quot;)&amp; 

CASE(Assessment_Folder__r.Group__r.Group_Type__c,&quot;School Group&quot;,&quot;2&quot;,&quot;Tutor Group&quot;,&quot;1&quot;,&quot;0&quot;)&amp; 

Assessment_Folder__r.Owner_Order_Copy__c &amp; 

Case(Assessment_Folder__r.Group__r.Subject_Name__c, &quot;Personal, Social and Emotional Development&quot;,&quot;70&quot;, &quot;Communication and Language&quot;,&quot;65&quot;, &quot;Physical Development&quot;,&quot;60&quot;, &quot;English&quot;,&quot;55&quot;, &quot;Literacy&quot;,&quot;54&quot;, &quot;Reading&quot;,&quot;53&quot;, &quot;Writing&quot;,&quot;52&quot;, &quot;Mathematics&quot;,&quot;47&quot;, &quot;Mathematics - Statistics&quot;,&quot;46&quot;, &quot;Numeracy&quot;,&quot;45&quot;, &quot;Understanding the World&quot;,&quot;44&quot;, &quot;Expressive Arts &amp; Design&quot;,&quot;43&quot;, &quot;Science&quot;,&quot;42&quot;, &quot;Physics&quot;,&quot;41&quot;, &quot;Chemistry&quot;,&quot;40&quot;, &quot;Biology&quot;,&quot;39&quot;, &quot;History&quot;,&quot;38&quot;, &quot;Geography&quot;,&quot;37&quot;, &quot;Humanities&quot;,&quot;36&quot;, &quot;Integrated Curriculum&quot;,&quot;35&quot;, &quot;ICT&quot;,&quot;34&quot;, &quot;Computing&quot;,&quot;33&quot;, &quot;Computer Science&quot;,&quot;32&quot;, &quot;Business Studies&quot;,&quot;30&quot;, &quot;Media Studies&quot;,&quot;29&quot;, &quot;Economics&quot;,&quot;28&quot;, &quot;Myanmar&quot;,&quot;26&quot;, &quot;Russian&quot;,&quot;25&quot;, &quot;Chinese&quot;,&quot;24&quot;, &quot;Bahasa&quot;,&quot;23&quot;, &quot;Portuguese&quot;,&quot;22&quot;, &quot;Uzbek&quot;,&quot;21&quot;, &quot;French&quot;,&quot;20&quot;, &quot;Spanish&quot;,&quot;19&quot;, &quot;Dutch&quot;,&quot;18&quot;, &quot;German&quot;,&quot;17&quot;, &quot;Music&quot;,&quot;15&quot;, &quot;Drama&quot;,&quot;14&quot;, &quot;Dance&quot;,&quot;13&quot;, &quot;Art &amp; Design&quot;,&quot;12&quot;, &quot;Graphic Design&quot;,&quot;11&quot;, &quot;PE&quot;,&quot;10&quot;, &quot;Religious Education&quot;,&quot;09&quot;, &quot;Sociology&quot;,&quot;08&quot;, &quot;Psychology&quot;, &quot;07&quot;,&quot;Extended Project&quot;,&quot;03&quot;, &quot;EAL&quot;,&quot;02&quot;, &quot;Learning Support&quot;,&quot;01&quot;, &quot;00&quot;)&amp;

CASE(Assessment_Folder__r.Type__c,&quot;Progress Report&quot;,&quot;2&quot;,&quot;Examination&quot;,&quot;1&quot;,&quot;0&quot;)&amp;

CASE(Assessment_Folder__r.Grade_Type__c, &quot;Exam&quot;, &quot;5&quot;, &quot;Predicted Grade&quot;, &quot;4&quot;, &quot;Mock Exam&quot;, &quot;3&quot;, &quot;Target Grade&quot;, &quot;2&quot;, &quot;Current Working Grade&quot;, &quot;1&quot;, &quot;0&quot;)&amp;

LEFT(RIGHT(TEXT(Assessment_Folder__r.CreatedDate), 15), 2) &amp; 
LEFT(RIGHT(TEXT(Assessment_Folder__r.CreatedDate), 12), 2) &amp; 
LEFT(RIGHT(TEXT(Assessment_Folder__r.CreatedDate), 9), 2) &amp; 
LEFT(RIGHT(TEXT(Assessment_Folder__r.CreatedDate), 6), 2) &amp; 
LEFT(RIGHT(TEXT(Assessment_Folder__r.CreatedDate), 3), 2)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Order Text</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <formula>VALUE( Order_Text__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Order</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Parent_Portal_Visibility__c</fullName>
        <formula>IF(OR(AND(OR(TEXT(Type__c) = &quot;Test&quot;, TEXT(Type__c) = &quot;Assignment&quot;), Number_of_Assessments_in_Folder__c &lt;&gt; 0), AND(OR(TEXT(Type__c) = &quot;Progress Report&quot;, TEXT(Type__c) = &quot;Examination&quot;),  Number_of_Assessments_in_Folder__c = Number_of_Approved_Assessments_in_Folder__c, Number_of_Assessments_in_Folder__c &lt;&gt; 0, Number_of_Approved_Assessments_in_Folder__c &lt;&gt; 0)), &quot;Visible in Portal&quot;, 

IF(AND(OR(TEXT(Type__c) = &quot;Progress Report&quot;, TEXT(Type__c) = &quot;Examination&quot;),  Number_of_Assessments_in_Folder__c &lt;&gt; Number_of_Approved_Assessments_in_Folder__c, Number_of_Assessments_in_Folder__c &lt;&gt; 0, Number_of_Approved_Assessments_in_Folder__c &lt;&gt; 0), &quot;Visible to Some Parents&quot;, 

IF(Number_of_Assessments_in_Folder__c = 0, &quot;Nothing to Display&quot;,

&quot;Not Visible in Portal&quot;)))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Parent Portal Visibility</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>School__c</fullName>
        <formula>Text( Group__r.Owner:User.School__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>School</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Student__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Student</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Assessments</relationshipLabel>
        <relationshipName>Assessments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Target_Predicted_Grade__c</fullName>
        <label>Target/Predicted Grade</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Term__c</fullName>
        <formula>IF(
   Term_Manual_Override__c = TRUE,
   TEXT(Manual_Term__c),
   IF(
      RecordType.Name = &quot;Assessment Folder&quot;, 
      IF(
         AND(
             MONTH(Assessment_Date__c)&gt;7,
             MONTH(Assessment_Date__c)&lt;13
             ),
         &quot;Term 1&quot;,
         IF(
            AND(
                MONTH(Assessment_Date__c)&gt;=1,
                (OR(
                    MONTH(Assessment_Date__c)&lt;4,
                    (AND(
                         MONTH(Assessment_Date__c)=4,
                         DAY(Assessment_Date__c)&lt;11
                         )
                     )
                     )
                 )
             ),
          &quot;Term 2&quot;,
          &quot;Term 3&quot;)
       ),  
    Assessment_Folder__r.Term_Copy__c )
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Term</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <label>Title</label>
        <length>65</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <inlineHelpText>Parent Portal Visibility
1) Progress Reports &amp; Examinations: Require Headteacher Approval
2) Tests &amp; Assignments: Visible in Portal on Save
3) Tracking: Never Visible in Portal</inlineHelpText>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Progress Report</fullName>
                </value>
                <value>
                    <fullName>Examination</fullName>
                </value>
                <value>
                    <fullName>Test</fullName>
                </value>
                <value>
                    <fullName>Assignment</fullName>
                </value>
                <value>
                    <fullName>Tracking</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Assessment</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assessments</pluralLabel>
    <recordTypes>
        <fullName>Assessment_Record</fullName>
        <active>true</active>
        <label>Assessment Record</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Group__c.object
<CustomObject>
    <fields>
        <fullName>Group_Name__c</fullName>
        <formula>IF( TEXT(Group_Type__c) =&quot;Tutor Group&quot;,

(IF( TEXT(Combined_Year_Group__c) =&quot;&quot;,

 TEXT(Year_Group__c)&amp;&quot; &quot;&amp;  Owner:User.Alias,
 TEXT(Year_Group__c) &amp;&quot;-&quot;&amp; Combined_Year_Group_Abb__c&amp;&quot; &quot;&amp; Owner:User.Alias  )),IF(TEXT(Group_Type__c) == &apos;School Group&apos;,&apos;&apos;, TEXT(Subject_Name__c)))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Group Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Group_Type__c</fullName>
        <label>Group Type</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Year_Group_Control__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Tutor Group</fullName>
                </value>
                <value>
                    <fullName>Subject</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>School Group</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>School__c</fullName>
        <formula>TEXT(Owner:User.School__c)</formula>
        <label>School</label>
        <type>Text</type>
    </fields>
    <label>Student Group</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Student Groups</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/StudentAssessments_Controller.cls
public with sharing class StudentAssessments_Controller {
	private Id studentId;
    public list<Assesment__c> assessments {get;set;}
    public StudentAssessments_Controller(ApexPages.StandardController controller) {
		studentId = controller.getId();
		fetchAssessments();
    }
    private void fetchAssessments(){
    	assessments = new list<Assesment__c>();
    	for(Assesment__c a:[Select a.Target_Predicted_Grade__c, a.Type__c, a.Title__c, a.Term__c, a.Student__c, a.School__c, a.Parent_Portal_Visibility__c, a.Order__c, a.Order_Text__c, a.Number_of_Assessments_in_Folder__c, a.Number_of_Approved_Assessments_in_Folder__c, a.Name, a.Mid_Term_Report__c, a.Is_Approved__c, a.Id, a.Group__c, a.Group_Type__c, a.Group_Name__c, a.Grade__c, a.Folder_Order__c, a.External_Examination__c, a.Effort__c, a.Description__c, a.Comment__c, a.Auto_Publish__c, a.Auto_Approve__c, a.Assessment_Name__c, a.Assessment_Folder__c, a.Assessment_Display_Name__c, a.Assessment_Date__c, a.Assessment_Date_Copy__c, a.CreatedById, a.Approval_Comments__c, a.Achievement__c, a.Academic_Year__c From Assesment__c a where Student__c=:studentId AND RecordType.DeveloperName = 'Assessment_Record' order by a.Order__c desc, a.Assessment_Folder__r.Assessment_Date__c desc]){
    		assessments.add(a);
    	}
    }

}