force-app/main/default/objects/Conduct__c.object
<CustomObject>
    <fields>
        <fullName>Academic_Year__c</fullName>
        <formula>IF(AND(MONTH(DATEVALUE(CreatedDate))&gt;7,MONTH(DATEVALUE(CreatedDate))&lt;13),TEXT(YEAR(DATEVALUE(CreatedDate)))&amp;&quot;/&quot;&amp; TEXT(CreatedDate_plus_1__c ),TEXT(CreatedDate_minus_1__c)&amp;&quot;/&quot;&amp;TEXT(YEAR(DATEVALUE(CreatedDate))))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Academic Year</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Display_Date__c</fullName>
        <description>The date as it is to be displayed in the parent portal</description>
        <formula>IF($User.Is_US_Locale__c = TRUE,

Display_Month__c&amp;&quot; &quot;&amp; TEXT(DAY(Pastoral_Date__c)) &amp;&quot;, &quot;&amp;TEXT(YEAR(Pastoral_Date__c)),

TEXT(DAY(Pastoral_Date__c))&amp;&quot; &quot;&amp;Display_Month__c&amp;&quot; &quot;&amp;TEXT(YEAR(Pastoral_Date__c)))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Display Date</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Display_Header__c</fullName>
        <description>header text to be displayed on portal</description>
        <formula>IF(AND(RecordType.Name = &quot;Incidents&quot;, Health_Related__c = TRUE), &quot;Incident - Health Related&quot;, CASE(RecordType.Name, &quot;Incidents&quot;, &quot;Incident&quot;, &quot;Achievements&quot;, &quot;Achievement&quot;, RecordType.Name))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Display Header</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Display_Title__c</fullName>
        <description>title text to be displayed on portal</description>
        <formula>Title__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>title text to be displayed on portal</inlineHelpText>
        <label>Display Title</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Display_in_Portal__c</fullName>
        <description>Controls whether or not a pastoral record is visible in the parent portal</description>
        <formula>IF(OR(RecordType.Name = &quot;Achievements&quot;, RecordType.Name = &quot;Incidents&quot;, AND(RecordType.Name = &quot;Effort &amp; Attitude&quot;, TEXT(House_Points__c) &lt;&gt; &quot;&quot;, TEXT(Effort__c) = &quot;&quot;)), TRUE,  Is_Approved__c)</formula>
        <label>Visible in Parent Portal</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Effort__c</fullName>
        <label>Effort</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Excellent</fullName>
                </value>
                <value>
                    <fullName>Good</fullName>
                </value>
                <value>
                    <fullName>Satisfactory</fullName>
                </value>
                <value>
                    <fullName>Improvement Needed</fullName>
                </value>
                <value>
                    <fullName>Cause for Concern</fullName>
                </value>
                <value>
                    <fullName>------------</fullName>
                </value>
                <value>
                    <fullName>Above Expected Level</fullName>
                </value>
                <value>
                    <fullName>Meeting Expectations</fullName>
                </value>
                <value>
                    <fullName>Below Expected Level</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Health_Related__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Health Related</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>House_Points__c</fullName>
        <inlineHelpText>Please enter a number between 1 and 999 to represent the number of house points, merits etc. that are being awarded</inlineHelpText>
        <label>Point Value (Optional)</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>House__c</fullName>
        <formula>Student_Name__r.House__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>House</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Owner_Title__c</fullName>
        <description>auto populated by workflow</description>
        <label>Owner Title</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Pastoral_Date__c</fullName>
        <label>Pastoral Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Private_Comment__c</fullName>
        <label>Internal Comment</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Reason__c</fullName>
        <label>Comment</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>School__c</fullName>
        <formula>Student_Group__r.School__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>School</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Student_Name__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Student Name</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Student Academic File</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Pastorals</relationshipLabel>
        <relationshipName>Behaviour</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <label>Title</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <label>Pastoral</label>
    <nameField>
        <displayFormat>B-{0000}</displayFormat>
        <label>Record Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pastoral</pluralLabel>
    <recordTypes>
        <fullName>Awards</fullName>
        <active>true</active>
        <label>Achievements</label>
    </recordTypes>
    <recordTypes>
        <fullName>Pastoral</fullName>
        <active>true</active>
        <label>Incidents</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Admissions_File__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Admissions File</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>House__c</fullName>
        <formula>TEXT( Admissions_File__r.House__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>House</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>School__c</fullName>
        <formula>Admissions_File__r.School__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>School</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Student_Name__c</fullName>
        <formula>IF(Admissions_File__r.Nickname__c &lt;&gt; &quot;&quot;, LastName&amp;&quot;, &quot;&amp;FirstName&amp;&quot; (&quot;&amp;Admissions_File__r.Nickname__c&amp;&quot;)&quot;,

LastName&amp;&quot;, &quot;&amp;FirstName)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Student Name</label>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Contact</fullName>
        <active>true</active>
        <label>Contact</label>
    </recordTypes>
    <recordTypes>
        <fullName>Student</fullName>
        <active>true</active>
        <label>Student Academic File</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>House__c</fullName>
        <description>Defaults: 
On lead convert: Pending
On student clone: Value of cloned record</description>
        <label>House</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                    <color>#DDDDDD</color>
                    <default>true</default>
                    <label>Pending</label>
                </value>
                <value>
                    <fullName>Romans</fullName>
                    <color>#3333FF</color>
                    <label>Romans</label>
                </value>
                <value>
                    <fullName>Saxons</fullName>
                    <color>#33FF33</color>
                    <label>Saxons</label>
                </value>
                <value>
                    <fullName>Vikings</fullName>
                    <color>#FFCC33</color>
                    <label>Vikings</label>
                </value>
                <value>
                    <fullName>Normans</fullName>
                    <color>#FF0000</color>
                    <label>Normans</label>
                </value>
                <value>
                    <fullName>Jaguars</fullName>
                    <color>#3333FF</color>
                    <label>Jaguars</label>
                </value>
                <value>
                    <fullName>Lions</fullName>
                    <color>#33FF33</color>
                    <label>Lions</label>
                </value>
                <value>
                    <fullName>Tigers</fullName>
                    <color>#FFCC33</color>
                    <label>Tigers</label>
                </value>
                <value>
                    <fullName>Panthers</fullName>
                    <color>#FF0000</color>
                    <label>Panthers</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>School__c</fullName>
        <formula>Account.SchoolText__pc</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>School</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Student_Name__c</fullName>
        <label>Student Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Student</fullName>
        <active>true</active>
        <businessProcess>Standard Admissions Process</businessProcess>
        <label>Student</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/School__c.object
<CustomObject>
    <label>School</label>
    <nameField>
        <label>School Code/UID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Schools</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/User.object
<CustomObject>
    <fields>
        <fullName>Email_Copy__c</fullName>
        <formula>Email</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Email Copy</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>School__c</fullName>
        <label>School</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>The British Schools Foundation</fullName>
                </value>
                <value>
                    <fullName>The British School of Guangzhou</fullName>
                </value>
                <value>
                    <fullName>The British School of Nanjing</fullName>
                </value>
                <value>
                    <fullName>The British International School of Marbella</fullName>
                </value>
                <value>
                    <fullName>The British School of Navarra</fullName>
                </value>
                <value>
                    <fullName>The British School of Tashkent</fullName>
                </value>
                <value>
                    <fullName>The British College of Brazil</fullName>
                </value>
                <value>
                    <fullName>The British International School of Kuala Lumpur</fullName>
                </value>
                <value>
                    <fullName>The International School of Moscow</fullName>
                </value>
                <value>
                    <fullName>Nord Anglia International School Manila</fullName>
                </value>
                <value>
                    <fullName>King&apos;s College Beijing</fullName>
                </value>
                <value>
                    <fullName>The British School Yangon</fullName>
                </value>
                <value>
                    <fullName>Ukraine International School</fullName>
                </value>
                <value>
                    <fullName>The New York International School</fullName>
                </value>
                <value>
                    <fullName>The British School of Brasilia</fullName>
                </value>
                <value>
                    <fullName>NAE</fullName>
                </value>
                <value>
                    <fullName>The British International School Yangon</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Title_Copy__c</fullName>
        <formula>Title</formula>
        <label>Title Copy</label>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/classes/PortalConduct_Controller.cls
public class PortalConduct_Controller extends PortalReportFilter{
	public Integer awards {get;set;}
	public Integer pastoral {get;set;}
	public Integer leadership {get;set;}
	public decimal housePoints {get;set;}
	public String schoolName {get;set;}
	public List<ConductWrapper> conductWrapperList {get;set;}
	public boolean hasItems{get{boolean flag = false;if(conductWrapperList != null){if(conductWrapperList.size() > 0){flag = true;}}return flag;}}
	//function to search attendances
	public PageReference filterConducts(){
		createTabClickEvent('pastoral');
		awards = 0;
		pastoral = 0;
		leadership = 0;
		housePoints = 0;
		conductWrapperList =  new List<ConductWrapper>();		
		System.debug('*****PortalConduct_Controller**filterConducts**selectedStudentId='+selectedStudentId);
		System.debug('*****PortalConduct_Controller**filterConducts**selectedAcademicYear='+selectedAcademicYear);
		System.debug('*****PortalConduct_Controller**filterConducts**conductTypeOptions='+conductTypeOptions);
		//set cookie to current selected student
		Cookie cookie_sid = new Cookie('sid', selectedStudentId,null,-1,false);
		ApexPages.currentPage().setCookies(new Cookie[]{cookie_sid});
		//make list of assessment report types
		List<String> selectedReportTypes =  new List<String>();
		for(PortalReportFilter.ReportTypeWrapper rt:conductTypeOptions){
			if(rt.selected){
				selectedReportTypes.add(rt.reportType);
			}
		}
		//fetch school name basis student selection
		if(selectedStudentId != null && selectedStudentId != '' && selectedAcademicYear != null && selectedAcademicYear != ''){
			schoolName = [Select c.Admissions_File__r.School__c, c.Admissions_File__r.Id, c.Admissions_File__c From Contact c where c.Id=:selectedStudentId].Admissions_File__r.School__c;	
			//fetch user infiormation
			//fetch assessments
			Set<Id> ownerIds =  new Set<Id>();
			Map<Id,User> userMap =  new Map<Id,User>();
			for(Conduct__c conduct:[Select c.Display_Date__c, c.CreatedById  From Conduct__c c where c.Academic_Year__c=:selectedAcademicYear AND c.Student_Name__c=:selectedStudentId AND c.RecordType.Name IN:selectedReportTypes AND c.Display_In_Portal__c = true]){
				ownerIds.add(conduct.CreatedById );
			}
			for(User u:[Select u.Email_Copy__c,u.Title, u.Title_Copy__c , u.SmallPhotoUrl, u.School__c, u.Name, u.LastName, u.IsActive, u.Id, u.FullPhotoUrl, u.FirstName, u.Email, u.Division, u.Department, u.ContactId, u.Alias, u.AboutMe From User u  where u.Id IN:ownerIds]){
				userMap.put(u.Id,u);
			}
			//fetch conduct records 
			for(Conduct__c c:[Select c.Display_Date__c, c.Effort__c ,c.Display_Header__c, c.Display_Title__c, c.Pastoral_Date__c, c.Owner_Title__c, c.Title__c, c.Student_Name__c, c.RecordType.Name, c.RecordTypeId, c.Reason__c, c.Private_Comment__c, c.Name, c.House__c, c.House_Points__c, c.Health_Related__c,  c.CreatedDate, c.CreatedById,  c.Academic_Year__c From Conduct__c c where c.Academic_Year__c=:selectedAcademicYear AND c.Student_Name__c=:selectedStudentId AND c.RecordType.Name IN:selectedReportTypes AND c.Display_In_Portal__c = true order by Pastoral_Date__c desc]){
				String reportType ;
				String comments ;
				String title;
				String titleDescription ; 
				Integer points = 0;
		        String userInfo_Name ;
		        String userInfo_Title ;
		        String userInfo_Email ;
		        String userInfo_PicURL ;
		        System.debug('***PortalConduct_Controller***filterConducts***c='+c);
				title = c.Display_Header__c;
				titleDescription = c.Display_Title__c;
				if(c.RecordType.Name.equalsIgnoreCase('Achievements')){
					awards++;
					
					comments = c.Reason__c;
					reportType = 'Achievements';
				}else if(c.RecordType.Name.equalsIgnoreCase('Incidents')){
					pastoral++;
					
					comments = c.Reason__c;
					reportType = 'Incidents';
					points = 1;
				}/*else if(c.RecordType.Name.equalsIgnoreCase('Leadership Roles')){
					leadership++;
					title = 'Leadership Roles';
					titleDescription = c.Title__c;
					comments = c.Reason__c;
					reportType = 'Leadership Roles';
				}*/else if(c.RecordType.Name.equalsIgnoreCase('Effort & Attitude')){
					if(c.House_Points__c != null){
						housePoints += c.House_Points__c;
					}
					
					comments = c.Reason__c;
					reportType = 'Effort & Attitude';
				}
				System.debug('***PortalConduct_Controller***filterConducts***title='+title);
				userinfo_Name =  userMap.get(c.CreatedById).Name;
				userinfo_Email =  userMap.get(c.CreatedById).Email_Copy__c;
				if(c.Owner_Title__c != null && c.Owner_Title__c != ''){
					userinfo_Title =  c.Owner_Title__c;
				}else{
					userinfo_Title =  userMap.get(c.CreatedById).Title_Copy__c;
				}
				
				userInfo_PicURL =  userMap.get(c.CreatedById).SmallPhotoUrl;
				
				ConductWrapper cw =  new ConductWrapper(c,reportType,comments,title,titleDescription,c.Pastoral_Date__c,userinfo_Name,userinfo_Email,userinfo_Title,userInfo_PicURL,conductWrapperList.size());
				conductWrapperList.add(cw);
			}
		}
		return null;
	}
	 
	//function to search attendances
	public PageReference reset(){
		PageReference pg = Page.PortalConductPage;
		pg.setRedirect(true);
		return pg;
	}
	
	public class ConductWrapper{
		public Conduct__c conduct{get;set;}  
        public String rType {get;set;}
        public String title1 {get;set;}
        public String titleDescription1 {get;set;}
        public String comments {get;set;}
        public Integer points {get;set;}
        public String dateString {get;set;}
        public String userInfo_Name {get;set;}
        public String userInfo_Title {get;set;}
        public String userInfo_Email {get;set;}
        public String userInfo_PicURL {get;set;}
        public Integer index {get;set;}
        public Integer rt {get;set;}
        public ConductWrapper(Conduct__c cd, String recordType,String c,String t, String td,Date d,String name, String email, String title, String pic, Integer i){
            conduct = cd;
            rType = recordType;
            comments = c;
            title1 = t;
            titleDescription1 = td;
            /*if(d != null){
            	dateString =  d.format();
            }else{
            	dateString = (date.valueOf(cd.CreatedDate)).format();
            }*/
            dateString = cd.Display_Date__c;     
            userInfo_Name = name;
            userInfo_Title = title;
            userInfo_Email = email;
            userInfo_PicURL = pic;            
            index = i+1;
            if(rType.equalsIgnoreCase('Incidents')){
            	rt = 4;
            }else if(rType.equalsIgnoreCase('Achievements')){
            	rt = 2;
            }/*else if(rType.equalsIgnoreCase('Leadership Roles')){
            	rt = 3;
            }*/else if(rType.equalsIgnoreCase('Effort & Attitude')){
            	rt = 1;
            } 
        }
    } 
}