force-app/main/default/objects/Conduct__c.object
<CustomObject>
    <fields>
        <fullName>Folder_Description__c</fullName>
        <label>Folder Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Folder_Title__c</fullName>
        <label>Title</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Folder_Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Effort &amp; Attitude</fullName>
                </value>
                <value>
                    <fullName>Achievements</fullName>
                </value>
                <value>
                    <fullName>Incidents</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Folder__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Folder</label>
        <referenceTo>Conduct__c</referenceTo>
        <relationshipLabel>Pastorals</relationshipLabel>
        <relationshipName>Pastorals</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Parent_Portal_Visibility__c</fullName>
        <formula>IF(OR(AND(OR(TEXT(Folder_Type__c) = &quot;Incidents&quot;, TEXT(Folder_Type__c) = &quot;Achievements&quot;), Number_of_Pastorals_in_Folder__c &lt;&gt; 0), AND(TEXT(Folder_Type__c) = &quot;Effort &amp; Attitude&quot;, Number_of_Pastorals_in_Folder__c = Number_of_Approved_Pastorals_in_Folder__c, Number_of_Pastorals_in_Folder__c &lt;&gt; 0, Number_of_Approved_Pastorals_in_Folder__c &lt;&gt; 0)), &quot;Visible in Portal&quot;, 

IF(AND(TEXT(Folder_Type__c) = &quot;Effort &amp; Attitude&quot;, Number_of_Pastorals_in_Folder__c &lt;&gt; Number_of_Approved_Pastorals_in_Folder__c, Number_of_Pastorals_in_Folder__c &lt;&gt; 0, Number_of_Approved_Pastorals_in_Folder__c &lt;&gt; 0), &quot;Visible to Some Parents&quot;, 

IF(Number_of_Pastorals_in_Folder__c = 0, &quot;Nothing to Display&quot;, 

&quot;Not Visible in Portal&quot;)))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Parent Portal Visibility</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Pastoral_Date__c</fullName>
        <label>Pastoral Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Student_Group__c</fullName>
        <label>Student Group</label>
        <referenceTo>Group__c</referenceTo>
        <relationshipLabel>Pastorals</relationshipLabel>
        <relationshipName>Pastoral</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Pastoral</label>
    <nameField>
        <displayFormat>B-{0000}</displayFormat>
        <label>Record Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pastoral</pluralLabel>
    <recordTypes>
        <fullName>Pastoral_Folder</fullName>
        <active>true</active>
        <label>Pastoral Folder</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/ManagePastorals.cls
public with sharing class ManagePastorals {
	public list<Conduct__c> pastoralFolders {get;set;}
    private Id gid{get;set;}
    public ManagePastorals(ApexPages.StandardController controller) {
    	pastoralFolders = new list<Conduct__c>();
		gid = controller.getId();
		for(Conduct__c pastoralFolder:[select CreatedById, Student_Group__c, CreatedDate,LastModifiedDate , Id,Folder_Title__c, Folder_Type__c, Folder_Description__c, Name, Pastoral_Date__c, Parent_Portal_Visibility__c from Conduct__c where RecordType.DeveloperName = 'Pastoral_Folder' AND Student_Group__c=:controller.getId() order by CreatedDate desc]){
			pastoralFolders.add(pastoralFolder);
		}
    }
    public PageReference deleteFolder(){ 
    	string fid = system.currentPageReference().getParameters().get('dfid');
    	if(fid != null && fid != ''){
    		list<Conduct__c> pastorals = new list<Conduct__c>();
    		for(Conduct__c c:[select Id from Conduct__c where Folder__c=:fid]){
    			pastorals.add(c);
    		}
    		if(pastorals.size() >0){
    			delete pastorals;
    		}
    		Conduct__c folder = new Conduct__c(Id=fid);
    		delete folder;
    		PageReference pg  = Page.Tabbed_Group_Detail ; 
    		pg.getParameters().put('id',gId);
    		pg.getParameters().put('stab','pastorals');
    		pg.setRedirect(true);
        	return pg;    		
    	}
    	return null;
    }
    
    public PageReference newFolder(){
    	//string fid = system.currentPageReference().getParameters().get('mfid');
    	PageReference pg  = Page.CreatePastorals ; 
		pg.getParameters().put('id',gId);
		//pg.getParameters().put('fid',fid);
		pg.setRedirect(true);
    	return pg;
    }

}