force-app/main/default/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Contact_Alternate_Email_Opt_Out__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Alternate Email Opt Out</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Contact_Alternate_Email__c</fullName>
        <label>Alternate Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Contact_Alternate_Phone__c</fullName>
        <label>Alternate Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Contact_Relationship__c</fullName>
        <label>Relationship</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Father</fullName>
                </value>
                <value>
                    <fullName>Mother</fullName>
                </value>
                <value>
                    <fullName>Step Father</fullName>
                </value>
                <value>
                    <fullName>Step Mother</fullName>
                </value>
                <value>
                    <fullName>Other Legal Guardian</fullName>
                </value>
                <value>
                    <fullName>Next of Kin</fullName>
                </value>
                <value>
                    <fullName>Grandparent</fullName>
                </value>
                <value>
                    <fullName>Sibling</fullName>
                </value>
                <value>
                    <fullName>Other Relative</fullName>
                </value>
                <value>
                    <fullName>Teacher/Tutor</fullName>
                </value>
                <value>
                    <fullName>Personal Assistant</fullName>
                </value>
                <value>
                    <fullName>Domestic Helper</fullName>
                </value>
                <value>
                    <fullName>Local Emergency Contact</fullName>
                </value>
                <value>
                    <fullName>Driver</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Main_Parent_File__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Family File</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Value does not exist or is not a parent record.</errorMessage>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Parent</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Additional Parents &amp; Student Academic Files</relationshipLabel>
        <relationshipName>Emails</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Staff_Member_Parent_Number_Formula__c</fullName>
        <description>A temporary field using only during migration to allow the auto-number field to be referenced indirectly in apex so that it can be changed to/from an auto-number field as required</description>
        <formula>Staff_Member_Parent_Number__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Contact UID (Formula)</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>xsms__Mobile_Phone_Country_Code__c</fullName>
        <description>country isd code.</description>
        <inlineHelpText>country isd code.</inlineHelpText>
        <label>Mobile Phone Country Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Additional_Parent</fullName>
        <active>true</active>
        <label>Additional Parent</label>
    </recordTypes>
    <recordTypes>
        <fullName>Contact</fullName>
        <active>true</active>
        <label>Contact</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/AdditionalParentList_Controller.cls
public with sharing class AdditionalParentList_Controller {
    public list<Contact> additionalParentList {get;set;}
    public AdditionalParentList_Controller(ApexPages.StandardController controller) {
        additionalParentList =  new list<Contact>();
        //fetch additional parents 
        for(Contact c:[Select c.Staff_Member_Parent_Number_Formula__c, c.Contact_Relationship__c, c.Phone, c.xsms__Mobile_Phone_Country_Code__c, c.Name, c.MobilePhone, c.Main_Parent_File__c, c.Id, c.Email, c.Contact_Alternate_Phone__c, c.Contact_Alternate_Email__c, c.Contact_Alternate_Email_Opt_Out__c, c.AccountId From Contact c where Main_Parent_File__c =:controller.getId() AND RecordType.DeveloperName='Additional_Parent' order by Name]){
            additionalParentList.add(c);
        }
    }

}