force-app/main/default/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Main_Parent_File__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Family File</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Value does not exist or is not a parent record.</errorMessage>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Parent</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Additional Parents &amp; Student Academic Files</relationshipLabel>
        <relationshipName>Emails</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Related_Event_Text_for_Email__c</fullName>
        <description>24/11/14 PENDING DELETION - NEEDS TO BE REMOVED FROM RELEVANT APEX CLASS</description>
        <label>Related Event Text for Email</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Related_Event_Trigger_First_Email_Send__c</fullName>
        <defaultValue>false</defaultValue>
        <description>A field populated via a trigger that will trigger the first event notification email to be sent, via an email alert, to all contacts that the event is relevant to</description>
        <label>Related Event Trigger First Email Send</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Related_Event_for_Email__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>A field populated via a trigger to link an event to a contact for the purposes of sending an email, via an email alert, to all contacts that an event is relevant to</description>
        <label>Related Event for Email</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Value does not exist or is a &apos;News&apos; record as opposed to one of the &apos;Event&apos; record types.</errorMessage>
            <filterItems>
                <field>News_Events__c.RecordTypeId</field>
                <operation>notEqual</operation>
                <value>News</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>News_Events__c</referenceTo>
        <relationshipLabel>Event Email Contacts - DO NOT ADD TO PAGE LAYOUT</relationshipLabel>
        <relationshipName>Event_Email_Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <formula>IF(AND(TEXT(Admissions_File__r.Add_to_Register__c)=&quot;Yes&quot;, TEXT(Admissions_File__r.StageName) = &quot;A/ Deposit&quot;), &quot;Enrolled&quot;, Text(Admissions_File__r.StageName))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Stage</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Student_Full_Name__c</fullName>
        <formula>Admissions_File__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Student Full Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Student_Name__c</fullName>
        <formula>IF(Admissions_File__r.Nickname__c &lt;&gt; &quot;&quot;, LastName&amp;&quot;, &quot;&amp;FirstName&amp;&quot; (&quot;&amp;Admissions_File__r.Nickname__c&amp;&quot;)&quot;,

LastName&amp;&quot;, &quot;&amp;FirstName)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Student Name</label>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Additional_Parent</fullName>
        <active>true</active>
        <label>Additional Parent</label>
    </recordTypes>
    <recordTypes>
        <fullName>Contact</fullName>
        <active>true</active>
        <label>Contact</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Group__c.object
<CustomObject>
    <label>Student Group</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Student Groups</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/News_Events__c.object
<CustomObject>
    <fields>
        <fullName>Automated_Reminder_Email_Sent__c</fullName>
        <description>Indicates when an automated reminder email has been sent for this event and prevents another one from being sent.</description>
        <label>Last Email Notification Sent</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Error_Ids__c</fullName>
        <label>Error Ids</label>
        <length>35000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Fst_Email_Notification_Text__c</fullName>
        <description>03/11/14 PENDING DELETION - NEEDS TO BE REMOVED FROM RELEVANT APEX CLASS</description>
        <label>Email Notification Text</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Retry_Sending_Email__c</fullName>
        <defaultValue>false</defaultValue>
        <description>if checked, workflow executes time based trigger to invoke apex logic to retry sending email notification.</description>
        <inlineHelpText>if checked, workflow executes time based trigger to invoke apex logic to retry sending email notification.</inlineHelpText>
        <label>Retry Sending Email</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Send_Automated_Reminder_Email__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Checked by means of a workflow rule/field update to trigger a reminder email to be sent when the new date falls within the next 2 weeks.</description>
        <label>Send Automated Reminder Email</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Student_Group__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Student Group</label>
        <referenceTo>Group__c</referenceTo>
        <relationshipLabel>Calendar</relationshipLabel>
        <relationshipName>News_Events</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>News &amp; Events</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>News &amp; Events</pluralLabel>
    <recordTypes>
        <fullName>Event</fullName>
        <active>true</active>
        <label>Event</label>
    </recordTypes>
    <recordTypes>
        <fullName>News</fullName>
        <active>true</active>
        <label>News</label>
    </recordTypes>
    <recordTypes>
        <fullName>Reminder</fullName>
        <active>true</active>
        <label>Notice</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/PersonAccount.object
<CustomObject>
    <recordTypes>
        <fullName>PersonAccount</fullName>
        <active>true</active>
        <label>Parent</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Registration__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>whether registration is active or not</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Group__c</fullName>
        <inlineHelpText>select group against which assessment is done.</inlineHelpText>
        <label>Group</label>
        <referenceTo>Group__c</referenceTo>
        <relationshipLabel>Registrations</relationshipLabel>
        <relationshipName>Assessments_Registrations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Parents_Included_in_Community_Group__c</fullName>
        <description>Indicates when a parent should be included in the community chatter group, included on event reminders and also if a related event should be available via their parent portal login</description>
        <formula>IF(OR(AND(TEXT(Group__r.Group_Type__c) = &quot;Tutor Group&quot;, Student__r.Admissions_File__r.Starting_Date_30__c = &quot;TRUE&quot;,  Student__r.Admissions_File__r.CloseDate &gt;= TODAY(), Parent_Has_Portal_User__c = TRUE),  AND(Active__c = TRUE,  Parent_Has_Portal_User__c = TRUE)), TRUE, FALSE)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Parents Included in Group Related Comms</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Student_Name__c</fullName>
        <formula>Student__r.Student_Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Student Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Student__c</fullName>
        <inlineHelpText>select student for this enrolment</inlineHelpText>
        <label>Student</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Registrations</relationshipLabel>
        <relationshipName>Registrations</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Registration</label>
    <nameField>
        <displayFormat>R-{000000}</displayFormat>
        <label>Registration #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Registrations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/EventEmailReminderBatch.cls
global without sharing class EventEmailReminderBatch implements Database.Batchable<sObject>,Database.Stateful{
    
    public string query; 
    public set<Id> nIds;
    global Id neId {get;set;}
    global Id groupId {get;set;}
    global string eventNotificatiionText {get;set;}
    global string errorMessage ;
    global set<Id> errorIds ;
    global boolean executeCalled ;
    /* 
    global EventEmailReminderBatch(set<Id> neIds){ 
        nIds = neIds;
    }
    global Database.QueryLocator start(Database.BatchableContext BC) {
        system.debug('****EventEmailReminderBatch***start***nIds='+nIds);
        if(nIds != null){
        	query = 'select Id from News_Events__c where Id IN:nIds';
        	system.debug('****EventEmailReminderBatch***start***query='+query);
        }
        return Database.getQueryLocator(query);
    }

    global void execute(Database.BatchableContext BC, List<News_Events__c> scope) {
         set<Id> neIds = new set<Id>();
         for(News_Events__c ne:scope){
         	neIds.add(ne.Id);
         }
         system.debug('****EventEmailReminderBatch***execute***query='+neIds);
         sendReminder(neIds);
         system.debug('****EventEmailReminderBatch***execute***complete');
    }
   
    global void SendReminder(set<Id> neIds){
        set<Id> groupIds = new set<Id>();
        list<News_Events__c> scope = new list<News_Events__c>();
        for(News_Events__c ne:[select Id,Student_Group__c,Fst_Email_Notification_Text__c from News_Events__c where Id IN:neIds]){
            groupIds.add(ne.Student_Group__c);
            scope.add(ne);
        }
        //fetch group parent person account
        set<Id> personAccountIds_all = new set<Id>();
        map<Id,set<Id>> personAccountIdMap = new  map<Id,set<Id>>(); //key = group Id, value = set of person account ids
        for(Registration__c r:[Select Student__r.Main_Parent_File__c, Student__r.Stage__c, r.Student__c, r.Student__r.Student_Name__c ,r.Student__r.Student_Full_Name__c,  r.Student__r.Name, r.Name, r.Id, r.Group__c, r.Active__c From Registration__c r where r.Group__c IN:groupIds AND r.Parents_Included_in_Community_Group__c = true  order by r.Student__r.Student_Name__c asc]){
            if(r.Student__r.Main_Parent_File__c != null){
                if(personAccountIdMap.containsKey(r.Group__c)){
                    personAccountIdMap.get(r.Group__c).add(r.Student__r.Main_Parent_File__c);
                }else{
                    set<Id> temp = new set<Id>();
                    temp.add(r.Student__r.Main_Parent_File__c);
                    personAccountIdMap.put(r.Group__c,temp);
                }
                personAccountIds_all.add(r.Student__r.Main_Parent_File__c);
            }
        }
        //fetch all additional parent records with fetched person accounts
        map<Id,set<Id>> additionalParentIdMap = new map<Id,set<Id>>(); // key = person account id, value = set of contact ids
        for(Contact c:[Select Id,Main_Parent_File__c,Email, HasOptedOutOfEmail From Contact where  HasOptedOutOfEmail = false AND RecordType.DeveloperName = 'Additional_Parent' AND Main_Parent_File__c IN:personAccountIds_all]){
            if(c.Main_Parent_File__c != null){
                if(additionalParentIdMap.containsKey(c.Main_Parent_File__c)){
                   additionalParentIdMap.get(c.Main_Parent_File__c).add(c.Id);
                }else{
                    set<Id> temp = new set<Id>();
                    temp.add(c.Id);
                    additionalParentIdMap.put(c.Main_Parent_File__c,temp);
                }
            }
        }
        
        list<Account> personAccountList = new list<Account>();
        list<Contact> additionalParentList = new list<Contact>();
        list<News_Events__c> neList = new list<News_Events__c>();
        for(News_Events__c ne:scope){
            //fetch group parent person account
            set<Id> personAccountIds = personAccountIdMap.get(ne.Student_Group__c);
            if(personAccountIds == null){personAccountIds = new set<Id>();}
            
            //fetch all additional parent records with fetched person accounts
            set<Id> additionalParentIds = new set<Id>();
            
            for(Id pid:personAccountIds){
                if(additionalParentIdMap.get(pid) != null){
                    additionalParentIds.addAll(additionalParentIdMap.get(pid));
                }
            }
            //update with event data
            
            for(Id personAccountId:personAccountIds){
                Account personAccount = new Account(Id=personAccountId);
                personAccount.Related_Event_for_Email__pc = ne.Id;
                //if(ne.Send_First_Reminder_Email__c == true){
                    personAccount.Related_Event_Text_for_Email__pc = ne.Fst_Email_Notification_Text__c; 
                    personAccount.Related_Event_Trigger_First_Email_Send__pc = true;
                //}
               
                personAccountList.add(personAccount);
            }
            
            for(Id additionalParentId:additionalParentIds){
                Contact additionalParent = new Contact(Id=additionalParentId);
                additionalParent.Related_Event_for_Email__c = ne.Id;
                //if(ne.Send_First_Reminder_Email__c == true){
                    additionalParent.Related_Event_Text_for_Email__c = ne.Fst_Email_Notification_Text__c;   
                    additionalParent.Related_Event_Trigger_First_Email_Send__c = true;
                //}
                
                additionalParentList.add(additionalParent);
            }
            //if(ne.Send_First_Reminder_Email__c == true){
                //ne.First_Reminder_Email_Sent__c = true;
                neList.add(new News_Events__c(Id=ne.Id,Automated_Reminder_Email_Sent__c=datetime.now(),Send_Automated_Reminder_Email__c=false));
            //}
           
        }
        
        
        //update records
            if(personAccountList.size() >0){
                update personAccountList;
            }   
            if(additionalParentList.size() > 0){
                update additionalParentList;
            }
            //update event
            if(neList.size() > 0){
                update neList;
            }
        
    }*/
    
 
    
    global EventEmailReminderBatch(Id nId, Id gId, string messageText){ 
        neId = nId;
        groupId = gId;
        eventNotificatiionText = messageText;
        errorIds = new set<Id>();
        errorMessage = '';
        executeCalled = false;
    }
    global Database.QueryLocator start(Database.BatchableContext BC) {
        system.debug('****EventEmailReminderBatch***start***neId='+neId);
        system.debug('****EventEmailReminderBatch***start***groupId='+groupId);
        system.debug('****EventEmailReminderBatch***start***eventNotificatiionText='+eventNotificatiionText);
        
    	query = 'Select Student__r.Main_Parent_File__c, Student__r.Stage__c, r.Student__c, r.Student__r.Student_Name__c ,r.Student__r.Student_Full_Name__c,  r.Student__r.Name, r.Name, r.Id, r.Group__c, r.Active__c From Registration__c r where r.Group__c =:groupId AND r.Parents_Included_in_Community_Group__c = true  order by r.Student__r.Student_Name__c asc';
    	system.debug('****EventEmailReminderBatch***start***query='+query);
       
        return Database.getQueryLocator(query);
    }
    
    global void execute(Database.BatchableContext BC, List<Registration__c> scope) {
        try{
        	executeCalled = true;
	        News_Events__c neObj ;
	        list<Registration__c> registrationList = scope;
	        //fetch group parent person account
	        set<Id> personAccountIds_all = new set<Id>();
	        map<Id,set<Id>> personAccountIdMap = new  map<Id,set<Id>>(); //key = group Id, value = set of person account ids
	        for(Registration__c r:registrationList){
	            if(r.Student__r.Main_Parent_File__c != null){
	                if(personAccountIdMap.containsKey(r.Group__c)){
	                    personAccountIdMap.get(r.Group__c).add(r.Student__r.Main_Parent_File__c);
	                }else{
	                    set<Id> temp = new set<Id>();
	                    temp.add(r.Student__r.Main_Parent_File__c);
	                    personAccountIdMap.put(r.Group__c,temp);
	                }
	                personAccountIds_all.add(r.Student__r.Main_Parent_File__c);
	            }
	        }
	        //fetch all additional parent records with fetched person accounts
	        map<Id,set<Id>> additionalParentIdMap = new map<Id,set<Id>>(); // key = person account id, value = set of contact ids
	        for(Contact c:[Select Id,Main_Parent_File__c,Email, HasOptedOutOfEmail From Contact where  HasOptedOutOfEmail = false AND RecordType.DeveloperName = 'Additional_Parent' AND Main_Parent_File__c IN:personAccountIds_all]){
	            if(c.Main_Parent_File__c != null){
	                if(additionalParentIdMap.containsKey(c.Main_Parent_File__c)){
	                   additionalParentIdMap.get(c.Main_Parent_File__c).add(c.Id);
	                }else{
	                    set<Id> temp = new set<Id>();
	                    temp.add(c.Id);
	                    additionalParentIdMap.put(c.Main_Parent_File__c,temp);
	                }
	            }
	        }
	        list<Account> personAccountList = new list<Account>();
	        list<Contact> additionalParentList = new list<Contact>();
	       //update data
	            //fetch group parent person account
	            set<Id> personAccountIds = personAccountIdMap.get(groupId);
	            if(personAccountIds == null){personAccountIds = new set<Id>();}
	            
	            //fetch all additional parent records with fetched person accounts
	            set<Id> additionalParentIds = new set<Id>();
	            
	            for(Id pid:personAccountIds){
	                if(additionalParentIdMap.get(pid) != null){
	                    additionalParentIds.addAll(additionalParentIdMap.get(pid));
	                }
	            }
	            //update with event data
	            
	            for(Id personAccountId:personAccountIds){
	                Account personAccount = new Account(Id=personAccountId);
	                personAccount.Related_Event_for_Email__pc = neId;
	                //if(ne.Send_First_Reminder_Email__c == true){
	                    personAccount.Related_Event_Text_for_Email__pc = eventNotificatiionText; 
	                    personAccount.Related_Event_Trigger_First_Email_Send__pc = true;
	                //}
	               
	                personAccountList.add(personAccount);
	            }
	            
	            for(Id additionalParentId:additionalParentIds){
	                Contact additionalParent = new Contact(Id=additionalParentId);
	                additionalParent.Related_Event_for_Email__c = neId;
	                //if(ne.Send_First_Reminder_Email__c == true){
	                    additionalParent.Related_Event_Text_for_Email__c = eventNotificatiionText;   
	                    additionalParent.Related_Event_Trigger_First_Email_Send__c = true;
	                //}
	                
	                additionalParentList.add(additionalParent);
	            }
	           
	            //update ne record
	            neObj = new News_Events__c(Id=neId,Automated_Reminder_Email_Sent__c=datetime.now(),Send_Automated_Reminder_Email__c=false);
	           
	        //}
	        //update records
	            if(personAccountList.size() >0){
	                //update personAccountList;
	                
			        list<Database.SaveResult> srList = Database.update(personAccountList,false);
			        integer i = 0;
			        for(Database.Saveresult sr:srlist){
			            if(!sr.isSuccess()){
			            	errorIds.add(personAccountList[i].Id);
			                if(errorMessage == ''){
			                    errorMessage += '<br/>'+'EventEmailReminderBatch - Error(s) Occured while updating parent accounts for sending calendar reminder email. ';
			                }
			                errorMessage += '<br/>'+'Error Occured updating parent record = '+personAccountList[i]+'. Error Message: '+sr.getErrors();
			            }
			            i++;
			        }
	            }   
	            if(additionalParentList.size() > 0){
	                //update additionalParentList;
	                list<Database.SaveResult> srList = Database.update(additionalParentList,false);
			        integer i = 0;
			        for(Database.Saveresult sr:srlist){
			            if(!sr.isSuccess()){
			                errorIds.add(additionalParentList[i].Id);
			                if(errorMessage == ''){
			                    errorMessage += '<br/>'+'EventEmailReminderBatch - Error(s) Occured while updating parent accounts for sending calendar reminder email. ';
			                }
			                errorMessage += '<br/>'+'Error Occured updating additional parent record = '+additionalParentList[i]+'. Error Message: '+sr.getErrors();
			            }
			            i++;
			        }
	            }
	            //update event
	            if(neObj != null){
	            	if(errorIds.size() > 0){
	            		string errorIdsStr = '';
	            		for(Id eid:errorIds){
	            			if(errorIdsStr == ''){
	            				errorIdsStr = eid;
	            			}else{
	            				errorIdsStr += ','+eid;
	            			}
	            		}
	            		neObj.Error_Ids__c = errorIdsStr;
	            		//neObj.Retry_Sending_Email__c = true;
	            	}else{
	            		neObj.Error_Ids__c = null;
	            		//neObj.Retry_Sending_Email__c = false;
	            	}
	            	neObj.Retry_Sending_Email__c = false;
	                //update neObj;
	                list<News_Events__c> tempList = new list<News_Events__c>();
	                tempList.add(neObj);
	                list<Database.SaveResult> srList = Database.update(tempList,false);
			        integer i = 0;
			        for(Database.Saveresult sr:srlist){
			            if(!sr.isSuccess()){
			                if(errorMessage == ''){
			                    errorMessage += '<br/>'+'EventEmailReminderBatch - Error(s) Occured while updating parent accounts for sending calendar reminder email. ';
			                }
			                errorMessage += '<br/>'+'Error Occured updating calendar event record = '+tempList[i]+'. Error Message: '+sr.getErrors();
			            }
			            i++;
			        }
	                
	                
	            }
        }catch(Exception e){
        	errorMessage = e.getMessage();
        }
        
    }
    
    global void finish(Database.BatchableContext BC) {
    	if(!executeCalled){
    		News_Events__c neObj = new News_Events__c(Id=neId,Send_Automated_Reminder_Email__c=false);
    		update neObj;
    	}
        if(errorMessage != ''){
            //send email to Ben, Kunal
           Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
           list<String> toAddresses =  new list<String>();
           toAddresses.add('ben.hails@britishschools.co.uk');
           toAddresses.add('kunal.sharma@britishschools.co.uk');
           toAddresses.add('anton.simanikhin@britishschools.co.uk');
           //String[] toAddresses = new String[] {'ben.hails@britishschools.co.uk','kunal.sharma@britishschools.co.uk'};
           mail.setToAddresses(toAddresses);
           mail.setSubject('Email Reminder Notification -  Error occured');
           string emailText = 'There were errors processing parent/contact records while updating sending email related to news/event record. Find error message below:';
           emailText += '<br/>';
           emailText += errorMessage;
           mail.setHtmlBody(emailText);
           Messaging.sendEmail(new Messaging.SingleEmailMessage[] { mail }); 
        }
    }

}