force-app/main/default/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Contact_Photo_URL__c</fullName>
        <formula>IF(
      !ISBLANK(Photo_Attachment_Id__c),
      &quot;/servlet/servlet.FileDownload?file=&quot;&amp;Photo_Attachment_Id__c,
      IF( Gender_Student__c == &quot;M&quot;, &quot;/resource/1444996516000/Contact_Photo_Boy&quot;, IF(Gender_Student__c == &quot;F&quot;, &quot;/resource/1444996517000/Contact_Photo_Girl&quot;, &quot;/resource/1444996517000/Contact_Photo_General&quot;))
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Student Photo URL</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Photo_Attachment_Id__c</fullName>
        <label>Photo Attachment Id</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Contact</fullName>
        <active>true</active>
        <label>Contact</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/ContactPhotoUpdateController.cls
public with sharing class ContactPhotoUpdateController {
	public Contact con {get;set;}
	public blob fileBody {get;set;}
	public transient Attachment attachment {get;set;}
	public String fileName {get;set;}
	public String contentType {get;set;}
	public Integer fileSize {get;set;}
	private Integer maxSize_Bits = 1048576;
    public ContactPhotoUpdateController(ApexPages.StandardController controller) {
		con = [select Id, Name , Photo_Attachment_Id__c,Contact_Photo_URL__c from Contact where Id=:controller.getId()];
    	
    }
	public PageReference saveAttachment(){
    	try{
	    	if(fileName != null && contentType != null){
		    	
		    	if(validate()){
		    		return null;
		    	}else{
		    		deleteExistingImage();
		    		attachment = new Attachment();
					attachment.ParentId = con.Id;
		    		attachment.Name = fileName;
		    		attachment.Body = fileBody;
		    		
		    		insert attachment;
		    		Id attachmentId = attachment.Id;
		    		
		    		con.Photo_Attachment_Id__c = attachmentId;
		    		update con;
		    		
		    		
		    		
		    		PageReference pg = new PageReference('/'+con.Id);
					return pg;
		    		
		    	}
	    	}else{
	    		ApexPages.Message errorMessage1 = new ApexPages.Message(ApexPages.severity.FATAL, 'No file selected.');
				ApexPages.addMessage(errorMessage1);
	    	}
    	}catch(Exception e){
    		ApexPages.Message errorMessage1 = new ApexPages.Message(ApexPages.severity.FATAL, 'Error Uploading File: '+e.getMessage());
			ApexPages.addMessage(errorMessage1);
    	}finally{
    		fileBody = null;
    		attachment = null;
    	}
    	
    	return null;
    }
    
    private boolean validate(){
    	boolean flag = false;
    	string errorMessage ;
    	set<string> contentImageTypes =  new set<string>();
    	contentImageTypes.add('image/gif');
    	contentImageTypes.add('image/jpeg');
    	contentImageTypes.add('image/jpg');
    	contentImageTypes.add('image/pjpeg');
    	contentImageTypes.add('image/png');
    	
    	if(filebody == null || fileName == null){
    		errorMessage = 'No image file provided.';
    		flag = true;
    	}else if(!contentImageTypes.contains(contentType)){
    		errorMessage = 'Provide file is not an image.';
    		flag = true;
    	}else if(fileSize > maxSize_Bits){
    		errorMessage = 'You can not uplaod photo more than 1 MB in size.';
    		flag = true;
    	}
    	if(flag){
    		ApexPages.Message errorMessage1 = new ApexPages.Message(ApexPages.severity.FATAL, errorMessage);
			ApexPages.addMessage(errorMessage1);	
    	}
    	return flag;
    }
    
    private void deleteExistingImage(){
    	if(con.Photo_Attachment_Id__c != null){
    		try{
    			Attachment a = new Attachment(Id=con.Photo_Attachment_Id__c);
    			delete a;
    			con.Photo_Attachment_Id__c = null;
    			update con;
    		}catch(Exception e){
    			//do nothing
    		}
    	}
    }
    
    public PageReference deletePhoto(){
    	deleteExistingImage();
    	return cancel();
    }
    
    //page reference function
	public PageReference cancel(){
		PageReference pg = new PageReference('/'+con.Id);
		return pg;
	}
    
}