force-app/main/default/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Class_Name__c</fullName>
        <formula>Admissions_File__r.Class_Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Admin Dept. Class Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>House__c</fullName>
        <formula>TEXT( Admissions_File__r.House__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>House</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Main_Parent_File__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Family File</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Value does not exist or is not a parent record.</errorMessage>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Parent</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Additional Parents &amp; Student Academic Files</relationshipLabel>
        <relationshipName>Emails</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Nickname__c</fullName>
        <formula>Admissions_File__r.Nickname__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Nickname</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <formula>IF(AND(TEXT(Admissions_File__r.Add_to_Register__c)=&quot;Yes&quot;, TEXT(Admissions_File__r.StageName) = &quot;A/ Deposit&quot;), &quot;Enrolled&quot;, Text(Admissions_File__r.StageName))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Stage</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Student_Email_Formula__c</fullName>
        <formula>Admissions_File__r.Student_Email__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Student Email</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Student_Name__c</fullName>
        <formula>IF(Admissions_File__r.Nickname__c &lt;&gt; &quot;&quot;, LastName&amp;&quot;, &quot;&amp;FirstName&amp;&quot; (&quot;&amp;Admissions_File__r.Nickname__c&amp;&quot;)&quot;,

LastName&amp;&quot;, &quot;&amp;FirstName)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Student Name</label>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Contact</fullName>
        <active>true</active>
        <label>Contact</label>
    </recordTypes>
    <recordTypes>
        <fullName>Student</fullName>
        <active>true</active>
        <label>Student Academic File</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/StudentListController.cls
public with sharing class StudentListController {
    public list<Contact> studentList {get;set;}
    public StudentListController(ApexPages.StandardController controller) {
        studentList =  new list<Contact>();
        //fetch student academic file
        for(Contact c:[Select  c.Stage__c, c.Student_Name__c, c.Nickname__c, c.Class_Name__c, House__c, Student_Email_Formula__c, c.Main_Parent_File__c, c.Id, c.Email From Contact c where Main_Parent_File__c =:controller.getId() AND RecordType.DeveloperName='Student' order by c.Student_Name__c]){
            studentList.add(c);
        }
    }

}