force-app/main/default/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Main_Parent_File__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Family File</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Value does not exist or is not a parent record.</errorMessage>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Parent</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Additional Parents &amp; Student Academic Files</relationshipLabel>
        <relationshipName>Emails</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>School__c</fullName>
        <formula>Admissions_File__r.School__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>School</label>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Contact</fullName>
        <active>true</active>
        <label>Contact</label>
    </recordTypes>
    <recordTypes>
        <fullName>Student</fullName>
        <active>true</active>
        <label>Student Academic File</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Group__c.object
<CustomObject>
    <fields>
        <fullName>Auto_Add_Parents_To_Group__c</fullName>
        <defaultValue>true</defaultValue>
        <inlineHelpText>to automatically add parents to chatter group.</inlineHelpText>
        <label>Auto Add Parents To Group</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Chatter_Group_Id__c</fullName>
        <inlineHelpText>System Field : Corresponding Chatter Group Id for this Student Group.</inlineHelpText>
        <label>Chatter Group Id</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Group_Name__c</fullName>
        <formula>IF( TEXT(Group_Type__c) =&quot;Tutor Group&quot;,

(IF( TEXT(Combined_Year_Group__c) =&quot;&quot;,

 TEXT(Year_Group__c)&amp;&quot; &quot;&amp;  Owner:User.Alias,
 TEXT(Year_Group__c) &amp;&quot;-&quot;&amp; Combined_Year_Group_Abb__c&amp;&quot; &quot;&amp; Owner:User.Alias  )),IF(TEXT(Group_Type__c) == &apos;School Group&apos;,&apos;&apos;, TEXT(Subject_Name__c)))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Group Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>School__c</fullName>
        <formula>TEXT(Owner:User.School__c)</formula>
        <label>School</label>
        <type>Text</type>
    </fields>
    <label>Student Group</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Student Groups</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Registration__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>whether registration is active or not</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Chatter_Group_Id__c</fullName>
        <formula>IF( AND(!ISBLANK(Group__c), !ISBLANK(Group__r.Chatter_Group_Id__c)), (Group__r.Chatter_Group_Id__c), &quot;&quot;)</formula>
        <label>Chatter Group Id</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Group_Name__c</fullName>
        <formula>Group__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Group Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Group__c</fullName>
        <inlineHelpText>select group against which assessment is done.</inlineHelpText>
        <label>Group</label>
        <referenceTo>Group__c</referenceTo>
        <relationshipLabel>Registrations</relationshipLabel>
        <relationshipName>Assessments_Registrations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Parent_File_Id__c</fullName>
        <formula>CASESAFEID(Student__r.Main_Parent_File__c)</formula>
        <label>Parent File Id</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>School__c</fullName>
        <formula>Group__r.School__c</formula>
        <label>School</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Student__c</fullName>
        <inlineHelpText>select student for this enrolment</inlineHelpText>
        <label>Student</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Registrations</relationshipLabel>
        <relationshipName>Registrations</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Registration</label>
    <nameField>
        <displayFormat>R-{000000}</displayFormat>
        <label>Registration #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Registrations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/School__c.object
<CustomObject>
    <fields>
        <fullName>School_Full_Name__c</fullName>
        <label>School Full Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>School</label>
    <nameField>
        <label>School Code/UID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Schools</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/School_Logo_Mapping__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>setting to store mapping of school name and school logo image URL</description>
    <fields>
        <fullName>Community_Id__c</fullName>
        <inlineHelpText>Id of the school&apos;s parent community Id.</inlineHelpText>
        <label>Community Id</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>School_Full_Name__c</fullName>
        <label>School Full Name</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <label>School Mapping</label>
</CustomObject>

force-app/main/default/objects/User.object
<CustomObject>
    <fields>
        <fullName>Family_File_Id__c</fullName>
        <formula>IF( Contact.RecordType.DeveloperName == &quot;Additional_Parent&quot;, CASESAFEID(Contact.Main_Parent_File__c) , CASESAFEID(Contact.AccountId))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Family File Id</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Is_Portal_User__c</fullName>
        <description>Identifies whether or not a user is a Portal/Community user (replaces &apos;IsPortalEnabled&apos; field that is no longer supported in new SFDC versions).</description>
        <formula>NOT(ISBLANK(ContactId))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Is Portal User</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>School__c</fullName>
        <label>School</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>The British Schools Foundation</fullName>
                </value>
                <value>
                    <fullName>The British School of Guangzhou</fullName>
                </value>
                <value>
                    <fullName>The British School of Nanjing</fullName>
                </value>
                <value>
                    <fullName>The British International School of Marbella</fullName>
                </value>
                <value>
                    <fullName>The British School of Navarra</fullName>
                </value>
                <value>
                    <fullName>The British School of Tashkent</fullName>
                </value>
                <value>
                    <fullName>The British College of Brazil</fullName>
                </value>
                <value>
                    <fullName>The British International School of Kuala Lumpur</fullName>
                </value>
                <value>
                    <fullName>The International School of Moscow</fullName>
                </value>
                <value>
                    <fullName>Nord Anglia International School Manila</fullName>
                </value>
                <value>
                    <fullName>King&apos;s College Beijing</fullName>
                </value>
                <value>
                    <fullName>The British School Yangon</fullName>
                </value>
                <value>
                    <fullName>Ukraine International School</fullName>
                </value>
                <value>
                    <fullName>The New York International School</fullName>
                </value>
                <value>
                    <fullName>The British School of Brasilia</fullName>
                </value>
                <value>
                    <fullName>NAE</fullName>
                </value>
                <value>
                    <fullName>The British International School Yangon</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/classes/PortalStudentGroupChatter_Controller.cls
/***
    Author: Kunal 
    Created Date: 23 August 2013
    Desc: VF controller PortalStudentGroupChatter_Controller
***/
public class PortalStudentGroupChatter_Controller {
    public boolean isChatterGroupExists {get;set;} 
    public boolean isFatalError {get;set;} 
    public CollaborationGroup chatterGroup{get;set;}
    public Group__c studentGroup {get;set;}
    public boolean addRegisteredStudentsParents {get;set;}
    private School_Logo_Mapping__c schoolSetting;
    
    //constructor
    public PortalStudentGroupChatter_Controller(ApexPages.StandardController controller) {
        isChatterGroupExists = false;
        isFatalError = false;
        addRegisteredStudentsParents = true;
        //fetch custom setting
        //populate schools setting map
        Map<String,School_Logo_Mapping__c>schoolSettingMap =  new Map<String,School_Logo_Mapping__c>();
        List<School_Logo_Mapping__c> settings = School_Logo_Mapping__c.getall().values(); 
        for(School_Logo_Mapping__c setting:settings){
            schoolSettingMap.put(setting.School_Full_Name__c,setting);
        }
        studentGroup = [Select Name,OwnerId,Owner.Name,Auto_Add_Parents_To_Group__c, Chatter_Group_Id__c, Group_Name__c,School__c, Id from Group__c where Id=:controller.getId()];
        studentGroup.Auto_Add_Parents_To_Group__c =  true;
        schoolSetting = schoolSettingMap.get(studentGroup.School__c);
        if(schoolSetting == null){
            ApexPages.Message errorMessage = new ApexPages.Message(ApexPages.severity.FATAL, 'Data Error: No settings are found for "'+studentGroup.School__c+'"".');
            ApexPages.addMessage(errorMessage);
            isFatalError = true;
        }else{
            if(schoolSetting.Community_Id__c == null){
                ApexPages.Message errorMessage = new ApexPages.Message(ApexPages.severity.FATAL, 'Data Error: No community Id for "'+studentGroup.School__c+'". Please verify if Parent Community Portal is created for this school.');
                ApexPages.addMessage(errorMessage);
                isFatalError = true;
            }else{
                studentGroup.Auto_Add_Parents_To_Group__c =  true;
                if(studentGroup.Chatter_Group_Id__c != null){
                    
                    try{
                        chatterGroup = [Select c.Name, c.MemberCount, c.Description, c.CollaborationType From CollaborationGroup c where c.Id=:studentGroup.Chatter_Group_Id__c];
                        isChatterGroupExists = true;
                    }catch(Exception e){
                        isChatterGroupExists = false;
                    }
                }
                
                if(chatterGroup == null){
                    chatterGroup =  new CollaborationGroup();
                    chatterGroup.Name = studentGroup.Group_Name__c + ' - '+studentGroup.Owner.Name;
                    chatterGroup.NetworkId = schoolSetting.Community_Id__c;
                    chatterGroup.CollaborationType = 'Private';
                    chatterGroup.OwnerId = studentGroup.OwnerId;
                }
            }
        }
    }
    
    public PageReference cancel(){
        PageReference pg = new PageReference('/'+studentGroup.Id);
        return pg;
    }
    
    //create chatter group
    public PageReference createChatterGroup(){
        try{
            //insert chatter group
            insert chatterGroup;
            //update student group
            studentGroup.Chatter_Group_Id__c = chatterGroup.Id;
            update studentGroup;
            //add registered student's parents
            if(addRegisteredStudentsParents == true){
                //fetch parent id of registered students
                Set<Id> parentAccountIds = new Set<Id>();
                for(Registration__c registration:[Select r.Parent_File_Id__c, r.Student__r.Main_Parent_File__c, r.Student__c, r.Active__c From Registration__c r where r.Active__c = true AND r.Group__c=:studentGroup.Id]){
                    parentAccountIds.add(registration.Parent_File_Id__c);
                }
                //fetch parent's user records
                List<CollaborationGroupMember> groupMembers =  new List<CollaborationGroupMember>(); 
                for(User u:[Select Id from User where Family_File_Id__c IN:parentAccountIds AND Is_Portal_User__c = true AND IsActive = true]){
                    CollaborationGroupMember member =  new CollaborationGroupMember();
                    member.CollaborationGroupId = chatterGroup.Id;
                    member.CollaborationRole = 'Standard';
                    member.MemberId = u.Id;
                    //member.NotificationFrequency = 'W';
                    groupMembers.add(member); 
                }
                if(groupMembers.size() > 0){
                    insert groupMembers; 
                }
                ApexPages.Message successMessage = new ApexPages.Message(ApexPages.severity.CONFIRM, 'Community Chatter Group is created and '+groupMembers.size()+' parent(s) are successfully addedd to community chatter group. Please access school\'s community for further chatter group management.');
                ApexPages.addMessage(successMessage);
                isChatterGroupExists = true;
            }
        
        }catch(Exception e){
            ApexPages.Message errorMessage = new ApexPages.Message(ApexPages.severity.FATAL, 'System Error: Oooops system has incurred an unexpected error. Please contact system administrator and provide following error message: '+e.getMessage());
            ApexPages.addMessage(errorMessage);
        }
        return null;
    }
    
    
    
    //create chatter group
    public PageReference addNewParents(){
        try{
            //fetch parent id of registered students
            Set<String> parentAccountIds = new Set<String>();
            for(Registration__c registration:[Select r.Parent_File_Id__c, r.Student__r.Main_Parent_File__c, r.Student__c, r.Active__c From Registration__c r where r.Active__c = true AND r.Group__c=:studentGroup.Id]){
                parentAccountIds.add(registration.Parent_File_Id__c);
            }
            //fetch existing members
            set<Id> existingMembers =  new Set<Id>();
            for(CollaborationGroupMember existingMember:[Select Id, MemberId from CollaborationGroupMember where CollaborationGroupId=:chatterGroup.Id]){
                existingMembers.add(existingMember.MemberId);
            }
            //fetch parent's user records
            List<CollaborationGroupMember> groupMembers =  new List<CollaborationGroupMember>();         
            for(User u:[Select Id from User where Family_File_Id__c IN:parentAccountIds AND Is_Portal_User__c = true AND IsActive = true]){
                if(!existingMembers.contains(u.Id)){
                    CollaborationGroupMember member =  new CollaborationGroupMember();
                    member.CollaborationGroupId = chatterGroup.Id;
                    member.CollaborationRole = 'Standard';
                    member.MemberId = u.Id;
                    member.NotificationFrequency = 'W';
                    groupMembers.add(member);
                }
            }
            if(groupMembers.size() > 0){
                insert groupMembers;
                chatterGroup = [Select c.Name, c.MemberCount, c.Description, c.CollaborationType From CollaborationGroup c where c.Id=:studentGroup.Chatter_Group_Id__c];
            }
            ApexPages.Message successMessage = new ApexPages.Message(ApexPages.severity.CONFIRM, groupMembers.size()+' parent(s) are successfully addedd to community chatter group. Please access school\'s community for further chatter group management.');
            ApexPages.addMessage(successMessage);
        }catch(Exception e){
            ApexPages.Message errorMessage = new ApexPages.Message(ApexPages.severity.FATAL, 'System Error: Oooops system has incurred an unexpected error. Please contact system administrator and provide following error message: '+e.getMessage());
            ApexPages.addMessage(errorMessage);
        }
        return null;
    }
    
    
}