force-app/main/default/objects/Financial_Information__c.object
<CustomObject>
    <description>To record the invoice/receipt requirements of parents/companies and the bank account information of employees</description>
    <fields>
        <fullName>Related_Company_Financial_Info__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Select the &apos;Financial Information&apos; record of the related company. To search by name, type the name of the company in the pop-up and then select the &apos;All Fields&apos; option before clicking the &apos;Go&apos; button. Remember to use * as a wildcard if required.</inlineHelpText>
        <label>Related Record</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Value does not exist or is not a company.</errorMessage>
            <filterItems>
                <field>Financial_Information__c.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Company_Financial_Information</value>
            </filterItems>
            <infoMessage>To search by company name, type the name of the company in the search box and select the &apos;All Fields&apos; option before clicking the &apos;Go&apos; button. Remember to use * as a wildcard if required.</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Financial_Information__c</referenceTo>
        <relationshipLabel>Families Related To</relationshipLabel>
        <relationshipName>Financial_Information</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Related_to__c</fullName>
        <label>Related to</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Financial Information</relationshipLabel>
        <relationshipName>Financial_Information</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Financial Information</label>
    <nameField>
        <displayFormat>FI-{YY}{00000}</displayFormat>
        <label>Financial Information</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Financial Information</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice_Date_Settings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Inc_Leave_Date__c</fullName>
        <label>Inc Leave Date</label>
        <precision>3</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Inc_Leave_sign__c</fullName>
        <label>Inc Leave sign</label>
        <length>4</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Inc_Month_Leave_Date__c</fullName>
        <label>Inc Month Leave Date</label>
        <precision>3</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Inc_Month_Leave_sign__c</fullName>
        <label>Inc Month Leave sign</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Inc_Month_Start_Date__c</fullName>
        <label>Inc Month Start Date</label>
        <precision>3</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Inc_Month_Start_Sign__c</fullName>
        <label>Inc Month Start Sign</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Inc_Start_Date__c</fullName>
        <label>Inc Start Date</label>
        <precision>3</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Inc_Start_Sign__c</fullName>
        <label>Inc Start Sign</label>
        <length>4</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Mth_Gen_Day__c</fullName>
        <label>Mth Gen Day</label>
        <precision>2</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Invoice Date Settings</label>
</CustomObject>

force-app/main/default/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Half_Day_PN_N_Checkbox__c</fullName>
        <formula>TEXT(Half_Day_PN_N__c) != &quot;&quot;</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Half Day? (PN/N)</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Half_Day_PN_N__c</fullName>
        <label>Half Day? (PN/N)</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Year_Group__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Morning</fullName>
                </value>
                <value>
                    <fullName>Afternoon</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Related_Financial_Info__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Related Record</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 AND 2</booleanFilter>
            <filterItems>
                <field>Financial_Information__c.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Parent_Financial_Information</value>
            </filterItems>
            <filterItems>
                <field>Financial_Information__c.Related_to__r.Id</field>
                <operation>equals</operation>
                <valueField>$Source.AccountId</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Financial_Information__c</referenceTo>
        <relationshipLabel>Students Related To</relationshipLabel>
        <relationshipName>Students_Related_To</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Year_Group__c</fullName>
        <label>Year Group / Grade</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>US_Year_Group_Control__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>PN1</fullName>
                </value>
                <value>
                    <fullName>PN</fullName>
                </value>
                <value>
                    <fullName>N</fullName>
                </value>
                <value>
                    <fullName>R</fullName>
                </value>
                <value>
                    <fullName>Y1</fullName>
                </value>
                <value>
                    <fullName>Y2</fullName>
                </value>
                <value>
                    <fullName>Y3</fullName>
                </value>
                <value>
                    <fullName>Y4</fullName>
                </value>
                <value>
                    <fullName>Y5</fullName>
                </value>
                <value>
                    <fullName>Y6</fullName>
                </value>
                <value>
                    <fullName>Y7</fullName>
                </value>
                <value>
                    <fullName>Y8</fullName>
                </value>
                <value>
                    <fullName>Y9</fullName>
                </value>
                <value>
                    <fullName>Y10</fullName>
                </value>
                <value>
                    <fullName>Y11</fullName>
                </value>
                <value>
                    <fullName>Y12</fullName>
                </value>
                <value>
                    <fullName>Y13</fullName>
                </value>
                <value>
                    <fullName>PK</fullName>
                </value>
                <value>
                    <fullName>K</fullName>
                </value>
                <value>
                    <fullName>G1</fullName>
                </value>
                <value>
                    <fullName>G2</fullName>
                </value>
                <value>
                    <fullName>G3</fullName>
                </value>
                <value>
                    <fullName>G4</fullName>
                </value>
                <value>
                    <fullName>G5</fullName>
                </value>
                <value>
                    <fullName>G6</fullName>
                </value>
                <value>
                    <fullName>G7</fullName>
                </value>
                <value>
                    <fullName>G8</fullName>
                </value>
                <value>
                    <fullName>G9</fullName>
                </value>
                <value>
                    <fullName>G10</fullName>
                </value>
                <value>
                    <fullName>G11</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Student</fullName>
        <active>true</active>
        <businessProcess>Standard Admissions Process</businessProcess>
        <label>Student</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>Current__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Current</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Custom__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Custom</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Due_Date__c</fullName>
        <label>Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Invoice_Date__c</fullName>
        <label>Invoice Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Invoicing_Term__c</fullName>
        <label>Invoicing Term</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yearly</fullName>
                </value>
                <value>
                    <fullName>Termly</fullName>
                </value>
                <value>
                    <fullName>Monthly</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Months_In_Year__c</fullName>
        <label>Months In Year</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>10</fullName>
                </value>
                <value>
                    <fullName>12</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Next_Generated_Invoice__c</fullName>
        <label>Next Generated Invoice</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Next_Year_Fee__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Check if this fee is an advanced fee for the next academic year</inlineHelpText>
        <label>Next Year Fee?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Payer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Payer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Opportunity Product</relationshipLabel>
        <relationshipName>Opportunity_Product</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Tuition__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Tuition</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

force-app/main/default/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Fee_Frequency__c</fullName>
        <label>Fee Frequency</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Monthly</fullName>
                </value>
                <value>
                    <fullName>Yearly</fullName>
                </value>
                <value>
                    <fullName>Termly</fullName>
                </value>
                <value>
                    <fullName>One Off</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Year_Group__c</fullName>
        <label>Year Group</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Description_of_fee__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>PN1</fullName>
                </value>
                <value>
                    <fullName>PN</fullName>
                </value>
                <value>
                    <fullName>N</fullName>
                </value>
                <value>
                    <fullName>R</fullName>
                </value>
                <value>
                    <fullName>Y1</fullName>
                </value>
                <value>
                    <fullName>Y2</fullName>
                </value>
                <value>
                    <fullName>Y3</fullName>
                </value>
                <value>
                    <fullName>Y4</fullName>
                </value>
                <value>
                    <fullName>Y5</fullName>
                </value>
                <value>
                    <fullName>Y6</fullName>
                </value>
                <value>
                    <fullName>Y7</fullName>
                </value>
                <value>
                    <fullName>Y8</fullName>
                </value>
                <value>
                    <fullName>Y9</fullName>
                </value>
                <value>
                    <fullName>Y10</fullName>
                </value>
                <value>
                    <fullName>Y11</fullName>
                </value>
                <value>
                    <fullName>Y12</fullName>
                </value>
                <value>
                    <fullName>Y13</fullName>
                </value>
                <value>
                    <fullName>PK</fullName>
                </value>
                <value>
                    <fullName>K</fullName>
                </value>
                <value>
                    <fullName>G1</fullName>
                </value>
                <value>
                    <fullName>G2</fullName>
                </value>
                <value>
                    <fullName>G3</fullName>
                </value>
                <value>
                    <fullName>G4</fullName>
                </value>
                <value>
                    <fullName>G5</fullName>
                </value>
                <value>
                    <fullName>G6</fullName>
                </value>
                <value>
                    <fullName>G7</fullName>
                </value>
                <value>
                    <fullName>G8</fullName>
                </value>
                <value>
                    <fullName>G9</fullName>
                </value>
                <value>
                    <fullName>G10</fullName>
                </value>
                <value>
                    <fullName>G11</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/FeeAssignmentController.cls
public with sharing class FeeAssignmentController {
    
    public Opportunity      student     { get; set; }
    
    //Selectable fields
    public Boolean          priceBookUnset { get; set; }
    public String           priceBook   { get; set; }
    
    //Fields for selecting all fees and their payers
    public OtherFee         tuitionFee          { get; set; }
    public OtherFee         newOtherFee         { get; set; }
    public OtherFee         newCustomYearlyFee  { get; set; }
    public List<OtherFee>   otherFees           { get; set; }
    public List<OtherFee>   customYearlyFees    { get; set; }
    
    //Constructor
    public FeeAssignmentController(ApexPages.StandardController sc) {
        
        this.student   = (Opportunity)sc.getRecord();
        this.student   = [Select Id, Half_Day_PN_N__c,Half_Day_PN_N_Checkbox__c, AccountId, Pricebook2Id, Related_Financial_Info__r.Related_Company_Financial_Info__r.Related_to__c, Related_Financial_Info__r.Related_Company_Financial_Info__r.Related_to__r.Name, Year_Group__c From Opportunity Where Id =: student.Id];
        this.priceBook = student.Pricebook2Id;

        // If a pricebook hasn't been set, we set the priceBookUnset variable to true so that the pricbook selection
        // will be displayed and maintained until the user sets a pricebook.
        if (this.priceBook == null || this.priceBook == '') {
            priceBookUnset = true;
        }
        
        initOtherFees();

        //Create a new fee so items can be added
        this.newOtherFee        = new OtherFee(null, 0 ,this.student, false);

        //Create a new custom yearly fee so items can be added
        this.newCustomYearlyFee = new OtherFee(null, 0 ,this.student, OtherFee.FeeType.All); 
        this.newCustomYearlyFee.term = 'Yearly';
        this.newCustomYearlyFee.months = null;

        //and a tuition fee if one doesnt exist yet
        if(this.tuitionFee == null)
            this.tuitionFee = new OtherFee(null, 0 ,this.student, true);
    }
    
    private void initOtherFees()
    {
        //Run through all Opportunity Line Items related to the Opportunity and create a fee object for it
        this.otherFees = new List<OtherFee>();
        this.customYearlyFees = new List<OtherFee>();
        for(OpportunityLineItem oli : [Select Id, PricebookEntryId, Current__c, Custom__c, Next_Year_Fee__c, Due_Date__c, Payer__c, Invoice_Date__c, Invoicing_Term__c, Months_In_Year__c, Next_Generated_Invoice__c, Tuition__c,
                                         Discount from OpportunityLineItem Where OpportunityId =: this.student.id and Current__c =: true])
        {
            OtherFee.FeeType feeType = oli.Custom__c ? OtherFee.FeeType.All : oli.Tuition__c ? OtherFee.FeeType.Tuition : OtherFee.FeeType.Other;
            System.debug('## oli : ' + oli);
            OtherFee fee = new OtherFee(oli.PricebookEntryId, oli.Discount, student, feeType); 
            fee.payer = oli.Payer__c;
            fee.months = oli.Months_In_Year__c;
            fee.term = oli.Invoicing_Term__c;
            fee.nextGenInvoice = fee.dateToString(oli.Next_Generated_Invoice__c);
            //Differentiate between tuition & other & custom fee
            if(oli.Tuition__c)
                this.tuitionFee = fee;
            else if( oli.Custom__c == true ) {
                fee.dateSource.Next_Generated_Invoice__c = oli.Next_Generated_Invoice__c;
                fee.dateSource.Invoice_Date__c = oli.Invoice_Date__c;
                fee.dateSource.Due_Date__c = oli.Due_Date__c;
                fee.nextYearFee = oli.Next_Year_Fee__c;

                this.customYearlyFees.add(fee);
            }
            else
                this.otherFees.add(fee);
        }
    }

    public Boolean getOppHasPriceBook()
    {
        return (this.student.priceBook2Id != null);
    }
    
    public Boolean getDifferingPriceBook()
    {
        //If the pricebook has been changed clear all currently selected fees
        if(this.student.priceBook2Id != null && this.student.priceBook2Id != this.priceBook)
        {
            this.tuitionFee.fee = null;
            for(OtherFee fee : this.otherFees)
            {
                fee.fee = null;
            }
            getOtherFeesView();
            return true;
        }
        else
        {
            return false;
        }
    }
    
    //Get the two possible Accounts related to the Opportunity
    public List<SelectOption> getPayerOptions() {
        
        List<SelectOption> options = new List<SelectOption>();
        if(student.Related_Financial_Info__r.Related_Company_Financial_Info__r.Related_to__c != null)
            options.add(new SelectOption(student.Related_Financial_Info__r.Related_Company_Financial_Info__r.Related_to__c, student.Related_Financial_Info__r.Related_Company_Financial_Info__r.Related_to__r.Name));
        if(student.AccountId != null)
        {
            Account acc = [Select Id, Name From Account Where Id =: student.AccountId limit 1];
            options.add(new SelectOption(acc.Id, acc.Name));
        }
        return options;
    }
    
    //Get a list of the pricebooks avaliable 
    public List<SelectOption> getPriceBookOptions() {
        
        List<SelectOption> options = new List<SelectOption>();
        for(PriceBook2 pb : [ Select Id, Name, IsActive From PriceBook2 Where isActive =: true]) {
            options.add(new SelectOption( pb.Id, pb.Name ));
        }
        return options;
    }
    
    //Load the list of Other fees, if there is any fees set to null then remove them
    //If a fee has been selected for new fee the add it to the list and empty new fee.
    public List<OtherFee> getOtherFeesView()
    {
        //Add a new fee if one has been selected
        if(this.newOtherFee.fee != null)
        {
            otherFees.add(this.newOtherFee);
            this.newOtherFee = new OtherFee(null, 0, this.student, false);
        }
        //Remove any fees that are now --None--
        List<OtherFee> nonNullFees = new List<OtherFee>();
        for(OtherFee fee : otherFees)
        {
            if(fee.fee != null) nonNullFees.add(fee);
        }
        otherFees.clear();
        otherFees.addAll(nonNullFees);
        
        return otherFees;
    }

    //Load the list of Custom Yearly fees, if there is any fees set to null then remove them
    //If a fee has been selected for new fee the add it to the list and empty new fee.
    public List<OtherFee> getCustomYearlyFeesView()
    {
        //Add a new fee if one has been selected
        if(this.newCustomYearlyFee.fee != null)
        {
            customYearlyFees.add(this.newCustomYearlyFee);
            this.newCustomYearlyFee = new OtherFee(null, 0, this.student, OtherFee.FeeType.All);
            this.newCustomYearlyFee.term = 'Yearly';
            this.newCustomYearlyFee.months = null;
        }
        //Remove any fees that are now --None--
        List<OtherFee> nonNullFees = new List<OtherFee>();
        for(OtherFee fee : customYearlyFees)
        {
            if(fee.fee != null) nonNullFees.add(fee);
        }
        customYearlyFees.clear();
        customYearlyFees.addAll(nonNullFees);
        
        return customYearlyFees;
    }
    
    //Save methods and redirect to the Opportunity page.
    public PageReference saveDontRedirect() {
        
        String error = saveOpp();
        if(error != null)
        {
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.Error, error));
        }
        return null;
    }
    public PageReference saveRedirect() {
        
        String error = saveOpp();
        if(error == null)
            return redirect();
        else
        {
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.Error, error));
            return null;
        }
    }
    public PageReference redirect()
    {
        return new PageReference('/' + student.Id);
    }
    
    //Save all variables to the opportunite, remove all old opportunity line itmes and add all new opportunity line items
    public String saveOpp() {
        
        try {
            getOtherFeesView();
            getCustomYearlyFeesView();
            
            Map<String, PriceBookEntry> allPBEs = new Map<String, PriceBookEntry>();
            for(PriceBookEntry pbe : [Select Id, Product2Id, PriceBook2Id, UnitPrice from PriceBookEntry where PriceBook2Id =:student.Pricebook2Id])
            {
                allPBEs.put(pbe.Id, pbe);
            } 
            
            List<OpportunityLineItem> newOLIs = new List<OpportunityLineItem>();

            //Create new Line Items for each Other item thats been selected
            for(OtherFee fee : otherFees)
            {
                if(fee.fee != null)
                {
                    PriceBookEntry pbe = allPbes.get(fee.fee);
                    OpportunityLineItem oli = new OpportunityLineItem();
                    oli.PricebookEntryId = pbe.Id;
                    oli.UnitPrice = pbe.UnitPrice;
                    oli.Quantity = 1;
                    oli.OpportunityId = this.student.Id;
                    oli.Current__c = true;
                    oli.Custom__c = false;
                    oli.Due_Date__c = null;
                    
                    oli.Discount = Decimal.valueOf(fee.discount);
                    oli.Tuition__c = fee.tuition;
                    oli.Payer__c = fee.payer;
                    oli.Invoicing_Term__c = fee.term;
                    oli.Months_In_Year__c = fee.months;
                    oli.Next_Generated_Invoice__c = fee.dateMap.get(fee.nextGenInvoice);
                    oli.Invoice_Date__c = InvoiceDateGeneration.getNextInvoiceDate(fee.term, fee.dateMap.get(fee.nextGenInvoice));
                    newOLIs.add(oli);
                } 
                
            }
            //Create new Line Items for each Custom Yearly item thats been selected
            for(OtherFee fee : customYearlyFees)
            {
                if(fee.fee != null)
                {
                    PriceBookEntry pbe = allPbes.get(fee.fee);
                    OpportunityLineItem oli = new OpportunityLineItem();
                    oli.PricebookEntryId = pbe.Id;
                    oli.UnitPrice = pbe.UnitPrice;
                    oli.Quantity = 1;
                    oli.OpportunityId = this.student.Id;
                    oli.Current__c = true;
                    oli.Custom__c = true;
                    oli.Tuition__c = false;
                    oli.Invoicing_Term__c = 'Yearly';

                    oli.Discount = Decimal.valueOf(fee.discount);
                    oli.Next_Year_Fee__c = fee.nextYearFee;
                    oli.Payer__c = fee.payer;
                    oli.Due_Date__c = fee.dateSource.Due_Date__c;
                    oli.Next_Generated_Invoice__c = fee.dateSource.Next_Generated_Invoice__c;
                    oli.Invoice_Date__c = fee.dateSource.Invoice_Date__c;

                    newOLIs.add(oli);
                }
                
            }
            //Create a new Line Item for the current Tuition fee
            if(this.tuitionFee.fee != null)
            {
                PriceBookEntry pbe = [Select Id, Name, PriceBook2Id, UnitPrice, Product2Id, Product2.Year_Group__c, Product2.Fee_Frequency__c From PriceBookEntry Where Id =: this.tuitionFee.fee ];
                if(pbe != null)
                {
                    OpportunityLineItem oli = new OpportunityLineItem();
                    oli.PricebookEntryId = pbe.Id;
                    oli.OpportunityId = this.student.Id;
                    oli.Quantity = 1;
                    oli.UnitPrice = pbe.UnitPrice;
                    oli.Current__c = true;
                    oli.Custom__c = false;
                    oli.Due_Date__c = null;
                    
                    oli.Discount = (tuitionFee.discount == null) ? 0 : Decimal.valueOf(tuitionFee.discount);
                    oli.Tuition__c = tuitionFee.tuition;
                    oli.Payer__c = tuitionFee.payer;
                    oli.Invoicing_Term__c = tuitionFee.term;
                    oli.Months_In_Year__c = tuitionFee.months;
                    oli.Next_Generated_Invoice__c = tuitionFee.dateMap.get(tuitionFee.nextGenInvoice);
                    oli.Invoice_Date__c = InvoiceDateGeneration.getNextInvoiceDate(tuitionFee.term, tuitionFee.dateMap.get(tuitionFee.nextGenInvoice));

                    newOLIs.add(oli);
                }
            }
            
            //Get the OLIs that are currently related to the Case and remove them
            List<OpportunityLineItem> currOLIs = new List<OpportunityLineItem>();
            currOLIs.addAll([Select Id, PricebookEntryId, Current__c, Payer__c from OpportunityLineItem Where OpportunityId =: this.student.id and Current__c =: true]);
            delete currOLIs;
            
            //If the pricebook is being changed then all OpplineItems must be deleted
            if(student.Pricebook2Id != priceBook)
            {
                delete [Select Id, OpportunityId from OpportunityLineItem Where OpportunityId =: this.student.id];
            }
            
            //Perform insertions/update
            student.Pricebook2Id = priceBook;
            update student;
            insert newOLIs;
            
            initOtherFees();
            return null;
        }
        catch (Exception e) {
            System.debug('### err ' +e.getMessage());
            return e.getMessage();
        }
    }
    
    /**             TEST METHODS            **/
    @IsTest(SeeAllData=True)
    static void testOpportunitySave() {
        
        //Setup model
        Invoice_Date_Settings__c settings = Invoice_Date_Settings__c.getInstance('Default');
        settings.Inc_Leave_Date__c = 40;        settings.Inc_Leave_sign__c = '>';
        settings.Inc_Start_Date__c = 90;        settings.Inc_Start_sign__c = '<=';
        settings.Inc_Month_Leave_Date__c = 40;  settings.Inc_Month_Leave_sign__c = '>';
        settings.Inc_Month_Start_Date__c = 90;  settings.Inc_Month_Start_sign__c = '<=';
        settings.Mth_Gen_Day__c = 25;           settings.Mth_Inv_Day__c = 1;
        settings.T1_Gen_Day__c = 15;    settings.T1_Gen_Mth__c = 'March';   settings.T1_Inv_Day__c = 15;    settings.T1_Inv_Mth__c = 'April';
        settings.T2_Gen_Day__c = 15;    settings.T2_Gen_Mth__c = 'July';    settings.T2_Inv_Day__c = 1;     settings.T2_Inv_Mth__c = 'August';
        settings.T3_Gen_Day__c = 15;    settings.T3_Gen_Mth__c = 'October'; settings.T3_Inv_Day__c = 15;    settings.T3_Inv_Mth__c = 'November';
        update settings;
        
        Account payer = new Account(Name = 'Test');
        insert payer;
        Pricebook2 pb = [Select Id, Name from Pricebook2 where IsStandard = true limit 1];
        Opportunity student = new Opportunity(Name = 'Test Student', Gender__c = 'Male', StageName = 'A/ Testing', Year_Group__c = 'Y1', CloseDate = System.today().addDays(10), 
                                                Student_Name__c = 'Morgan',  PriceBook2Id = pb.Id);
        insert student;
        student.StageName = 'Enrolled';
        update student;
        
        student = [Select Id, Year_Group__c From Opportunity Where Id =: student.Id];
        
        ApexPages.Standardcontroller sc = new ApexPages.Standardcontroller(student);
        FeeAssignmentController fac = new FeeAssignmentController(sc);
        
        Product2 prod1 = new Product2();
        prod1.IsActive = true;
        prod1.Name = 'prod1 Monthly, Termly or Yearly';
        prod1.Year_Group__c = ' 1 Monthly, Termly or Yearly';
        prod1.Invoice_Currency__c = 'EUR';
        prod1.Description = 'Monthly, Termly or Yearly';
        prod1.Fee_Frequency__c = 'Monthly';
        prod1.Description_of_fee__c = 'Tuition';
        insert prod1;
        prod1 = [select Id from Product2 Where Id =: prod1.Id];
        
        PricebookEntry pbe1 = new PriceBookEntry();
        pbe1.isActive = true;
        pbe1.UnitPrice = 1.0;
        pbe1.Pricebook2Id = pb.Id;
        pbe1.Product2Id = prod1.Id;
        insert pbe1;
        pbe1 = [Select Id, UnitPrice from PriceBookEntry Where Id =: pbe1.Id ];
        fac.otherFees.add(new OtherFee(pbe1.Id, 0.0, student, false));
        fac.getOtherFeesView();

        Product2 prod2 = new Product2();
        prod2.IsActive = true;
        prod2.Name = 'prod2 Monthly, Termly or Yearly';
        prod2.Year_Group__c = 'Y2';
        prod2.Invoice_Currency__c = 'EUR';
        prod2.Description = 'Monthly, Termly or Yearly';
        prod2.Fee_Frequency__c = 'Monthly';
        prod2.Description_of_fee__c = 'Tuition';
        insert prod2;
        prod2 = [select Id from Product2 Where Id =: prod2.Id];
        
        PricebookEntry pbe2 = new PriceBookEntry();
        pbe2.isActive = true;
        pbe2.UnitPrice = 1.0;
        pbe2.Pricebook2Id = pb.Id;
        pbe2.Product2Id = prod2.Id;
        insert pbe2;
        fac.tuitionFee.fee = pbe2.Id;
        
        fac.saveRedirect();
        
        List<OpportunityLineItem> oli = [Select Id, OpportunityId from OpportunityLineItem where OpportunityId =: student.Id];
        System.assertEquals(2, oli.size());
    }
    
    @IsTest(SeeAllData=True)
    static void testFeeLoading()
    {
        //Setup model
        Invoice_Date_Settings__c settings = Invoice_Date_Settings__c.getInstance('Default');
        settings.Inc_Leave_Date__c = 40;        settings.Inc_Leave_sign__c = '>';
        settings.Inc_Start_Date__c = 90;        settings.Inc_Start_sign__c = '<=';
        settings.Inc_Month_Leave_Date__c = 40;  settings.Inc_Month_Leave_sign__c = '>';
        settings.Inc_Month_Start_Date__c = 90;  settings.Inc_Month_Start_sign__c = '<=';
        settings.Mth_Gen_Day__c = 25;           settings.Mth_Inv_Day__c = 1;
        settings.T1_Gen_Day__c = 15;    settings.T1_Gen_Mth__c = 'March';   settings.T1_Inv_Day__c = 15;    settings.T1_Inv_Mth__c = 'April';
        settings.T2_Gen_Day__c = 15;    settings.T2_Gen_Mth__c = 'July';    settings.T2_Inv_Day__c = 1;     settings.T2_Inv_Mth__c = 'August';
        settings.T3_Gen_Day__c = 15;    settings.T3_Gen_Mth__c = 'October'; settings.T3_Inv_Day__c = 15;    settings.T3_Inv_Mth__c = 'November';
        update settings;
        
        Account payer = new Account(Name = 'Test');
        insert payer;
        Pricebook2 pb = [Select Id, Name from Pricebook2 where IsStandard = true limit 1];
        Opportunity student = new Opportunity(Name = 'Test Student', Gender__c = 'Male', StageName = 'A/ Testing', Year_Group__c = 'Y1', CloseDate = System.today().addDays(10), 
                                                Student_Name__c = 'Morgan',  PriceBook2Id = pb.Id);
        insert student;
        student.StageName = 'Enrolled';
        update student;
        
        student = [Select Id, Year_Group__c  From Opportunity Where Id =: student.Id];
        //Preload a tuition line item
        Product2 prod1 = new Product2();
        prod1.IsActive = true;
        prod1.Name = 'Monthly, Termly or Yearly';
        prod1.Year_Group__c = 'Y1';
        prod1.Invoice_Currency__c = 'EUR';
        prod1.Description = 'Monthly, Termly or Yearly';
        prod1.Fee_Frequency__c = 'Monthly';
        prod1.Description_of_fee__c = 'Tuition';
        insert prod1;
        prod1 = [select Id from Product2 Where Id =: prod1.Id];
        
        PricebookEntry pbe1 = new PriceBookEntry();
        pbe1.isActive = true;
        pbe1.UnitPrice = 1.0;
        pbe1.Pricebook2Id = pb.Id;
        pbe1.Product2Id = prod1.Id;
        insert pbe1;
        pbe1 = [Select Id, UnitPrice from PriceBookEntry Where Id =: pbe1.Id ];
        
        OpportunityLineItem tuition = new OpportunityLineItem();
        tuition.PricebookEntryId = pbe1.Id;
        tuition.OpportunityId = student.Id;
        tuition.Quantity = 1;
        tuition.UnitPrice = pbe1.UnitPrice;
        tuition.Current__c = true;
        tuition.Tuition__c = true;
        insert tuition;
        
        //And an other line item
        Product2 prod2 = new Product2();
        prod2.IsActive = true;
        prod2.Name = 'prod2 Monthly, Termly or Yearly';
        prod2.Year_Group__c = 'Y2';
        prod2.Invoice_Currency__c = 'EUR';
        prod2.Description = 'Monthly, Termly or Yearly';
        prod2.Fee_Frequency__c = 'Monthly';
        prod2.Description_of_fee__c = 'Tuition';
        insert prod2;
        prod2 = [select Id from Product2 Where Id =: prod2.Id];
        
        PricebookEntry pbe2 = new PriceBookEntry();
        pbe2.isActive = true;
        pbe2.UnitPrice = 1.0;
        pbe2.Pricebook2Id = pb.Id;
        pbe2.Product2Id = prod2.Id;
        insert pbe2;
        
        OpportunityLineItem other = new OpportunityLineItem();
        other.PricebookEntryId = pbe2.Id;
        other.OpportunityId = student.Id;
        other.Quantity = 1;
        other.UnitPrice = pbe2.UnitPrice;
        other.Current__c = true;
        other.Tuition__c = false;
        insert other;
        
        //And the controller
        ApexPages.Standardcontroller sc = new ApexPages.Standardcontroller(student);
        FeeAssignmentController fac = new FeeAssignmentController(sc);
        //assert the tuition item exists
        System.assertEquals(pbe1.Id, fac.tuitionFee.fee);
        //and the other item
        System.assertEquals(1, fac.otherFees.size());
    }
    
    @IsTest(SeeAllData=True)
    static void boostCoverage()
    {
        //Setup model
        Invoice_Date_Settings__c settings = Invoice_Date_Settings__c.getInstance('Default');
        settings.Inc_Leave_Date__c = 40;        settings.Inc_Leave_sign__c = '>';
        settings.Inc_Start_Date__c = 90;        settings.Inc_Start_sign__c = '<=';
        settings.Inc_Month_Leave_Date__c = 40;  settings.Inc_Month_Leave_sign__c = '>';
        settings.Inc_Month_Start_Date__c = 90;  settings.Inc_Month_Start_sign__c = '<=';
        settings.Mth_Gen_Day__c = 25;           settings.Mth_Inv_Day__c = 1;
        settings.T1_Gen_Day__c = 15;    settings.T1_Gen_Mth__c = 'March';   settings.T1_Inv_Day__c = 15;    settings.T1_Inv_Mth__c = 'April';
        settings.T2_Gen_Day__c = 15;    settings.T2_Gen_Mth__c = 'July';    settings.T2_Inv_Day__c = 1;     settings.T2_Inv_Mth__c = 'August';
        settings.T3_Gen_Day__c = 15;    settings.T3_Gen_Mth__c = 'October'; settings.T3_Inv_Day__c = 15;    settings.T3_Inv_Mth__c = 'November';
        update settings;
        
        Account payer = new Account(Name = 'Test');
        insert payer;
        Pricebook2 pb = [Select Id, Name from Pricebook2 where IsStandard = true limit 1];
        Opportunity student = new Opportunity(Name = 'Test Student', Gender__c = 'Male', StageName = 'A/ Testing', Year_Group__c = 'Y1', CloseDate = System.today().addDays(10), 
                                                Student_Name__c = 'Morgan',   PriceBook2Id = pb.Id);
        insert student;
        
        Product2 prod1 = new Product2();
        prod1.IsActive = true;
        prod1.Name = 'Monthly, Termly or Yearly prod1';
        prod1.Year_Group__c = 'Y1';
        prod1.Invoice_Currency__c = 'EUR';
        prod1.Description = 'Monthly, Termly or Yearly';
        prod1.Fee_Frequency__c = 'Monthly';
        prod1.Description_of_fee__c = 'Tuition';
        insert prod1;
        prod1 = [select Id from Product2 Where Id =: prod1.Id];
        
        PricebookEntry pbe = new PriceBookEntry();
        pbe.isActive = true;
        pbe.UnitPrice = 1.0;
        pbe.Pricebook2Id = pb.Id;
        pbe.Product2Id = prod1.Id;
        insert pbe;
        pbe = [Select Id, UnitPrice from PriceBookEntry Where Id =: pbe.Id ];
        
        ApexPages.Standardcontroller sc = new ApexPages.Standardcontroller(student);
        FeeAssignmentController fac = new FeeAssignmentController(sc);
        fac.getOppHasPriceBook();
        fac.getPayerOptions();
        fac.getPriceBookOptions();
    } 
}