force-app/main/default/objects/Group_Website__c.object
<CustomObject>
    <fields>
        <fullName>English_Parent__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Points at the parent (english) version of this record</description>
        <label>English Parent</label>
        <referenceTo>Group_Website__c</referenceTo>
        <relationshipLabel>Translations</relationshipLabel>
        <relationshipName>english_parent</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Internal_Link__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field will be used in Web Block records to select a link to an internal node of the school website. NOTE 19/08/2015 I don&apos;t think this field is now being used and can maybe be deleted, unless it&apos;s used somewhere on the group site</description>
        <label>Internal Link</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.Language__c</field>
                <operation>equals</operation>
                <valueField>Web_Content__c.Language__c</valueField>
            </filterItems>
            <filterItems>
                <field>Web_Content__c.School_List__c</field>
                <operation>contains</operation>
                <valueField>$User.School__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Web_Content__c</referenceTo>
        <relationshipLabel>Internal Links</relationshipLabel>
        <relationshipName>internal_links</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Language__c</fullName>
        <description>The language of the record. This field is used in connection with the school websites</description>
        <inlineHelpText>Select the language of your record.</inlineHelpText>
        <label>Language</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>EN</fullName>
                    <default>true</default>
                    <label>EN</label>
                </value>
                <value>
                    <fullName>ES</fullName>
                </value>
                <value>
                    <fullName>PT</fullName>
                </value>
                <value>
                    <fullName>RU</fullName>
                </value>
                <value>
                    <fullName>UK</fullName>
                </value>
                <value>
                    <fullName>UZ</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <label>Order</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Website</label>
    <nameField>
        <label>Menu Item</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Websites</pluralLabel>
    <recordTypes>
        <fullName>Home_Page_2</fullName>
        <active>true</active>
        <label>Homepage</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/News_Events__c.object
<CustomObject>
    <fields>
        <fullName>English_Parent__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Points at the parent (english) version of this record</description>
        <inlineHelpText>Only required for records in languages other than English</inlineHelpText>
        <label>English Parent</label>
        <referenceTo>News_Events__c</referenceTo>
        <relationshipLabel>Translations</relationshipLabel>
        <relationshipName>Translated_Records</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Event_Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Language__c</fullName>
        <description>The language of the record. This field is used in connection with the school websites</description>
        <inlineHelpText>Select the language for this record.</inlineHelpText>
        <label>Language</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>EN</fullName>
                    <default>true</default>
                    <label>EN</label>
                </value>
                <value>
                    <fullName>ES</fullName>
                </value>
                <value>
                    <fullName>PT</fullName>
                </value>
                <value>
                    <fullName>RU</fullName>
                </value>
                <value>
                    <fullName>UK</fullName>
                </value>
                <value>
                    <fullName>UZ</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Publish_in_Portal_School_Hub__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Publish in Portal Calendar</label>
        <type>Checkbox</type>
    </fields>
    <label>News &amp; Events</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>News &amp; Events</pluralLabel>
    <recordTypes>
        <fullName>Event</fullName>
        <active>true</active>
        <label>Event</label>
    </recordTypes>
    <recordTypes>
        <fullName>Event_Translation</fullName>
        <active>true</active>
        <label>Event Translation</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Web_Content__c.object
<CustomObject>
    <fields>
        <fullName>Assigned_Translator__c</fullName>
        <description>The translator that the translation has been assigned to. Also (indirectly) controls record sharing.</description>
        <label>Assigned Translator</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Laura González (Spanish 1)</fullName>
                </value>
                <value>
                    <fullName>Emma Watkins (Spanish 2)</fullName>
                </value>
                <value>
                    <fullName>Alexandra Mostaza (Spanish 3)</fullName>
                </value>
                <value>
                    <fullName>Sonia Fernandez (Spanish 4)</fullName>
                </value>
                <value>
                    <fullName>TBD (Spanish 5)</fullName>
                </value>
                <value>
                    <fullName>Tania Ramos (Portuguese 1)</fullName>
                </value>
                <value>
                    <fullName>TBD (Portuguese 2)</fullName>
                </value>
                <value>
                    <fullName>External Translator TBD (Portuguese 3)</fullName>
                </value>
                <value>
                    <fullName>Elena Savtsova (Russian 1)</fullName>
                </value>
                <value>
                    <fullName>Aziz Abdumukhtarov (Russian 2)</fullName>
                </value>
                <value>
                    <fullName>Oksana Zueva (Russian 3)</fullName>
                </value>
                <value>
                    <fullName>Test Translator (Spanish, Portuguese, Russian)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Available_Under_Web_Content__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Available Under Web Content</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>(1 AND 2 AND 3) OR (1 AND 4 AND 5)</booleanFilter>
            <errorMessage>Value does not exist, is not an &apos;EN&apos; (English) record or is not the correct record type.</errorMessage>
            <filterItems>
                <field>Web_Content__c.Language__c</field>
                <operation>equals</operation>
                <value>EN</value>
            </filterItems>
            <filterItems>
                <field>Web_Content__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Normal Web Content</value>
            </filterItems>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>equals</operation>
                <value>Additional Navigable Content</value>
            </filterItems>
            <filterItems>
                <field>Web_Content__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Additional Navigable Content, Normal Web Content</value>
            </filterItems>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>equals</operation>
                <value>Groupable</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Web_Content__c</referenceTo>
        <relationshipLabel>Additional Navigable Content &amp; Groupables</relationshipLabel>
        <relationshipName>Web_Sub_Content</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>English_Parent__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Points at the parent (english) version of this record</description>
        <label>English Parent</label>
        <referenceTo>Web_Content__c</referenceTo>
        <relationshipLabel>Translations</relationshipLabel>
        <relationshipName>Translated_Records</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Internal_Link__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is used to create internal links to the own site when creating a Web Block.</description>
        <label>Internal Link</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>The &apos;Internal Link&apos; must be to a record of the same language with its own URL</errorMessage>
            <filterItems>
                <field>Web_Content__c.Language__c</field>
                <operation>equals</operation>
                <valueField>$Source.Language__c</valueField>
            </filterItems>
            <filterItems>
                <field>Web_Content__c.RecordType.Name</field>
                <operation>contains</operation>
                <value>Additional Navigable Content, Normal Web Content, Groupable</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Web_Content__c</referenceTo>
        <relationshipLabel>Web Blocks Linking to this Record</relationshipLabel>
        <relationshipName>web_content_link</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Language__c</fullName>
        <description>Language switch for website translation management.</description>
        <label>Language</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>EN</fullName>
                    <default>true</default>
                    <label>EN</label>
                </value>
                <value>
                    <fullName>ES</fullName>
                </value>
                <value>
                    <fullName>PT</fullName>
                </value>
                <value>
                    <fullName>RU</fullName>
                </value>
                <value>
                    <fullName>UK</fullName>
                </value>
                <value>
                    <fullName>UZ</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <defaultValue>IF(
   OR(
      $RecordType.DeveloperName = &quot;Menu_Image&quot;, 
      $RecordType.DeveloperName = &quot;Announcement_Bar&quot;
      ),
   -1, 
   null
   )</defaultValue>
        <inlineHelpText>Orders items from top to bottom, left to right, from lowest number to highest. Cannot be blank and must be in the range 0-199 for Home Page Top Slideshow Images, 200-299 for other Home Page Items, 50-99 for Groupables and 0-49 for all other content types.</inlineHelpText>
        <label>Order</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Parent_Item__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Parent Item</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Value does not exist or is not an &apos;EN&apos; (English) record.</errorMessage>
            <filterItems>
                <field>Group_Website__c.Language__c</field>
                <operation>equals</operation>
                <value>EN</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Group_Website__c</referenceTo>
        <relationshipLabel>Web Contents</relationshipLabel>
        <relationshipName>Web_Contents</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Related_to_Web_Content__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Defines the web content record which the sidebar block is related to</description>
        <label>Related to Web Content</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Value does not exist or is not an English parent record</errorMessage>
            <filterItems>
                <field>Web_Content__c.Language__c</field>
                <operation>equals</operation>
                <value>EN</value>
            </filterItems>
            <filterItems>
                <field>Web_Content__c.English_Parent__c</field>
                <operation>equals</operation>
                <value></value>
            </filterItems>
            <infoMessage>The related web contect record must be an English record</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Web_Content__c</referenceTo>
        <relationshipLabel>Sidebar Blocks</relationshipLabel>
        <relationshipName>Sidebar_Block</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Section_1_Main_Text_English__c</fullName>
        <label>Main Text (English)</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <label>Web Content</label>
    <nameField>
        <label>Menu Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Web Content</pluralLabel>
    <recordTypes>
        <fullName>Groupable</fullName>
        <active>true</active>
        <label>Groupable</label>
    </recordTypes>
    <recordTypes>
        <fullName>Home_Page_Picture_Carousel_Translation</fullName>
        <active>true</active>
        <label>Home Page Picture Carousel Translation</label>
    </recordTypes>
    <recordTypes>
        <fullName>Home_Page_Picture_Carrousel</fullName>
        <active>true</active>
        <description>For picture carousels on the home page of the school site. In the future will also be used for the group site.</description>
        <label>Home Page Picture Carousel</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/TestWebContent.cls
@isTest
private class TestWebContent{
    //test delete validations
    static testMethod void testWebContentDeletion(){
        Group_Website__c gw = new Group_Website__c(Name='Test',Order__c =1 );
        gw.RecordTypeId = [select Id from RecordType where SObjectType = 'Group_Website__c' AND DeveloperName = 'Home_Page_2'].Id;
        insert gw;
        //create web content
        Web_Content__c wc = new Web_Content__c();
        wc.RecordTypeId = [select Id from RecordType where SObjectType = 'Web_Content__c' AND DeveloperName = 'Home_Page_Picture_Carrousel'].Id;
        wc.Name = 'Test';
        wc.Order__c  = 1;
        wc.Parent_Item__c = gw.Id;
        wc.Section_1_Main_Text_English__c = 'Test';
        insert wc;
        
        //create available under web content 
        Web_Content__c wc1 = new Web_Content__c();
        wc1.Language__c = 'EN';
        wc1.RecordTypeId = [select Id from RecordType where SObjectType = 'Web_Content__c' AND DeveloperName = 'Groupable'].Id;
        wc1.Name = 'wc1';
        wc1.Order__c = 55;
        wc1.Section_1_Main_Text_English__c = 'Test';
        wc1.Parent_Item__c = gw.Id;
        insert wc1;
        //create web content translation
        Web_Content__c wc2 = new Web_Content__c();
        wc2.RecordTypeId = [select Id from RecordType where SObjectType = 'Web_Content__c' AND DeveloperName = 'Home_Page_Picture_Carousel_Translation'].Id;
        wc2.Name = 'Test';
        wc2.Order__c  = 1;
        wc2.Language__c = 'ES';
        wc2.Assigned_Translator__c = 'Emma Watkins (Spanish 2)';
        //wc2.Parent_Item__c = gw.Id;
        wc2.Section_1_Main_Text_English__c = 'Test';
        //wc2.Available_Under_Web_Content__c = wc1.Id;
        wc2.English_Parent__c = wc.Id;
        //wc2.Internal_Link__c = wc.Id;
        //wc2.Related_to_Web_Content__c = wc.Id;        
        insert wc2;
        
        Test.startTest();
            try{
                delete wc;
            }catch(Exception e){
                
            }
        Test.stopTest();
        
    }
    
    static testMethod void testNewsEventDeletion(){
        News_Events__c newsEvent = new News_Events__c();
        newsEvent.RecordTypeId = [select Id from RecordType where SObjectType='News_Events__c' AND DeveloperName='Event'].Id;
        newsEvent.Name = 'Test Event';
        
        newsEvent.Event_Start_Date__c = date.today();
        //newsEvent.Publish_in_Portal_School_Hub__c = true;
        //newsEvent.Post_Entry_in_Related_Blog__c = 'Yes - And tag as Essential Communication'; 
        newsEvent.Subtitle__c = 'Teaser Text';          
        insert newsEvent;
        
        News_Events__c newsEventChild = new News_Events__c();
        newsEventChild.RecordTypeId = [select Id from RecordType where SObjectType='News_Events__c' AND DeveloperName='Event_Translation'].Id;
        newsEventChild.Name = 'Test Event';
        
        newsEventChild.Event_Start_Date__c = date.today();
        //newsEvent.Publish_in_Portal_School_Hub__c = true;
        //newsEventChild.Post_Entry_in_Related_Blog__c = 'Yes - And tag as Essential Communication'; 
        newsEventChild.Subtitle__c = 'Teaser Text';    
        newsEventChild.English_Parent__c =   newsEvent.Id;  
        newsEventChild.Language__c = 'ES';
        //newsEventChild.Assigned_Translator__c = 'Emma Watkins (Spanish 2)';
        insert newsEventChild;  
        Test.startTest();
            try{
                delete newsEvent;
            }catch(Exception e){
                
            }
        Test.stopTest();
            
    }
}