force-app/main/default/objects/Group_Website__c.object
<CustomObject>
    <fields>
        <fullName>Attachment_Id__c</fullName>
        <description>This field captures the id of any attachment created in its parent record</description>
        <label>Attachment Id</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Content_Subtitle__c</fullName>
        <label>Content Subtitle</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Deleted_Attachment_Id__c</fullName>
        <description>Captures the att id of any deleted attachment in its parent record</description>
        <label>Deleted Attachment Id</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <label>Order</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Website</label>
    <nameField>
        <label>Menu Item</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Websites</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Web_Content__c.object
<CustomObject>
    <fields>
        <fullName>Attachment_Id__c</fullName>
        <description>This field captures the id of any attachment created in its parent record</description>
        <label>Attachment Id</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Content_Subtitle__c</fullName>
        <description>NB. If Web Content type = Home Page Picture Carousel this field is only applicable for the group website and defines the text in the bottom right corner of the home page pictures.</description>
        <label>Subtitle</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Deleted_Attachment_Id__c</fullName>
        <description>Captures the att id of any deleted attachment in its parent record</description>
        <label>Deleted Attachment Id</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <defaultValue>IF(
   OR(
      $RecordType.DeveloperName = &quot;Menu_Image&quot;, 
      $RecordType.DeveloperName = &quot;Announcement_Bar&quot;
      ),
   -1, 
   null
   )</defaultValue>
        <inlineHelpText>Orders items from top to bottom, left to right, from lowest number to highest. Cannot be blank and must be in the range 0-199 for Home Page Top Slideshow Images, 200-299 for other Home Page Items, 50-99 for Groupables and 0-49 for all other content types.</inlineHelpText>
        <label>Order</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Parent_Item__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Parent Item</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Value does not exist or is not an &apos;EN&apos; (English) record.</errorMessage>
            <filterItems>
                <field>Group_Website__c.Language__c</field>
                <operation>equals</operation>
                <value>EN</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Group_Website__c</referenceTo>
        <relationshipLabel>Web Contents</relationshipLabel>
        <relationshipName>Web_Contents</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Web Content</label>
    <nameField>
        <label>Menu Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Web Content</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/Test_att_notice_webcontent.cls
@isTest
private class Test_att_notice_webcontent  {
        
        static testMethod void myUnitTest() {
            test.starttest();
            
            Group_Website__c parent =new Group_Website__c();
            parent.Name = 'test parent';
            parent.Order__c =  10;
            insert parent;
            
            Web_Content__c objWeb_Content=new Web_Content__c(Name='test child');
            objWeb_Content.Parent_Item__c=parent.Id;
            objWeb_Content.Content_Subtitle__c = 'title';
            objWeb_Content.Order__c =10;
            insert objWeb_Content;
            list<Attachment> listAttachment = new list<Attachment>();
            
            Attachment attach=new Attachment();    
            attach.Name='Unit Test Attachment';
            Blob bodyBlob=Blob.valueOf('Unit Test Attachment Body');
            attach.body=bodyBlob;
            attach.parentId=parent.id;
            listAttachment.add(attach);
            
            Attachment attach1=new Attachment();    
            attach1.Name='Unit Test Attachment1';
            Blob bodyBlob1=Blob.valueOf('Unit Test Attachment Body');
            attach1.body=bodyBlob1;
            attach1.parentId=parent.id;
            listAttachment.add(attach1);
            
            insert listAttachment;
            
            test.stoptest();
            
            list<Group_Website__c> parentList =[Select id,Attachment_Id__c from Group_Website__c  where id=:parent.Id];
            //system.assert(parentList.get(0).Attachment_Id__c <> null);
        }
        
        static testMethod void myUnitTest_delete() {
            test.starttest();
            
            Group_Website__c parent =new Group_Website__c();
            parent.Name = 'test parent';
            parent.Order__c =  10;
            insert parent;
            
            Web_Content__c objWeb_Content=new Web_Content__c(Name='test child');
            objWeb_Content.Parent_Item__c=parent.Id;
            objWeb_Content.Content_Subtitle__c = 'title';
            objWeb_Content.Order__c =10;
            insert objWeb_Content;
            list<Attachment> listAttachment = new list<Attachment>();
            
            Attachment attach=new Attachment();    
            attach.Name='Unit Test Attachment';
            Blob bodyBlob=Blob.valueOf('Unit Test Attachment Body');
            attach.body=bodyBlob;
            attach.parentId=parent.id;
            listAttachment.add(attach);
            
            Attachment attach1=new Attachment();    
            attach1.Name='Unit Test Attachment1';
            Blob bodyBlob1=Blob.valueOf('Unit Test Attachment Body');
            attach1.body=bodyBlob1;
            attach1.parentId=parent.id;
            listAttachment.add(attach1);
            
            insert listAttachment;
            delete listAttachment;
            test.stoptest();
            
            list<Group_Website__c> parentList =[Select id,Deleted_Attachment_Id__c from Group_Website__c  where id=:parent.Id];
            //system.assert(parentList.get(0).Deleted_Attachment_Id__c <> null);
        }
        
}