force-app/main/default/objects/Group__c.object
<CustomObject>
    <fields>
        <fullName>Academic_Year__c</fullName>
        <formula>IF(
   TEXT(Group_Type__c)=&quot;School Group&quot;, 
   Current_Academic_Year__c, 
   IF(
      AND(
          MONTH(DATEVALUE(CreatedDate))&lt;=12, 
          MONTH(DATEVALUE(CreatedDate))&gt;=8
          ), 
      TEXT(YEAR(DATEVALUE(CreatedDate)))&amp;&quot;/&quot;&amp; TEXT(CreatedDate_plus_1__c ),  
      TEXT(CreatedDate_minus_1__c)&amp;&quot;/&quot;&amp;TEXT(YEAR(DATEVALUE(CreatedDate)))
      )
   )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Academic Year</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>School__c</fullName>
        <formula>TEXT(Owner:User.School__c)</formula>
        <label>School</label>
        <type>Text</type>
    </fields>
    <label>Student Group</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Student Groups</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/News_Events__c.object
<CustomObject>
    <fields>
        <fullName>Academic_Year__c</fullName>
        <formula>IF(MONTH(Event_Start_Date__c)&gt;=8, 

TEXT(YEAR(Event_Start_Date__c))&amp;&quot;-&quot;&amp;TEXT(YEAR(Event_Start_Date__c)+1),

TEXT(YEAR(Event_Start_Date__c)-1)&amp;&quot;-&quot;&amp;TEXT(YEAR(Event_Start_Date__c)))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Academic Year</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Event_End_Date__c</fullName>
        <inlineHelpText>If the end date is the same as the start date then please leave blank</inlineHelpText>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Event_End_Month__c</fullName>
        <formula>CASE(TEXT(MONTH(Event_End_Date__c)), &quot;1&quot;, &quot;Jan&quot;, &quot;2&quot;, &quot;Feb&quot;, &quot;3&quot;, &quot;Mar&quot;, &quot;4&quot;, &quot;Apr&quot;, &quot;5&quot;, &quot;May&quot;, &quot;6&quot;, &quot;Jun&quot;, &quot;7&quot;, &quot;Jul&quot;, &quot;8&quot;, &quot;Aug&quot;, &quot;9&quot;, &quot;Sep&quot;, &quot;10&quot;, &quot;Oct&quot;, &quot;11&quot;, &quot;Nov&quot;, &quot;12&quot;, &quot;Dec&quot;, &quot;&quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Event End Month</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Event_Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Event_Start_Month__c</fullName>
        <formula>CASE(TEXT(MONTH(Event_Start_Date__c)), &quot;1&quot;, &quot;Jan&quot;, &quot;2&quot;, &quot;Feb&quot;, &quot;3&quot;, &quot;Mar&quot;, &quot;4&quot;, &quot;Apr&quot;, &quot;5&quot;, &quot;May&quot;, &quot;6&quot;, &quot;Jun&quot;, &quot;7&quot;, &quot;Jul&quot;, &quot;8&quot;, &quot;Aug&quot;, &quot;9&quot;, &quot;Sep&quot;, &quot;10&quot;, &quot;Oct&quot;, &quot;11&quot;, &quot;Nov&quot;, &quot;12&quot;, &quot;Dec&quot;, &quot;&quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Event Start Month</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Is_More_Date__c</fullName>
        <description>Defines when a record should be included in the &apos;More&apos; filter on the &apos;Calendar&apos; tab in the parent portal</description>
        <formula>OR( 
   Event_Start_Date__c &gt;= TODAY(), 
   Event_End_Date__c &gt;= TODAY() 
   )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Is More Date</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Is_My_Record__c</fullName>
        <formula>OwnerId = $User.Id</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Is My Record</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Is_This_Term_Record__c</fullName>
        <description>Defines when a record should be included in the &apos;This Term&apos; filter on the &apos;Calendar&apos; tab in the parent portal</description>
        <formula>IF(AND(TODAY()&gt;=DATE(YEAR(First_Date_of_Term_3_Copy__c)-1,08,01), TODAY()&lt;=DATE(YEAR(First_Date_of_Term_3_Copy__c)-1,12,31), OR(Event_Start_Date__c&gt;=TODAY(), Event_End_Date__c&gt;=TODAY()), Event_Start_Date__c&lt;=DATE(YEAR(First_Date_of_Term_3_Copy__c)-1,12,31)), TRUE, 

IF(AND(TODAY()&gt;=DATE(YEAR(First_Date_of_Term_3_Copy__c),01,01), TODAY()&lt;First_Date_of_Term_3_Copy__c, OR(Event_Start_Date__c&gt;=TODAY(), Event_End_Date__c&gt;=TODAY()), Event_Start_Date__c&lt;First_Date_of_Term_3_Copy__c), TRUE,

IF(AND(TODAY()&gt;=First_Date_of_Term_3_Copy__c, TODAY()&lt;=DATE(YEAR(First_Date_of_Term_3_Copy__c),07,31), OR(Event_Start_Date__c&gt;=TODAY(), Event_End_Date__c&gt;=TODAY()), Event_Start_Date__c&lt;=DATE(YEAR(First_Date_of_Term_3_Copy__c),07,31)), TRUE,

FALSE)))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Is This Term Record</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Is_This_Year_Record__c</fullName>
        <description>Defines when a record should be included in the &apos;This Term&apos; filter on the &apos;Calendar&apos; tab in the parent portal</description>
        <formula>AND(OR(Event_Start_Date__c &gt;=TODAY(), Event_End_Date__c &gt;=TODAY()), Event_Start_Date__c &lt;  Student_Group__r.Start_Date_Next_Academic_Year__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Is This Year Record</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Language__c</fullName>
        <description>The language of the record. This field is used in connection with the school websites</description>
        <inlineHelpText>Select the language for this record.</inlineHelpText>
        <label>Language</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>EN</fullName>
                    <default>true</default>
                    <label>EN</label>
                </value>
                <value>
                    <fullName>ES</fullName>
                </value>
                <value>
                    <fullName>PT</fullName>
                </value>
                <value>
                    <fullName>RU</fullName>
                </value>
                <value>
                    <fullName>UK</fullName>
                </value>
                <value>
                    <fullName>UZ</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Link_1_Title__c</fullName>
        <label>Link 1 Title</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Link_1__c</fullName>
        <label>Link 1</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Link_2_Title__c</fullName>
        <label>Link 2 Title</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Link_2__c</fullName>
        <label>Link 2</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Link_3_Title__c</fullName>
        <label>Link 3 Title</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Link_3__c</fullName>
        <label>Link 3</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Main_Text__c</fullName>
        <inlineHelpText>Please add the main text in a standard font such as Arial 12 Black (Regular) for best results.</inlineHelpText>
        <label>Main Text</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Notification_Type__c</fullName>
        <description>Defines the type of notification to be sent (set by button click or workflow rule action) when a calendar entry that falls within the next 14 days is created, edited or cancelled</description>
        <label>Notification Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Standard</fullName>
                    <default>true</default>
                    <label>Standard</label>
                </value>
                <value>
                    <fullName>Edited</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Publish_in_Portal_School_Hub__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Publish in Portal Calendar</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Publish_on_Group_Site__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Publish on Group Site</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Publish_on_School_Site__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Publish on Site(s)</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>School__c</fullName>
        <formula>IF(
   AND(
       TEXT(Share_with_Admin_Dept_of__c) != &quot;&quot;, 
       TEXT(Share_with_Admin_Dept_of__c) != &quot;Do Not Share&quot;
       ),
   TEXT(Share_with_Admin_Dept_of__c), 
   TEXT(Owner:User.School__c)
   )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>School</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Student_Group__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Student Group</label>
        <referenceTo>Group__c</referenceTo>
        <relationshipLabel>Calendar</relationshipLabel>
        <relationshipName>News_Events</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Subtitle__c</fullName>
        <inlineHelpText>- For portal dates, please include any essential info (inc. time) in this field. This text will be visible under the title by default. (i.e. unlike the &apos;main text&apos; field, no extra clicks are required to view).
- For News, please add a short teaser</inlineHelpText>
        <label>Essential Info (inc time, if any)/Teaser</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Video_1_TITLE__c</fullName>
        <description>The title of the matching video</description>
        <inlineHelpText>Introduce the title of the video you want to show in the Group Website.</inlineHelpText>
        <label>Video 1 TITLE</label>
        <length>75</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Video_1_URL__c</fullName>
        <description>This field is used to upload videos to the Group Site. The videos are hosted in the VIMEO premium account and this field only needs the url of it.</description>
        <inlineHelpText>Introduce the URL of the video you want to show in the Group Website. Include the whole url, ex: http://www.myvideo.com</inlineHelpText>
        <label>Video 1 URL</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Video_2_TITLE__c</fullName>
        <description>The title of the matching video</description>
        <inlineHelpText>Introduce the title of the video you want to show in the Group Website.</inlineHelpText>
        <label>Video 2 TITLE</label>
        <length>75</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Video_2_URL__c</fullName>
        <description>This field is used to upload videos to the Group Site. The videos are hosted in the VIMEO premium account and this field only needs the url of it.</description>
        <inlineHelpText>Introduce the URL of the video you want to show in the Group Website. Include the whole url, ex: http://www.myvideo.com</inlineHelpText>
        <label>Video 2 URL</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Video_3_TITLE__c</fullName>
        <description>The title of the matching video</description>
        <inlineHelpText>Introduce the title of the video you want to show in the Group Website.</inlineHelpText>
        <label>Video 3 TITLE</label>
        <length>75</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Video_3_URL__c</fullName>
        <description>This field is used to upload videos to the Group Site. The videos are hosted in the VIMEO premium account and this field only needs the url of it.</description>
        <inlineHelpText>Introduce the URL of the video you want to show in the Group Website. Include the whole url, ex: http://www.myvideo.com</inlineHelpText>
        <label>Video 3 URL</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Video_4_TITLE__c</fullName>
        <description>The title of the matching video</description>
        <inlineHelpText>Introduce the title of the video you want to show in the Group Website.</inlineHelpText>
        <label>Video 4 TITLE</label>
        <length>75</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Video_4_URL__c</fullName>
        <description>This field is used to upload videos to the Group Site. The videos are hosted in the VIMEO premium account and this field only needs the url of it.</description>
        <inlineHelpText>Introduce the URL of the video you want to show in the Group Website. Include the whole url, ex: http://www.myvideo.com</inlineHelpText>
        <label>Video 4 URL</label>
        <type>Url</type>
    </fields>
    <label>News &amp; Events</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>News &amp; Events</pluralLabel>
    <recordTypes>
        <fullName>Event</fullName>
        <active>true</active>
        <label>Event</label>
    </recordTypes>
    <recordTypes>
        <fullName>Holiday</fullName>
        <active>true</active>
        <label>Holiday</label>
    </recordTypes>
    <recordTypes>
        <fullName>Reminder</fullName>
        <active>true</active>
        <label>Notice</label>
    </recordTypes>
    <recordTypes>
        <fullName>Term</fullName>
        <active>true</active>
        <label>Term</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/School__c.object
<CustomObject>
    <label>School</label>
    <nameField>
        <label>School Code/UID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Schools</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/NewsEventList_Controller.cls
public with sharing class NewsEventList_Controller {   
    private Id groupId {get;set;}
    private string groupName {get;set;}
    private boolean pageLoad {get;set;}
    public string pageURL {get{
        return '/apex/Tabbed_Group_Detail?id='+groupId+'&stab=calendar&st='+selectedTermFilter+'&stab=calendar';
    }}
    //for filter
    public list<SelectOption> termOptions {get;set;}
    public String selectedTermFilter {get;set;}
    public List<News_Events__c> records {get{
        return paginationSet.getRecords();
    }set;}
    private ApexPages.StandardSetController paginationSet {get;set;} 
    public integer totalRegistrations {get{
        return paginationSet.getResultSize();
    }}
    public integer totalPages {get{
        return Integer.valueOf((totalRegistrations/decimal.valueOf(pageSize)).round(System.RoundingMode.CEILING));
    }}
    public integer pageNum {get;set;}
    private integer pageSize {get;set;}
    //for status filtering
    public list<SelectOption> statusOptions {get;set;}
    public string selectedStatus {get;set;}
    //for owner filtering
    public list<SelectOption> ownerOptions {get;set;}
    public string selectedOwner {get;set;}
    public NewsEventList_Controller(ApexPages.StandardController controller){
        pageLoad = true;
        pageSize = 20;
        groupId = controller.getId();
        groupName = [select Name from Group__c where Id=:groupId].Name;
        termOptions = new list<SelectOption>();
        termOptions.add(new SelectOption('Past','Past'));
        termOptions.add(new SelectOption('This Term','This Term'));
        termOptions.add(new SelectOption('This Year','This Year')); 
        termOptions.add(new SelectOption('More','More'));
        string sterm = system.currentPageReference().getParameters().get('st');
        if(sterm == null | sterm == ''){
            selectedTermFilter = 'This Term';
        }else{
            selectedTermFilter = sterm;
        }
        //for status options
        statusOptions = new list<SelectOption>();
        statusOptions.add(new SelectOption('All','All'));
        statusOptions.add(new SelectOption('Published','Published'));
        statusOptions.add(new SelectOption('Cancelled','Not Published / Cancelled'));
        selectedStatus = 'Published';
        
        //for owner options
        ownerOptions = new list<SelectOption>();
        ownerOptions.add(new SelectOption('All','All Events'));
        ownerOptions.add(new SelectOption('My','My Events Only'));
        selectedOwner = 'All';
        
        //fetch events
        fetchEvents();
        pageNum = paginationSet.getPageNumber();
    }
    
    
    public PageReference fetchEvents(){
        records = new list<News_Events__c>();
        string query = 'Select n.CreatedById, n.Publish_on_Group_Site__c,  n.Publish_on_School_Site__c, n.Publish_in_Portal_School_Hub__c, n.Language__c, n.Video_4_URL__c, n.Video_4_TITLE__c, n.Video_3_URL__c, n.Video_3_TITLE__c, n.Video_2_URL__c, n.Video_2_TITLE__c, n.Video_1_URL__c, n.Video_1_TITLE__c, n.Subtitle__c, n.Student_Group__c, n.School__c, n.RecordType.Name, n.RecordTypeId, n.OwnerId, n.Name, n.Main_Text__c, n.Link_3__c, n.Link_3_Title__c, n.Link_2__c, n.Link_2_Title__c, n.Link_1__c, n.Link_1_Title__c, n.Id, n.Event_Start_Month__c, n.Event_Start_Date__c, n.Event_End_Month__c, n.Event_End_Date__c, n.CreatedDate, n.Academic_Year__c From News_Events__c n where n.Student_Group__c =:groupId  ';
        system.debug('****NewsEventList_Controller***fetchEvents****selectedTermFilter='+selectedTermFilter);   
        if(selectedTermFilter != null){
            if(selectedTermFilter == 'This Term'){
                query += ' AND Is_This_Term_Record__c  = true ';
            }else if(selectedTermFilter == 'This Year'){
                query += ' AND Is_This_Year_Record__c  = true ';
            }else if(selectedTermFilter == 'More'){
                query += ' AND Is_More_Date__c   = true ';
            }else if(selectedTermFilter == 'Past'){
                query += ' AND Is_This_Term_Record__c  = false ';
                query += ' AND Is_This_Year_Record__c  = false ';
                query += ' AND Is_More_Date__c   = false ';
            }
        }
        if(selectedStatus != null){
            if(selectedStatus == 'Published'){
                query += ' AND Publish_in_Portal_School_Hub__c   = true ';  
            }else if(selectedStatus == 'Cancelled'){
                query += ' AND Publish_in_Portal_School_Hub__c   = false ';
            }
        }
        
        if(selectedOwner != null){
            if(selectedOwner == 'My'){
                query += ' AND Is_my_record__c   =  true ';
            }
        }
        /*
        if(selectedFilters != null){
            set<String> temp_set = new set<String>();
            for(String s:selectedFilters){
                temp_set.add(s);                
            }
            if(temp_set.contains('Published')){
                query += ' AND Publish_in_Portal_School_Hub__c   = true ';  
            }else{
                query += ' AND Publish_in_Portal_School_Hub__c   = false ';
            }
            if(temp_set.contains('Cancelled')){
                query += ' AND Notification_Type__c   = \'Cancelled\' ';
            }else{
                query += ' AND Notification_Type__c   != \'Cancelled\' ';
            }
            if(temp_set.contains('My Events Only')){
                query += ' AND Is_my_record__c   =  true ';
            }else{
                //query += ' AND Is_my_record__c   = false ';
            }
            
        }*/
        
        if(selectedTermFilter == 'Past'){       
            query += 'order by Event_Start_Date__c desc ';
        }else{
            query += 'order by Event_Start_Date__c asc ';
        }
        system.debug('****NewsEventList_Controller***fetchEvents****query='+query);
        paginationSet = new ApexPages.StandardSetController(Database.getQueryLocator(query));
        paginationSet.setPageSize(pageSize);
                
        /*PageReference pg  = Page.Tabbed_Group_Detail ; 
        pg.getParameters().put('id',groupId);
        pg.getParameters().put('stab','calendar');
        pg.getParameters().put('st',selectedTermFilter);
        pg.setRedirect(true);
        return pg;*/
        if(pageLoad){
            pageLoad = false;
        }else{
            system.currentPageReference().getParameters().put('stab','calendar');
        }
        return null; 
    }
    
    //function to delete folder
    public PageReference deleteRecord(){
        //fetch id of the folder to be deleted
        try{
            String recordIdToBeDeleted =  System.currentPageReference().getParameters().get('rid');
            if(recordIdToBeDeleted != null){
                
                News_Events__c ne = new News_Events__c(Id=recordIdToBeDeleted);
                delete ne;
                PageReference pg  = Page.Tabbed_Group_Detail ; 
                pg.getParameters().put('id',groupId);
                pg.getParameters().put('stab','calendar');
                pg.getParameters().put('st',selectedTermFilter);
                pg.setRedirect(true);
                return pg;
            }
        }catch(Exception e){
            
        }
        return null;
    }
    
    public PageReference newNotice(){
        PageReference pg  = new PageReference('/a2C/e') ; 
        pg.getParameters().put('CF00N6F00000M2zYQ',groupName);
        pg.getParameters().put('CF00N6F00000M2zYQ_lkid',groupId);
        pg.getParameters().put('nooverride','1');
        pg.getParameters().put('retURL',pageURL);
        pg.getParameters().put('cancelURL',pageURL);
        pg.getParameters().put('saveURL',pageURL);
        Id rid = [select Id from RecordType where SObjectType='News_Events__c' AND DeveloperName='Reminder'].Id;
        pg.getParameters().put('RecordType',rid);
        
        pg.setRedirect(true);
        return pg;
    }
    
    public PageReference newSchoolEvent(){
        PageReference pg  = new PageReference('/a2C/e') ; 
        pg.getParameters().put('CF00N6F00000M2zYQ',groupName);
        pg.getParameters().put('CF00N6F00000M2zYQ_lkid',groupId);
        pg.getParameters().put('nooverride','1');
        pg.getParameters().put('retURL',pageURL);
        pg.getParameters().put('cancelURL',pageURL);
        pg.getParameters().put('saveURL',pageURL);
        Id rid = [select Id from RecordType where SObjectType='News_Events__c' AND DeveloperName='Event'].Id;
        pg.getParameters().put('RecordType',rid);
        
        pg.setRedirect(true);
        return pg;
    }
    
    public PageReference newTermDate(){
        PageReference pg  = new PageReference('/a2C/e') ; 
        pg.getParameters().put('CF00N6F00000M2zYQ',groupName);
        pg.getParameters().put('CF00N6F00000M2zYQ_lkid',groupId);
        pg.getParameters().put('nooverride','1');
        pg.getParameters().put('retURL',pageURL);
        pg.getParameters().put('cancelURL',pageURL);
        pg.getParameters().put('saveURL',pageURL);
        pg.getParameters().put('Name','Auto-Complete');
        pg.getParameters().put('00N6F00000M2zY6','1');
        Id rid = [select Id from RecordType where SObjectType='News_Events__c' AND DeveloperName='Term'].Id;
        pg.getParameters().put('RecordType',rid);
        
        pg.setRedirect(true);
        return pg;
    }
    
    public PageReference newHolidayDate(){
        PageReference pg  = new PageReference('/a2C/e') ; 
        pg.getParameters().put('CF00N6F00000M2zYQ',groupName);
        pg.getParameters().put('CF00N6F00000M2zYQ_lkid',groupId);
        pg.getParameters().put('nooverride','1');
        pg.getParameters().put('retURL',pageURL);
        pg.getParameters().put('cancelURL',pageURL);
        pg.getParameters().put('saveURL',pageURL);
        pg.getParameters().put('00N6F00000M2zY6','1');
        Id rid = [select Id from RecordType where SObjectType='News_Events__c' AND DeveloperName='Holiday'].Id;
        pg.getParameters().put('RecordType',rid);
        
        pg.setRedirect(true);
        return pg;
    }
    
    
    
    //for pagination
    // indicates whether there are more records after the current page set.
    public Boolean hasNext {
        get {
            return paginationSet.getHasNext();
        }
        set;
    }

    // indicates whether there are more records before the current page set.
    public Boolean hasPrevious {
        get {
            return paginationSet.getHasPrevious();
        }
        set;
    }

    // returns the page number of the current page set
    public Integer pageNumber {
        get {
            return paginationSet.getPageNumber();
        }
        set;
    }

    // returns the first page of records
     public void first() {
         paginationSet.first();
         pageNum = paginationSet.getPageNumber();
     }

     // returns the last page of records
     public void last() {
         paginationSet.last();
         pageNum = paginationSet.getPageNumber();
     }

     // returns the previous page of records
     public void previous() {
         paginationSet.previous();
         pageNum = paginationSet.getPageNumber();
     }

     // returns the next page of records
     public void next() {
         paginationSet.next();
         pageNum = paginationSet.getPageNumber();
     }
     
     // sets page number
     public void  setPageNumber() {
         paginationSet.setPageNumber(pageNum);
     }
    
    

}