force-app/main/default/objects/Micro_Site__c.object
<CustomObject>
    <fields>
        <fullName>End_Zip_Postal_Code_Range__c</fullName>
        <description>When an individual Zip/Postal Code is searched via the public Site, Micro Site records that fall between the Start Zip/Postal Code and the End Zip/Postal Code will be displayed.</description>
        <inlineHelpText>When an individual Zip/Postal Code is searched via the public Site, Micro Site records that fall between the Start Zip/Postal Code and the End Zip/Postal Code will be displayed.</inlineHelpText>
        <label>End Zip/Postal Code Range</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Language__c</fullName>
        <description>Language switch for website translation management.</description>
        <inlineHelpText>Select the language of your record.</inlineHelpText>
        <label>Language</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>EN</fullName>
                    <default>true</default>
                    <label>EN</label>
                </value>
                <value>
                    <fullName>ES</fullName>
                </value>
                <value>
                    <fullName>PT</fullName>
                </value>
                <value>
                    <fullName>RU</fullName>
                </value>
                <value>
                    <fullName>UK</fullName>
                </value>
                <value>
                    <fullName>UZ</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Publish_Status__c</fullName>
        <description>Only the Status Value of &quot;Active&quot; will publish the Micro Site details to the public web.</description>
        <inlineHelpText>Only the Status Value of &quot;Active&quot; will publish the Micro Site details to the public web.</inlineHelpText>
        <label>Publish_Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>Under Review</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Start_Zip_Postal_Code_Range__c</fullName>
        <description>When an individual Zip/Postal Code is searched via the public Site, Micro Site records that fall between the Start Zip/Postal Code and the End Zip/Postal Code will be displayed.</description>
        <inlineHelpText>When an individual Zip/Postal Code is searched via the public Site, Micro Site records that fall between the Start Zip/Postal Code and the End Zip/Postal Code will be displayed.</inlineHelpText>
        <label>Positioning</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Tying a Micro Site to a user allows each user to modify their Micro Site through the default application or though the portal.</description>
        <inlineHelpText>Tying a Micro Site to a user allows each user to modify their Micro Site through the default application or though the portal.</inlineHelpText>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Micro_Sites</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Micro Site</label>
    <nameField>
        <label>Positioning</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Micro Sites</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/micrositeTestingUtil.cls
public with sharing class micrositeTestingUtil {

  public String micrositeId   {get; set;}
  public String userId        {get; set;}
 
  public micrositeTestingUtil(){
	 	Micro_Site__c m = new Micro_Site__c();
	 	m.Name = 'Test tester';
	 	m.User__c=Userinfo.getUserId();
	 	m.Name = Userinfo.getName();
	 	m.Publish_Status__c = 'Active';
	 	m.Start_Zip_Postal_Code_Range__c = '00000';
	 	m.End_Zip_Postal_Code_Range__c='99999';
	 	m.Language__c = 'EN'; 
	 	insert m;
	  micrositeId = m.Id;
	  userId = Userinfo.getUserId();
	 }

}