force-app/main/default/objects/Micro_Site__c.object
<CustomObject>
    <fields>
        <fullName>Biography__c</fullName>
        <label>Biography</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Degree__c</fullName>
        <label>Degree</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Department__c</fullName>
        <formula>TEXT(Staff_Member__r.School_Department__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Department</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EmailFormula__c</fullName>
        <formula>Staff_Member__r.Email_1__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Staff Email</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <formula>IF(Name_Override__c &lt;&gt; &quot;&quot;, Name_Override__c, TEXT(Staff_Member__r.Salutation) &amp;&quot; &quot;&amp; Staff_Member__r.FirstName &amp;&quot; &quot;&amp; Staff_Member__r.LastName )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Nationality__c</fullName>
        <formula>TEXT(Staff_Member__r.Nationality__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Country of Origin</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Other_Qualifications__c</fullName>
        <label>Other Qualifications</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Personal_Information__c</fullName>
        <label>Personal Interests</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Photo_ID__c</fullName>
        <label>Photo ID</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Photo_Id_URL__c</fullName>
        <formula>IF(Photo_ID__c != null,&quot;/servlet/servlet.FileDownload?file=&quot; &amp; Photo_ID__c &amp; &quot;&amp;oid=&quot; &amp; $Organization.Id ,&quot;/servlet/servlet.FileDownload?file=015D0000001RZWe&amp;oid=&quot; &amp; $Organization.Id)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Photo Id URL</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Position__c</fullName>
        <formula>IF( Position_Override__c =&quot;&quot;,Staff_Member__r.Position_Staff_Directory__c, Position_Override__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Position</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <formula>Staff_Member__r.Status__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Status</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>User_Extension__c</fullName>
        <description>This Extension is pulled from the User record</description>
        <formula>User__r.Extension</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>This Extension is pulled from the User record</inlineHelpText>
        <label>Extension</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>User_Phone__c</fullName>
        <description>This Phone number is pulled from the User record</description>
        <formula>Staff_Member__r.Email_1__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>This Phone number is pulled from the User record</inlineHelpText>
        <label>Email</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Tying a Micro Site to a user allows each user to modify their Micro Site through the default application or though the portal.</description>
        <inlineHelpText>Tying a Micro Site to a user allows each user to modify their Micro Site through the default application or though the portal.</inlineHelpText>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Micro_Sites</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Years_of_Experience__c</fullName>
        <label>Years of Experience</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <label>Micro Site</label>
    <nameField>
        <label>Positioning</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Micro Sites</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/microPageController.cls
public with sharing class microPageController {
  
  public String        microId             {get; set;}
  public Micro_Site__c microSite           {get; set;}
  public String        msName              {get; set;}
  public String        msStaffName         {get; set;}
  public String        msTitle             {get; set;}
  public String        msEmail             {get; set;}
  public String        msEmail2            {get; set;}
  public String        msDepartment        {get; set;}
  public String        msPosition          {get; set;}
  public String        msNationality       {get; set;}
  public String        msYearsOfExperience     {get; set;}
  public String        msDegree            {get; set;}
  public String        msOtherQualifications       {get; set;}
  public String        msStatus            {get; set;}
  public String        msBiography         {get; set;}
  public String        msPersonalInfo      {get; set;}
  public String        msPhone             {get; set;}
  public String        msOID               {get; set;}
  public String        imageLink           {get; set;}
  public String        userId              {get; set;}
  public String        yuiDepend           {get; set;}
  public String        msExtension         {get; set;}
  public Boolean       renderForm          {get; set;}
  public String        pathVar             {get; set;}
  public Boolean       testing             {get; set;}
  
  //contsructor
  public  microPageController(){
   microId = Apexpages.currentPage().getParameters().get('id');
   try{
    setupPathVar();
   }catch(Exception e){
    Apexpages.addMessages(e);
   }
   if(microId != null & microId !='')
     setupObjects();      
  }

  //setup pathVar for any extra path variables
  private void setupPathVar(){
    String Url=Site.getDomain();
    String prefix=Site.getPrefix();
    if(prefix==null)
     prefix='';
    pathVar ='http://'+Url+prefix;
    if(Site.getDomain()==null){
      pathVar='';
      String currentSite = Apexpages.currentPage().getUrl();
      if (testing){
        currentSite = 'http://microsite-developer-edition.na7.force.com/micropage?id='+userId;
      }
      Integer i;
      List <String> currentSiteSplit = currentSite.split('/');
      
      for(i=0; i<currentSiteSplit.size(); i++){
        if(currentSiteSplit[i].startsWith('micropage'))
          break;
      }
      
      i=i-1;
      if(currentSiteSplit[i].endsWith('com')&&testing)
        pathVar=currentSiteSplit[i];
      while(i>=0 && currentSiteSplit[i] !=null && !currentSiteSplit[i].endsWith('com')){
        pathVar=currentSiteSplit[i]+'/'+pathVar;
        i=i-1;
      }
      if(pathVar.length()>0)
        pathVar=pathVar.substring(0, pathVar.length()-1);
    }
  }
  
  //get and set all the object properties needed  
  private void setupObjects(){
    try{
      microSite = [Select Photo_Id_URL__c,Photo_ID__c,Department__c,Status__c,Degree__c,Years_of_Experience__c,Other_Qualifications__c,Nationality__c,Name__c,Position__c, Name, User_Phone__c, User_Extension__c, Id, User__r.Id,EmailFormula__c, User__r.Email, User__r.Title, User__c, Biography__c, Personal_Information__c 
                   From Micro_Site__c 
                   where Id = :microId];
    }catch(Exception e){
      Apexpages.addMessages(e);
    }
      if(microSite != null){
        microId=microSite.Id;
        msName = microSite.Name;
        msTitle = microSite.User__r.Title;
        msEmail = microSite.User__r.Email;
        msEmail2 = microSite.EmailFormula__c;
        msDepartment = microSite.Department__c;
        msPosition = microSite.Position__c;
        msNationality = microSite.Nationality__c;
        msDegree = microSite.Degree__c;
        msOtherQualifications = microSite.Other_Qualifications__c;
        msYearsOfExperience= microSite.Years_of_Experience__c;
        msStatus= microSite.Status__c;
        msStaffName = microSite.Name__c;
        msBiography = microSite.Biography__c;
        msPersonalInfo = microSite.Personal_Information__c;
        msPhone = microSite.User_Phone__c;
        userId = microSite.User__r.Id;
        if(userId!=null && userId!='')
         renderForm=true;
        else
         renderForm=false;
        msExtension = microSite.User_Extension__c;
        if(msExtension!=null && msExtension !='')
         msPhone= msPhone+' x'+msExtension;
    }
    msOID=System.Userinfo.getOrganizationId();
    //imageLink ='/servlet/servlet.ImageServer?id='+microSite.Photo_ID__c+'&oid='+msOID+'&lastMod=1263330074000';
  	 imageLink = microSite.Photo_Id_URL__c;
  }
  
  static testMethod void testMicroPageController(){
    micrositeTestingUtil mtu = new micrositeTestingUtil();
    microPageController mpc = new microPageController();
    Apexpages.currentPage().getParameters().put('id',mtu.micrositeId);
    mpc = new microPageController();
    mpc.testing = true;
    mpc.setupPathVar();
    System.assert(mpc.pathVar.length()>0);
  }

}