force-app/main/default/objects/Micro_Site__c.object
<CustomObject>
    <fields>
        <fullName>Department__c</fullName>
        <formula>TEXT(Staff_Member__r.School_Department__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Department</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EmailFormula__c</fullName>
        <formula>Staff_Member__r.Email_1__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Staff Email</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>End_Zip_Postal_Code_Range__c</fullName>
        <description>When an individual Zip/Postal Code is searched via the public Site, Micro Site records that fall between the Start Zip/Postal Code and the End Zip/Postal Code will be displayed.</description>
        <inlineHelpText>When an individual Zip/Postal Code is searched via the public Site, Micro Site records that fall between the Start Zip/Postal Code and the End Zip/Postal Code will be displayed.</inlineHelpText>
        <label>End Zip/Postal Code Range</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <formula>IF(Name_Override__c &lt;&gt; &quot;&quot;, Name_Override__c, TEXT(Staff_Member__r.Salutation) &amp;&quot; &quot;&amp; Staff_Member__r.FirstName &amp;&quot; &quot;&amp; Staff_Member__r.LastName )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Nationality__c</fullName>
        <formula>TEXT(Staff_Member__r.Nationality__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Country of Origin</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Photo_ID__c</fullName>
        <label>Photo ID</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Photo_Id_URL__c</fullName>
        <formula>IF(Photo_ID__c != null,&quot;/servlet/servlet.FileDownload?file=&quot; &amp; Photo_ID__c &amp; &quot;&amp;oid=&quot; &amp; $Organization.Id ,&quot;/servlet/servlet.FileDownload?file=015D0000001RZWe&amp;oid=&quot; &amp; $Organization.Id)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Photo Id URL</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Position__c</fullName>
        <formula>IF( Position_Override__c =&quot;&quot;,Staff_Member__r.Position_Staff_Directory__c, Position_Override__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Position</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Start_Zip_Postal_Code_Range__c</fullName>
        <description>When an individual Zip/Postal Code is searched via the public Site, Micro Site records that fall between the Start Zip/Postal Code and the End Zip/Postal Code will be displayed.</description>
        <inlineHelpText>When an individual Zip/Postal Code is searched via the public Site, Micro Site records that fall between the Start Zip/Postal Code and the End Zip/Postal Code will be displayed.</inlineHelpText>
        <label>Positioning</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <formula>Staff_Member__r.Status__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Status</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>User_Extension__c</fullName>
        <description>This Extension is pulled from the User record</description>
        <formula>User__r.Extension</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>This Extension is pulled from the User record</inlineHelpText>
        <label>Extension</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>User_Phone__c</fullName>
        <description>This Phone number is pulled from the User record</description>
        <formula>Staff_Member__r.Email_1__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>This Phone number is pulled from the User record</inlineHelpText>
        <label>Email</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Tying a Micro Site to a user allows each user to modify their Micro Site through the default application or though the portal.</description>
        <inlineHelpText>Tying a Micro Site to a user allows each user to modify their Micro Site through the default application or though the portal.</inlineHelpText>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Micro_Sites</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Micro Site</label>
    <nameField>
        <label>Positioning</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Micro Sites</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/searchPageController.cls
public with sharing class searchPageController {

  public list <Micro_Site__c>    msList               {get; set;}
  public list <MsClass>          smallMsClassList     {get; set;}
  public list <MsClass>          masterMsClassList    {get; set;}
  public list <list <MsClass>>   msClassLists         {get; set;}
  public String                  searchPhrase         {get; set;}
  public String                  Department           {get; set;}
  public String                  pathVar              {get; set;}
  public Boolean                 testing              {get; set;}
  //constructor 
  public searchPageController(){
    testing = false;
    setupPathVar();
    searchPhrase=Apexpages.currentPage().getParameters().get('search');
    Department=Apexpages.currentPage().getParameters().get('search');
    msList = [Select ID, EmailFormula__c,Department__c,Nationality__c,name__c,Position__c, Start_Zip_Postal_Code_Range__c, Photo_ID__c,
             Name, End_Zip_Postal_Code_Range__c, User_Phone__c, User_Extension__c,
             User__r.Email, User__r.Title, User__r.FirstName, User__r.LastName, User__c , Photo_Id_URL__c 
             From Micro_Site__c where Status__c = 'Employed' order by Name asc];
//msList.sort();
    setupMasterMsClassList();
  
    if(searchPhrase!=Null)
      doSearch();
      
    else
     setupSmallMsClassList();
    
      
  }


  //setup pathVar for any extra path variables
   private void setupPathVar(){
    String Url=Site.getDomain();
    String prefix=Site.getPrefix();
    if(prefix==null)
     prefix='';
    pathVar ='http://'+Url+prefix;
    if(Site.getDomain()==null){
      pathVar='';
      String currentSite = Apexpages.currentPage().getUrl();
      if (testing){
        currentSite = 'http://microsite-developer-edition.na7.force.com/searchpage';
      }
      Integer i;







      
      if(currentSite==null){
        return;
      }
      
      List <String> currentSiteSplit = currentSite.split('/');
      
      if(currentSiteSplit == null)
        return;
      
      for(i=0; i<currentSiteSplit.size(); i++){
        if(currentSiteSplit[i].startsWith('searchpage'))
          break;
      }
      
      i=i-1;
      
      while(i>=0 && currentSiteSplit[i] !=null && !currentSiteSplit[i].endsWith('com')){
        pathVar=currentSiteSplit[i]+'/'+pathVar;
        i=i-1;
      }
      if(pathVar.length()>0)
        pathVar=pathVar.substring(0, pathVar.length()-1);
    }
  }
  
 
   //returns a searchpage with search
  public pageReference micropageSearch(){
  
   
   if(searchPhrase!='All'){
      PageReference pageRef = new PageReference('/searchpage?search='+searchPhrase);
      return pageRef;}
      
    
      
      
      
      
    else{
 
  
  
    PageReference pageRef = new PageReference('/searchpage?search=');
    return pageRef;
  }}
  
  

  
  
  
 
  
  
  //performs search of either zip code or name
  private void doSearch(){
    smallMsClassList=new list<MsClass>();
    nameSearch();
   
    
    
   
   
  }
  
   //ensures search is made up of letters and
  //searches for name on all possible name fields
  private void nameSearch(){
    String phrase=Department.toLowerCase();
    for(MsClass ms:masterMSClassList){
      if(ms.firstName.toLowerCase().startsWith(Department.toLowerCase()))
        smallMsClassList.add(ms);
      else if(ms.lastName.toLowerCase().startsWith(Department.toLowerCase()))
        smallMsClassList.add(ms);
      else{
       List <String> splitName = ms.Department.split(' ');
       for (String s: splitName){
          if(s.toLowerCase().startsWith(Department.toLowerCase()))
            smallMsClassList.add(ms);
       }
      }
    } 
    
  }
 
  
  
  
  //returns a searchpage with search
  public pageReference micropageSearch2(){
    PageReference pageRef = new PageReference('/searchpage?search='+Department);
    return pageRef;
  }
  
  
  
  
  //performs search of either zip code or name
  private void doSearch2(){
    smallMsClassList=new list<MsClass>();
    nameSearch2();
    
    
   
   
  }
  
  //ensures search is made up of letters and
  //searches for name on all possible name fields
  private void nameSearch2(){
    String phrase=Department.toLowerCase();
    for(MsClass ms:masterMSClassList){
      if(ms.firstName.toLowerCase().startsWith(Department.toLowerCase()))
        smallMsClassList.add(ms);
      else if(ms.lastName.toLowerCase().startsWith(Department.toLowerCase()))
        smallMsClassList.add(ms);
      else{
       List <String> splitName = ms.startZip.split(' ');
       for (String s: splitName){
          if(s.toLowerCase().startsWith(Department.toLowerCase()))
            smallMsClassList.add(ms);
       }
      }
    } 
    
  }
  
 
  




  
  //sets up list used in page
  private void setupSmallMsClassList(){ 
    smallMsClassList = new list<MsClass>();
    
    //if less than 8 just add the list
    if(masterMsClassList.size()<300){
      for(MsClass mc:masterMsClassList)
       smallMsClassList.add(mc);
    }
    else{
      //get 8 random
      for (Integer i=0;i<8;i++)
        smallMsClassList.add(masterMsClassList.remove(Math.round((masterMsClassList.size()-1)*Math.random())));
      //add the 8 back to master list
      for(MsClass mc:smallMsClassList)
       masterMsClassList.add(mc);       
    }
  }
  
  //inner class of objects to display on the page
  private void setupMasterMsClassList(){
    masterMsClassList=new list<MsClass>();
    for (Micro_Site__c ms : msList)
     masterMsClassList.add(new MsClass(ms));
  }

  public Class MsClass{
    public String id             {get; set;}
    public String startZip       {get; set;}
    public String photoId        {get; set;}
    public String phone          {get; set;} 
    public String name           {get; set;}
    public String endZip         {get; set;}
    public String email          {get; set;}
    public String Department     {get; set;}
    public String Position       {get; set;}
    public String StaffName      {get; set;}
    public String Nationality    {get; set;}
    public String firstName      {get; set;}
    public String lastName       {get; set;}
    public String photoLink      {get; set;}
    public String title          {get; set;}
    public String Ext            {get; set;}
  
    
    public MsClass(Micro_Site__c ms){
      title       =nullCheck(ms.User__r.Title);
      id          =nullCheck(ms.ID);
      startZip    =nullCheck(ms.Start_Zip_Postal_Code_Range__c);
      photoId     =nullCheck(ms.Photo_ID__c);
      phone       =nullCheck(ms.User_Phone__c);
      name        =nullCheck(ms.Name);
      endZip      =nullCheck(ms.End_Zip_Postal_Code_Range__c);
      email       =nullCheck(ms.EmailFormula__c);
      Department  =nullCheck(ms.Department__c);
      Nationality =nullCheck(ms.Nationality__c);
      StaffName    =nullCheck(ms.name__c);
      Position    =nullCheck(ms.Position__c);
      firstName   =nullCheck(ms.User__r.FirstName);
      lastName    =nullCheck(ms.User__r.LastName);
      //photoLink   =nullCheck('/servlet/servlet.ImageServer?id='+ms.Photo_ID__c+'&oid='+System.Userinfo.getOrganizationId()+'&lastMod=1263330074000');
      photoLink   =nullCheck(ms.Photo_Id_URL__c);
      
      if(ms.User_Extension__c!=null)
       phone=phone+' x'+ms.User_Extension__c;
    }
  public String nullCheck(String val){
    if(val==null)
     return '.';
    else 
     return val;
  }
 }
 
 
}