force-app/main/default/objects/News_Events__c.object
<CustomObject>
    <fields>
        <fullName>Date__c</fullName>
        <defaultValue>IF($RecordType.DeveloperName = &quot;News&quot;, TODAY(), null)</defaultValue>
        <description>Used for &apos;Term Dates&apos;, &apos;Notices&apos; &amp; &apos;News&apos;. Copies to the &apos;Start Date&apos; field by means of workflow. Only required so that the field has a more appropriate label e.g. &apos;Start Date&apos; and &apos;End Date&apos; labels would be confusing if there is only one date</description>
        <inlineHelpText>For News: The date which the news is relevant to
For a Notice: The date or deadline that the notice is relevant to e.g. date a permission slip is due
For a Term Date: The &apos;First Day Of&apos; or &apos;Last Day Of&apos; the term as defined in the &apos;Date Is&apos; field</inlineHelpText>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Event_End_Date__c</fullName>
        <inlineHelpText>If the end date is the same as the start date then please leave blank</inlineHelpText>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Event_Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Fst_Email_Notification_Preview__c</fullName>
        <description>Provides a plain text preview of the email.</description>
        <inlineHelpText>This is a plain text preview only.</inlineHelpText>
        <label>Email Notification Preview</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Fst_Email_Notification_Text__c</fullName>
        <description>03/11/14 PENDING DELETION - NEEDS TO BE REMOVED FROM RELEVANT APEX CLASS</description>
        <label>Email Notification Text</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>School__c</fullName>
        <formula>IF(
   AND(
       TEXT(Share_with_Admin_Dept_of__c) != &quot;&quot;, 
       TEXT(Share_with_Admin_Dept_of__c) != &quot;Do Not Share&quot;
       ),
   TEXT(Share_with_Admin_Dept_of__c), 
   TEXT(Owner:User.School__c)
   )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>School</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Student_Group__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Student Group</label>
        <referenceTo>Group__c</referenceTo>
        <relationshipLabel>Calendar</relationshipLabel>
        <relationshipName>News_Events</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>News &amp; Events</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>News &amp; Events</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/School__c.object
<CustomObject>
    <label>School</label>
    <nameField>
        <label>School Code/UID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Schools</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/SchedulerEventReminderEmail.cls
global with sharing class SchedulerEventReminderEmail implements Schedulable{
	
	global void execute(SchedulableContext sc) {   
        /*
        string query = 'Select n.Student_Group__c, n.Snd_Email_Notification_Text__c, n.Snd_Email_Notification_Preview__c, n.Snd_Email_Notification_Date_Time__c, n.Send_Second_Reminder_Email__c, n.Send_First_Reminder_Email__c, n.Second_Reminder_Email_Sent__c, n.School__c, n.RecordType.DeveloperName, n.RecordType.Name, n.RecordTypeId, n.Id, n.Fst_Email_Notification_Text__c, n.Fst_Email_Notification_Preview__c, n.Fst_Email_Notification_Date_Time__c, n.First_Reminder_Email_Sent__c, n.Event_Start_Date__c, n.Event_End_Date__c, n.Date__c From News_Events__c n where n.Send_First_Reminder_Email__c = true OR n.Send_Second_Reminder_Email__c = true';
        EventEmailReminderBatch b = new EventEmailReminderBatch(query);
        Database.executeBatch(b, 1);*/
    }
    
}