force-app/main/default/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Half_Day_PN_N_Checkbox__c</fullName>
        <formula>TEXT(Half_Day_PN_N__c) != &quot;&quot;</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Half Day? (PN/N)</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Invoice_Year_Group__c</fullName>
        <formula>IF(
   OR(  
      AND(
          OR( 
             AND(
                 TEXT(School_Controlling_Picklist__c)=&quot;The New York International School&quot;,
                 OR(
                    AND(
                        MONTH(TODAY()) = 2, 
                        DAY(TODAY()) &gt;= 24
                        ), 
                    AND(
                        MONTH(TODAY()) &gt;= 3,
                        MONTH(TODAY()) &lt;= 7
                        )
                    )
                 ), 
             AND(
                 MONTH(TODAY()) = 5, 
                 DAY(TODAY()) &gt;= 24
                 ), 
             MONTH(TODAY()) = 6,
             MONTH(TODAY()) = 7,
             AND(
                 TEXT(School_Controlling_Picklist__c)=&quot;The International School of Moscow&quot;,
                 AND(
                     YEAR(TODAY()) = 2019,
                     MONTH(TODAY()) = 3,
                     DAY(TODAY()) &gt;= 29
                     )
                 )
             ),
          CloseDate &lt; DATE(YEAR(TODAY()),08,01),
          Monthly_Tuition__c != TRUE,
          Keep_Back_Next_Year__c != TRUE
          ),
      AND( 
          MONTH(TODAY()) = 7, 
          CloseDate &lt; DATE(YEAR(TODAY()),08,01), 
          Monthly_Tuition__c = TRUE,
          Keep_Back_Next_Year__c != TRUE
          )
      ),
   Year_Group_Increment__c ,   
   TEXT(Year_Group__c) 
   )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Invoice Year Group</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Year_Group__c</fullName>
        <label>Year Group / Grade</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>US_Year_Group_Control__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>PN1</fullName>
                </value>
                <value>
                    <fullName>PN</fullName>
                </value>
                <value>
                    <fullName>N</fullName>
                </value>
                <value>
                    <fullName>R</fullName>
                </value>
                <value>
                    <fullName>Y1</fullName>
                </value>
                <value>
                    <fullName>Y2</fullName>
                </value>
                <value>
                    <fullName>Y3</fullName>
                </value>
                <value>
                    <fullName>Y4</fullName>
                </value>
                <value>
                    <fullName>Y5</fullName>
                </value>
                <value>
                    <fullName>Y6</fullName>
                </value>
                <value>
                    <fullName>Y7</fullName>
                </value>
                <value>
                    <fullName>Y8</fullName>
                </value>
                <value>
                    <fullName>Y9</fullName>
                </value>
                <value>
                    <fullName>Y10</fullName>
                </value>
                <value>
                    <fullName>Y11</fullName>
                </value>
                <value>
                    <fullName>Y12</fullName>
                </value>
                <value>
                    <fullName>Y13</fullName>
                </value>
                <value>
                    <fullName>PK</fullName>
                </value>
                <value>
                    <fullName>K</fullName>
                </value>
                <value>
                    <fullName>G1</fullName>
                </value>
                <value>
                    <fullName>G2</fullName>
                </value>
                <value>
                    <fullName>G3</fullName>
                </value>
                <value>
                    <fullName>G4</fullName>
                </value>
                <value>
                    <fullName>G5</fullName>
                </value>
                <value>
                    <fullName>G6</fullName>
                </value>
                <value>
                    <fullName>G7</fullName>
                </value>
                <value>
                    <fullName>G8</fullName>
                </value>
                <value>
                    <fullName>G9</fullName>
                </value>
                <value>
                    <fullName>G10</fullName>
                </value>
                <value>
                    <fullName>G11</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Student</fullName>
        <active>true</active>
        <businessProcess>Standard Admissions Process</businessProcess>
        <label>Student</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Description_of_fee__c</fullName>
        <label>Description of fee</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Tuition</fullName>
                </value>
                <value>
                    <fullName>Lunch</fullName>
                </value>
                <value>
                    <fullName>Bus</fullName>
                </value>
                <value>
                    <fullName>Enrolment</fullName>
                </value>
                <value>
                    <fullName>Application</fullName>
                </value>
                <value>
                    <fullName>EAL</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Fee_Frequency__c</fullName>
        <label>Fee Frequency</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Monthly</fullName>
                </value>
                <value>
                    <fullName>Yearly</fullName>
                </value>
                <value>
                    <fullName>Termly</fullName>
                </value>
                <value>
                    <fullName>One Off</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Half_Day__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Half Day</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Year_Group__c</fullName>
        <label>Year Group</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Description_of_fee__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>PN1</fullName>
                </value>
                <value>
                    <fullName>PN</fullName>
                </value>
                <value>
                    <fullName>N</fullName>
                </value>
                <value>
                    <fullName>R</fullName>
                </value>
                <value>
                    <fullName>Y1</fullName>
                </value>
                <value>
                    <fullName>Y2</fullName>
                </value>
                <value>
                    <fullName>Y3</fullName>
                </value>
                <value>
                    <fullName>Y4</fullName>
                </value>
                <value>
                    <fullName>Y5</fullName>
                </value>
                <value>
                    <fullName>Y6</fullName>
                </value>
                <value>
                    <fullName>Y7</fullName>
                </value>
                <value>
                    <fullName>Y8</fullName>
                </value>
                <value>
                    <fullName>Y9</fullName>
                </value>
                <value>
                    <fullName>Y10</fullName>
                </value>
                <value>
                    <fullName>Y11</fullName>
                </value>
                <value>
                    <fullName>Y12</fullName>
                </value>
                <value>
                    <fullName>Y13</fullName>
                </value>
                <value>
                    <fullName>PK</fullName>
                </value>
                <value>
                    <fullName>K</fullName>
                </value>
                <value>
                    <fullName>G1</fullName>
                </value>
                <value>
                    <fullName>G2</fullName>
                </value>
                <value>
                    <fullName>G3</fullName>
                </value>
                <value>
                    <fullName>G4</fullName>
                </value>
                <value>
                    <fullName>G5</fullName>
                </value>
                <value>
                    <fullName>G6</fullName>
                </value>
                <value>
                    <fullName>G7</fullName>
                </value>
                <value>
                    <fullName>G8</fullName>
                </value>
                <value>
                    <fullName>G9</fullName>
                </value>
                <value>
                    <fullName>G10</fullName>
                </value>
                <value>
                    <fullName>G11</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/SingleInvoiceFee.cls
public with sharing class SingleInvoiceFee {

	//Variables
	public Boolean tuition			{ get; set; }
	public String pricebook2Id		{ get; set; }
	public List<Student> students	{ get; set; }
	
	public String fee				{ get; set; }
	public String term				{ get; set; }
	public String discount			{ get; set; }

	private List<String> allMonths = new List<String> { 'January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December' };
	
	//fee = PriceBookEntryId (fee can be null), oppor = The student that owns this fee, Tuition = if this fee is tuition or other. 
	public class Student
	{
		public Boolean isSelected 	{ get; set; }
		public Opportunity opp		{ get; set; }
		
		public Student( Opportunity opp ) 
		{
			this.opp 		= opp;
			this.isSelected	= false;	
		}
	}
	
	public SingleInvoiceFee( Boolean tuition, String Pricebook2Id, List<Opportunity> opportunities ) 
	{
		this.fee 			= '';
		this.tuition		= tuition;
		this.pricebook2Id 	= pricebook2Id;
		this.students 		= new List<Student>();
		
		for( Opportunity opp : opportunities ) 
		{
			students.add( new Student( opp ) );
		}
		
		//initialize to a 10 monthly fee 
		if(this.tuition == true){
			this.term = 'Recurring';
		}else{
			this.term 		= 'One_Off';
		}
		this.discount 	= '0';
	}
	
	//Get the list of fees avaliable filtered by the selected Term, month and the current Opportunites year group
	public List<SelectOption> getFeeOptions() 
	{
		List<SelectOption> options = new List<SelectOption>{
			new SelectOption('', '--None--')
		};
		
		List<PricebookEntry> pbes = new List<PricebookEntry>(); 
		String yrGroup = ( this.tuition && this.students.size() == 1 ) ? this.students.get(0).opp.Invoice_Year_Group__c : null;
		boolean isOppHalfPNN = ( this.tuition && this.students.size() == 1 ) ? this.students.get(0).opp.Half_Day_PN_N_CheckBox__c : false;
		if( this.term == 'Recurring' )
		{
			pbes.addAll([ 
				SELECT Id, Name, PriceBook2Id, UnitPrice, Product2Id, Product2.Year_Group__c, Product2.Fee_Frequency__c,
						Product2.Description_of_fee__c, Product2.Half_Day__c 
				  FROM PriceBookEntry 
				 WHERE Product2.Fee_Frequency__c !=: 'One Off'
				   AND Product2.Year_Group__c =: yrGroup 
				   AND PriceBook2Id =: this.pricebook2Id
			     order by Name
			]);
		}
		else if( this.term == 'One_Off' ) 
		{
			pbes.addAll([ 
				SELECT Id, Name, PriceBook2Id, UnitPrice, Product2Id, Product2.Year_Group__c, Product2.Fee_Frequency__c,
						Product2.Description_of_fee__c,  Product2.Half_Day__c 
				  FROM PriceBookEntry 
				 WHERE Product2.Fee_Frequency__c =: 'One Off'
				   AND Product2.Year_Group__c =: yrGroup 
				   AND PriceBook2Id =: this.pricebook2Id
			     order by Name
			]);
		}
		
		//Setup all the other products
		for(PriceBookEntry pbe : pbes) 
		{ 
			if(tuition == true ){
				if(isOppHalfPNN == true && pbe.Product2.Half_Day__c == true){
					options.add(new SelectOption( pbe.Id, pbe.Name ));
				}else if(isOppHalfPNN != true && pbe.Product2.Half_Day__c == false){
					options.add(new SelectOption( pbe.Id, pbe.Name ));
				}
			}else{
				options.add(new SelectOption( pbe.Id, pbe.Name ));
			}
		}
		return options;
	}
	
	//Returns the choice of Monthly, Termly or Yearly invoicing term
	public List<SelectOption> getTermOptions() 
	{	
		List<SelectOption> options = new List<SelectOption>();
		options.add(new SelectOption('One_Off', 'One Off'));
		options.add(new SelectOption('Recurring', 'Recurring'));
		return options;
	}
}