force-app/main/default/objects/Web_Content__c.object
<CustomObject>
    <fields>
        <fullName>Notify_Me_When_Translation_is_Complete__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Notify Me When Translation is Complete?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Send_Update_Request_Email__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Checked by completing the &apos;Request Updated Translation&apos; custom button process, sends the relevant email notification. Value returns to unchecked once the &apos;Translation Complete&apos; button is clicked.</description>
        <label>Send Update Request Email</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Translation_Status__c</fullName>
        <defaultValue>IF(CONTAINS($RecordType.DeveloperName, &quot;Translation&quot;), &quot;Requested&quot;, &quot;&quot;)</defaultValue>
        <description>Populated by means of various workflow rules to define the status of the translation in the process lifecycle (Requested, Complete)</description>
        <label>Translation Status</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Update_Request_Description__c</fullName>
        <description>Populated when sending a request for an updated translation, indicates in the email template what changes have been made to warrant the updated translation request</description>
        <label>Update Request Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Web Content</label>
    <nameField>
        <label>Menu Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Web Content</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/TranslateWebContent.cls
public class TranslateWebContent{
    public Web_Content__c webContentRecord {get;set;}
    public string requestDescription {get;set;}
    public boolean notify {get;set;}
    public boolean isSuccess {get;set;}
    //constructor
    public TranslateWebContent(ApexPages.StandardController controller){
        isSuccess = false;
        webContentRecord = (Web_Content__c)controller.getRecord(); 
        notify = false;
    }
    //function to update calendarRecord
    public PageReference submitTranslationRequest(){
    	try{
	    	webContentRecord.Translation_Status__c = 'Requested';
	    	webContentRecord.Update_Request_Description__c = requestDescription;
	    	webContentRecord.Send_Update_Request_Email__c = true;
	    	webContentRecord.Notify_Me_When_Translation_is_Complete__c = notify;
	    	update webContentRecord;
	    	isSuccess = true;
    	}catch(Exception e){
    		isSuccess = false;
    		ApexPages.Message errorMessage = new ApexPages.Message(ApexPages.severity.FATAL, 'There were errors when sending the Updated Translation Request email. Please report this error to the system administrator, including the URL of the record in your email. Error Message: '+e.getMessage());
			ApexPages.addMessage(errorMessage);	
    	}
        return null;
    }
}