force-app/main/default/objects/DocumentChecklist__c/DocumentChecklist__c.object-meta.xml
<CustomObject>
    <label>Document Checklist</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Document Checklists</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/DocumentChecklist__c/fields/DateReceived__c.field-meta.xml
<CustomField>
    <fullName>DateReceived__c</fullName>
    <label>Date Received</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/DocumentChecklist__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Document Checklists</relationshipLabel>
    <relationshipName>DocumentChecklists</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/DocumentChecklist__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Enquiry</fullName>
            </value>
            <value>
                <fullName>Application</fullName>
            </value>
            <value>
                <fullName>Acceptance</fullName>
            </value>
            <value>
                <fullName>Enrolled</fullName>
            </value>
            <value>
                <fullName>Visit</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DocumentChecklist__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Requested</fullName>
                <default>true</default>
                <label>Requested</label>
            </value>
            <value>
                <fullName>Received</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DocumentChecklist__c/fields/YearGrade__c.field-meta.xml
<CustomField>
    <fullName>YearGrade__c</fullName>
    <label>YearGrade</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>-4</fullName>
            </value>
            <value>
                <fullName>-3</fullName>
            </value>
            <value>
                <fullName>-2</fullName>
            </value>
            <value>
                <fullName>-1</fullName>
            </value>
            <value>
                <fullName>0</fullName>
            </value>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>6</fullName>
            </value>
            <value>
                <fullName>7</fullName>
            </value>
            <value>
                <fullName>8</fullName>
            </value>
            <value>
                <fullName>9</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
            <value>
                <fullName>11</fullName>
            </value>
            <value>
                <fullName>12</fullName>
            </value>
            <value>
                <fullName>13</fullName>
            </value>
            <value>
                <fullName>14</fullName>
            </value>
            <value>
                <fullName>15</fullName>
            </value>
            <value>
                <fullName>16</fullName>
            </value>
            <value>
                <fullName>17</fullName>
            </value>
            <value>
                <fullName>18</fullName>
            </value>
            <value>
                <fullName>19</fullName>
            </value>
            <value>
                <fullName>20</fullName>
            </value>
            <value>
                <fullName>21</fullName>
            </value>
            <value>
                <fullName>22</fullName>
            </value>
            <value>
                <fullName>23</fullName>
            </value>
            <value>
                <fullName>24</fullName>
            </value>
            <value>
                <fullName>25</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/YearGrade__c/YearGrade__c.object-meta.xml
<CustomObject>
    <label>Year/Grade</label>
    <nameField>
        <label>Year/Grade Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Years/Grades</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/YearGrade__c/fields/TECH_Year_Grade_Number__c.field-meta.xml
<CustomField>
    <fullName>TECH_Year_Grade_Number__c</fullName>
    <label>YearGrade Number</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/LC04_DocumentChecklist.cls
public without sharing class LC04_DocumentChecklist {
/**************************************************************************************
-- - Author        : Spoon Consulting
-- - Description   : Apex Controller for lightning component LC04_DocumentChecklist
--
-- Maintenance History: 
--
-- Date         Name  Version  Remarks 
-- -----------  ----  -------  -------------------------------------------------------
-- 21-DEC-2017  RRAJ    1.0     Initial version
-- 10-JUN-2021  VJA     1.1     fetchDocumentCheklists modified 
--------------------------------------------------------------------------------------
***************************************************************************************/
    /**
     * Method to query Document Checklists related to opportunity
     * @param  oppId Opportunity Id
     * @return       List of Document checklist corresponding to opportunity and opportunity stage
     */
    @AuraEnabled
    public static List<DocumentChecklist__c> fetchDocumentCheklists (String oppId){ 
        Opportunity opp = [SELECT StageName, TECH_SchoolCode__c, YearGrade__r.TECH_Year_Grade_Number__c, RecordTypeId FROM Opportunity WHERE Id =: oppId limit 1];
        List<String> lstDocChecklistStage = new List<String>();
        Map<String, List<String>> mapOppStageToDocChecklistStage = new Map<String, List<String>>();

        //***1.1***MAP to store the document checklists to display wrt the opportunity stage.*****// 
        //1. Enquiry
        mapOppStageToDocChecklistStage.put(AP_Constant.oppStageNameEnquiry, new List<String>{AP_Constant.oppStageNameEnquiry});
        //2. Visit
        mapOppStageToDocChecklistStage.put(AP_Constant.oppStageNameVisit, new List<String>{AP_Constant.oppStageNameEnquiry, AP_Constant.oppStageNameVisit});
        //3. Application
        mapOppStageToDocChecklistStage.put(AP_Constant.oppStageNameApplication, new List<String>{AP_Constant.oppStageNameEnquiry, AP_Constant.oppStageNameVisit,AP_Constant.oppStageNameApplication});
        //4. Offer Out
        mapOppStageToDocChecklistStage.put(AP_Constant.oppStageNameOfferOut, new List<String>{AP_Constant.oppStageNameEnquiry, AP_Constant.oppStageNameVisit,AP_Constant.oppStageNameApplication, AP_Constant.oppStageNameOfferOut, AP_Constant.oppStageNameAcceptance});
        //5. Acceptance
        mapOppStageToDocChecklistStage.put(AP_Constant.oppStageNameAcceptance, new List<String>{AP_Constant.oppStageNameEnquiry, AP_Constant.oppStageNameVisit,AP_Constant.oppStageNameApplication, AP_Constant.oppStageNameOfferOut, AP_Constant.oppStageNameAcceptance});
        //6. Enrolled
        mapOppStageToDocChecklistStage.put(AP_Constant.oppStageNameEnrolled, new List<String>{AP_Constant.oppStageNameEnquiry, AP_Constant.oppStageNameVisit,AP_Constant.oppStageNameApplication, AP_Constant.oppStageNameOfferOut, AP_Constant.oppStageNameAcceptance,AP_Constant.oppStageNameEnrolled});

        if(mapOppStageToDocChecklistStage.containsKey(opp.StageName)){
            lstDocChecklistStage = mapOppStageToDocChecklistStage.get(opp.StageName);
        }
        
        if(Schema.SObjectType.Opportunity.getRecordTypeInfosById().get(opp.RecordTypeId).getName() == AP_Constant.oppRecordTypeJulliardSummerArtsLabel
           && opp.TECH_SchoolCode__c == 'CBS'){
            return [SELECT Id, Name, Status__c, DateReceived__c, yeargrade__c, Required__c FROM DocumentChecklist__c WHERE Opportunity__c = :oppId 
                           AND (Stage__c in: lstDocChecklistStage OR Stage__c =: null) 
                           AND (yeargrade__c includes  (:opp.YearGrade__r.TECH_Year_Grade_Number__c ) OR yeargrade__c = '')
                           AND recordtype__c = :AP_Constant.oppRecordTypeJulliardSummerArtsLabel ORDER BY Name ASC];
        }else{
            return [SELECT Id, Name, Status__c, DateReceived__c, yeargrade__c, Required__c FROM DocumentChecklist__c WHERE Opportunity__c = :oppId 
                        AND (Stage__c in: lstDocChecklistStage  OR Stage__c =: null) 
                        AND (yeargrade__c includes  (:opp.YearGrade__r.TECH_Year_Grade_Number__c ) OR yeargrade__c = '' )
                        AND recordtype__c != :AP_Constant.oppRecordTypeJulliardSummerArtsLabel ORDER BY Name ASC];
        } 
    }

    /**
     * [saveDocumentCheckList description]
     * @param  strJSONDocChk [description]
     * @return               [description]
     */
    @AuraEnabled
    public static void saveDocumentCheckList (String strJSONDocChk){
        try{
            DocumentChecklist__c docChecklist = (DocumentChecklist__c)System.JSON.deserialize(strJSONDocChk, DocumentChecklist__c.class); //deserialise list of docuent from JSON input
            //update document checklist
            update docChecklist;
        }catch(exception ex){
            throw new AuraHandledException(ex.getMessage());
        }
    }

    /**
     * controller method to save list of document checklist from JSON string
     * @param  strJSONlstDocChk Serialised list of document checklists
     * @return                  Map of update results
     */
    @AuraEnabled
    public static Map<String, String> saveDocumentCheckLists (String strJSONlstDocChk){ 
        Map<String, String> result = new Map<String, String>();
        try{
        	List<DocumentChecklist__c> lstDocChecklist = (List<DocumentChecklist__c>)System.JSON.deserialize(strJSONlstDocChk, List<DocumentChecklist__c>.class); //deserialise list of docuent from JSON input
            //update document checklists
            if(lstDocChecklist.size()>0){
                update lstDocChecklist;
                result.put('SUCCESS', Label.RecordUpdateSuccessMessage);
            }
        }catch(exception ex){
            System.debug('### Error: ' + ex.getMessage() + '\nStack Trace: ' + ex.getStackTraceString());
            result.put('ERROR', ex.getMessage() + '\nStack Trace: ' + ex.getStackTraceString());
        }
        return result;
    }
}